### ISSUE TITLE
Resources: New templates of Gdańskie Autobusy i Tramwaje

### ISSUE THREAD

**Issue by THIAS18** [railmapgen/rmg-templates#100]
**Justification:** https://ztm.gda.pl & https://www.gdansk.pl/wiadomosci/Ujescisko-Lostowice-Tramwaje-na-ul-Nowej-Warszawskiej-od-4-marca,a,235539

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gaittram" line="_config"><summary>New company: GAiT Tram</summary><details type="name">{"en":"GAiT Tram","zh-Hans":"GAiT Tram","zh-Hant":"GAiT Tram"}</details></details>

<details repo="rmg-templates" company="gaittram" line="gda2"><summary>gaittram/gda2</summary><details type="name">{"en":"2","zh-Hans":"2","zh-Hant":"2"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2500,"indoor":3000},"svg_height":300,"style":"shmetro","y_pc":50,"padding":20,"branchSpacingPct":38,"direction":"r","platform_num":"","theme":["hongkong","twl","#E2231A","#fff"],"line_name":["2",""],"current_stn_idx":"4r4OIQ","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["4r4OIQ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4r4OIQ":{"name":["LAWENDOWE WZGÓRZE","LAWENDOWE WZGÓRZE"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["jZ4pAE"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jZ4pAE":{"name":["UJEŚCISKO","UJEŚCISKO"],"secondaryName":false,"num":"02","services":["local"],"parents":["4r4OIQ"],"children":["2V5np9"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"l","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["AvqqLy"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"2V5np9":{"name":["CZĘSTOCHOWSKA","CZĘSTOCHOWSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["jZ4pAE"],"children":["M0SdH3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"M0SdH3":{"name":["PIOTRKOWSKA","PIOTRKOWSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["2V5np9"],"children":["4D2t0J"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4D2t0J":{"name":["ŁÓDZKA","ŁÓDZKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["M0SdH3"],"children":["KO4BKK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KO4BKK":{"name":["PRZEMYSKA","PRZEMYSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["4D2t0J"],"children":["HgX7mX"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HgX7mX":{"name":["WILANOWSKA","WILANOWSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["KO4BKK"],"children":["cKxUUA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cKxUUA":{"name":["CEBERTOWICZA","CEBERTOWICZA"],"secondaryName":false,"num":"00","services":["local"],"parents":["HgX7mX"],"children":["atdCSp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"atdCSp":{"name":["CIESZYŃSKIEGO","CIESZYŃSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["cKxUUA"],"children":["O9VBIa"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"O9VBIa":{"name":["SIKORSKIEGO","SIKORSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["atdCSp"],"children":["Uqq1WN"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Uqq1WN":{"name":["CHAŁUBIŃSKIEGO","CHAŁUBIŃSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["O9VBIa"],"children":["U1o8zy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"U1o8zy":{"name":["ODRZAŃSKA","ODRZAŃSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["Uqq1WN"],"children":["INAocS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"INAocS":{"name":["POHULANKA","POHULANKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["U1o8zy"],"children":["72Vrsm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"72Vrsm":{"name":["ŚRÓDMIEŚCIE SKM","ŚRÓDMIEŚCIE SKM"],"secondaryName":false,"num":"00","services":["local"],"parents":["INAocS"],"children":["_Q02Wb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_Q02Wb":{"name":["BRAMA WYŻYNNA","BRAMA WYŻYNNA"],"secondaryName":false,"num":"00","services":["local"],"parents":["72Vrsm"],"children":["A2NLcY"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"A2NLcY":{"name":["DWORZEC GŁÓWNY","DWORZEC GŁÓWNY"],"secondaryName":false,"num":"00","services":["local"],"parents":["_Q02Wb"],"children":["xoSXfy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xoSXfy":{"name":["BRAMA OLIWSKA","BRAMA OLIWSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["A2NLcY"],"children":["6rd18n"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6rd18n":{"name":["CHODOWIECKIEGO","CHODOWIECKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["xoSXfy"],"children":["iZXhpW"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iZXhpW":{"name":["UNIWERSYTET MEDYCZNY","UNIWERSYTET MEDYCZNY"],"secondaryName":false,"num":"00","services":["local"],"parents":["6rd18n"],"children":["f2ZQm-"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"f2ZQm-":{"name":["TRAUGUTTA","TRAUGUTTA"],"secondaryName":false,"num":"00","services":["local"],"parents":["iZXhpW"],"children":["tb8A28"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"tb8A28":{"name":["OPERA BAŁTYCKA","OPERA BAŁTYCKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["f2ZQm-"],"children":["rw2B0v"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rw2B0v":{"name":["WYSPIAŃSKIEGO","WYSPIAŃSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["tb8A28"],"children":["fwiD5u"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fwiD5u":{"name":["REJA","REJA"],"secondaryName":false,"num":"00","services":["local"],"parents":["rw2B0v"],"children":["Aqu4Bz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Aqu4Bz":{"name":["MICKIEWICZA","MICKIEWICZA"],"secondaryName":false,"num":"00","services":["local"],"parents":["fwiD5u"],"children":["95OPEs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"95OPEs":{"name":["PL. KOMOROWSKIEGO","PL. KOMOROWSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["Aqu4Bz"],"children":["hCz1CZ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hCz1CZ":{"name":["LEGIONÓW","LEGIONÓW"],"secondaryName":false,"num":"00","services":["local"],"parents":["95OPEs"],"children":["IF5r7z"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IF5r7z":{"name":["BAJANA","BAJANA"],"secondaryName":false,"num":"00","services":["local"],"parents":["hCz1CZ"],"children":["rFhTxs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rFhTxs":{"name":["ŻWIRKI I WIGURY","ŻWIRKI I WIGURY"],"secondaryName":false,"num":"00","services":["local"],"parents":["IF5r7z"],"children":["pEBF4C"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pEBF4C":{"name":["JANA PAWŁA II","JANA PAWŁA II"],"secondaryName":false,"num":"00","services":["local"],"parents":["rFhTxs"],"children":["evdLYU"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"evdLYU":{"name":["STARTOWA","STARTOWA"],"secondaryName":false,"num":"00","services":["local"],"parents":["pEBF4C"],"children":["zmiC0l"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zmiC0l":{"name":["ZASPA","ZASPA"],"secondaryName":false,"num":"00","services":["local"],"parents":["evdLYU"],"children":["wIKrfF"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wIKrfF":{"name":["KOŁOBRZESKA","KOŁOBRZESKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["zmiC0l"],"children":["pXSZUu"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pXSZUu":{"name":["BORA - KOMOROWSKIEGO","B. - KOMOROWSKIEGO"],"secondaryName":false,"num":"00","services":["local"],"parents":["wIKrfF"],"children":["8AlTSS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8AlTSS":{"name":["CZERWONY DWÓR","CZERWONY DWÓR"],"secondaryName":false,"num":"00","services":["local"],"parents":["pXSZUu"],"children":["OKMWc0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"OKMWc0":{"name":["PIASTOWSKA","PIASTOWSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["8AlTSS"],"children":["Zkas9w"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Zkas9w":{"name":["POMORSKA","POMORSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["OKMWc0"],"children":["Ik0LEY"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Ik0LEY":{"name":["OS. WEJHERA","OS. WEJHERA"],"secondaryName":false,"num":"00","services":["local"],"parents":["Zkas9w"],"children":["j9zCqD"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"j9zCqD":{"name":["HELSKA","HELSKA"],"secondaryName":false,"num":"00","services":["local"],"parents":["Ik0LEY"],"children":["AvqqLy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AvqqLy":{"name":["JELITKOWO","JELITKOWO"],"secondaryName":false,"num":"00","services":["local"],"parents":["j9zCqD"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":true,"terminal":["JELITKOWO","JELITKOWO"]},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

<b>https://github.com/railmapgen/rmg-palette/issues/388</b>

**Comment by 52PD** [comment]
您好，我们注意到您对线路的命名不规范，且未对各线路和轨交系统进行中文翻译。
请在规范线路命名并补齐中文翻译后重新提交一次，谢谢。
