### ISSUE TITLE
Resources: New templates of Chengdu Metro

### ISSUE THREAD

**Issue by thislgcityrecord** [railmapgen/rmg-templates#1002]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Lines opening status:** OPENED

**Reference source:** 2. 互联网上在车站里拍摄的视频

**Justification:** 18号线与2023.6.1改为直达车，原来的大站车已经全剧终

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="chengdumetro" line="cd18" major="false"><summary>chengdumetro/cd18</summary><details type="name">{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線","ru":"Звено 18","ko":"라인 18"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1800,"indoor":2200},"svg_height":350,"style":"shmetro","y_pc":50,"padding":12,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["chengdu","cd18","#006268","#fff"],"line_name":["18号线","Line 18"],"current_stn_idx":"Ve4Q4g","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["49boLf"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":255,"branch":{}},"Ve4Q4g":{"name":["天府机场北","Tianfu International Airport North"],"num":"17","services":["local","direct"],"parents":["C2Xqr1"],"children":["lineend"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["Ve4Q4g"],"children":[],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":255},"49boLf":{"name":["火车南站","South Railway Station"],"num":"05","services":["local","direct"],"parents":["linestart"],"children":["EeH0KY"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]},{"theme":["chengdu","cd7","#6dc6d6","#fff"],"name":["7号线","Line 7"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"EeH0KY":{"name":["孵化园","Incubation Park"],"num":"06","services":["local"],"parents":["49boLf"],"children":["N9M4Rt"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]},{"theme":["chengdu","cd9","#f1ad17","#fff"],"name":["9号线","Line 9"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"N9M4Rt":{"name":["锦城广场东","Jincheng Plaza East"],"num":"07","services":["local"],"parents":["EeH0KY"],"children":["DfOmv1"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{},{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]}]},{}]},"loop_pivot":false,"one_line":true,"int_padding":255},"DfOmv1":{"name":["世纪城","Century City"],"num":"08","services":["local"],"parents":["N9M4Rt"],"children":["p5bn8r"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"p5bn8r":{"name":["海昌路","Haichang Road"],"num":"09","services":["local"],"parents":["DfOmv1"],"children":["kWpvMP"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"kWpvMP":{"name":["西博城","Western China Int'l Expo City"],"num":"10","services":["local"],"parents":["p5bn8r"],"children":["u9UeXb"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd1","#222a8c","#fff"],"name":["1号线","Line 1"]},{"theme":["chengdu","cd6","#be7331","#fff"],"name":["6号线","Line 6"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"u9UeXb":{"name":["兴隆","Xinglong"],"num":"11","services":["local"],"parents":["kWpvMP"],"children":["NZUXxr"],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":255},"uzaCst":{"name":["三岔","Sancha"],"num":"13","services":["local"],"parents":["NZUXxr"],"children":["9csC46"],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":255},"C2Xqr1":{"name":["天府机场1号2号航站楼","Terminal 1&amp;2 of Tianfu International Airport"],"num":"16","services":["local","direct"],"parents":["Gg9XUE"],"children":["Ve4Q4g"],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":255,"facility":"airport"},"9csC46":{"name":["福田","Futian"],"num":"00","services":["local"],"parents":["uzaCst"],"children":["Gg9XUE"],"transfer":{"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":255,"branch":{}},"NZUXxr":{"name":["天府站（仅换乘）","Tianfu Station(transfer only)"],"num":"00","services":["local"],"parents":["u9UeXb"],"children":["uzaCst"],"transfer":{"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":255,"branch":{}},"Gg9XUE":{"name":["天府机场3号4号航站楼","Terminal 3&amp;4 of Tianfu International Airport"],"num":"00","services":[],"parents":["9csC46"],"children":["C2Xqr1"],"transfer":{"groups":[{"lines":[{"theme":["chengdu","cd19","#89ABE3","#fff"],"name":["19号线","Line 19"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":255}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"18","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.13"}</details></details>

**Comment by Charlis-Wong** [comment]
@wongchito / @thekingofcity / @28yfang / @Windows-Taskmgr 請關閉此Issue並加上 Need Fixing，謝謝🙏
