### ISSUE TITLE
Resources: New templates of Zhengzhou Metro

### ISSUE THREAD

**Issue by Bachongshenzi1453** [railmapgen/rmg-templates#1006]
**Lines opening status:** OPENED

**Reference source:** 4. 互联网上的路线图

**Justification:** 增加郑许线（17号线）。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zzmetro" line="zz17" major="false"><summary>zzmetro/zz17</summary><details type="name">{"en":"Line 17","zh-Hans":"17号线","zh-Hant":"17號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1400,"railmap":2500,"indoor":1800},"svg_height":400,"style":"gzmtr","y_pc":50,"padding":6,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["zhengzhou","zz17","#1D4155","#fff"],"line_name":["郑许线","ZHENGXU Line"],"current_stn_idx":"QC003H","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["w7xnbR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"w7xnbR":{"name":["长安路北","CHANG'AN LU BEI"],"num":"01","services":["local"],"parents":["linestart"],"children":["AoWx1G"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QC003H":{"name":["许昌东站","XUCHANGDONG RAILWAY STATION"],"num":"27","services":["local"],"parents":["SSP9KC"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["QC003H"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"AoWx1G":{"name":["港区北","GANGQU BEI"],"num":"02","services":["local"],"parents":["w7xnbR"],"children":["2nq9JE"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz9","#828C47","#fff"],"name":["城郊线","CHENGJIAO Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":160},"2nq9JE":{"name":["文体中心","WENTI ZHONGXIN"],"num":"03","services":["local"],"parents":["AoWx1G"],"children":["3xTZNl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3xTZNl":{"name":["枣园","ZAOYUAN"],"num":"04","services":["local"],"parents":["2nq9JE"],"children":["7r4jvb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7r4jvb":{"name":["翱翔路","AOXIANG LU"],"num":"05","services":["local"],"parents":["3xTZNl"],"children":["koC5u0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"koC5u0":{"name":["长安路南","CHANG'AN LU NAN"],"num":"06","services":["local"],"parents":["7r4jvb"],"children":["8VvPUp"],"transfer":{"groups":[{},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":180},"8VvPUp":{"name":["新郑机场","XINZHENG INTERNATIONAL AIRPORT"],"num":"07","services":["local"],"parents":["koC5u0"],"children":["Q0LFq_"],"transfer":{"groups":[{},{"lines":[{"theme":["zhengzhou","zz9","#828C47","#fff"],"name":["城郊线","CHENGJIAO Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Q0LFq_":{"name":["遵大路","ZUNDA LU"],"num":"08","services":["local"],"parents":["8VvPUp"],"children":["a2Qao1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"a2Qao1":{"name":["苑陵故城西","YUANLINGGUCHENG XI"],"num":"09","services":["local"],"parents":["Q0LFq_"],"children":["8JtL8-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8JtL8-":{"name":["洵美路","XUNMEI LU"],"num":"10","services":["local"],"parents":["a2Qao1"],"children":["PK0_cH"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"PK0_cH":{"name":["龙王","LONGWANG"],"num":"11","services":["local"],"parents":["8JtL8-"],"children":["ZTlHU2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ZTlHU2":{"name":["龙王南","LONGWANG NAN"],"num":"12","services":["local"],"parents":["PK0_cH"],"children":["cgR1gv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cgR1gv":{"name":["双鹤湖北","SHUANGHEHU BEI"],"num":"13","services":["local"],"parents":["ZTlHU2"],"children":["GhRu0-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GhRu0-":{"name":["双鹤湖","SHUANGHEHU"],"num":"14","services":["local"],"parents":["cgR1gv"],"children":["WNiv-x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WNiv-x":{"name":["双鹤湖南","SHUANGHEHUNAN"],"num":"15","services":["local"],"parents":["GhRu0-"],"children":["RwLe5_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RwLe5_":{"name":["八千","BAQIAN"],"num":"16","services":["local"],"parents":["WNiv-x"],"children":["vZoVGm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vZoVGm":{"name":["双庙李","SHUANGMIAOLI"],"num":"17","services":["local"],"parents":["RwLe5_"],"children":["ho7kPv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ho7kPv":{"name":["大周","DAZHOU"],"num":"18","services":["local"],"parents":["vZoVGm"],"children":["HTTawk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HTTawk":{"name":["颍川路","YINGCHUAN LU"],"num":"19","services":["local"],"parents":["ho7kPv"],"children":["3VOK9a"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3VOK9a":{"name":["葛天源","GETIANYUAN"],"num":"20","services":["local"],"parents":["HTTawk"],"children":["uY17Uh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"uY17Uh":{"name":["永和路","YONGHE LU"],"num":"21","services":["local"],"parents":["3VOK9a"],"children":["IWW-xD"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"IWW-xD":{"name":["农大路","NONGDA LU"],"num":"22","services":["local"],"parents":["uY17Uh"],"children":["nXKI06"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"nXKI06":{"name":["体育中心","XUCHANG SPORTS CENTER"],"num":"23","services":["local"],"parents":["IWW-xD"],"children":["403_H8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"403_H8":{"name":["电气谷","DIANQIGU"],"num":"24","services":["local"],"parents":["nXKI06"],"children":["PWR9Rc"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"PWR9Rc":{"name":["芙蓉湖","FURONGHU"],"num":"25","services":["local"],"parents":["403_H8"],"children":["SSP9KC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"SSP9KC":{"name":["鹿鸣湖","LUMINGHU"],"num":"26","services":["local"],"parents":["PWR9Rc"],"children":["QC003H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"17","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.16.3"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，线路名称应为“郑许线”而不为“17号线”，请您修改后重新提交，感谢您的贡献。
