### ISSUE TITLE
Resources: New templates of Zhengzhou Metro

### ISSUE THREAD

**Issue by G9913** [railmapgen/rmg-templates#1023]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Lines opening status:** OPENED

**Reference source:** 6. 其他（请于下方注明）

**Justification:** 参考来源：https://api.zzmetro.com/lines/map

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zzmetro" line="zx" major="false"><summary>zzmetro/zx</summary><details type="name">{"en":"ZHENGXU Line","zh-Hans":"郑许线","zh-Hant":"鄭許線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":2000},"svg_height":350,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["zhengzhou","zz17","#1D4155","#fff"],"line_name":["郑许线","Zhengxu Line"],"current_stn_idx":"stn_sC0p212K41","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["stn_ORrPXLHThD"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["stn_sC0p212K41"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_sC0p212K41":{"name":["许昌东站","XUCHANG EAST\\RAILWAY STATION"],"num":"24","services":["local"],"parents":["stn_K65AEpmWCL"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_K65AEpmWCL":{"name":["鹿鸣湖","LUMINGHU"],"num":"23","services":["local"],"parents":["stn_DacdsTHue6"],"children":["stn_sC0p212K41"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_DacdsTHue6":{"name":["芙蓉湖","FURONGHU"],"num":"22","services":["local"],"parents":["stn_iv3tVVneC_"],"children":["stn_K65AEpmWCL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_iv3tVVneC_":{"name":["电气谷","DIANQIGU"],"num":"21","services":["local"],"parents":["stn_WEmNxgS7n8"],"children":["stn_DacdsTHue6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_WEmNxgS7n8":{"name":["体育中心","TIYUZHONGXIN"],"num":"20","services":["local"],"parents":["stn_EQHG-b6M59"],"children":["stn_iv3tVVneC_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_EQHG-b6M59":{"name":["农大路","NONGDALU"],"num":"19","services":["local"],"parents":["stn_IMEJBNU70Q"],"children":["stn_WEmNxgS7n8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_IMEJBNU70Q":{"name":["永和路","YONGHELU"],"num":"18","services":["local"],"parents":["stn_wx40iwpnUC"],"children":["stn_EQHG-b6M59"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_wx40iwpnUC":{"name":["葛天源","GETIANYUAN"],"num":"17","services":["local"],"parents":["stn_Z6ch3AfxLO"],"children":["stn_IMEJBNU70Q"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_Z6ch3AfxLO":{"name":["颍川路","YINGCHUAN LU"],"num":"16","services":["local"],"parents":["stn_4xCkHW30bG"],"children":["stn_wx40iwpnUC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_4xCkHW30bG":{"name":["大周","DAZHOU"],"num":"15","services":["local"],"parents":["stn_jzl-kfUbKW"],"children":["stn_Z6ch3AfxLO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_jzl-kfUbKW":{"name":["双庙李","SHUANGMIAOLI"],"num":"14","services":["local"],"parents":["stn_zYYIkMhN9E"],"children":["stn_4xCkHW30bG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_zYYIkMhN9E":{"name":["八千","BAQIAN"],"num":"13","services":["local"],"parents":["stn_YDlQ90msew"],"children":["stn_jzl-kfUbKW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_YDlQ90msew":{"name":["双鹤湖南","SHUANGHEHU NAN"],"num":"12","services":["local"],"parents":["stn_MbSTbG5C0U"],"children":["stn_zYYIkMhN9E"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_MbSTbG5C0U":{"name":["双鹤湖","SHUANGHEHU"],"num":"11","services":["local"],"parents":["stn_VGtCDaDQ73"],"children":["stn_YDlQ90msew"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_VGtCDaDQ73":{"name":["双鹤湖北","SHUANGHEHU BEI"],"num":"10","services":["local"],"parents":["stn_n_jAbVE5WS"],"children":["stn_MbSTbG5C0U"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_n_jAbVE5WS":{"name":["龙王南","LONGWANG NAN"],"num":"9","services":["local"],"parents":["stn_WEqfZKnnf8"],"children":["stn_VGtCDaDQ73"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_WEqfZKnnf8":{"name":["龙王","LONGWANG"],"num":"8","services":["local"],"parents":["stn_GJCBzoachr"],"children":["stn_n_jAbVE5WS"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_GJCBzoachr":{"name":["洵美路","XUNMEI LU"],"num":"7","services":["local"],"parents":["stn_YdTmjWyGTs"],"children":["stn_WEqfZKnnf8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_YdTmjWyGTs":{"name":["苑陵故城西","YUANLINGGUCHENG XI"],"num":"6","services":["local"],"parents":["stn_k4YuHicbH2"],"children":["stn_GJCBzoachr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_k4YuHicbH2":{"name":["遵大路","ZUNDA LU"],"num":"5","services":["local"],"parents":["stn_85sPRNaLWO"],"children":["stn_YdTmjWyGTs"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_85sPRNaLWO":{"name":["新郑机场","XINZHENG INTERNATIONAL\\AIRPORT"],"num":"4","services":["local"],"parents":["stn_hgm-1-KCRQ"],"children":["stn_k4YuHicbH2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"stn_hgm-1-KCRQ":{"name":["翱翔路","AOXIANG LU"],"num":"3","services":["local"],"parents":["h8CGvC"],"children":["stn_85sPRNaLWO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250,"branch":{}},"stn_ADR0SFo6Qf":{"name":["港区北","GANGQU NORTH"],"num":"2","services":["local"],"parents":["stn_ORrPXLHThD"],"children":["c-oGKJ"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz9","#828C47","#fff"],"name":["城郊线","Suburban Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250,"branch":{}},"stn_ORrPXLHThD":{"name":["长安路北","CHANG'AN LU BEI"],"num":"1","services":["local"],"parents":["linestart"],"children":["stn_ADR0SFo6Qf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"c-oGKJ":{"name":["文体中心","WENTIZHONGXIN"],"num":"00","services":["local"],"parents":["stn_ADR0SFo6Qf"],"children":["h8CGvC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"h8CGvC":{"name":["枣园","ZAOYUAN"],"num":"00","services":["local"],"parents":["c-oGKJ"],"children":["stn_hgm-1-KCRQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"郑许","psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"version":"5.16.2"}</details></details>

**Comment by 52PD** [comment]
> @52PD 最终提交的模板是[本模板](https://github.com/railmapgen/rmg-palette/issues/1070)。

Closed as duplicate contents, the remained version (#1027 ) was conformed by the author with reason above.
