### ISSUE TITLE
Resources: New templates of Basic（Guizhou-Guangzhou Highspeed Railway）

### ISSUE THREAD

**Issue by 0311TiYuXiLu** [railmapgen/rmg-templates#1031]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Lines opening status:** OPENED

**Reference source:** 互联网上的路线图

**Reference link:** https://baike.baidu.com/item/%E8%B4%B5%E5%B9%BF%E9%AB%98%E9%80%9F%E9%93%81%E8%B7%AF/7258814#2-2

**Justification:** 贵广复刻

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="basic" line="GGHR" major="false"><summary>basic/GGHR</summary><details type="name">{"en":"Guizhou to Guangzhou Highspeed Railway","zh-Hans":"默认","zh-Hant":"預設"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":3000,"railmap":3000,"indoor":3000},"svg_height":300,"style":"gzmtr","y_pc":56,"padding":21,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hongkong","twl","#e60013","#fff"],"line_name":["贵州-广州高速铁路","Guizhou-Guangzhou Highspeed Railway"],"current_stn_idx":"xUPX8K","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["fOKBsC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"fOKBsC":{"name":["广州南站","Guanzgzhou South Railway Station"],"num":"01","services":["local","express","direct"],"parents":["linestart"],"children":["uGVNK-"],"transfer":{"groups":[{"lines":[]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"},"uGVNK-":{"name":["佛山西站","Foshan West Railway Station"],"num":"02","services":["local"],"parents":["fOKBsC"],"children":["AdtSdn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["F9jGQ7"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"AdtSdn":{"name":["三水南站","Sanshui South Railway Station"],"num":"03","services":["local"],"parents":["uGVNK-"],"children":["RYwL0x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"RYwL0x":{"name":["肇庆东站","Zhaoqing East Railway Station"],"num":"04","services":["local"],"parents":["AdtSdn"],"children":["VT-XU8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"VT-XU8":{"name":["广宁站","Guangning Railway Station"],"num":"05","services":["local"],"parents":["RYwL0x"],"children":["24SsLq"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"24SsLq":{"name":["怀集站","Huaiji Railway Station"],"num":"06","services":["local"],"parents":["VT-XU8"],"children":["XwYoht"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"XwYoht":{"name":["贺州站","Hezhou Railway Station"],"num":"07","services":["local"],"parents":["24SsLq"],"children":["4xsi1d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"4xsi1d":{"name":["钟山西站","Zhongshan West Railway Station"],"num":"08","services":["local"],"parents":["XwYoht"],"children":["eQv1VG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"eQv1VG":{"name":["恭城站","Gongcheng Raiwway Station"],"num":"09","services":["local"],"parents":["4xsi1d"],"children":["XMNIHY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"XMNIHY":{"name":["阳朔站","Yangshuo Railway Station"],"num":"10","services":["local"],"parents":["eQv1VG"],"children":["xUPX8K"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"xUPX8K":{"name":["桂林西站","Guiling West Railway Station"],"num":"11","services":["local","express"],"parents":["XMNIHY"],"children":["tj0WS_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"tj0WS_":{"name":["五通站","Wutong Railway Station"],"num":"12","services":["local"],"parents":["xUPX8K"],"children":["hkajkW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"hkajkW":{"name":["三江南站","Sanjiang South Railway Station"],"num":"13","services":["local"],"parents":["tj0WS_"],"children":["m6bTK1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"m6bTK1":{"name":["从江站","Congjiang Railway Station"],"num":"14","services":["local"],"parents":["hkajkW"],"children":["7QTCdC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"7QTCdC":{"name":["榕江站","Rongjiang Railway Station"],"num":"15","services":["local"],"parents":["m6bTK1"],"children":["g8tB4S"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"g8tB4S":{"name":["三都县站","Sanduxian Railway Station"],"num":"16","services":["local"],"parents":["7QTCdC"],"children":["fek6DY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"fek6DY":{"name":["都匀东站","Dunyun East Railway Station"],"num":"17","services":["local"],"parents":["g8tB4S"],"children":["SxipYc"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"},"SxipYc":{"name":["贵定县站","Guidingxian Railway Station"],"num":"18","services":["local"],"parents":["fek6DY"],"children":["O5DmJ6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"O5DmJ6":{"name":["龙里北站","Longli North Railway Station"],"num":"19","services":["local"],"parents":["SxipYc"],"children":["XOb2Z2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"XOb2Z2":{"name":["龙洞堡站","Longdongbu Railway Station"],"num":"20","services":["local"],"parents":["O5DmJ6"],"children":["F9jGQ7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"F9jGQ7":{"name":["贵阳北站","Guiyang North Railway Station"],"num":"21","services":["local","express","direct"],"parents":["XOb2Z2"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":true,"terminal":false},"line_num":"GGHR","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":39,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Charlis-Wong** [comment]
@0311TiYuXiLu 您好，
由於您沒有刪除(REPLACE ME/替代我)，因此系統識別不到您的作品。請重開一個Issue提交，不好意思。

**Comment by Charlis-Wong** [comment]
@wongchito / @thekingofcity / @28yfang / @Windows-Taskmgr 請關閉此Issue，謝謝

**Comment by 28yfang** [comment]
@Charlis-Wong 不用重开，直接把那段文字删了就可以了
（我已经删掉了）
