### ISSUE TITLE
Resources: New templates of Shanghai Metro Line 13

### ISSUE THREAD

**Issue by 816R** [railmapgen/rmg-templates#1037]
**Lines opening status:** OPENED

**Reference source:** 6. 其他（请于下方注明）

**Justification:** 长清路换乘13号线英文未加数字

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="shmetro" line="sh7" major="false"><summary>shmetro/sh7</summary><details type="name">{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線","ko":"7호선"}</details><details type="param">{"style":"shmetro","svg_height":400,"padding":8.750201061605276,"y_pc":40,"theme":["shanghai","sh7","#ED6F00","#000"],"direction":"r","current_stn_idx":"wyk2","platform_num":"","stn_list":{"linestart":{"parents":[],"children":["l1mz"],"name":["路綫左端","LEFT END"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"00","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫右端","RIGHT END"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"00","loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["linestart"],"children":["5qhf"],"name":["美兰湖","Meilan Lake"],"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["lineend"],"parents":["3jml"],"name":["花木路","Huamu Road"],"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"qg34":{"name":["芳华路","Fanghua Road"],"num":"00","services":["local"],"parents":["vifb"],"children":["3jml"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"3jml":{"name":["龙阳路","Longyang Road"],"num":"00","services":["local"],"parents":["qg34"],"children":["iwf6"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh2","#82BF25","#000"],"name":["2号线","Line 2"]},{"theme":["shanghai","sh16","#98D1C0","#000"],"name":["16号线","Line 16"]},{"theme":["shanghai","sh18","#C4984F","#000"],"name":["18号线","Line 18"]}]},{},{"lines":[{"theme":["shanghai","maglev","#009090","#fff"],"name":["磁浮线","Maglev Line"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"vifb":{"name":["锦绣路","Jinxiu Road"],"num":"00","services":["local"],"parents":["a9xr"],"children":["qg34"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"a9xr":{"name":["杨高南路","South Yanggao Road"],"num":"00","services":["local"],"parents":["mrhv"],"children":["vifb"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"mrhv":{"name":["高科西路","West Gaoke Road"],"num":"00","services":["local"],"parents":["vhwl"],"children":["a9xr"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh6","#D40068","#fff"],"name":["6号线","Line 6"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"vhwl":{"name":["云台路","Yuntai Road"],"num":"00","services":["local"],"parents":["zv8o"],"children":["mrhv"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"zv8o":{"name":["耀华路","Yaohua Road"],"num":"00","services":["local"],"parents":["gwtu"],"children":["vhwl"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh8","#0094D8","#fff"],"name":["8号线","Line 8"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"gwtu":{"name":["长清路","Changqing Road"],"num":"00","services":["local"],"parents":["b2hj"],"children":["zv8o"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{},{"lines":[{"theme":["other","other","#EF95CF","#000"],"name":["13号线","Line 13"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"b2hj":{"name":["后滩","Houtan"],"num":"00","services":["local"],"parents":["yec8"],"children":["gwtu"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"yec8":{"name":["龙华中路","Middle Longhua Road"],"num":"00","services":["local"],"parents":["v44x"],"children":["b2hj"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh12","#007A60","#fff"],"name":["12号线","Line 12"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"v44x":{"name":["东安路","Dong'an Road"],"num":"00","services":["local"],"parents":["g9l3"],"children":["yec8"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh4","#461D84","#fff"],"name":["4号线","Line 4"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"g9l3":{"name":["肇嘉浜路","Zhaojiabang Road"],"num":"00","services":["local"],"parents":["wyk2"],"children":["v44x"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh9","#87CAED","#000"],"name":["9号线","Line 9"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"wyk2":{"name":["常熟路","Changshu Road"],"num":"00","services":["local"],"parents":["oua9"],"children":["g9l3"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh1","#E3002B","#fff"],"name":["1号线","Line 1"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"oua9":{"name":["静安寺","Jing'an Temple"],"num":"00","services":["local"],"parents":["9lmq"],"children":["wyk2"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh2","#82BF25","#000"],"name":["2号线","Line 2"]},{"theme":["shanghai","sh14","#626020","#fff"],"name":["14号线","Line 14"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"9lmq":{"name":["昌平路","Changping Road"],"num":"00","services":["local"],"parents":["48po"],"children":["oua9"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"48po":{"name":["长寿路","Changshou Road"],"num":"00","services":["local"],"parents":["16qe"],"children":["9lmq"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#EF95CF","#000"],"name":["13号线","Line 13"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"16qe":{"name":["镇坪路","Zhenping Road"],"num":"00","services":["local"],"parents":["zqho"],"children":["48po"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh3","#FCD600","#000"],"name":["3号线","Line 3"]},{"theme":["shanghai","sh4","#461D84","#fff"],"name":["4号线","Line 4"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"zqho":{"name":["岚皋路","Lan'gao Road "],"num":"00","services":["local"],"parents":["2i8c"],"children":["16qe"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"2i8c":{"name":["新村路","Xincun Road"],"num":"00","services":["local"],"parents":["ltqr"],"children":["zqho"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"ltqr":{"name":["大华三路","Dahuasan Road"],"num":"00","services":["local"],"parents":["3j1w"],"children":["2i8c"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"3j1w":{"name":["行知路","Xingzhi Road"],"num":"00","services":["local"],"parents":["epvt"],"children":["ltqr"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"epvt":{"name":["大场镇","Dachang Town"],"num":"00","services":["local"],"parents":["mb4g"],"children":["3j1w"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"mb4g":{"name":["场中路","Changzhong Road"],"num":"00","services":["local"],"parents":["26gh"],"children":["epvt"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"26gh":{"name":["上大路","Shangda Road"],"num":"00","services":["local"],"parents":["96rp"],"children":["mb4g"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"96rp":{"name":["南陈路","Nanchen Road"],"num":"00","services":["local"],"parents":["j0f3"],"children":["26gh"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"j0f3":{"name":["上海大学","Shanghai University"],"num":"00","services":["local"],"parents":["ljq6"],"children":["96rp"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"ljq6":{"name":["祁华路","Qihua Road"],"num":"00","services":["local"],"parents":["g7x1"],"children":["j0f3"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"g7x1":{"name":["顾村公园","Gucun Park"],"num":"00","services":["local"],"parents":["6iy3"],"children":["ljq6"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["shanghai","sh15","#BCA886","#000"],"name":["15号线","Line 15"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"6iy3":{"name":["刘行","Liuhang"],"num":"00","services":["local"],"parents":["qfyk"],"children":["g7x1"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"qfyk":{"name":["潘广路","Panguang Road"],"num":"00","services":["local"],"parents":["5qhf"],"children":["6iy3"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"5qhf":{"name":["罗南新村","Luonan Xincun"],"num":"00","services":["local"],"parents":["l1mz"],"children":["qfyk"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355}},"line_name":["7号线","Line7"],"psd_num":"1","line_num":"7","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1500,"runin":1500,"railmap":2000,"indoor":2500},"namePosMTR":{"isStagger":true,"isFlip":true},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":34,"version":"5.16.4"}</details></details>

**Comment by 28yfang** [comment]
您好，经检查，您的模版无问题，并将在稍后进行汇入。感谢您的贡献！
