### ISSUE TITLE
Resources: New templates of Qingdao Metro

### ISSUE THREAD

**Issue by SamBianYiLin** [railmapgen/rmg-templates#1046]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | To be opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://zh.wikipedia.org/wiki/%E9%9D%92%E5%B2%9B%E5%9C%B0%E9%93%816%E5%8F%B7%E7%BA%BF |
|     Justification     | 维基百科详细信息以及个人媒体已经宣布，青岛地铁6号线一期工程在今年稍晚时间将进行试运营。 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="qdmetro" line="6" major="false"><summary>qdmetro/6</summary><details type="name">{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1800,"railmap":1600,"indoor":1200},"svg_height":400,"style":"gzmtr","y_pc":60,"padding":4,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["qingdao","qd6","#6CACE4","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"s5AWMY","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["_8f9GF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"_8f9GF":{"name":["横云山路","Hengyunshan Rd"],"num":"01","services":["local"],"parents":["linestart"],"children":["s5AWMY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"s5AWMY":{"name":["山王河(福莱社区)","Shanwanghe"],"num":"02","services":["local"],"parents":["_8f9GF"],"children":["Tu4ZMb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["7Icwb6"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Tu4ZMb":{"name":["河洛埠(中德生态园)","Heluobu"],"num":"03","services":["local"],"parents":["s5AWMY"],"children":["XADdAt"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"XADdAt":{"name":["青岛九中","Qingdao No.9 Middle School"],"num":"04","services":["local"],"parents":["Tu4ZMb"],"children":["iiWV9d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"iiWV9d":{"name":["抓马山","Zhuama Mountain"],"num":"05","services":["local"],"parents":["XADdAt"],"children":["5-c1hm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"5-c1hm":{"name":["马家楼","Majialou"],"num":"06","services":["local"],"parents":["iiWV9d"],"children":["V-WpD_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"V-WpD_":{"name":["薛家泊子","Xuejiapozi"],"num":"07","services":["local"],"parents":["5-c1hm"],"children":["nv6GIi"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"nv6GIi":{"name":["港头","Gangtou"],"num":"08","services":["local"],"parents":["V-WpD_"],"children":["--hvrl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"--hvrl":{"name":["青大附院西海岸院区","The Affiliated Hospital of Qingdao Univeristy West Coast Part"],"num":"09","services":["local"],"parents":["nv6GIi"],"children":["hRGuiq"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"hRGuiq":{"name":["扒山(滨海学院)","Pashan(Qingdao Binhai University)"],"num":"10","services":["local"],"parents":["--hvrl"],"children":["uQsosX"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"uQsosX":{"name":["钱塘江路(青职学院)","Qiantangjiang Rd(Qingdao Technical College)"],"num":"11","services":["local"],"parents":["hRGuiq"],"children":["QnJ-Uh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"QnJ-Uh":{"name":["九顶山","Jiudingshan"],"num":"12","services":["local"],"parents":["uQsosX"],"children":["mLtwGE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"mLtwGE":{"name":["王家港","Wangjiagang"],"num":"13","services":["local"],"parents":["QnJ-Uh"],"children":["DX-UNy"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd1","#EAAA00","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"DX-UNy":{"name":["北门外","Beimenwai"],"num":"14","services":["local"],"parents":["mLtwGE"],"children":["kTLKbU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"kTLKbU":{"name":["西门外","Ximenwai"],"num":"15","services":["local"],"parents":["DX-UNy"],"children":["a0l3yK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"a0l3yK":{"name":["毛家山(黄海学院)","Maojiashan(Qingdao Huanghai University)"],"num":"16","services":["local"],"parents":["kTLKbU"],"children":["K4Dc3W"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"K4Dc3W":{"name":["赵家庙(影视产业园)","Zhaojiamiao(Film and Television Industrial Park)"],"num":"17","services":["local"],"parents":["a0l3yK"],"children":["yXH1XO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"yXH1XO":{"name":["星海滩路","Xinghaitan Rd"],"num":"18","services":["local"],"parents":["K4Dc3W"],"children":["euezhI"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"euezhI":{"name":["华山","Huashan"],"num":"19","services":["local"],"parents":["yXH1XO"],"children":["yo0VBA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"yo0VBA":{"name":["辛屯(灵山湾)","Xintun(Lingshan Bay)"],"num":"20","services":["local"],"parents":["euezhI"],"children":["7Icwb6"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd13","#00AB84","#fff"],"name":["13号线","Line 13"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"7Icwb6":{"name":["灵山湾","Lingshan Bay"],"num":"21","services":["local"],"parents":["yo0VBA"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":75,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Charlis-Wong** [comment]
@SamBianYiLin 您好，由於您沒有去除（Replace Me/替代我），因此系統不能識別您的作品。請在編輯中去除。感謝您的貢獻以及配合。

**Comment by 28yfang** [comment]
您好，感谢您的贡献。经检查，您的模版含有以下问题：
1. 青岛线路图中并没有线路与车站编号，因此请将风格替换成上海或港铁风格。
2. 山王河站英文名错误，正确的为Shanwanghe (Fulai Community)
3. 河洛埠站英文名错误，正确的为Heluobu (Sino-German Ecopark)
4. 青岛九中站中英文名均错误，正确的为：青岛九中(幸福小镇) Qingdao No. 9 High School\(Xingfuxiaozhen)
5. 抓马山站英文名错误，正确的为Zhuamashan
6. 青大附院西海岸院区站英文名错误，正确的为West Coast Campus of the\Affiliated Hospital of Qingdao University
7. 赵家庙站英文名错误，正确的为Zhaojiamiao\(Film Metropolis)
8. 辛屯站中英文名均错误，正确的为：辛屯 Xintun

请在修正后重新提交，并附上本议题编号（#1046），感谢！

**Comment by 28yfang** [comment]
您好，#1267 已经做出同样更新且已经汇入，因此您无需继续进行更新，感谢。
