### ISSUE TITLE
Resources: New templates of Harbin Metro

### ISSUE THREAD

**Issue by jiaaoran** [railmapgen/rmg-templates#1066]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | To be opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://baike.baidu.com/item/%E5%93%88%E5%B0%94%E6%BB%A8%E5%9C%B0%E9%93%819%E5%8F%B7%E7%BA%BF/17505454 |
|     Justification     | 9号线（机场线） |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hrbmetro" line="9号线（暂未开通）" major="false"><summary>hrbmetro/9号线（暂未开通）</summary><details type="name">{"en":"Line 9","zh-Hans":"(Not yet available)","zh-Hant":"9号线"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":400,"style":"gzmtr","y_pc":51,"padding":8,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#bea1cf","#fff"],"line_name":["9号线","Line 9"],"current_stn_idx":"mCZOKi","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["RZu2WO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"rkA65n":{"name":["阎家岗","Yanjiagang"],"num":"10","services":["local"],"parents":["EztgeJ"],"children":["mCZOKi"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"mCZOKi":{"name":["太平机场","Taiping Airport"],"num":"11","services":["local"],"parents":["rkA65n"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["mCZOKi"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RZu2WO":{"name":["哈尔滨站","Harbin Railway Station"],"num":"01","services":["local"],"parents":["linestart"],"children":["HZDFZH"],"transfer":{"groups":[{"lines":[{"theme":["harbin","hrb2","#44AF52","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HZDFZH":{"name":["哈工大","Harbin Institute of Technology"],"num":"02","services":["local"],"parents":["RZu2WO"],"children":["w2f-Bf"],"transfer":{"groups":[{"lines":[{"theme":["harbin","hrb1","#C8102E","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"w2f-Bf":{"name":["林兴街","Linxing Street"],"num":"03","services":["local"],"parents":["HZDFZH"],"children":["nyMwHy"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#66a4ff","#fff"],"name":["R1线","Line R1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"nyMwHy":{"name":["学府路","Xuefu Road"],"num":"04","services":["local"],"parents":["w2f-Bf"],"children":["LZOy1v"],"transfer":{"groups":[{"lines":[{"theme":["harbin","hrb1","#C8102E","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"LZOy1v":{"name":["未命名车站-1","Unnamed Station-1"],"num":"05","services":["local"],"parents":["nyMwHy"],"children":["X9CjLy"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ffab57","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"X9CjLy":{"name":["未命名车站-2","Unnamed Station-2"],"num":"06","services":["local"],"parents":["LZOy1v"],"children":["B68YQS"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff9999","#fff"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"B68YQS":{"name":["哈尔滨西站","Harbin West Railway Station"],"num":"07","services":["local"],"parents":["X9CjLy"],"children":["Gb3GGn"],"transfer":{"groups":[{"lines":[{"theme":["harbin","hrb3","#FFC72C","#fff"],"name":["3号线","Line 3"]},{"theme":["other","other","#ffab57","#fff"],"name":["5号线","Line 5"]}]},{},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Gb3GGn":{"name":["新发镇","Xinfazhen"],"num":"08","services":["local"],"parents":["B68YQS"],"children":["EztgeJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EztgeJ":{"name":["新农镇","Xinnongzhen"],"num":"09","services":["local"],"parents":["Gb3GGn"],"children":["rkA65n"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gzgf","direction_gz_x":5,"direction_gz_y":92,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.16.9"}</details></details>

**Comment by linchen1965** [comment]
您好，我们只接收已开通线路或近期开通线路的模板，以保证准确，鉴于此线路为规划中，我们不能使用您的作品，谢谢！
