### ISSUE TITLE
Resources: New templates of Wuxi Metro

### ISSUE THREAD

**Issue by niuzhix** [railmapgen/rmg-templates#1073]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Lines opening status:** OPENED

**Reference source:** 6. 其他（请于下方注明）

**Justification:** 添加无锡地铁于2024年1月31日开通的S1线（锡澄线），来源于“http://www.wxmetro.net/ws/front/cn/55/content/7201.html”
（霞客湾科学城站来源于“https://www.sohu.com/a/474711115_121123912”）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="wxmetro" line="S1" major="false"><summary>wxmetro/S1</summary><details type="name">{"en":"Line S1","zh-Hans":"S1号线","zh-Hant":"S1號線","ko":"S1号線"}</details><details type="param">{"svgViewBoxZoom":70,"svgViewBoxMin":{"x":500.29895782473255,"y":-773.8792991638205},"graph":{"options":{"type":"directed","multi":true,"allowSelfLoops":true},"attributes":{},"nodes":[{"key":"stn_mohMom-MNX","attributes":{"visible":true,"zIndex":0,"x":950,"y":-510,"type":"shmetro-basic","shmetro-basic":{"names":["马镇","Mazhen"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_iJ9LcbiwJw","attributes":{"visible":true,"zIndex":0,"x":950,"y":-580,"type":"shmetro-basic","shmetro-basic":{"names":["霞客湾科学城","Xiakewan Scinece Museum"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"misc_node_VjG4r9syx_","attributes":{"visible":true,"zIndex":0,"x":985,"y":-565,"type":"text","text":{"content":"预留站点","fontSize":10,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"en","color":["shanghai","pjl","#B5B5B6","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}},{"key":"stn_TahSotJRNd","attributes":{"visible":true,"zIndex":0,"x":950,"y":-650,"type":"shmetro-basic","shmetro-basic":{"names":["青阳","Qingyang"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_3GWmiFiI79","attributes":{"visible":true,"zIndex":0,"x":950,"y":-720,"type":"shmetro-basic","shmetro-basic":{"names":["峭岐","Qiaoqi"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_WA9YKCxPta","attributes":{"visible":true,"zIndex":0,"x":950,"y":-790,"type":"shmetro-basic","shmetro-basic":{"names":["南闸","Nanzha"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_SCJd0WDGKp","attributes":{"visible":true,"zIndex":0,"x":950,"y":-860,"type":"shmetro-basic","shmetro-basic":{"names":["江阴高铁站","Jiangyin Railway Station"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"misc_node_SDnrZXJNiQ","attributes":{"visible":true,"zIndex":0,"x":975,"y":-840,"type":"facilities","facilities":{"type":"railway"}}},{"key":"stn_OZHc_4qPIX","attributes":{"visible":true,"zIndex":0,"x":950,"y":-930,"type":"shmetro-basic","shmetro-basic":{"names":["江阴中医院","Jiangyin TCM Hospital"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_RXDuweh7PX","attributes":{"visible":true,"zIndex":0,"x":950,"y":-1000,"type":"shmetro-basic","shmetro-basic":{"names":["南门","Nanmen"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_lm7RDhe-De","attributes":{"visible":true,"zIndex":0,"x":950,"y":-1070,"type":"shmetro-basic","shmetro-basic":{"names":["中山公园","Zhongshan Park"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"stn_x-XgT5lOKS","attributes":{"visible":true,"zIndex":0,"x":950,"y":-1140,"type":"shmetro-basic","shmetro-basic":{"names":["江阴外滩","Jiangyin Bund"],"nameOffsetX":"right","nameOffsetY":"middle"}}},{"key":"misc_node_aMlDY8SIy9","attributes":{"visible":true,"zIndex":0,"x":890,"y":-1165,"type":"bjsubway-text-line-badge","bjsubway-text-line-badge":{"names":["S1线/锡澄线","Line S1/Xicheng Line"],"color":["wuxi","wx1","#EE2737","#fff"]}}},{"key":"misc_node_VnABRiL3lw","attributes":{"visible":true,"zIndex":0,"x":875,"y":-510,"type":"bjsubway-text-line-badge","bjsubway-text-line-badge":{"names":["S1线/锡澄线","Line S1/Xicheng Line"],"color":["wuxi","wx1","#EE2737","#fff"]}}}],"edges":[{"key":"line_rCgjlrY90Y","source":"stn_iJ9LcbiwJw","target":"stn_mohMom-MNX","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","reconcileId":"","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]}}},{"key":"line_vcAoV1C_WY","source":"stn_iJ9LcbiwJw","target":"stn_TahSotJRNd","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","reconcileId":"","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]}}},{"key":"line_hSQeBmQfPg","source":"stn_TahSotJRNd","target":"stn_3GWmiFiI79","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line__PvcH1tyR4","source":"stn_3GWmiFiI79","target":"stn_WA9YKCxPta","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line_p-rf3xtQ6E","source":"stn_WA9YKCxPta","target":"stn_SCJd0WDGKp","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line_XvfRyC8D2B","source":"stn_SCJd0WDGKp","target":"stn_OZHc_4qPIX","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line__kNTkVrLew","source":"stn_OZHc_4qPIX","target":"stn_RXDuweh7PX","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line_XDM6VscjJu","source":"stn_RXDuweh7PX","target":"stn_lm7RDhe-De","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}},{"key":"line_8MvUs42kc8","source":"stn_lm7RDhe-De","target":"stn_x-XgT5lOKS","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["wuxi","wx1","#EE2737","#fff"]},"reconcileId":""}}]},"version":26}</details></details>

**Comment by 28yfang** [comment]
您好，由于您的模版已经损坏无法打开，我们无法对其进行检查。请您重新提交一份可以打开的模版，感谢。
