### ISSUE TITLE
Resources: New templates of Wuhan Metro

### ISSUE THREAD

**Issue by Liangyunbao** [railmapgen/rmg-templates#1075]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | https://www.wuhanrt.com/wh-metro-public-page/comprehensive.html?anchorPoint=%E5%88%97%E8%BD%A6%E6%97%B6%E5%88%BB%E8%A1%A8& |
|     Justification     | 没有19号线 |
| Major update of Line 19/19号线/19號線 | 增加了已开通的十九号线 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="wh19" major="true"><summary>whrt/wh19(M)</summary><details type="name">{"en":"Line 19","zh-Hans":"19号线","zh-Hant":"19號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["wuhan","wh19","#18a079","#fff"],"line_name":["",""],"current_stn_idx":"stn_1PaclHM9ZD","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["stn_1PaclHM9ZD"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["stn_VjJBGSMAdY"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_VjJBGSMAdY":{"name":["新月溪公园","Xinyuexi Park\\"],"num":"4","services":["local"],"parents":["stn_sISY22pivS"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_sISY22pivS":{"name":["花山新城","Huashanxincheng"],"num":"3","services":["local"],"parents":["stn_1PaclHM9ZD"],"children":["stn_VjJBGSMAdY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_1PaclHM9ZD":{"name":["武汉站西广场","West Square of Wuhan Railway Station"],"num":"1","services":["local"],"parents":["linestart"],"children":["stn_sISY22pivS"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"","psd_num":"1","info_panel_type":"sh","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，对于您的模板长时间未被审核，我们深表歉意。
此网站在此评论发布时已无法打开，且利用“网页时光机”工具查看到此issue发布前的此网站也无法打开。此网站确实是正确的吗？麻烦您解释下。

**Comment by Windows-Taskmgr** [comment]
您好，此模板已超过一个月未回复，遵循惯例我们将关闭此issue，谢谢配合。感谢您的贡献。
