### ISSUE TITLE
Resources: New templates of Wuhan Metro

### ISSUE THREAD

**Issue by Liangyunbao** [railmapgen/rmg-templates#1077]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | https://www.wuhanrt.com/wh-metro-public-page/comprehensive.html?anchorPoint=%E5%88%97%E8%BD%A6%E6%97%B6%E5%88%BB%E8%A1%A8& |
|     Justification     | 将路线图拉直使线路更真实 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="wh11" major="false"><summary>whrt/wh11</summary><details type="name">{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["wuhan","wh11","#F2CF01","#fff"],"line_name":["",""],"current_stn_idx":"stn_-GcdcIiqqQ","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["stn_-GcdcIiqqQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["stn_Y3edyu9KXT"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_Y3edyu9KXT":{"name":["葛店南站","Gedian South Railway Station"],"num":"14","services":["local"],"parents":["stn_F3JxmvaE6B"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_F3JxmvaE6B":{"name":["左岭","Zuoling"],"num":"13","services":["local"],"parents":["stn_mAf8sPp5IY"],"children":["stn_Y3edyu9KXT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_mAf8sPp5IY":{"name":["未来三路","Weilai 3rd Road"],"num":"12","services":["local"],"parents":["stn_QNANSZ6Ovu"],"children":["stn_F3JxmvaE6B"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_QNANSZ6Ovu":{"name":["未来一路","Weilai 1st Road"],"num":"11","services":["local"],"parents":["stn_XcA-F9PcEl"],"children":["stn_mAf8sPp5IY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_XcA-F9PcEl":{"name":["长岭山","Changlingshan"],"num":"10","services":["local"],"parents":["stn_CwkR8R5Ci6"],"children":["stn_QNANSZ6Ovu"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_CwkR8R5Ci6":{"name":["光谷七路","Guanggu 7th Road"],"num":"9","services":["local"],"parents":["stn_PfDxPmcSuE"],"children":["stn_XcA-F9PcEl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_PfDxPmcSuE":{"name":["豹澥","Baoxie"],"num":"8","services":["local"],"parents":["stn_wfmy59PYO7"],"children":["stn_CwkR8R5Ci6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_wfmy59PYO7":{"name":["光谷六路","Guanggu 6th Road"],"num":"7","services":["local"],"parents":["stn_VaK1ir5Lcs"],"children":["stn_PfDxPmcSuE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_VaK1ir5Lcs":{"name":["光谷五路","Guanggu 5th Road"],"num":"6","services":["local"],"parents":["stn_LV3KGraTrr"],"children":["stn_wfmy59PYO7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_LV3KGraTrr":{"name":["光谷四路","Guanggu 4th Road"],"num":"5","services":["local"],"parents":["stn_fI280unnte"],"children":["stn_VaK1ir5Lcs"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_fI280unnte":{"name":["光谷生物园","Guanggushengwuyuan"],"num":"4","services":["local"],"parents":["stn_WhDxkrC1O5"],"children":["stn_LV3KGraTrr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_WhDxkrC1O5":{"name":["光谷同济医院","Tongji Hospital"],"num":"3","services":["local"],"parents":["stn_HxSVFLZNke"],"children":["stn_fI280unnte"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_HxSVFLZNke":{"name":["湖口","Hukou"],"num":"2","services":["local"],"parents":["stn_-GcdcIiqqQ"],"children":["stn_WhDxkrC1O5"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_-GcdcIiqqQ":{"name":["武汉东站","Wuhan East Railway Station"],"num":"1","services":["local"],"parents":["linestart"],"children":["stn_HxSVFLZNke"],"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh2","#EB7CAF","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"","psd_num":"1","info_panel_type":"sh","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
与 #1075 相同的问题，在此不做重复。

**Comment by Windows-Taskmgr** [comment]
您好，此模板已超过一个月未回复，遵循惯例我们将关闭此issue，谢谢配合。感谢您的贡献。
