### ISSUE TITLE
Resources: New templates of SHENYANG METRO

### ISSUE THREAD

**Issue by binnnnn123** [railmapgen/rmg-templates#1079]
**Justification:** 线路添加

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="symtc" line="00config"><summary>New company: SHENYANG METRO</summary><details type="name">{"en":"SHENYANG METRO","zh-Hans":"沈阳地铁","zh-Hant":"沈陽地鐵"}</details></details>

<details repo="rmg-templates" company="symtc" line="SY4" major="false"><summary>symtc/SY4</summary><details type="name">{"en":"Line 4","zh-Hans":"4 号线","zh-Hant":"4 號線","ko":"라인 4"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2500,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"4","theme":["other","other","#7030A0","#fff"],"line_name":["4 号线","Line 4"],"current_stn_idx":"WYbP8I","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["OadjUa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"OadjUa":{"name":["创新路","CHUANGXINLU"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["cdBkUa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WYbP8I":{"name":["正新路","ZHENGXINLU"],"secondaryName":false,"num":"02","services":["local"],"parents":["yq9nLA"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["WYbP8I"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cdBkUa":{"name":["沈阳南站","SHENYANGNANZHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["OadjUa"],"children":["3RbINs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3RbINs":{"name":["城建学院","CHENGJIANXUEYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["cdBkUa"],"children":["DZrqMi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DZrqMi":{"name":["红椿路","HONGCHUNLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["3RbINs"],"children":["aE1Fg8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"aE1Fg8":{"name":["云杉路","YUNSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["DZrqMi"],"children":["af5M01"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"af5M01":{"name":["金仓路","JINCANGLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["aE1Fg8"],"children":["yVh6Ae"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yVh6Ae":{"name":["长白南","CHANGBAINAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["af5M01"],"children":["klOb_x"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#26bafc","#fff"],"name":["9 号线","Line 9"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"klOb_x":{"name":["长白岛","CHANBAIDAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["yVh6Ae"],"children":["d9iaGw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"d9iaGw":{"name":["南京桥","NANJINGQIAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["klOb_x"],"children":["SQE7Ys"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SQE7Ys":{"name":["砂阳","SHAYANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["d9iaGw"],"children":["u8GKWT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"u8GKWT":{"name":["南五马路","NANWUMALU"],"secondaryName":false,"num":"00","services":["local"],"parents":["SQE7Ys"],"children":["eDEC29"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eDEC29":{"name":["太原街","TAIYUANJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["u8GKWT"],"children":["VNN1Rr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff0000","#fff"],"name":["1 号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VNN1Rr":{"name":["市府大路","HUANGSILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["eDEC29"],"children":["pOctzM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pOctzM":{"name":["黄寺路","HUANGSILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["VNN1Rr"],"children":["T9Cq2I"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"T9Cq2I":{"name":["沈阳北站","SHENYANGBEIZHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["pOctzM"],"children":["Mf63Lc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ffc000","#fff"],"name":["2 号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Mf63Lc":{"name":["沈阳大学","SHENYANGDAXUE"],"secondaryName":false,"num":"00","services":["local"],"parents":["T9Cq2I"],"children":["9NaZjg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9NaZjg":{"name":["洮昌街","TAOCHANGJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["Mf63Lc"],"children":["42-5-1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"42-5-1":{"name":["合作街","HEZUOJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["9NaZjg"],"children":["eG0UFu"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#76ed08","#fff"],"name":["10 号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eG0UFu":{"name":["北大营","BEIDAYING"],"secondaryName":false,"num":"00","services":["local"],"parents":["42-5-1"],"children":["3iD-2z"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3iD-2z":{"name":["观泉路","GUANQUANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["eG0UFu"],"children":["iB3x9l"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iB3x9l":{"name":["望花","WANGHUA"],"secondaryName":false,"num":"00","services":["local"],"parents":["3iD-2z"],"children":["yq9nLA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yq9nLA":{"name":["文官街","WENGUANJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["iB3x9l"],"children":["WYbP8I"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":true,"terminal":["创新路","CHUANGXINLU"]},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，RMG模版中沈阳地铁公司与4号线模版已经存在，您不需要重新创建。
