### ISSUE TITLE
Resources: New templates of Nanjing Metro

### ISSUE THREAD

**Issue by SmartTabST** [railmapgen/rmg-templates#1097]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | https://www.njmetro.com.cn/njdtweb/home/go-line-intro.do?columnId=8a8080076512510d0165130727520004&rowId=8a80800765a29a780165a8538b6f0018 |
|     Justification     | 增加S8号线 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="njmetro" line="njs8" major="false"><summary>njmetro/njs8</summary><details type="name">{"en":"Line S8","zh-Hans":"S8号线","zh-Hant":"S8號線"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":2000,"railmap":2000,"indoor":2000},"svg_height":300,"style":"shmetro","y_pc":50,"padding":11,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["nanjing","s8","#ff8000","#fff"],"line_name":["S8号线","Line S8"],"current_stn_idx":"CVXOM2","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["CVXOM2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"CVXOM2":{"name":["长江大桥北","Changjiangdaqiaobei"],"num":"01","services":["local"],"parents":["linestart"],"children":["AkMFJE"],"transfer":{"groups":[{"lines":[{"theme":["nanjing","nj11","#ef426f","#fff"],"name":["11号线","Line 11"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"AkMFJE":{"name":["毛纺厂路","Maofangchanglu"],"num":"02","services":["local"],"parents":["CVXOM2"],"children":["8HsWp-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["GZChgi"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"8HsWp-":{"name":["泰山新村","Taishanxincun"],"num":"00","services":["local"],"parents":["AkMFJE"],"children":["pbqz5x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"d1HvLL":{"name":["六合开发区","Luhe Development Zone "],"num":"00","services":["local"],"parents":["WDNre-"],"children":["LcRxat"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"WDNre-":{"name":["化工园","Huagongyuan "],"num":"00","services":["local"],"parents":["TVZL1x"],"children":["d1HvLL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"TVZL1x":{"name":["长芦","Changlu "],"num":"00","services":["local"],"parents":["VkwBsa"],"children":["WDNre-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"VkwBsa":{"name":["葛塘","Getang "],"num":"00","services":["local"],"parents":["vNemE5"],"children":["TVZL1x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"vNemE5":{"name":["大厂","Dachang "],"num":"00","services":["local"],"parents":["VWiv50"],"children":["VkwBsa"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"VWiv50":{"name":["卸甲甸","Xiejiadian "],"num":"00","services":["local"],"parents":["WuStE6"],"children":["vNemE5"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"WuStE6":{"name":["信息工程大学","Nanjing University of Information Science &amp; Technology"],"num":"00","services":["local"],"parents":["k_G_p_"],"children":["VWiv50"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"k_G_p_":{"name":["高新开发区","Gaoxin Development Zone"],"num":"00","services":["local"],"parents":["pbqz5x"],"children":["WuStE6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"pbqz5x":{"name":["泰冯路","Taifenglu"],"num":"00","services":["local"],"parents":["8HsWp-"],"children":["k_G_p_"],"transfer":{"groups":[{"lines":[{"theme":["nanjing","nj3","#009a44","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"R8Jjiw":{"name":["雄州","Xiongzhou "],"num":"00","services":["local"],"parents":["LcRxat"],"children":["IGyw91"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"LcRxat":{"name":["龙池","Longchi "],"num":"00","services":["local"],"parents":["d1HvLL"],"children":["R8Jjiw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"K4yq_C":{"name":["沈桥","Shenqiao "],"num":"00","services":["local"],"parents":["aQseQK"],"children":["cfmp0c"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"aQseQK":{"name":["方州广场","Fangzhouguangchang "],"num":"00","services":["local"],"parents":["IGyw91"],"children":["K4yq_C"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"IGyw91":{"name":["凤凰山公园","Fenghuangshangongyuan "],"num":"00","services":["local"],"parents":["R8Jjiw"],"children":["aQseQK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GZChgi":{"name":["金牛湖","Jinniuhu "],"num":"00","services":["local"],"parents":["cfmp0c"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"cfmp0c":{"name":["八百桥","Babaiqiao "],"num":"00","services":["local"],"parents":["K4yq_C"],"children":["GZChgi"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
