### ISSUE TITLE
Resources: New templates of Fuzhou Metro

### ISSUE THREAD

**Issue by Lshengevery** [railmapgen/rmg-templates#1108]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://zh.wikipedia.org/wiki/%E7%A6%8F%E5%B7%9E%E5%9C%B0%E9%93%81#%E7%BA%BF%E7%BD%91%E5%9B%BE |
|     Justification     | 福州地鐵4號線已開通 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="fzmtr" line="4" major="false"><summary>fzmtr/4</summary><details type="name">{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號綫"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["fuzhou","fz4","#ff7f41","#fff"],"line_name":["4号线","Line 4"],"current_stn_idx":"dRb9x7","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["s3erFa"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"s3erFa":{"name":["帝封江","Difengjiang"],"num":"01","services":["local"],"parents":["linestart"],"children":["dRb9x7"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz5","#893b67","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"dRb9x7":{"name":["螺洲温泉","Luozhou Hot Spring"],"num":"02","services":["local"],"parents":["s3erFa"],"children":["doZGo8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["PgxUE7"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"doZGo8":{"name":["城门","Chengmen"],"num":"00","services":["local"],"parents":["dRb9x7"],"children":["Uf4d5N"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz1","#bb1e10","#fff"],"name":["1号线","Line 1"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Uf4d5N":{"name":["林浦","Linpu"],"num":"00","services":["local"],"parents":["doZGo8"],"children":["OnG372"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz6","#005eb8","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"OnG372":{"name":["会展中心","Exhibition Center"],"num":"00","services":["local"],"parents":["Uf4d5N"],"children":["6BNi2G"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"6BNi2G":{"name":["花海公园","Huahai Park"],"num":"00","services":["local"],"parents":["OnG372"],"children":["Y1F08C"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Y1F08C":{"name":["鳌峰洲","Aofengzhou"],"num":"00","services":["local"],"parents":["6BNi2G"],"children":["6LF21S"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"6LF21S":{"name":["光明港","Guangminggang"],"num":"00","services":["local"],"parents":["Y1F08C"],"children":["dUjJtW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"dUjJtW":{"name":["前屿","Qianyu"],"num":"00","services":["local"],"parents":["6LF21S"],"children":["pjZ6o7"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz2","#325928","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"pjZ6o7":{"name":["后屿","Houyu"],"num":"00","services":["local"],"parents":["dUjJtW"],"children":["hVHNz_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"hVHNz_":{"name":["横屿","Hengyu"],"num":"00","services":["local"],"parents":["pjZ6o7"],"children":["gR8V1d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"gR8V1d":{"name":["竹屿","Zhuyu"],"num":"00","services":["local"],"parents":["hVHNz_"],"children":["_Qld88"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"_Qld88":{"name":["三角池","Sanjiaochi"],"num":"00","services":["local"],"parents":["gR8V1d"],"children":["YIB76O"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"YIB76O":{"name":["东门","Dongmen"],"num":"00","services":["local"],"parents":["_Qld88"],"children":["CSu7Vk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"CSu7Vk":{"name":["省立医院","Provincial Hospital"],"num":"00","services":["local"],"parents":["YIB76O"],"children":["pR9Q_D"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"pR9Q_D":{"name":["东街口","Dongjiekou"],"num":"00","services":["local"],"parents":["CSu7Vk"],"children":["UUAerh"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz1","#bb1e10","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"UUAerh":{"name":["西门","Ximen"],"num":"00","services":["local"],"parents":["pR9Q_D"],"children":["RSQXN9"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"RSQXN9":{"name":["陆庄","Luzhuang"],"num":"00","services":["local"],"parents":["UUAerh"],"children":["PgxUE7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"PgxUE7":{"name":["凤凰池","Fenghuangchi"],"num":"00","services":["local"],"parents":["RSQXN9"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by lingmofengling** [comment]
这是线路图

**Comment by lingmofengling** [comment]
This is the subway map
![Uploading mmexport1710591247990.jpg…]()
