### ISSUE TITLE
Resources: New templates of Hefei Metro

### ISSUE THREAD

**Issue by HFF6125Bill** [railmapgen/rmg-templates#1117]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)

**Comment by 28yfang** [comment]
Hi, please paste the text you copied when updating templates and remove (REPLACE ME/代替我)  :)
