### ISSUE TITLE
Resources: New templates of MTR

### ISSUE THREAD

**Issue by caleryFsb** [railmapgen/rmg-templates#1135]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://hkrail.fandom.com/wiki/東涌綫延綫?file=TCE_Map.png |
|     Justification     | 部分車站（東涌東、東涌西）預計於2029年通車。 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mtr" line="tcl" major="false"><summary>mtr/tcl</summary><details type="name">{"en":"Tung Chung Line","zh-Hans":"东涌线","zh-Hant":"東涌綫","ko":"둥충선"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1200,"railmap":1500,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"direction":"r","platform_num":"3","theme":["hongkong","tcl","#f3982c","#fff"],"line_name":["東涌綫","Tung Chung Line"],"current_stn_idx":"rIJvOH","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["rIJvOH"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"rIJvOH":{"name":["香港","Hong Kong"],"num":"01","services":["local"],"parents":["linestart"],"children":["iSbXuF"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"iSbXuF":{"name":["九龍","Kowloon"],"num":"02","services":["local"],"parents":["rIJvOH"],"children":["2h6dKk"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":false,"groups":[{"lines":[]},{"name":["香港西九龍","Hong Kong West Kowloon"],"lines":[{"theme":["hongkong","hsr","#9d948b","#fff"],"name":["高速鐵路","High Speed Rail"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["rSiHYY"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"2h6dKk":{"name":["奧運","Olympic"],"num":"00","services":["local"],"parents":["iSbXuF"],"children":["MP01CM"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"MP01CM":{"name":["南昌","Nam Cheong"],"num":"00","services":["local"],"parents":["2h6dKk"],"children":["DuQYGM"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","mol","#9c2e00","#fff"],"name":["屯馬綫","Tuen Ma Line"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"DuQYGM":{"name":["茘景","Lai King"],"num":"00","services":["local"],"parents":["MP01CM"],"children":["vhkjzB"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","twl","#e60013","#fff"],"name":["荃灣綫","Tsuen Wan Line"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"vhkjzB":{"name":["青衣","Tsing Yi"],"num":"00","services":["local"],"parents":["DuQYGM"],"children":["XyLKzm"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"XyLKzm":{"name":["欣澳","Sunny Bay"],"num":"00","services":["local"],"parents":["vhkjzB"],"children":["9RY2gZ"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","drl","#e66ea5","#fff"],"name":["迪士尼綫","Disneyland Resort Line"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"NwJ06l":{"name":["東涌","Tung Chung"],"num":"00","services":["local"],"parents":["9RY2gZ"],"children":["rSiHYY"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"rSiHYY":{"name":["東涌西","Tung Chung West"],"num":"00","services":["local"],"parents":["NwJ06l"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"9RY2gZ":{"name":["東涌東","Tung Chung East"],"num":"00","services":["local"],"parents":["XyLKzm"],"children":["NwJ06l"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":["東涌及迪士尼綫","Tung Chung and Disneyland Resort Line"]},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":7}</details></details>

**Comment by Charlis-Aviation** [comment]
@caleryFsb 您好，
由於東涌綫延綫的通車日期太久，因此，我們不接納您的作品。
不好意思：（

謝謝：）
