### ISSUE TITLE
Resources: New templates of JR East

### ISSUE THREAD

**Issue by KaynethWong** [railmapgen/rmg-templates#1146]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_ | Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Others (Please indicate below) |
|     Reference link    | https://www.youtube.com/watch?v=KHr2n4neEy8 |
|     Justification     | 作出貢獻 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="jreast" line="00config"><summary>New company: JR East</summary><details type="name">{"en":"JR East","zh-Hans":"JR东日本","zh-Hant":"JR東日本"}</details></details>

<details repo="rmg-templates" company="jreast" line="jy" major="false"><summary>jreast/jy</summary><details type="name">{"en":"Yamanote Line","zh-Hans":"山手线","zh-Hant":"山手線","ja":"やまのめせん"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":7800,"indoor":1200},"svg_height":400,"style":"mtr","y_pc":50,"padding":3,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["tokyo","jy","#7bab4f","#000"],"line_name":["山手線","Yamanote Line"],"current_stn_idx":"1nnxb0","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["1nnxb0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1nnxb0":{"name":["新宿","Shinjuku"],"num":"01","services":["local"],"parents":["linestart"],"children":["_k79zU"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jc","#f15921","#fff"],"name":["中央線","Chūō Line"]},{"theme":["tokyo","jb","#fed304","#000"],"name":["中央線各駅停車","Chūō Line(Local)"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","oh","#0085CE","#fff"],"name":["小田急線","Odakyū Line"]},{"theme":["tokyo","ko","#D5007F","#fff"],"name":["京王線","Keiō Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["地下鉄丸ノ内線","Marunouchi Subway Line"]},{"theme":["tokyo","s","#abba41","#fff"],"name":["都営地下鉄新宿線","Shinjuku Subway Line"]},{"theme":["tokyo","e","#ce1c64","#fff"],"name":["都営地下鉄大江戸線","Oedo Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"V4I37j":{"name":["新宿","Shinjuku"],"num":"02","services":["local"],"parents":["K-yQoR"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jc","#f15921","#fff"],"name":["中央線","Chūō Line"]},{"theme":["tokyo","jb","#fed304","#000"],"name":["中央線各駅停車","Chūō Line(Local)"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","oh","#0085CE","#fff"],"name":["小田急線","Odakyū Line"]},{"theme":["tokyo","ko","#D5007F","#fff"],"name":["京王線","Keiō Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["地下鉄丸ノ内線","Marunouchi Subway Line"]},{"theme":["tokyo","s","#abba41","#fff"],"name":["都営地下鉄新宿線","Shinjuku Subway Line"]},{"theme":["tokyo","e","#ce1c64","#fff"],"name":["都営地下鉄大江戸線","Oedo Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["V4I37j"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3NOyHb":{"name":["原宿","Harajuku"],"num":"00","services":["local"],"parents":["_k79zU"],"children":["RSel7x"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","c","#1bb267","#fff"],"name":["地下鉄千代田線","Chiyoda Subway Line"]},{"theme":["tokyo","f","#9c5e31","#fff"],"name":["地下鉄副都心線","Fukutoshin Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"_k79zU":{"name":["代々木","Yoyogi"],"num":"00","services":["local"],"parents":["1nnxb0"],"children":["3NOyHb"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jb","#fed304","#000"],"name":["中央線各駅停車","Chūō Line(Local)"]},{"theme":["tokyo","e","#ce1c64","#fff"],"name":["都営地下鉄大江戸線","Oedo Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RSel7x":{"name":["渋谷","Shibuya"],"num":"00","services":["local"],"parents":["3NOyHb"],"children":["r7z1kO"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ty","#DA0042","#fff"],"name":["東急東横線","Tōkyū Tōyoko Line"]},{"theme":["tokyo","dt","#00AA8D","#fff"],"name":["東急田園都市線","Tōkyū Den-en-toshi Line"]},{"theme":["tokyo","in","#103675","#fff"],"name":["京王井の頭線","Keiō Inokashira Line"]},{"theme":["tokyo","g","#f9a328","#fff"],"name":["地下鉄銀座線","Ginza Subway Line"]},{"theme":["tokyo","z","#8c7dba","#fff"],"name":["地下鉄半蔵門線","Hanzōmon Subway Line"]},{"theme":["tokyo","f","#9c5e31","#fff"],"name":["地下鉄副都心線","Fukutoshin Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"r7z1kO":{"name":["恵比寿","Ebisu"],"num":"00","services":["local"],"parents":["RSel7x"],"children":["ncU6sf"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","h","#c7beb3","#fff"],"name":["地下鉄日比谷線","Hibiya Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"ncU6sf":{"name":["目黑","Meguro"],"num":"00","services":["local"],"parents":["r7z1kO"],"children":["Yw_6gT"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","mg","#009CD3","#fff"],"name":["東急目黒線","Tōkyū Meguro Line"]},{"theme":["tokyo","n","#02b69b","#fff"],"name":["地下鉄南北線","Namboku Subway Line"]},{"theme":["tokyo","i","#0068a5","#fff"],"name":["都営地下鉄三田線","Mita Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Yw_6gT":{"name":["五反田","Gotanda"],"num":"00","services":["local"],"parents":["ncU6sf"],"children":["J1YqbJ"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","ik","#EE86A8","#fff"],"name":["東急池上線","Tōkyū Ikegami Line"]},{"theme":["tokyo","a","#dd4231","#fff"],"name":["都営地下鉄浅草線","Asakusa Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"J1YqbJ":{"name":["大崎","Ōsaki"],"num":"00","services":["local"],"parents":["Yw_6gT"],"children":["j-pH2R"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["相鉄線直通列車","through service to the Sotetsu Line"]},{"theme":["tokyo","r","#00418e","#fff"],"name":["東京臨海高速鉄道りんかい線","Tōkyō Rinksi Kosoku Tetsudo Rinkai Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"j-pH2R":{"name":["品川","Shinagawa"],"num":"00","services":["local"],"parents":["J1YqbJ"],"children":["gAtDcC"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#185caa","#fff"],"name":["東海道·山陽新幹線","Tōkaidō·Sanyō Shinkansen"]},{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","jt","#f68b1f","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","uen-tyo","#91268f","#fff"],"name":["上野東京ライン","Ueno-Tōkyō Line"]},{"theme":["tokyo","jo","#007ac0","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","kk","#00BFFF","#fff"],"name":["京急線","Keikyū Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"gAtDcC":{"name":["高輪ゲートウェイ","Takanawa Gateway"],"num":"00","services":["local"],"parents":["j-pH2R"],"children":["R0N-3s"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"R0N-3s":{"name":["田町","Tamachi"],"num":"00","services":["local"],"parents":["gAtDcC"],"children":["U-XeZ6"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"U-XeZ6":{"name":["浜松町","Hamamatsucho"],"num":"00","services":["local"],"parents":["R0N-3s"],"children":["PwQSHD"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","mo","#26326A","#fff"],"name":["東京モノレール羽田空港線","Tōkyō Monorail Haneda airport Line"]},{"theme":["tokyo","e","#ce1c64","#fff"],"name":["都営地下鉄大江戸線","Oedo Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"PwQSHD":{"name":["新橋","Shimbashi"],"num":"00","services":["local"],"parents":["U-XeZ6"],"children":["qxdT_q"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","g","#f9a328","#fff"],"name":["地下鉄銀座線","Ginza Subway Line"]},{"theme":["tokyo","a","#dd4231","#fff"],"name":["都営地下鉄浅草線","Asakusa Subway Line"]},{"theme":["tokyo","u","#1662B8","#fff"],"name":["ゆりかもめ","Yurikamome Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"qxdT_q":{"name":["有楽町","Yurakuchō"],"num":"00","services":["local"],"parents":["PwQSHD"],"children":["j_zwPg"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","h","#c7beb3","#fff"],"name":["地下鉄日比谷線","Hibiya Subway Line"]},{"theme":["tokyo","y","#d1a662","#fff"],"name":["地下鉄有楽町線","Yurakuchō Subway Line"]},{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"j_zwPg":{"name":["東京","Tōkyō"],"num":"00","services":["local"],"parents":["qxdT_q"],"children":["UkT5mg"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#006400","#fff"],"name":["東北·山形·秋田·北海道·上越·北陸新龫線","Tōhoku·Yamagata·Akita·Hokkaidō·Jōetsu·Hokuriku Shinkansen"]},{"theme":["other","other","#185caa","#fff"],"name":["東海道·山陽新幹線","Tōkaidō·Sanyō Shinkansen"]},{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","jc","#f15921","#fff"],"name":["中央線","Chūō Line"]},{"theme":["tokyo","jt","#f68b1f","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","uen-tyo","#91268f","#fff"],"name":["上野東京ライン","Ueno-Tōkyō Line"]},{"theme":["tokyo","jo","#007ac0","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","jo","#007ac0","#fff"],"name":["総武線快速","Sobu Line(Rapid)"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["地下鉄丸ノ内線","Marunouchi Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"UkT5mg":{"name":["神田","Kanda"],"num":"00","services":["local"],"parents":["j_zwPg"],"children":["2qHFAC"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jc","#f15921","#fff"],"name":["中央線","Chūō Line"]},{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","g","#f9a328","#fff"],"name":["地下鉄銀座線","Ginza Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"2qHFAC":{"name":["秋葉原","Akihabara"],"num":"00","services":["local"],"parents":["UkT5mg"],"children":["3SU2T5"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","jb","#fed304","#000"],"name":["総武線各駅停車","Sobu Line(Local)"]},{"theme":["tokyo","h","#c7beb3","#fff"],"name":["地下鉄日比谷線","Hibiya Subway Line"]},{"theme":["tokyo","tx","#003b83","#fff"],"name":["つくばエクスプレス線","Tsukuba express Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"3SU2T5":{"name":["御徒町","Okachimachi"],"num":"00","services":["local"],"parents":["2qHFAC"],"children":["oTeRZo"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","e","#ce1c64","#fff"],"name":["都営地下鉄大江戸線","Oedo Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"oTeRZo":{"name":["上野","Ueno"],"num":"00","services":["local"],"parents":["3SU2T5"],"children":["oXeFOv"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#006400","#fff"],"name":["東北·山形·秋田·北海道·上越·北陸新龫線","Tōhoku·Yamagata·Akita·Hokkaidō·Jōetsu·Hokuriku Shinkansen"]},{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","ju","#f68b1f","#fff"],"name":["宇都宮線(東北線)","Utsunomiya Line (Tōhoku Line)"]},{"theme":["tokyo","ju","#f68b1f","#fff"],"name":["高崎線","Takasaki Line"]},{"theme":["tokyo","jj","#1DAF7E","#fff"],"name":["常磐線","Jōban Line"]},{"theme":["tokyo","ks","#005AAA","#fff"],"name":["京成線","Keisei Line"]},{"theme":["tokyo","g","#f9a328","#fff"],"name":["地下鉄銀座線","Ginza Subway Line"]},{"theme":["tokyo","h","#c7beb3","#fff"],"name":["地下鉄日比谷線","Hibiya Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"oXeFOv":{"name":["鶯谷","Uguisudani"],"num":"00","services":["local"],"parents":["oTeRZo"],"children":["4XXfcW"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"4XXfcW":{"name":["日暮里","Nippori"],"num":"00","services":["local"],"parents":["oXeFOv"],"children":["YK0aPh"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","jj","#1DAF7E","#fff"],"name":["常磐線","Joban Line"]},{"theme":["tokyo","ks","#005AAA","#fff"],"name":["京成線","Keisei Line"]},{"theme":["tokyo","nt","#D53A77","#fff"],"name":["日暮里·舎人ライナー","Nippori-Toneri Liner"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"YK0aPh":{"name":["西日暮里","Nishi-Nippori"],"num":"00","services":["local"],"parents":["4XXfcW"],"children":["M_WAvR"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]},{"theme":["tokyo","c","#1bb267","#fff"],"name":["地下鉄千代田線","Chiyoda Subway Line"]},{"theme":["tokyo","nt","#D53A77","#fff"],"name":["日暮里·舎人ライナー","Nippori-Toneri Liner"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"M_WAvR":{"name":["田端","Tabata"],"num":"00","services":["local"],"parents":["YK0aPh"],"children":["IdTifN"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","jk","#00b2e6","#fff"],"name":["京浜東北線","Keihin-Tōhoku Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"IdTifN":{"name":["駒込","Komagome"],"num":"00","services":["local"],"parents":["M_WAvR"],"children":["Pq4kEI"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","n","#02b69b","#fff"],"name":["地下鉄南北線","Namboku Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Pq4kEI":{"name":["巣鴨","Sugamo"],"num":"00","services":["local"],"parents":["IdTifN"],"children":["ZyJwUd"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","i","#0068a5","#fff"],"name":["都営地下鉄三田線","Mita Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"ZyJwUd":{"name":["大塚","Otsuka"],"num":"00","services":["local"],"parents":["Pq4kEI"],"children":["2sENs7"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","sa","#d75b80","#fff"],"name":["都電荒川線","Tōkyō Sakura Tram"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"2sENs7":{"name":["池袋","Ikebukuro"],"num":"00","services":["local"],"parents":["ZyJwUd"],"children":["Cez-Zd"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","ja","#0ab38d","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","si","#EF7A00","#fff"],"name":["西武池袋線","Seibu Ikebukuro Line"]},{"theme":["tokyo","tj","#00428E","#fff"],"name":[" 東武東上線","Tōbu Tōjō Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["地下鉄丸ノ内線","Marunouchi Subway Line"]},{"theme":["tokyo","y","#d1a662","#fff"],"name":["地下鉄有楽町線","Yurakuchō Subway Line"]},{"theme":["tokyo","f","#9c5e31","#fff"],"name":["地下鉄副都心線","Fukutoshin Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Cez-Zd":{"name":["目白","Mejiro"],"num":"00","services":["local"],"parents":["2sENs7"],"children":["t8AMhU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"t8AMhU":{"name":["高田馬場","Takadanobaba"],"num":"00","services":["local"],"parents":["Cez-Zd"],"children":["K-yQoR"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","ss","#00A6BF","#fff"],"name":["西武新宿線","Seibu Shinjuku Line"]},{"theme":["tokyo","t","#00a4db","#fff"],"name":["地下鉄東西線","Tozai Subway Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"K-yQoR":{"name":["新大久保","Shin-Okubo"],"num":"00","services":["local"],"parents":["t8AMhU"],"children":["V4I37j"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":false,"isFlip":true},"customiseMTRDest":{"isLegacy":true,"terminal":["渋谷·品川","Shibuya&amp;Shinagawa"]},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Charlis-Aviation** [comment]
@KaynethWong 您好，
由於 JR East 公司已經在Template上有了，而山手綫也是。
因此，我們會關閉您的 Issue。

不好意思，謝謝您的貢獻
