### ISSUE TITLE
Resources: New templates of Shenyang Metro

### ISSUE THREAD

**Issue by xxcpeter** [railmapgen/rmg-templates#1150]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | To be opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://zh.wikipedia.org/wiki/%E6%B2%88%E9%98%B3%E5%9C%B0%E9%93%81 |
|     Justification     | Add new Line 3 and Line 6. Update Line 1 east extension part. Update interchange stations in other lines. |
| Major update of Line 1/1号线/1號線/1호선 | Add Line 1 east extension part and interchange stations with Line 3 & 6. |
| Major update of Line 2/2号线/2號線/2호선 | Update interchange stations with Line 3 & 6. |
| Major update of Line 4/4号线/4號線/4호선 | Update interchange stations with Line 3 & 6. |
| Major update of Line 9/9号线/9號線/9호선 | Update interchange stations with Line 3 & 6. |
| Major update of Line 10/10号线/10號線/10호선 | Update interchange stations with Line 3 & 6. |

**Do not edit lines below, they are meant for bots only!!!**

The length of code below is over the maximum characters of github issue. So it is attached in this text file below.
[update.txt](https://github.com/railmapgen/rmg-templates/files/15060077/update.txt)

**Comment by 28yfang** [comment]
您好，RMG模版不支持识别txt文件，您需要分成多个议题进行上传。
