### ISSUE TITLE
Resources: New templates of Qingdao Metro (Part II)

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#1153]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | http://www.qd-metro.com/passervice/pic.html |
|     Justification     | 6号线已于4月26日开通，同时11号线更名为蓝谷快线，13号线更名为西海岸快线。以此更新模板。 |
| Major update of Line 13/13号线/13號線 | 将13号线更名为西海岸快线，同时修正部分错误。 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="qdmetro" line="qd13" major="true"><summary>qdmetro/qd13(M)</summary><details type="name">{"en":"The West Coast Line","zh-Hans":"西海岸快线","zh-Hant":"西海岸快線","ko":"서해안 쾌속선","ja":"西海岸快速線"}</details><details type="param">{"style":"gzmtr","svg_height":311,"padding":4.216780871148593,"y_pc":47.71,"theme":["qingdao","qd13","#00AB84","#fff"],"direction":"l","current_stn_idx":"iwf6","platform_num":"2","stn_list":{"linestart":{"parents":[],"children":["1qsn"],"name":["路綫左端","LEFT END"],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"00","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"24","loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["6th3"],"children":["iwf6"],"name":["泊里","Poli"],"branch":{},"num":"22","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["lineend"],"parents":["l1mz"],"name":["董家口火车站 ","Dongjiakou Railway Station"],"branch":{},"num":"23","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"facility":"hsr","loop_pivot":false,"one_line":false,"int_padding":355},"6th3":{"branch":{},"parents":["o594"],"children":["l1mz"],"name":["董家口港","Dongjiakou Port"],"num":"21","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"o594":{"branch":{},"parents":["vqo5"],"children":["6th3"],"name":["贡口湾","Gongkou Bay"],"num":"20","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"vqo5":{"branch":{},"parents":["ocv4"],"children":["o594"],"name":["琅琊","Langya "],"num":"19","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"ocv4":{"branch":{},"parents":["6vxs"],"children":["vqo5"],"name":["龙湾","Longwan Bay"],"num":"18","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"6vxs":{"branch":{},"parents":["hewc"],"children":["ocv4"],"name":["古镇口","Guzhenkou"],"num":"17","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hewc":{"branch":{},"parents":["pe88"],"children":["6vxs"],"name":["张家楼","Zhangjialou"],"num":"16","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"pe88":{"branch":{},"parents":["4olr"],"children":["hewc"],"name":["大珠山","Dazhu Mountain"],"num":"15","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"4olr":{"branch":{},"parents":["581h"],"children":["pe88"],"name":["盛海路（世博城）","\t Shenghai Road(World Expo City)"],"num":"14","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"581h":{"branch":{},"parents":["a2zk"],"children":["4olr"],"name":["世纪大道","Shiji Ave"],"num":"13","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"a2zk":{"branch":{},"parents":["bhi4"],"children":["581h"],"name":["双珠路","Shuangzhu Rd"],"num":"12","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"bhi4":{"branch":{},"parents":["2tzt"],"children":["a2zk"],"name":["凤凰山路","Fenghuangshan Rd"],"num":"11","transfer":{"tick_direc":"l","paid_area":false,"groups":[{},{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"2tzt":{"branch":{},"parents":["u2e7"],"children":["bhi4"],"name":["隐珠","Yinzhu"],"num":"10","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"u2e7":{"branch":{},"parents":["1r1c"],"children":["2tzt"],"name":["两河","Lianghe"],"num":"09","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"1r1c":{"branch":{},"parents":["jz7x"],"children":["u2e7"],"name":["辛屯","Xintun"],"num":"08","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["qingdao","qd6","#6CACE4","#fff"],"name":["6号线","Line 6"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"jz7x":{"branch":{},"parents":["pluc"],"children":["1r1c"],"name":["朝阳山","Chaoyangshan"],"num":"07","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"pluc":{"branch":{},"parents":["hroa"],"children":["jz7x"],"name":["学院路","Xueyuan Rd"],"num":"06","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hroa":{"branch":{},"parents":["hebc"],"children":["pluc"],"name":["灵山卫","Lingshanwei"],"num":"05","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hebc":{"branch":{},"parents":["pprg"],"children":["hroa"],"name":["积米崖","Jimiya"],"num":"04","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"pprg":{"branch":{},"parents":["r74n"],"children":["hebc"],"name":["井冈山路","Jinggangshan Rd"],"num":"03","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["qingdao","qd1","#EAAA00","#fff"],"name":["1号线","Line 1"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"r74n":{"branch":{},"parents":["1qsn"],"children":["pprg"],"name":["香江路","Xiangjiang Rd"],"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"1qsn":{"branch":{},"parents":["linestart"],"children":["r74n"],"name":["嘉陵江西路","Jialingjiang West Rd"],"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355}},"line_name":["西海岸快线","The West Coast Line"],"psd_num":"6","line_num":"13","info_panel_type":"gz1421","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1100,"runin":1143,"railmap":1510,"indoor":1400},"notesGZMTR":[["","",90.5,71,false]],"namePosMTR":{"isStagger":true,"isFlip":true},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":29,"spanLineNum":true,"version":"5.16.12"}</details></details>

**Comment by 28yfang** [comment]
您好，由于官方路线图中并没有车站编号，请您将模版样式更改为上海地铁或MTR样式，感谢。
