### ISSUE TITLE
Resources: New templates of Qingdao Metro

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#1157]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | http://www.qd-metro.com/passervice/pic.html |
|     Justification     | 6号线已于4月26日开通，同时11号线更名为蓝谷快线，13号线更名为西海岸快线。以此更新模版。同时修正上一issue (#1153)中的错误。 |
| Major update of Line 13/13号线/13號線 | 将13号线更名为西海岸快线。 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="qdmetro" line="qd13" major="true"><summary>qdmetro/qd13(M)</summary><details type="name">{"en":"The West Coast Line","zh-Hans":"西海岸快线","zh-Hant":"西海岸快線","ko":"서해안 익스프레스","ja":"西海岸エクスプレス"}</details><details type="param">{"svgWidth":{"destination":1400,"runin":1200,"railmap":1800,"indoor":1200},"svg_height":330,"style":"mtr","y_pc":50,"padding":6,"branchSpacingPct":33,"direction":"l","platform_num":"3","theme":["qingdao","qd13","#00AB84","#fff"],"line_name":["西海岸快线","The West Coast Line"],"current_stn_idx":"NflSvR","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["GHpho2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"2bEOqe":{"name":["积米崖","Jimiya"],"num":"01","services":["local"],"parents":["EJFWOX"],"children":["NflSvR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"NflSvR":{"name":["井冈山路","Jinggangshan Rd"],"num":"02","services":["local"],"parents":["2bEOqe"],"children":["TaiNZQ"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd1","#EAAA00","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["___7Y3"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"TaiNZQ":{"name":["香江路","Xiangjiang Rd"],"num":"00","services":["local"],"parents":["NflSvR"],"children":["___7Y3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"___7Y3":{"name":["嘉陵江西路","Jialingjiang West Rd"],"num":"00","services":["local"],"parents":["TaiNZQ"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EJFWOX":{"name":["灵山卫","Lingshanwei"],"num":"00","services":["local"],"parents":["mD0O_m"],"children":["2bEOqe"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"mD0O_m":{"name":["学院路","Xueyuan Rd"],"num":"00","services":["local"],"parents":["43dzyL"],"children":["EJFWOX"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"43dzyL":{"name":["朝阳山","Chaoyangshan"],"num":"00","services":["local"],"parents":["5Qlkbx"],"children":["mD0O_m"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"5Qlkbx":{"name":["辛屯","Xintun"],"num":"00","services":["local"],"parents":["zNuuhI"],"children":["43dzyL"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd6","#6CACE4","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"zNuuhI":{"name":["两河","Lianghe"],"num":"00","services":["local"],"parents":["JVEfBf"],"children":["5Qlkbx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"JVEfBf":{"name":["隐珠","Yinzhu"],"num":"00","services":["local"],"parents":["XExx9K"],"children":["zNuuhI"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"XExx9K":{"name":["凤凰山路","Fenghuangshan Rd"],"num":"00","services":["local"],"parents":["J8Gh32"],"children":["JVEfBf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"J8Gh32":{"name":["双珠路","Shuangzhu Rd"],"num":"00","services":["local"],"parents":["AgPTxy"],"children":["XExx9K"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"AgPTxy":{"name":["世纪大道","Shiji Ave"],"num":"00","services":["local"],"parents":["DEdwgL"],"children":["J8Gh32"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"DEdwgL":{"name":["盛海路 (世博城)","Shenghai Rd \\(World Expo City)"],"num":"00","services":["local"],"parents":["Q4jQ0l"],"children":["AgPTxy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Q4jQ0l":{"name":["大珠山","Dazhu Mountain"],"num":"00","services":["local"],"parents":["1Z5jzj"],"children":["DEdwgL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"1Z5jzj":{"name":["张家楼","Zhangjialou"],"num":"00","services":["local"],"parents":["MzWiaN"],"children":["Q4jQ0l"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"MzWiaN":{"name":["古镇口","Guzhenkou"],"num":"00","services":["local"],"parents":["UH6Auk"],"children":["1Z5jzj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"UH6Auk":{"name":["龙湾","Longwan Bay"],"num":"00","services":["local"],"parents":["D3gf3Y"],"children":["MzWiaN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"D3gf3Y":{"name":["琅琊","Langya"],"num":"00","services":["local"],"parents":["D6m_Vt"],"children":["UH6Auk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"D6m_Vt":{"name":["贡口湾","Gongkou Bay"],"num":"00","services":["local"],"parents":["8xtCjM"],"children":["D3gf3Y"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"8xtCjM":{"name":["董家口港","Dongjiakou Port"],"num":"00","services":["local"],"parents":["Wj_pNN"],"children":["D6m_Vt"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Wj_pNN":{"name":["泊里","Poli"],"num":"00","services":["local"],"parents":["GHpho2"],"children":["8xtCjM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"GHpho2":{"name":["董家口火车站","Dongjiakou Railway Station"],"num":"00","services":["local"],"parents":["linestart"],"children":["Wj_pNN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"hsr"}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":true,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.16.12"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，对于您的模板长时间未被审核，我们深表歉意。
您的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
