### ISSUE TITLE
Resources: New templates of MTR

### ISSUE THREAD

**Issue by tscchris** [railmapgen/rmg-templates#1168]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | To be opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://zh.wikipedia.org/wiki/北環綫 |
|     Justification     | This is a railway line proposed to be opened in 2034. |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mtr" line="NRL" major="false"><summary>mtr/NRL</summary><details type="name">{"en":"Northern Link","zh-Hans":"北环线","zh-Hant":"北環綫"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hongkong","nol","#b0008e","#fff"],"line_name":["北環綫","Northern link"],"current_stn_idx":"5bKb09","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["B9R_ID"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"B9R_ID":{"name":["錦上路","Kam Sheung Road"],"num":"01","services":["local"],"parents":["linestart"],"children":["mqA1Lq"],"transfer":{"groups":[{"lines":[{"theme":["hongkong","mol","#9c2e00","#fff"],"name":["屯馬綫","Tuen Ma Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"5bKb09":{"name":["古洞","Kwu Tung "],"num":"02","services":["local"],"parents":["kASNrA"],"children":["RI-2Qr"],"transfer":{"groups":[{"lines":[{"theme":["hongkong","eal","#5db7e8","#fff"],"name":["東鐵綫","East Rail Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["RI-2Qr"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"mqA1Lq":{"name":["凹頭","Au Tau"],"num":"00","services":["local"],"parents":["B9R_ID"],"children":["HwCbCH"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"kASNrA":{"name":["新田","San Tin"],"num":"00","services":["local"],"parents":["HwCbCH"],"children":["5bKb09"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"HwCbCH":{"name":["牛潭尾","Ngau Tam Mei "],"num":"00","services":["local"],"parents":["mqA1Lq"],"children":["kASNrA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RI-2Qr":{"name":["","Unnamed RI-2Qr"],"num":"00","services":["local"],"parents":["5bKb09"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
See #1170 .
