### ISSUE TITLE
Resources: New templates of Suzhou Rail Transit

### ISSUE THREAD

**Issue by QYQACB** [railmapgen/rmg-templates#1187]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | To be opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://baike.baidu.com/item/苏州轨道交通6号线/7211250?fr=ge_ala |
|     Justification     | 本線路將於本月開通，在蘇州軌道交通官網也有提到。百度百科是可信度很高的網站。 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmtr" line="sz6" major="false"><summary>szmtr/sz6</summary><details type="name">{"en":"Suzhou Rail Transit Line 6","zh-Hans":"苏州轨道交通6号线","zh-Hant":"蘇州軌道交通6號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":3100,"indoor":3700},"svg_height":540,"style":"shmetro","y_pc":50,"padding":6,"branchSpacingPct":0,"direction":"r","platform_num":"","theme":["suzhou","sz6","#41b6e6","#fff"],"line_name":["6号线","Line 6"],"current_stn_idx":"koONnG","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["zy05ss"],"branch":{"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zy05ss":{"name":["苏州新区火车站","Suzhou Xinqu Railway Station"],"num":"01","services":["local"],"parents":["linestart"],"children":["Rcq2kA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"Rcq2kA":{"name":["宝丰","Baofeng"],"num":"02","services":["local"],"parents":["zy05ss"],"children":["8sXly8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["koONnG"],"children":[],"branch":{"left":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8sXly8":{"name":["富强","Fuqiang"],"num":"00","services":["local"],"parents":["Rcq2kA"],"children":["IjT4xG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"IjT4xG":{"name":["长青","Changqing"],"num":"00","services":["local"],"parents":["8sXly8"],"children":["j7kCDa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"j7kCDa":{"name":["白洋湾","Baiyangwan"],"num":"00","services":["local"],"parents":["IjT4xG"],"children":["pj6Njd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pj6Njd":{"name":["金鸡墩","Jinjidun"],"num":"00","services":["local"],"parents":["j7kCDa"],"children":["AHhwYZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"AHhwYZ":{"name":["虎丘","Huqiu"],"num":"00","services":["local"],"parents":["pj6Njd"],"children":["QWQT8u"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QWQT8u":{"name":["青山桥浜","Qingshanqiaobang"],"num":"00","services":["local"],"parents":["AHhwYZ"],"children":["Y3TzT5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Y3TzT5":{"name":["江星桥南","Jiangxinqiao South"],"num":"00","services":["local"],"parents":["QWQT8u"],"children":["wreZ6F"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vI93zW":{"name":["平和路","Pinghelu"],"num":"00","services":["local"],"parents":["wreZ6F"],"children":["8ioddF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wreZ6F":{"name":["苏锦","Sujin"],"num":"00","services":["local"],"parents":["Y3TzT5"],"children":["vI93zW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz4","#196EAE","#fff"],"name":["4号线","Line 4"]}]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8ioddF":{"name":["梅巷","Meixiang"],"num":"00","services":["local"],"parents":["vI93zW"],"children":["1gg4pI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1gg4pI":{"name":["拙政园","Zhuozhengyuan"],"num":"00","services":["local"],"parents":["8ioddF"],"children":["Bt2Txs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Bt2Txs":{"name":["悬桥巷","Xuanqiaoxiang"],"num":"00","services":["local"],"parents":["1gg4pI"],"children":["Eev0PY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Eev0PY":{"name":["临顿路","Lindunlu"],"num":"00","services":["local"],"parents":["Bt2Txs"],"children":["7ojrMY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz1","#78BA25","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7ojrMY":{"name":["忘星桥","Wangxingqiao"],"num":"00","services":["local"],"parents":["Eev0PY"],"children":["EN9MMh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EN9MMh":{"name":["徐家浜","Xujiabang"],"num":"00","services":["local"],"parents":["7ojrMY"],"children":["v3VKHg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"v3VKHg":{"name":["惹云桥","Reyunqiao"],"num":"00","services":["local"],"parents":["EN9MMh"],"children":["jJZW4k"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"jJZW4k":{"name":["秋塘浜","Qiutangbang"],"num":"00","services":["local"],"parents":["v3VKHg"],"children":["a0E9qw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"a0E9qw":{"name":["李公堤西","Ligongdi West"],"num":"00","services":["local"],"parents":["jJZW4k"],"children":["MnE_8P"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["3号线","Line 3"]},{"theme":["suzhou","sz11","#f1c6a6","#fff"],"name":["11号线","Line 11"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"MnE_8P":{"name":["琼基墩","Qiongjidun"],"num":"00","services":["local"],"parents":["a0E9qw"],"children":["zw26lz"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zw26lz":{"name":["南施公园","Nanshigongyuan"],"num":"00","services":["local"],"parents":["MnE_8P"],"children":["ANj9L6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ANj9L6":{"name":["苏州奥体中心","Suzhou Olympic Sports Centre"],"num":"00","services":["local"],"parents":["zw26lz"],"children":["2eZ8ue"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz5","#E63A9A","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2eZ8ue":{"name":["丰泰桥","Fengtaiqiao"],"num":"00","services":["local"],"parents":["ANj9L6"],"children":["pxNEkx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pxNEkx":{"name":["涵青桥","Hanqingqiao"],"num":"00","services":["local"],"parents":["2eZ8ue"],"children":["ugU53L"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ugU53L":{"name":["金家堰","Jinjiayan"],"num":"00","services":["local"],"parents":["pxNEkx"],"children":["aYyrBJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aYyrBJ":{"name":["北斜步","Beixiebu"],"num":"00","services":["local"],"parents":["ugU53L"],"children":["sinsbN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sinsbN":{"name":["南斜步","Nanxiebu"],"num":"00","services":["local"],"parents":["aYyrBJ"],"children":["XFs44i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"XFs44i":{"name":["金尚路","Jinshanglu"],"num":"00","services":["local"],"parents":["sinsbN"],"children":["4qS5JM"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"4qS5JM":{"name":["桑田岛","Sangtiandao"],"num":"00","services":["local"],"parents":["XFs44i"],"children":["koONnG"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"koONnG":{"name":["华云","Huayun"],"num":"00","services":["local"],"parents":["4qS5JM"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Charlis-Aviation** [comment]
@QYQACB 您好，
您所提交的模板有以下的問題，請儘快更改並重新提交一份 Issue

- 所在站點錯誤，先前的站點變成灰色
- 苏州新区火车站 缺少 苏州高新有轨电车2号线 的換乘信息
- 宝丰站 名字錯了，應爲保丰站
- 长青站 Changqing 名字錯了，應爲 长泾站 Changjing
- 白洋湾站 Baiyangwan 名字錯了，應爲 白洋湾公园站 Baiyangwangongyuan
- 拙政园站 Zhuozhengyuan 名字錯了，應爲 拙政园苏博站 Humble Administrator’s Garden Suzhou Museum
- 忘星桥站 Wangxingqiao 名字錯了，應爲 望星桥苏大站 Wangxingqiao Soochow University
- 南施公园站 Nanshigongyuan 名字錯了，應爲 南施公园南站 Nanshigongyuan South
- 苏州奥体中心站 中間缺少 儿童医院总院站，多了 丰泰桥站

謝謝：）

**Comment by QYQACB** [comment]
已經完成修改。感謝指正。
