### ISSUE TITLE
Resources: New templates of Guangzhou Metro

### ISSUE THREAD

**Issue by xiexiaogongyang** [railmapgen/rmg-templates#1191]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Line diagram on the Internet |
|     Reference link    | https://cs.gzmtr.com/ckfw/xlu_2020/202405/W020240524846059965254.png |
|     Justification     | 6号线的萝岗站可以换成7号线，但是在现有RMG模板里没有更新， |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gzmtr" line="gz6" major="false"><summary>gzmtr/gz6</summary><details type="name">{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線","ko":"6호선"}</details><details type="param">{"style":"gzmtr","svg_height":300,"padding":1.6100436053476448,"y_pc":40,"theme":["guangzhou","gz6","#80225F","#fff"],"direction":"l","current_stn_idx":"l1mz","platform_num":"2","stn_list":{"linestart":{"parents":[],"children":["2n3c"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"num":"00","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"num":"00","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["4yoy"],"children":["iwf6"],"name":["萝岗","Luogang"],"branch":{"left":[],"right":[]},"num":"31","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz7","#97D700","#fff"],"name":["7号线","Line 7"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["lineend"],"parents":["l1mz"],"name":["香雪","Xiangxue"],"branch":{"left":[],"right":[]},"num":"32","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"4yoy":{"branch":{"left":[],"right":[]},"parents":["e5aw"],"children":["l1mz"],"name":["苏元","Suyuan"],"num":"30","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz21","#211747","#fff"],"name":["21号线","Line 21"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"e5aw":{"branch":{"left":[],"right":[]},"parents":["5hy5"],"children":["4yoy"],"name":["暹岗","Xiangang"],"num":"29","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"5hy5":{"branch":{"left":[],"right":[]},"parents":["9bwm"],"children":["e5aw"],"name":["金峰","Jinfeng"],"num":"28","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"9bwm":{"branch":{"left":[],"right":[]},"parents":["huco"],"children":["5hy5"],"name":["黄陂","Huangbei"],"num":"27","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"huco":{"branch":{"left":[],"right":[]},"parents":["bmk1"],"children":["9bwm"],"name":["高塘石","Gaotangshi"],"num":"26","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"bmk1":{"branch":{"left":[],"right":[]},"parents":["6uin"],"children":["huco"],"name":["柯木塱","Kemulang"],"num":"25","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"6uin":{"branch":{"left":[],"right":[]},"parents":["6zky"],"children":["bmk1"],"name":["龙洞","Longdong"],"num":"24","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"6zky":{"branch":{"left":[],"right":[]},"parents":["9l7g"],"children":["6uin"],"name":["植物园","Botanical Garden"],"num":"23","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"9l7g":{"branch":{"left":[],"right":[]},"parents":["un8f"],"children":["6zky"],"name":["长湴","Changban"],"num":"22","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"un8f":{"branch":{"left":[],"right":[]},"parents":["svif"],"children":["9l7g"],"name":["天河客运站","Tianhe Coach Terminal"],"num":"21","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz3","#ECA154","#fff"],"name":["3号线","Line 3"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"svif":{"branch":{"left":[],"right":[]},"parents":["k6p4"],"children":["un8f"],"name":["燕塘","Yantang"],"num":"20","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz3","#ECA154","#fff"],"name":["3号线","Line 3"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"k6p4":{"branch":{"left":[],"right":[]},"parents":["3yow"],"children":["svif"],"name":["天平架","Tianpingjia"],"num":"19","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"3yow":{"branch":{"left":[],"right":[]},"parents":["6qq5"],"children":["k6p4"],"name":["沙河顶","Shaheding"],"num":"17","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"6qq5":{"branch":{"left":[],"right":[]},"parents":["oeq6"],"children":["3yow"],"name":["黄花岗","Huanghuagang"],"num":"16","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"oeq6":{"branch":{"left":[],"right":[]},"parents":["45g2"],"children":["6qq5"],"name":["区庄","Ouzhuang"],"num":"15","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz5","#C5003E","#fff"],"name":["5号线","Line 5"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"45g2":{"branch":{"left":[],"right":[]},"parents":["3ik5"],"children":["oeq6"],"name":["东山口","Dongshankou"],"num":"14","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz1","#F3D03E","#000"],"name":["1号线","Line 1"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"3ik5":{"branch":{"left":[],"right":[]},"parents":["inj5"],"children":["45g2"],"name":["东湖","Donghu"],"num":"13","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"inj5":{"branch":{"left":[],"right":[]},"parents":["qfar"],"children":["3ik5"],"name":["团一大广场","Tuanyida Square"],"num":"12","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"qfar":{"branch":{"left":[],"right":[]},"parents":["hcfi"],"children":["inj5"],"name":["北京路","Beijing Lu"],"num":"11","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hcfi":{"branch":{"left":[],"right":[]},"parents":["x4wt"],"children":["qfar"],"name":["海珠广场","Haizhu Square"],"num":"10","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz2","#00629B","#fff"],"name":["2号线","Line 2"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"x4wt":{"branch":{"left":[],"right":[]},"parents":["l1z2"],"children":["hcfi"],"name":["一德路","Yide Lu"],"num":"09","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"l1z2":{"branch":{"left":[],"right":[]},"parents":["dul8"],"children":["x4wt"],"name":["文化公园","Cultural Park"],"num":"08","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz8","#008C95","#fff"],"name":["8号线","Line 8"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"dul8":{"branch":{"left":[],"right":[]},"parents":["7m99"],"children":["l1z2"],"name":["黄沙","Huangsha"],"num":"07","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz1","#F3D03E","#000"],"name":["1号线","Line 1"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"7m99":{"branch":{"left":[],"right":[]},"parents":["dz4j"],"children":["dul8"],"name":["如意坊","Ruyifang"],"num":"06","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"dz4j":{"branch":{"left":[],"right":[]},"parents":["z1lf"],"children":["7m99"],"name":["坦尾","Tanwei"],"num":"05","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["guangzhou","gz5","#C5003E","#fff"],"name":["5号线","Line 5"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"z1lf":{"branch":{"left":[],"right":[]},"parents":["dc3p"],"children":["dz4j"],"name":["河沙","Hesha"],"num":"04","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"dc3p":{"branch":{"left":[],"right":[]},"parents":["wzas"],"children":["z1lf"],"name":["沙贝","Shabei"],"num":"03","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"wzas":{"branch":{"left":[],"right":[]},"parents":["2n3c"],"children":["dc3p"],"name":["横沙","Hengsha"],"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"2n3c":{"branch":{"left":[],"right":[]},"parents":["linestart"],"children":["wzas"],"name":["浔峰岗","Xunfenggang"],"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355}},"line_name":["6号线","Line 6"],"psd_num":"1","line_num":"6","info_panel_type":"gz28","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1000,"runin":1000,"railmap":2500,"indoor":2500},"namePosMTR":{"isStagger":true,"isFlip":true},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":30}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
