### ISSUE TITLE
Resources: New templates of qcsgdjt

### ISSUE THREAD

**Issue by qcs123-mz** [railmapgen/rmg-templates#1222]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Others (Please indicate below) |
|     Reference link    | www. |
|     Justification     | 自主设计的 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="QCSGDJT" line="00config"><summary>New company: qcsgdjt</summary><details type="name">{"en":"qcsgdjt","zh-Hans":"清城市轨道交通","zh-Hant":"清城市轨道交通"}</details></details>

<details repo="rmg-templates" company="QCSGDJT" line="QCSYGDCSFX" major="false"><summary>QCSGDJT/QCSYGDCSFX</summary><details type="name">{"en":"Qingcheng City Tram Demonstration Line","zh-Hans":"清城市有轨电车示范线","zh-Hant":"清都市有軌電車示範線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hongkong","twl","#e60013","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"uO4ubk","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["aUEjfe"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aUEjfe":{"name":["顺通路","Shuntong Rd"],"num":"01","services":["local"],"parents":["linestart"],"children":["N88mJe"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"secondaryName":["1号航站楼",""]},"N88mJe":{"name":["海岛市场","Island Market"],"num":"02","services":["local"],"parents":["aUEjfe"],"children":["uO4ubk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["uO4ubk"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"uO4ubk":{"name":["清城北一环","Qingcheng North First Ring Road"],"num":"00","services":["local"],"parents":["N88mJe"],"children":["lineend"],"transfer":{"groups":[{},{},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.16.15"}</details></details>

**Comment by linchen1965** [comment]
您好，感谢您对本项目的支持。由于目前RMG模板暂不支持提交虚构世界的RMG模板，很抱歉您所提交的RMG模板不会汇入到本项目中。
