### ISSUE TITLE
Resources: New templates of Beijing Suburban Railway

### ISSUE THREAD

**Issue by Jwanpandenwaa** [railmapgen/rmg-templates#1226]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)

**Comment by Charlis-Aviation** [comment]
@Jwanpandenwaa 您好，
由於您沒有附上任何内容，我們將會關閉您的Issue。請重開一個提交您的範本，謝謝：》
