### ISSUE TITLE
Resources: New templates of Wenzhou Rail Transit

### ISSUE THREAD

**Issue by FLYER2048** [railmapgen/rmg-templates#125]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/rmg-templates/new and paste the palette data below_

**Justification:** 新增温州轨道交通S2线 参考https://baike.baidu.com/item/%E6%B8%A9%E5%B7%9E%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AS2%E7%BA%BF/23321999?fr=aladdin

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="wzrail" line="00config"><summary>New company: Wenzhou Rail Transit</summary><details type="name">{"en":"Wenzhou Rail Transit","zh-Hans":"温州轨道交通","zh-Hant":"溫州軌道交通"}</details></details>

<details repo="rmg-templates" company="wzrail" line="wzs2" major="false"><summary>wzrail/wzs2</summary><details type="name">{"en":"Line S2","zh-Hans":"S2线","zh-Hant":"S2缐"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":16,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["hongkong","twl","#E2231A","#fff"],"line_name":["S2线","Line S2"],"current_stn_idx":"fK1mzz","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["72OI-L"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"72OI-L":{"name":["清东路","Qingdong Road"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["p-64UV"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"p-64UV":{"name":["旭阳路","Xuyang Road"],"secondaryName":false,"num":"02","services":["local"],"parents":["72OI-L"],"children":["ae2hfC"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["fK1mzz"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ae2hfC":{"name":["万岙","Wan'ao"],"secondaryName":false,"num":"00","services":["local"],"parents":["p-64UV"],"children":["6TO0I_"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fK1mzz":{"name":["东山","Dongshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["7pU9vy"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#ff9900","#fff","S3线","Line S3"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7pU9vy":{"name":["上东路","Shangdong Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["xW3n0R"],"children":["fK1mzz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xW3n0R":{"name":["上望","Shangwang"],"secondaryName":false,"num":"00","services":["local"],"parents":["mYqlH9"],"children":["7pU9vy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mYqlH9":{"name":["新塍","Xincheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["_Xy_h6"],"children":["xW3n0R"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_Xy_h6":{"name":["汀田","Tingtian"],"secondaryName":false,"num":"00","services":["local"],"parents":["QwUdeS"],"children":["mYqlH9"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QwUdeS":{"name":["大典下","Dadianxia"],"secondaryName":false,"num":"00","services":["local"],"parents":["KzEc2k"],"children":["_Xy_h6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KzEc2k":{"name":["鲍田","Baotian"],"secondaryName":false,"num":"00","services":["local"],"parents":["wPRYGV"],"children":["QwUdeS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wPRYGV":{"name":["海城","Haicheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["qUCkhz"],"children":["KzEc2k"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qUCkhz":{"name":["天河","Tianhe"],"secondaryName":false,"num":"00","services":["local"],"parents":["NN8HB_"],"children":["wPRYGV"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NN8HB_":{"name":["沙城","Shacheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["IdyuhA"],"children":["qUCkhz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IdyuhA":{"name":["永兴","Yongxing"],"secondaryName":false,"num":"00","services":["local"],"parents":["Jsrd6O"],"children":["NN8HB_"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#0000ff","#fff","S1线","S1线"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Jsrd6O":{"name":["机场","Airport"],"secondaryName":false,"num":"00","services":["local"],"parents":["SDU2Qs"],"children":["IdyuhA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#0000ff","#fff","S1线","Line S1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SDU2Qs":{"name":["灵昆","Lingkun"],"secondaryName":false,"num":"00","services":["local"],"parents":["I1Xrlr"],"children":["Jsrd6O"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"I1Xrlr":{"name":["黄华","Huanghua"],"secondaryName":false,"num":"00","services":["local"],"parents":["3xgAho"],"children":["SDU2Qs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3xgAho":{"name":["翁垟","Wengyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["EUbVdF"],"children":["I1Xrlr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EUbVdF":{"name":["新望","Xinwang"],"secondaryName":false,"num":"00","services":["local"],"parents":["6TO0I_"],"children":["3xgAho"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6TO0I_":{"name":["盐盆","Yanpen"],"secondaryName":false,"num":"00","services":["local"],"parents":["ae2hfC"],"children":["EUbVdF"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @FLYER2048,

溫州S2線尚未開通，該範本暫不會被合入，直至路線開通為止。多謝閣下的貢獻。

**Comment by wongchito** [comment]
Hi @FLYER2048 ,

經檢查，閣下所提交的範本存在但不限於以下問題：

- S3線尚未開通，不應加入
- 路線提供快車服務，使用上海風格時請於相應車站選擇「快車」

由於該Issue提交時間過早，RMG已作出不少變更，因此請閣下在修正問題後開啟新Issue。多謝閣下的頁獻！
