### ISSUE TITLE
Resources: New templates of Qingdao Metro

### ISSUE THREAD

**Issue by 116143641** [railmapgen/rmg-templates#1256]
| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Images taken in the stations (Upload separately in Issue) |
|     Reference link    |  |
|     Justification     | 青岛是我家乡，我做仿真线路 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="qdmetro" line="6号线" major="false"><summary>qdmetro/6号线</summary><details type="name">{"en":"Qingdao Metro Line 6","zh-Hans":"青岛地铁6号线","zh-Hant":"青島捷運6號線","ja":"青島地下鉄6号線","ko":"청도 지하철 6호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1500,"railmap":2600,"indoor":1500},"svg_height":300,"style":"mtr","y_pc":51,"padding":7,"branchSpacingPct":0,"direction":"r","platform_num":"6","theme":["qingdao","qd6","#6ca3d8","#fff"],"line_name":["6号线"," Line 6"],"current_stn_idx":"stn_kNYyijJm5w","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["stn_kNYyijJm5w"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["stn_dufZJc6xSY"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_dufZJc6xSY":{"name":["横云山路","Hengyunshan Rd"],"num":"21","services":["local"],"parents":["stn_5A_zKu1cjb"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_5A_zKu1cjb":{"name":["山王河(福莱社区)","Shanwanghe (Fulai Community)"],"num":"20","services":["local"],"parents":["stn_1tKBbeN81B"],"children":["stn_dufZJc6xSY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_1tKBbeN81B":{"name":["河洛埠(中德生态园)","Heluobu (Sino-German Ecopark)"],"num":"19","services":["local"],"parents":["stn_axDGEyFnqx"],"children":["stn_5A_zKu1cjb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_axDGEyFnqx":{"name":["青岛九中(幸福小镇)","Qingdao No. 9 High School\n(Xingfuxiaozhen)"],"num":"18","services":["local"],"parents":["stn_mQEFf5TtQM"],"children":["stn_1tKBbeN81B"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_mQEFf5TtQM":{"name":["抓马山","Zhuamashan"],"num":"17","services":["local"],"parents":["stn_aeXqbr4tP_"],"children":["stn_axDGEyFnqx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_aeXqbr4tP_":{"name":["马家楼","Majialou"],"num":"16","services":["local"],"parents":["stn_vFFV5XiTfP"],"children":["stn_mQEFf5TtQM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_vFFV5XiTfP":{"name":["薛家泊子","Xuejiapozi"],"num":"15","services":["local"],"parents":["stn_nTvu7_QMdG"],"children":["stn_aeXqbr4tP_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_nTvu7_QMdG":{"name":["港头","Gangtou"],"num":"14","services":["local"],"parents":["stn_MKd05MP1pk"],"children":["stn_vFFV5XiTfP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_MKd05MP1pk":{"name":["青大附院西海岸院区","West Coast Campus of the\nAffiliated Hospital of Qingdao University"],"num":"13","services":["local"],"parents":["stn_Y61Tza6Xfl"],"children":["stn_nTvu7_QMdG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_Y61Tza6Xfl":{"name":["扒山(滨海学院)","Pashan (Qingdao Binhai University)"],"num":"12","services":["local"],"parents":["stn_QRwGEkL-OU"],"children":["stn_MKd05MP1pk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_QRwGEkL-OU":{"name":["钱塘江路(青职学院)","Qiantangjiang Rd (Qingdao Technical College)"],"num":"11","services":["local"],"parents":["stn_Jd0mJrBgg6"],"children":["stn_Y61Tza6Xfl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_Jd0mJrBgg6":{"name":["九顶山","Jiudingshan"],"num":"10","services":["local"],"parents":["stn_N9Sk1aA6aV"],"children":["stn_QRwGEkL-OU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_N9Sk1aA6aV":{"name":["王家港","Wangjiagang"],"num":"9","services":["local"],"parents":["stn_JbBOwrJwMx"],"children":["stn_Jd0mJrBgg6"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd1","#f7b000","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_JbBOwrJwMx":{"name":["北门外","Beimenwai"],"num":"8","services":["local"],"parents":["stn_ASJIIACmiy"],"children":["stn_N9Sk1aA6aV"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_ASJIIACmiy":{"name":["西门外","Ximenwai"],"num":"7","services":["local"],"parents":["stn_VXblF2vjuE"],"children":["stn_JbBOwrJwMx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_VXblF2vjuE":{"name":["毛家山(黄海学院)","Maojiashan (Qingdao\nHuanghai University)"],"num":"6","services":["local"],"parents":["stn_rkARqky-SQ"],"children":["stn_ASJIIACmiy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_rkARqky-SQ":{"name":["赵家庙\n(影视产业园)","Zhaojiamiao\n(Film Metropolis)"],"num":"5","services":["local"],"parents":["stn_kTFx1NNT-2"],"children":["stn_VXblF2vjuE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_kTFx1NNT-2":{"name":["星海滩路","Xinghaitan Rd"],"num":"4","services":["local"],"parents":["stn_vIm2HVsE24"],"children":["stn_rkARqky-SQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_vIm2HVsE24":{"name":["华山","Huashan"],"num":"3","services":["local"],"parents":["stn_qImCVux4BC"],"children":["stn_kTFx1NNT-2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_qImCVux4BC":{"name":["辛屯","Xintun"],"num":"2","services":["local"],"parents":["stn_kNYyijJm5w"],"children":["stn_vIm2HVsE24"],"transfer":{"groups":[{"lines":[{"theme":["qingdao","qd13","#009c86","#fff"],"name":["西海岸快线","The West Coast Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"stn_kNYyijJm5w":{"name":["灵山湾","Lingshan Bay"],"num":"1","services":[],"parents":["linestart"],"children":["stn_qImCVux4BC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"6","psd_num":"1","info_panel_type":"sh","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，#1267 已经做出同样更新且更新时间更早，因此我们遵循先到先得的原则接受了该更新，因此您无需继续进行更新，感谢。
