### ISSUE TITLE
Resources: New templates of Shenzhen Metro

### ISSUE THREAD

**Issue by IamDaHuang** [railmapgen/rmg-templates#134]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/rmg-templates/new and paste the palette data below_

(REPLACE ME/替代我）
6号线支线更新（四期）

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。您需要遵从rmg-templates的提示将提供的内容复制到issue的对应地方，目前的issue由于没有任何数据所以我们无法进行进一步的操作，谢谢。
