### ISSUE TITLE
[New Templates] Great Tokyo Area Subway&Metro Lines

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg-templates#14]
Some templates here. I would like to add them into the rmg templates.

Toei Subway lines:
[浅草線.zip](https://github.com/railmapgen/rmg/files/8589218/default.zip)
[三田線.zip](https://github.com/railmapgen/rmg/files/8589221/default.zip)
[新宿缐.zip](https://github.com/railmapgen/rmg/files/8589225/default.zip)
Because of the bug of loop line with branches, Oedo Line isn't here.

Tokyo Metro lines:
[日比谷線.zip](https://github.com/railmapgen/rmg/files/8589233/default.zip)
[銀座線.zip](https://github.com/railmapgen/rmg/files/8589242/default.zip)
[丸ノ内線.zip](https://github.com/railmapgen/rmg/files/8589244/default.zip)
[東西線.zip](https://github.com/railmapgen/rmg/files/8589248/default.zip)
[南北線.zip](https://github.com/railmapgen/rmg/files/8589249/default.zip)
[有楽町缐.zip](https://github.com/railmapgen/rmg/files/8589250/default.zip)
[千代田線.zip](https://github.com/railmapgen/rmg/files/8589252/default.zip)
[半蔵門線.zip](https://github.com/railmapgen/rmg/files/8589256/default.zip)
[副都心線.zip](https://github.com/railmapgen/rmg/files/8589267/default.zip)

That's all of my templates. @thekingofcity  @wongchito   Please add them into the rmg templates.

**Comment by e233-1000** [comment]
> Hi, thanks for your contribution. What's the difference between this, #10, and #9? If they contain the same lines, you may only leave one open. 😄

I fixed some bugs in the old templates. This is the lastest one.

**Comment by thekingofcity** [comment]
Great. Loop line with branches will be available in the coming few days. Stay tuned. railmapgen/rmg#342

**Comment by e233-1000** [comment]
The loop line with branch line is available now. Although there's still a bug, but I finnished the Oedo Line.

Toei Subway Line:
[大江戸線.zip](https://github.com/railmapgen/rmg-templates/files/8628279/default.zip)

This is the Oedo Line templates. Please add the Toei Subway Lines and Tokyo Metro Lines in the rmg at once!

@thekingofcity @wongchito

**Comment by thekingofcity** [comment]
[Toei Subway Line.zip](https://github.com/railmapgen/rmg-templates/files/8628559/Toei.Subway.Line.zip)

Loop line with branches requires precise tuning as stated in https://github.com/railmapgen/rmg/pull/342. You may have a look at the updated template.

> The first branch should head to left and the second branch should head to right (may be fixed in later issues).

Which case do you need to have a branch head to right? In fact, I can't see the reason to flip the entire main line since it is a LOOP.

**Comment by e233-1000** [comment]
The Oedo Line is finnished!

Toei Subway Lines:
[大江戸線.zip](https://github.com/railmapgen/rmg-templates/files/8648338/default.zip)

@thekingofcity Please add the templates into rmg at once.The name will be:
English `Great Tokyo Area Railways`
Mainland Chinese `东京都区域内轨道交通`
Taiwan, Hong kong and Macao Chinese `東京都區域內軌道交通`

And don't close the issue. The JR lines in Great Tokyo Area will be finnished in the few days.

**Comment by thekingofcity** [comment]
> The JR lines in Great Tokyo Area will be finnished in the few days.

You may open a new issue for the JR lines.

**Comment by e233-1000** [comment]
> You may open a new issue for the JR lines.

I know. There're a lot of JR lines.

**Comment by 52PD** [comment]
Hi,

Since our Template submission tool is introduced, we will follow same out-of-date rule for all problem contents that same to the RMG Palette.

Consider this issue is no any response since May 9, 2022, we will close this issue. Sorry about that.

**Comment by 52PD** [comment]
Closed as no response over 1 month.
