### ISSUE TITLE
Resources: New templates of Milanese Transports Company

### ISSUE THREAD

**Issue by yileitu** [railmapgen/rmg-templates#1479]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://en.wikipedia.org/wiki/Milan_Metro_Line_4 |
|     Justification     | Added Milan Metro Line 4. |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="atm" line="00config"><summary>New company: Milanese Transports Company</summary><details type="name">{"en":"Milanese Transports Company","zh-Hans":"米兰交通公司","zh-Hant":"米蘭交通公司"}</details></details>

<details repo="rmg-templates" company="atm" line="M4" major="false"><summary>atm/M4</summary><details type="name">{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線","it":"M4"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2000,"indoor":1200},"svg_height":600,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["milan","mm4","#003777","#fff"],"line_name":["M4",""],"current_stn_idx":"hjZPpX","stn_list":{"linestart":{"localisedName":{"en":"LEFT END"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":[],"children":["Z8ajN2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Z8ajN2":{"localisedName":{"zh":"San Cristoforo","en":"圣克里斯托福罗"},"localisedSecondaryName":{},"num":"01","services":["local"],"parents":["linestart"],"children":["uhzVxv"],"transfer":{"groups":[{},{},{"lines":[{"theme":["milan","ms9","#A83B8E","#fff"],"name":["S9",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"uhzVxv":{"localisedName":{"zh":"Segneri","en":"塞格内里"},"localisedSecondaryName":{},"num":"02","services":["local"],"parents":["Z8ajN2"],"children":["C-sTYE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"localisedName":{"en":"RIGHT END"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["hjZPpX"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"C-sTYE":{"localisedName":{"zh":"Gelsomini","en":"茉莉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["uhzVxv"],"children":["3zSOm2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6g0aNh":{"localisedName":{"zh":"Santa Sofia","en":"圣索菲亚"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["vppk8-"],"children":["_HK9OS"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vppk8-":{"localisedName":{"zh":"Vetra","en":"维特拉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["21T_G6"],"children":["6g0aNh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"21T_G6":{"localisedName":{"zh":"De Amicis","en":"德·亚米契斯"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["8_Un_R"],"children":["vppk8-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8_Un_R":{"localisedName":{"zh":"Sant'Ambrogio","en":"圣安波罗修 "},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["vJ32ry"],"children":["21T_G6"],"transfer":{"groups":[{"lines":[{"theme":["milan","mm2","#5F9334","#fff"],"name":["M2",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vJ32ry":{"localisedName":{"zh":"Coni Zugna","en":"祖格纳山"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["P98HLL"],"children":["8_Un_R"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"P98HLL":{"localisedName":{"zh":"California","en":"加利福尼亚"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["Ybqi9T"],"children":["vJ32ry"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Ybqi9T":{"localisedName":{"zh":"Bolivar","en":"玻利瓦尔"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["YMO7d5"],"children":["P98HLL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YMO7d5":{"localisedName":{"zh":"Tolstoj","en":"托尔斯泰"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["3zSOm2"],"children":["Ybqi9T"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3zSOm2":{"localisedName":{"zh":"Frattini","en":"弗拉蒂尼\t"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["C-sTYE"],"children":["YMO7d5"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YKZA_0":{"localisedName":{"zh":"Dateo","en":"达泰奥"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["qQ1juP"],"children":["WRGPxQ"],"transfer":{"groups":[{},{},{"lines":[{"theme":["milan","ms1","#E43129","#fff"],"name":["S1",""]},{"theme":["milan","ms2","#009775","#fff"],"name":["S2",""]},{"theme":["milan","ms5","#F0922B","#000"],"name":["S5",""]},{"theme":["milan","ms6","#F4CE0E","#000"],"name":["S6",""]},{"theme":["milan","ms13","#8E5536","#fff"],"name":["S13",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"qQ1juP":{"localisedName":{"zh":"Tricolore","en":"三色"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["6AeMO9"],"children":["YKZA_0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6AeMO9":{"localisedName":{"zh":"San Babila","en":"圣巴比拉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["_HK9OS"],"children":["qQ1juP"],"transfer":{"groups":[{"lines":[{"theme":["milan","mm1","#E01023","#fff"],"name":["M1",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"_HK9OS":{"localisedName":{"zh":"Sforza Policlinico","en":"斯福尔扎医院"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["6g0aNh"],"children":["6AeMO9"],"transfer":{"groups":[{},{"lines":[{"theme":["milan","mm3","#F3A800","#fff"],"name":["M3",""]}],"name":["Missori","米索里"]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YoKlcT":{"localisedName":{"zh":"Argonne","en":"阿尔贡"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["WRGPxQ"],"children":["OIayw_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WRGPxQ":{"localisedName":{"zh":"Susa","en":"苏萨"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["YKZA_0"],"children":["YoKlcT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QWQ371":{"localisedName":{"zh":"Repetti","en":"雷佩蒂"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["OIayw_"],"children":["hjZPpX"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"OIayw_":{"localisedName":{"zh":"Stazione Forlanini","en":"弗拉尼尼站"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["YoKlcT"],"children":["QWQ371"],"transfer":{"groups":[{},{},{"lines":[{"theme":["milan","ms5","#F0922B","#000"],"name":["S5",""]},{"theme":["milan","ms6","#F4CE0E","#000"],"name":["S6",""]},{"theme":["milan","ms9","#A83B8E","#fff"],"name":["S9",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hjZPpX":{"localisedName":{"zh":"Linate Aeroporto","en":"利纳特机场"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["QWQ371"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"airport"}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.17.1"}</details></details>

**Comment by thekingofcity** [comment]
Thanks for your contribution! Your template is merged and will be available soon :)
