### ISSUE TITLE
Resources: New templates of Milanese Transports Company

### ISSUE THREAD

**Issue by yileitu** [railmapgen/rmg-templates#1481]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

| Item | Value |
|---|---|
| Route map in stations | Yes |
|    Opening status     | Opened |
| Reference source type | Online encyclopaedia (e.g. Wikipedia) |
|     Reference link    | https://en.wikipedia.org/wiki/Milan_Metro_Line_5 |
|     Justification     | Added Milan Metro Line 5 |

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="atm" line="m5" major="false"><summary>atm/m5</summary><details type="name">{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線","it":"M5"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2000,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["milan","mm5","#A394C6","#fff"],"line_name":["M5","Line 5"],"current_stn_idx":"VVttzc","stn_list":{"linestart":{"localisedName":{"en":"LEFT END"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":[],"children":["CmvNs-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"CmvNs-":{"localisedName":{"zh":"Bignami","en":"比格纳米"},"localisedSecondaryName":{},"num":"01","services":["local"],"parents":["linestart"],"children":["nJ_NHu"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"localisedName":{"en":"RIGHT END"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["VVttzc"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"8pROVx":{"localisedName":{"zh":"Tre Torri","en":"三塔"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["4n3ea4"],"children":["kNba0k"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"4n3ea4":{"localisedName":{"zh":"Domodossola","en":"多莫多索拉站"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["c2qujO"],"children":["8pROVx"],"transfer":{"groups":[{},{"lines":[]},{"lines":[{"theme":["milan","ms3","#AD2237","#fff"],"name":["S3",""]},{"theme":["milan","ms4","#7FB829","#000"],"name":["S4",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"},"c2qujO":{"localisedName":{"zh":"Gerusalemme","en":"耶路撒冷"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["MVQEa0"],"children":["4n3ea4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"MVQEa0":{"localisedName":{"zh":"Cenisio","en":"塞尼西奥"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["MAtEby"],"children":["c2qujO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"MAtEby":{"localisedName":{"zh":"Monumentale","en":"纪念墓园"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["SGYNzf"],"children":["MVQEa0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"SGYNzf":{"localisedName":{"zh":"Garibaldi FS","en":"加里波底门站"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["4BAarf"],"children":["MAtEby"],"transfer":{"groups":[{"lines":[{"theme":["milan","mm2","#5F9334","#fff"],"name":["M2",""]}]},{"lines":[]},{"lines":[{"theme":["milan","ms1","#E43129","#fff"],"name":["S1",""]},{"theme":["milan","ms2","#009775","#fff"],"name":["S2",""]},{"theme":["milan","ms5","#F0922B","#000"],"name":["S5",""]},{"theme":["milan","ms6","#F4CE0E","#000"],"name":["S6",""]},{"theme":["milan","ms7","#E3296F","#fff"],"name":["S7",""]},{"theme":["milan","ms8","#F4B4B6","#fff"],"name":["S8",""]},{"theme":["milan","ms11","#9bafd9","#fff"],"name":["S11",""]},{"theme":["milan","ms12","#223434","#fff"],"name":["S12",""]},{"theme":["milan","ms13","#8E5536","#fff"],"name":["S13",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{},"facility":"hsr"},"4BAarf":{"localisedName":{"zh":"Isola","en":"伊索拉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["lenpTl"],"children":["SGYNzf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lenpTl":{"localisedName":{"zh":"Zara","en":"扎拉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["a9BvYx"],"children":["4BAarf"],"transfer":{"groups":[{"lines":[{"theme":["milan","mm3","#F3A800","#fff"],"name":["M3",""]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"a9BvYx":{"localisedName":{"zh":"Marche","en":"马尔凯"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["FIcC9K"],"children":["lenpTl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"FIcC9K":{"localisedName":{"zh":"Istria","en":"伊斯特拉"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["G4TK0A"],"children":["a9BvYx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"G4TK0A":{"localisedName":{"zh":"Ca' Granda","en":"格兰达"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["MCm4Jg"],"children":["FIcC9K"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"MCm4Jg":{"localisedName":{"zh":"Bicocca","en":"比可卡"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["nJ_NHu"],"children":["G4TK0A"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"nJ_NHu":{"localisedName":{"zh":"Ponale","en":"波纳莱"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["CmvNs-"],"children":["MCm4Jg"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kNba0k":{"localisedName":{"zh":"Portello","en":"波特洛"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["8pROVx"],"children":["tJeJsh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"VVttzc":{"localisedName":{"zh":"San Siro Stadio","en":"圣西罗球场"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["KcX7wK"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"KcX7wK":{"localisedName":{"zh":"San Siro Ippodromo","en":"圣西罗赛马场"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["asg8ss"],"children":["VVttzc"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"asg8ss":{"localisedName":{"zh":"Segesta","en":"塞杰斯塔"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["tJeJsh"],"children":["KcX7wK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"tJeJsh":{"localisedName":{"zh":"Lotto","en":"洛托"},"localisedSecondaryName":{},"num":"00","services":["local"],"parents":["kNba0k"],"children":["asg8ss"],"transfer":{"groups":[{},{"lines":[]},{"lines":[{"theme":["milan","mm1","#E01023","#fff"],"name":["M1",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your template is merged and will be available soon :)
