### ISSUE TITLE
重庆轨道交通部分线路模板

### ISSUE THREAD

**Issue by TNLHK** [railmapgen/rmg-templates#15]
[CRT.zip](https://github.com/wongchito/RailMapGenerator/files/8131505/CRT.zip)
[CRT0.zip](https://github.com/wongchito/RailMapGenerator/files/8312923/CRT0.zip)
[CRT1.zip](https://github.com/wongchito/RailMapGenerator/files/8140681/CRT1.zip)
[重庆轨道交通2号线.zip](https://github.com/wongchito/RailMapGenerator/files/8131507/2.zip)
[CRT3+空港线.zip](https://github.com/railmapgen/rmg-templates/files/9388770/CRT3%2B.zip)
[CRT4.zip](https://github.com/wongchito/RailMapGenerator/files/8140680/CRT4.zip)
[CRT5.zip](https://github.com/wongchito/RailMapGenerator/files/8176153/CRT5.zip)
[CRT9.zip](https://github.com/railmapgen/rmg-templates/files/9388691/CRT9.zip)
[CRT10.zip](https://github.com/railmapgen/rmg-templates/files/9388759/CRT10.zip)

第一次做线路图模板，可能会有一些错误（

**Comment by Sherwoodniki** [comment]
请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了

**Comment by 52PD** [comment]
> 请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了

线路模版投稿可以参照这里：https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates

**Comment by 52PD** [comment]
您好，在上次（5月20日）楼主更新线路模版投稿后，空港线、6号线、国博线、9号线、10号线和本月开通的江跳线的线路模版仍然未见提交，所以就像@thekingofcity 所说的，建议您将剩余六条线制作完成后与已经上传的六条线一起打包上传，这样也方便我们将所有线路汇入到项目中。

再次感谢您对本项目的支持！

**Comment by TNLHK** [comment]
> 您好，在上次（5月20日）楼主更新线路模版投稿后，空港线、6号线、国博线、9号线、10号线和本月开通的江跳线的线路模版仍然未见提交，所以就像@thekingofcity 所说的，建议您将剩余六条线制作完成后与已经上传的六条线一起打包上传，这样也方便我们将所有线路汇入到项目中。
> 
> 再次感谢您对本项目的支持！

知道了，最近我抽空做一下，之前几个月比较忙，一直没时间去做...
P.S:事实上，空港线是包含在3号线的线路图里的...

**Comment by Sherwoodniki** [comment]
> > 请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了
> 
> 线路模版投稿可以参照这里：https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates

不是的，我问的是这个模板在那个网页上做。。。就是怎么个制作法。。

**Comment by thekingofcity** [comment]
> > > 请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了
> > 
> > 线路模版投稿可以参照这里：https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates
> 
> 不是的，我问的是这个模板在那个网页上做。。。就是怎么个制作法。。

您或许可以参考这个视频，及其ta之后的一些视频 https://www.bilibili.com/video/BV1cY4y1W7mg

**Comment by Sherwoodniki** [comment]
> > > > 请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了
> > > 
> > > 
> > > 线路模版投稿可以参照这里：https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates
> > 
> > 
> > 不是的，我问的是这个模板在那个网页上做。。。就是怎么个制作法。。
> 
> 您或许可以参考这个视频，及其ta之后的一些视频 https://www.bilibili.com/video/BV1cY4y1W7mg

啊不是，我说线路图模板，不是怎么制作线路图。。。这个线路图的模板在那里制作。。。

**Comment by 52PD** [comment]
> 啊不是，我说线路图模板，不是怎么制作线路图。。。这个线路图的模板在那里制作。。。

如果你问的是哪里可以制作线路图的话就是这里（其实这个GitHub就是负责储存所有这个制作器中的现有模版的）：https://railmapgen.github.io/rmg/

**Comment by 52PD** [comment]
然后就是关于本投稿的问题。

由于本issue中所提到的问题在解决前已经有其他用户投稿了完整的重庆地铁线路模版，考虑到我们在处理相同城市/都市圈铁路系统的投稿issue时会首选没有问题的投稿，所以很抱歉您的投稿我们不会考虑汇入到项目中了😂

**Comment by thekingofcity** [comment]
> > > > > 请问大佬这个怎么做的，我也是重庆的，打算把重庆的其他线路资源搞了
> > > > 
> > > > 
> > > > 线路模版投稿可以参照这里：https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates
> > > 
> > > 
> > > 不是的，我问的是这个模板在那个网页上做。。。就是怎么个制作法。。
> > 
> > 
> > 您或许可以参考这个视频，及其ta之后的一些视频 https://www.bilibili.com/video/BV1cY4y1W7mg
> 
> 啊不是，我说线路图模板，不是怎么制作线路图。。。这个线路图的模板在那里制作。。。

制作其他风格的线路图可以参考 railmapgen/rmg#208 的讨论。

**Comment by 52PD** [comment]
> 制作其他风格的线路图可以参考 [railmapgen/rmg#208](https://github.com/railmapgen/rmg/issues/208) 的讨论。

额。。。我大概理解了一下，他问的应该是哪里可以做线路图（从之前他发的一些issue来看他应该是不知道RMG本体的），而不是如何做香港/广州/上海以外风格的线路图😂
