### ISSUE TITLE
【多伦多地铁】关于上次我提交的多伦多地铁名称的问题

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg-templates#16]
![Screen Shot 2022-05-02 at 5 06 08 PM](https://user-images.githubusercontent.com/98044618/166327924-006bf2ce-f4ea-4761-8088-3e05a044b9f0.png)
如图，因为上次我提交线路名的时候疏忽把4号线（雪柏线）的编号写成1了😂，所以想问一下下个小更新能不能把我犯的这个小错纠正一下，谢谢🙏。

正确的中英法文名字应该是：
en: 'Line 4 Sheppard',
fr: 'Ligne 4 Sheppard',
'zh-Hans': '4 雪柏线',
'zh-Hant': '4 雪柏線',

**Comment by thekingofcity** [comment]
感谢您对项目的支持与贡献！已修复于上述commit。
