### ISSUE TITLE
补充南京地铁线路图 (suburb系列)

### ISSUE THREAD

**Issue by zhuyicheng-eason** [railmapgen/rmg-templates#19]
@wongchito 
[NJ Subways.zip](https://developer.lanzoug.com/file/?UzUCPA08BTQACVFpVmMCblJtV29eTwpCByBRBFB5WjkHcFJkCy9QdwJ6U39TbgV0US1XNFNlUD5SMFcOATRaP1NuAmMNaQVnAGVRNVY7AjVSOVd0XmcKewc9UW9QOlpoBzdSIwsmUHQCaVM3UzcFNlE5V31TPFBnUnpXYQFqWnRTagIwDTYFNQBuUWFWOwI0UjBXa144CjsHZFE1UG5aYgc+UmELYlA2Am1TYVNlBTFROlcxU2pQYFJlVzABb1pvU30CLw05BSEAcFFyVnECZlJ6VzteZQo1BzJRYVA/WmsHNFIxC2NQIgIgU2xTagVhUW1Xb1M9UGRSYFdgAWRaa1NmAmENZQVlAHhRKVYkAmVSZFclXjwKOAcmUSJQfFosBzpSNAtgUDECZVM8UzcFMFE/V2dTPVB0UiBXOAEtWmZTYgJlDWEFfwBuUTdWLAIyUjxXZV4vCjwHNw==)
运用 mtr 格式的模板制作的南京地铁线路图。
可能会有错误，如果有的话望指出，我会及时修改并再次提交。

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。不过项目中已有南京的线路模板，且也为mte风格，不知您的存档中有什么不一样之处呢？

**Comment by zhuyicheng-eason** [comment]
> 嗨，感谢您对项目的支持与贡献。不过我无法打开次文件链接，您可以直接拖动压缩包到对话框中并等待上传完毕即可。

[NJ Subways.zip](https://github.com/railmapgen/rmg-templates/files/8645001/NJ.Subways.zip)
抱歉😂，我没有提供有效的链接，不太了解github中的功能

**Comment by 52PD** [comment]
> 你好 @zhuyicheng-eason ，若使用港鐵風格，請為將月台編號留空。多謝。

关于线路风格这里我提个建议：考虑到南京地铁并没使用站台编号，加上南京地铁的屏蔽门通长为“线路名与终点站牌-当前站牌-线路图”的样式，相比于使用港铁风格来制作南京地铁线路图，我其实更建议采用上海地铁风格来制作。

这样的话既能解决上面@wongchito 所提到的问题（上海地铁风格在站台编号留空后会自动隐藏站台编号），同时也更符合南京地铁现用通长的风格一些。

**Comment by 52PD** [comment]
> 你好 @zhuyicheng-eason ，若使用港鐵風格，請為將月台編號留空。多謝。

而且说到将新增线路的站台编号留空这一问题，我觉得不如连着现有模版都一起改了（现有模版都有站台编号）🤔

**Comment by 52PD** [comment]
您好，经检查目前你提交的模版有以下问题：

- 除南京南站和禄口国际机场站外，大部分车站英文名与南京地铁官方所给英文名并不匹配。
- S8号线浦口公园站和柳州南路站并未开通，如果您想要使用港铁风格提交线路模版的话建议您将这两个站从模版中删去（如使用广州地铁风格提交的话建议在车站第二名称中标上“暂未开通”；如使用上海地铁风格提交的话建议在列车类别中将“普通车”反向勾选以达到隐藏车站的效果）。

请在对照以上内容进行修改后将修改的模版提交至本issue下。

感谢您对本项目的支持与贡献！

**Comment by 52PD** [comment]
Closed as no response over 1 month.
