### ISSUE TITLE
[New Templates] Great Tokyo Area JR Lines

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg-templates#21]
I finnished JR lines just now.
[東海道線.zip](https://github.com/railmapgen/rmg-templates/files/8651854/default.zip)
[横須賀・総武快速線.zip](https://github.com/railmapgen/rmg-templates/files/8651857/default.zip)
[湘南新宿ライン.zip](https://github.com/railmapgen/rmg-templates/files/8651860/default.zip)
[京滨東北·根岸缐.zip](https://github.com/railmapgen/rmg-templates/files/8651863/default.zip)
[相模缐.zip](https://github.com/railmapgen/rmg-templates/files/8651869/default.zip)
[横浜·根岸缐.zip](https://github.com/railmapgen/rmg-templates/files/8651870/default.zip)
[南武缐.zip](https://github.com/railmapgen/rmg-templates/files/8651874/default.zip)
[南武支缐.zip](https://github.com/railmapgen/rmg-templates/files/8651875/default.zip)
[鶴見線.zip](https://github.com/railmapgen/rmg-templates/files/8651877/default.zip)
[鶴見線大川支線.zip](https://github.com/railmapgen/rmg-templates/files/8651924/default.zip)
[鶴見線海芝浦支線.zip](https://github.com/railmapgen/rmg-templates/files/8651929/default.zip)
[山手線.zip](https://github.com/railmapgen/rmg-templates/files/8651934/default.zip)
[中央本線.zip](https://github.com/railmapgen/rmg-templates/files/8651937/default.zip)
[中央缐快速.zip](https://github.com/railmapgen/rmg-templates/files/8651939/default.zip)
[中央·総武緩行线.zip](https://github.com/railmapgen/rmg-templates/files/8651940/default.zip)
[青梅缐.zip](https://github.com/railmapgen/rmg-templates/files/8651947/default.zip)
[五日市缐.zip](https://github.com/railmapgen/rmg-templates/files/8651949/default.zip)
[八高北缐.zip](https://github.com/railmapgen/rmg-templates/files/8651960/default.zip)
[宇都宮線.zip](https://github.com/railmapgen/rmg-templates/files/8651963/default.zip)
[高崎缐.zip](https://github.com/railmapgen/rmg-templates/files/8651965/default.zip)
[埼京·川越缐.zip](https://github.com/railmapgen/rmg-templates/files/8651968/default.zip)
[川越·八高缐（八高南缐）.zip](https://github.com/railmapgen/rmg-templates/files/8651971/default.zip)
[常磐缐快速.zip](https://github.com/railmapgen/rmg-templates/files/8651972/default.zip)
[常磐緩行缐.zip](https://github.com/railmapgen/rmg-templates/files/8651974/default.zip)
[総武本缐.zip](https://github.com/railmapgen/rmg-templates/files/8651977/default.zip)
[内房缐.zip](https://github.com/railmapgen/rmg-templates/files/8651979/default.zip)
[外房缐.zip](https://github.com/railmapgen/rmg-templates/files/8651982/default.zip)
[成田缐.zip](https://github.com/railmapgen/rmg-templates/files/8651983/default.zip)
[東金缐.zip](https://github.com/railmapgen/rmg-templates/files/8651990/default.zip)
[京葉缐.zip](https://github.com/railmapgen/rmg-templates/files/8651995/default.zip)
[武蔵野線.zip](https://github.com/railmapgen/rmg-templates/files/8651997/default.zip)
[上越缐.zip](https://github.com/railmapgen/rmg-templates/files/8652003/default.zip)
[両毛缐.zip](https://github.com/railmapgen/rmg-templates/files/8652005/default.zip)
[水戸缐.zip](https://github.com/railmapgen/rmg-templates/files/8652006/default.zip)
[伊東線.zip](https://github.com/railmapgen/rmg-templates/files/8652009/default.zip)
[東京モノレール羽田空港線.zip](https://github.com/railmapgen/rmg-templates/files/8652012/default.zip)
[日光缐.zip](https://github.com/railmapgen/rmg-templates/files/8652014/default.zip)

That's all of the JR lines in Great Tokyo Area.
@thekingofcity Please add them into the rmg.

**Comment by Jasper-233** [comment]
大工程欸😄

**Comment by Jasper-233** [comment]
大工程欸😄

**Comment by thekingofcity** [comment]
Thanks for supporting and contributing to the RMG!

Could you please zip all the jsons in one file and include the line names in the step 5 of [How to add line templates](https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates).

**Comment by e233-1000** [comment]
> Thanks for supporting and contributing to the RMG!
> 
> Could you please zip all the jsons in one file and include the line names in the step 5 of [How to add line templates](https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates).

OK. I'll finnish it today.

**Comment by e233-1000** [comment]
Now there's the whole zip.

JR Lines:
[JR東日本.zip](https://github.com/railmapgen/rmg-templates/files/8665706/JR.zip)

**Comment by thekingofcity** [comment]
Hi, I checked your zip but can find line names in step 5. Where is it?

**Comment by Jasper-233** [comment]
> Hi, I checked your zip but can find line names in step 5. Where is it?
I'm his classmate. He is busy recently and will not be free until the summer vacation.

**Comment by Jasper-233** [comment]
I'm his classmate. He is busy recently and will not be free until the summer vacation.

**Comment by Jasper-233** [comment]
I'm his classmate. He is busy recently and will not be free until the summer vacation.

**Comment by thekingofcity** [comment]
> I'm his classmate. He is busy recently and will not be free until the summer vacation.

Hi, which country is he currently located in? I'm interested in a country that has a different summer vacation period 😁

**Comment by 52PD** [comment]
Closed as no response over 1 month.
