### ISSUE TITLE
北京地铁11号线的问题

### ISSUE THREAD

**Issue by Gzline4-24hc** [railmapgen/rmg-templates#216]
11号线在金安桥会显示模式口，应该调到北辛安，再把方向调到往新首钢
1号线也是，要调到其他站，我建议调到四惠东，因为这个站曾经是1号线和八通线的换乘站

**Comment by wongchito** [comment]
@52PD - 能否提供閣下的看法，由於閣下為主要作者。

**Comment by 52PD** [comment]
> 11号线在金安桥会显示模式口，应该调到北辛安，再把方向调到往新首钢

关于终点站改为金安桥站这个问题虽然可以通过把风格改为港铁然后自定义终点站来实现，但首先问题是风格会跟其他线路不协调，其次是隐藏模式口站的设定也会跟着失效（目前只有上海地铁风格能隐藏车站）。而在金安桥站的时候上一站/下一站不显示模式口站这个由于目前上海地铁风格缺陷也是无法实现的。

关于自定义终点站和无视隐藏车站这两个问题我觉得可以去RMG单独跟上海地铁风格开发者@thekingofcity 说一下。

> 1号线也是，要调到其他站，我建议调到四惠东，因为这个站曾经是1号线和八通线的换乘站

这个建议我的答案是直接退回。对于楼主来说可能你所在的城市的跨线线路只会标出该线路区间所属的终点站而不是跨线终点站，然而在北京地铁，无论是1号线/八通线还是4号线/大兴线这两组跨线线路上，官方线路图显示的均为整条线路的终点站，因此不存在1号线区间显示终点站为四惠东这种情况。（在1号线与八通线贯通之后，官方就已经把1号线的终点站由古城-四惠东改成了古城-环球度假区，八通线的四惠东-环球度假区以及4号线/大兴线也是同理）

**Comment by thekingofcity** [comment]
终点站无视隐藏车站的设定已在 railmapgen/rmg#217 中被讨论，由于上海地铁暂无此情况，实现此功能的优先级被无限制调低，当然我们仍然会在未来实现此功能，stay tuned :)
