### ISSUE TITLE
北京房山线的问题

### ISSUE THREAD

**Issue by Gzline4-24hc** [railmapgen/rmg-templates#217]
共线怎么这样啊
![A174BCF3-7342-4410-849B-69268A48BCC6](https://user-images.githubusercontent.com/128379352/226803153-c01e32c7-622a-4ee5-a7d4-edede4f52a3f.jpeg)
用我这个吧
[BJSBY 9:房山.zip](https://github.com/railmapgen/rmg/files/11036250/BJSBY.9.zip)

**Comment by wongchito** [comment]
Hi @Gzline4-24hc ,

請透過 https://railmapgen.github.io/rmg-templates/new 提供範本更新，並按指引將生成的內容貼上至本 Issue 中。多謝！

**Comment by 52PD** [comment]
您好，很抱歉由于距上次建议你亲自提交线路模版后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的建议，谢谢。
