### ISSUE TITLE
深圳地铁新模版

### ISSUE THREAD

**Issue by Gzline4-24hc** [railmapgen/rmg-templates#218]
这是14、16、和6支的模版
线路号就是站台编号
[14、16、6B.zip](https://github.com/railmapgen/rmg/files/11036254/14.16.6B.zip)

**Comment by wongchito** [comment]
Hi @Gzline4-24hc ,

請透過 https://railmapgen.github.io/rmg-templates/new 提供範本更新，並按指引將生成的內容貼上至本 Issue 中。多謝！

**Comment by s1s1s1s1s1s** [comment]
好奇6号线支线的编号是6B还是6Z

**Comment by wongchito** [comment]
Hi @s1s1s1s1s1s ,

深圳地鐵車站導向系統使用「Branch Line 6」作為6號線支線的英文翻譯。我們會儘量遵從該命名規則，將相關範本編碼設定為`sz6b`。

**Comment by wongchito** [comment]
Close as duplicated with #207
