### ISSUE TITLE
资源：广州地铁的新模板

### ISSUE THREAD

**Issue by 12zhiwuyua** [railmapgen/rmg-templates#222]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/rmg-templates/new and paste the palette data below_

(REPLACE ME/替代我) **Justification:** 10号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gzmtr" line="gz10" major="false"><summary>gzmtr/gz10</summary><details type="name">{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線","ko":"십호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":3100,"indoor":3000},"svg_height":400,"style":"gzmtr","y_pc":50,"padding":4,"branchSpacingPct":3,"direction":"l","platform_num":"2","theme":["guangzhou","gz10","#7D9CC0","#fff"],"line_name":["10号线","Line 10"],"current_stn_idx":"k834TC","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["9asGy3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9asGy3":{"name":["西塱","Xilang"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["xxVUoc"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz1","#F3D03E","#000","1号线","Line 1"],["guangzhou","gz22","#CD5228","#fff","22号线","Line 22"],["guangzhou","gfl","#C4D600","#000","广佛线","Line Guangfo"]]],"tick_direc":"l","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"xxVUoc":{"name":["广钢新城","Guanggang New Town"],"secondaryName":false,"num":"02","services":["local"],"parents":["9asGy3"],"children":["AhO1Wy"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["foshan","fs11","#035C67","#fff","佛山11号线","Foshan Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["JepLDV"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AhO1Wy":{"name":["东沙","Dongsha"],"secondaryName":false,"num":"03","services":["local"],"parents":["xxVUoc"],"children":["gXMM-4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gXMM-4":{"name":["大干围","Daganwei"],"secondaryName":false,"num":"04","services":["local"],"parents":["AhO1Wy"],"children":["LoIR_d"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LoIR_d":{"name":["石溪","Shixi"],"secondaryName":false,"num":"05","services":["local"],"parents":["gXMM-4"],"children":["-g100j"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[["guangzhou","gfl","#C4D600","#000","广佛线","Line Guangfo"]]],"tick_direc":"r","paid_area":true,"osi_names":[["石溪","Shixi"]]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-g100j":{"name":["东晓南","Dongxiaonan"],"secondaryName":false,"num":"06","services":["local"],"parents":["LoIR_d"],"children":["jO2cCu"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz2","#00629B","#fff","2号线","Line 2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jO2cCu":{"name":["五凤","Wufeng"],"secondaryName":false,"num":"07","services":["local"],"parents":["-g100j"],"children":["rnPgGg"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz11","#470A68","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rnPgGg":{"name":["中大南门","South Gate of\\Zhongda University"],"secondaryName":false,"num":"08","services":["local"],"parents":["jO2cCu"],"children":["ayOSFJ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[["guangzhou","gz8","#008C95","#fff","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[["中大","Zhongda"]]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ayOSFJ":{"name":["滨江东路","Binjiang Rd.（E）"],"secondaryName":false,"num":"09","services":["local"],"parents":["rnPgGg"],"children":["7bCK4h"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#b18cfe","#fff","28号线","Line 28"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7bCK4h":{"name":["东湖","Donghu"],"secondaryName":false,"num":"10","services":["local"],"parents":["ayOSFJ"],"children":["u86y8C"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz6","#80225F","#fff","6号线","Line 6"],["guangzhou","gz12","#59621D","#fff","12号线","Line 12"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"u86y8C":{"name":["五羊邨","Wuyangcun"],"secondaryName":false,"num":"11","services":["local"],"parents":["7bCK4h"],"children":["MNNcaf"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz5","#C5003E","#fff","5号线","Line 5"],["other","other","#f4a4c0","#fff","26号线","Line 26"]]],"tick_direc":"l","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"MNNcaf":{"name":["广州大道中","Guangzhou Ave. （M）"],"secondaryName":false,"num":"12","services":["local"],"parents":["u86y8C"],"children":["KjAktA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["other","other","#f4a4c0","#fff","26号线","Line 26"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KjAktA":{"name":["天河路","Tianhe Rd."],"secondaryName":false,"num":"13","services":["local"],"parents":["MNNcaf"],"children":["03LOJB"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[["guangzhou","gz3","#ECA154","#fff","3号线","Line 3"],["guangzhou","gz1","#F3D03E","#000","1号线","Line 1"],["guangzhou","gz13","#8E8C13","#fff","13号线","Line 13"]]],"tick_direc":"l","paid_area":true,"osi_names":[["体育西路","Tiyuxi Rd."]]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"03LOJB":{"name":["石牌桥","Shipaiqiao"],"secondaryName":false,"num":"14","services":["local"],"parents":["KjAktA"],"children":["AHUoON"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz20","#D60078","#fff","20号线","Line 20"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AHUoON":{"name":["岗顶","Gangding"],"secondaryName":false,"num":"15","services":["local"],"parents":["03LOJB"],"children":["OjMIOs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"OjMIOs":{"name":["华师","Huashi"],"secondaryName":false,"num":"16","services":["local"],"parents":["AHUoON"],"children":["dNr_Lw"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz11","#470A68","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dNr_Lw":{"name":["五山","Wushan"],"secondaryName":false,"num":"17","services":["local"],"parents":["OjMIOs"],"children":["k834TC"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"k834TC":{"name":["天河客运站","Tianhe Passenger Station"],"secondaryName":false,"num":"18","services":["local"],"parents":["dNr_Lw"],"children":["xiW3GF"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz6","#80225F","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xiW3GF":{"name":["长湴公园","Changban Park"],"secondaryName":false,"num":"19","services":["local"],"parents":["k834TC"],"children":["nAp8K3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz20","#D60078","#fff","20号线","Line 20"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nAp8K3":{"name":["岑村北","Cencun N."],"secondaryName":false,"num":"20","services":["local"],"parents":["xiW3GF"],"children":["aftvEU"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"aftvEU":{"name":["环场北路","Huangchang Rd.（N）"],"secondaryName":false,"num":"21","services":["local"],"parents":["nAp8K3"],"children":["dAC5Gk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dAC5Gk":{"name":["凌塘","Lingtang"],"secondaryName":false,"num":"22","services":["local"],"parents":["aftvEU"],"children":["Cz8Fq2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Cz8Fq2":{"name":["软件路","Ruanjian Rd."],"secondaryName":["大观湿地","Grand View Wetland"],"num":"23","services":["local"],"parents":["dAC5Gk"],"children":["pTuwHJ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pTuwHJ":{"name":["高普路","Gaopu Rd."],"secondaryName":false,"num":"24","services":["local"],"parents":["Cz8Fq2"],"children":["JepLDV"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JepLDV":{"name":["高塘石","Gaotangshi"],"secondaryName":false,"num":"25","services":["local"],"parents":["pTuwHJ"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz6","#80225F","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"10","psd_num":"13","info_panel_type":"gz1421","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":80,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @12zhiwuyua ,

由於10號線尚在建設階段，車站名稱尚未公示，因此我們暫不會接受該範本提交。多謝閣下的貢獻。
