### ISSUE TITLE
Resources: New templates of Guangzhou Metro

### ISSUE THREAD

**Issue by Zongzi07** [railmapgen/rmg-templates#239]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the palette data below_

**Justification:** 新·18号线快慢车停靠站台

- Major update of Line 18/18호선/18号线/18號線: None

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gzmtr" line="gz18" major="true"><summary>gzmtr/gz18(M)</summary><details type="name">{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線","ko":"18호선"}</details><details type="param">{"style":"gzmtr","svg_height":300,"padding":8.750201061605276,"y_pc":40,"theme":["guangzhou","gz18","#0047BA","#fff"],"direction":"r","current_stn_idx":"qbbb","platform_num":"3","stn_list":{"linestart":{"parents":[],"children":["qbbb"],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"09","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["lyqw"],"children":["iwf6"],"name":["磨碟沙","Modiesha"],"branch":{"left":[],"right":[]},"num":"07","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz8","#008C95","#fff","8号线","Line 8"]]]},"services":["local","express"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["lineend"],"parents":["l1mz"],"name":["冼村","Xiancun"],"branch":{"left":[],"right":[]},"num":"08","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local","express"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"qbbb":{"parents":["linestart"],"children":["tgp4"],"branch":{"left":[],"right":[]},"name":["万顷沙","Wanqingsha"],"num":"01","services":["local","express"],"facility":"","transfer":{"info":[[]],"osi_names":[],"paid_area":true,"tick_direc":"r"},"secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"tgp4":{"parents":["qbbb"],"children":["ecsx"],"branch":{"left":[],"right":[]},"name":["横沥","Hengli"],"num":"02","services":["local","express"],"facility":"","transfer":{"info":[[]],"osi_names":[],"paid_area":true,"tick_direc":"r"},"secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"su3g":{"parents":["ecsx"],"children":["9v64"],"branch":{"left":[],"right":[]},"name":["南村万博","Nancun Wanbo"],"num":"04","services":["local"],"facility":"","transfer":{"info":[[["guangzhou","gz7","#97D700","#000","7号线","Line 7"]]],"osi_names":[],"paid_area":true,"tick_direc":"r"},"secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"9v64":{"parents":["su3g"],"children":["lyqw"],"branch":{"left":[],"right":[]},"name":["沙溪","Shaxi"],"num":"05","services":["local"],"facility":"","transfer":{"info":[[]],"osi_names":[],"paid_area":true,"tick_direc":"r"},"secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lyqw":{"parents":["9v64"],"children":["l1mz"],"branch":{"left":[],"right":[]},"name":["龙潭","Longtan"],"num":"06","services":["local"],"facility":"","transfer":{"info":[[]],"osi_names":[],"paid_area":true,"tick_direc":"r"},"secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"ecsx":{"name":["番禺广场","Panyu Square"],"secondaryName":false,"num":"03","services":["local","express"],"parents":["tgp4"],"children":["su3g"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["guangzhou","gz3","#ECA154","#000","3号线","Line 3"],["guangzhou","gz22","#CD5228","#fff","22号线","Line 22"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355}},"line_name":["18号线","Line 18"],"psd_num":"3","line_num":"18","info_panel_type":"gz1421","direction_gz_x":57.35,"direction_gz_y":80,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1000,"runin":1000,"railmap":1500,"indoor":1000},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":30}</details></details>

**Comment by wongchito** [comment]
重設18號線作者 - 因我們不認為該變更屬「重大更新」
