### ISSUE TITLE
Resources: New templates of Shanghai Metro

### ISSUE THREAD

**Issue by Jwanpandenwaa** [railmapgen/rmg-templates#241]
[rmg.浦江线.Pujiang_Line.zip](https://github.com/railmapgen/rmg-templates/files/11185679/rmg.Pujiang_Line.zip)
[rmg.浦江线.Pujiang_Line (1).zip](https://github.com/railmapgen/rmg-templates/files/11185681/rmg.Pujiang_Line.1.zip)
[rmg.浦江线.Pujiang_Line (2).zip](https://github.com/railmapgen/rmg-templates/files/11185684/rmg.Pujiang_Line.2.zip)
[rmg.浦江线.Pujiang_Line (3).zip](https://github.com/railmapgen/rmg-templates/files/11185686/rmg.Pujiang_Line.3.zip)
 RMG team! I would like to contribute the templates below.However, since the email does not support json. format, only pictures can be sent.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the palette data below_

(REPLACE ME/替代我)

**Comment by 52PD** [comment]
您好，我们已经不再接受通过上传打包格式的模版投稿，因此请透过 https://railmapgen.github.io/rmg-templates/new 提供范本更新，并按指引将生成的内容贴上至一个新的Issue中并连接上此Issue的编号。多谢！

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路模版未采用新版上传工具进行提交以及浦江线模版重复后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
