### ISSUE TITLE
Resources: New templates of Suzhou Wujiang ART System

### ISSUE THREAD

**Issue by beiguangrailtransit** [railmapgen/rmg-templates#251]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)

**Comment by beiguangrailtransit** [comment]
**Justification:** 缺失线路
来源https://www.china-emu.cn/UrbanRail/Line/?Detail-1193-show.html



**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szART" line="00config"><summary>New company: Suzhou Wujiang ART System</summary><details type="name">{"en":"Suzhou Wujiang ART System","zh-Hans":"苏州吴江捷运系统","zh-Hant":"蘇州吳江捷運系統","ko":"쑤저우 우장 ART"}</details></details>

<details repo="rmg-templates" company="szART" line="szT1" major="false"><summary>szART/szT1</summary><details type="name">{"en":" Suzhou Wujiang ART System Line T1","zh-Hans":" 苏州吴江捷运系统T1线","zh-Hant":" 蘇州吳江捷運系統T1線","ko":" 쑤저우 우장 ART 시스템 라인 T1"}</details><details type="param">{"svgWidth":{"destination":1280,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["other","other","#0062a8","#fff"],"line_name":["T1示范线","T1 demonstration line"],"current_stn_idx":"bNbqPb","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["bNbqPb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bNbqPb":{"name":["同里","Tongli"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["Rn_DBS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[],[["other","other","#036eb7","#fff","苏州轨道交通4号线","Suzhou Rail Transit Line 4"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Rn_DBS":{"name":["同里古镇","Tongli Ancient Town"],"secondaryName":false,"num":"02","services":["local"],"parents":["bNbqPb"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Rn_DBS"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"T1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好，很抱歉由于您将投稿模版拆开了，因此导致我们无法将其进行汇入。

请您将投稿模版放在同一楼内后重新提交一遍，谢谢。
