### ISSUE TITLE
Resources: New templates of Shenzhen Metro

### ISSUE THREAD

**Issue by zyx19851218** [railmapgen/rmg-templates#255]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 亲爱的RMG RMP开发者：
  您好！
  本人根据深圳地铁运营线网图，根据情况在深圳地铁内添加深圳地铁12号线模板。RMG模板内其他模板未更改。
  另外，希望我制作的深圳地铁12号线模板能够添加至RMG模板内，为大众开放此模板，谢谢！

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmetro" line="sz12" major="false"><summary>szmetro/sz12</summary><details type="name">{"en":"Shenzhen Metro Line 12","zh-Hans":"深圳地铁12号线","zh-Hant":"深圳捷運12號線","ko":"선전지하철 12호선"}</details><details type="param">{"svgWidth":{"destination":1600,"runin":1200,"railmap":3000,"indoor":1200},"svg_height":360,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"12","theme":["shenzhen","sz12","#A192B2","#fff"],"line_name":["12号线","Line 12"],"current_stn_idx":"sKcM5r","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["sKcM5r"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"sKcM5r":{"name":["左炮台东","Zuopaotai East"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["FoppYE"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FoppYE":{"name":["太子湾","Taiziwan"],"secondaryName":false,"num":"02","services":["local"],"parents":["sKcM5r"],"children":["BLk0f2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Dkz-gd"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"BLk0f2":{"name":["海上世界","Ocean Would"],"secondaryName":false,"num":"00","services":["local"],"parents":["FoppYE"],"children":["YDrg0C"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz2","#B94700","#fff","2号线\\Line 2\\8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"YDrg0C":{"name":["花果山","Huaguoshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["BLk0f2"],"children":["HIoaGB"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HIoaGB":{"name":["四海","Sihai"],"secondaryName":false,"num":"00","services":["local"],"parents":["YDrg0C"],"children":["LZPjdf"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LZPjdf":{"name":["南油","Nanyou"],"secondaryName":false,"num":"00","services":["local"],"parents":["HIoaGB"],"children":["QoMCq4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz9","#7B6469","#fff","9号线","Line 9"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QoMCq4":{"name":["南光","Nanguang"],"secondaryName":false,"num":"00","services":["local"],"parents":["LZPjdf"],"children":["VNFp9b"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VNFp9b":{"name":["南山","Nanshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["QoMCq4"],"children":["Il4Cx8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz11","#672146","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Il4Cx8":{"name":["桃园","Taoyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["VNFp9b"],"children":["bd_vLw"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz1","#00B140","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bd_vLw":{"name":["南头古城","Nantougucheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["Il4Cx8"],"children":["4z-ovM"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4z-ovM":{"name":["中山公园","Zhongshan Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["bd_vLw"],"children":["WmbyE3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WmbyE3":{"name":["同乐南","Tong'le South"],"secondaryName":false,"num":"00","services":["local"],"parents":["4z-ovM"],"children":["z7Qls2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"z7Qls2":{"name":["新安公园","Xin'an Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["WmbyE3"],"children":["ZLtIIG"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZLtIIG":{"name":["灵芝","Lingzhi"],"secondaryName":false,"num":"00","services":["local"],"parents":["z7Qls2"],"children":["1C2KwS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz5","#A05EB5","#fff","5号线","Line 5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1C2KwS":{"name":["上川","Shangchuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZLtIIG"],"children":["GZ3TLO"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GZ3TLO":{"name":["流塘","Liutang"],"secondaryName":false,"num":"00","services":["local"],"parents":["1C2KwS"],"children":["EqJnha"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EqJnha":{"name":["宝安客运站","Bao'an Couch Terminal"],"secondaryName":false,"num":"00","services":["local"],"parents":["GZ3TLO"],"children":["Pfz3-f"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Pfz3-f":{"name":["宝田一路","Baotian No.1 Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EqJnha"],"children":["h3yF4h"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"h3yF4h":{"name":["平峦山","Pingluanshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["Pfz3-f"],"children":["SOhHwb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SOhHwb":{"name":["西乡桃源","Xixiangtaoyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["h3yF4h"],"children":["wi1FPS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wi1FPS":{"name":["钟屋南","Zhongwu South"],"secondaryName":false,"num":"00","services":["local"],"parents":["SOhHwb"],"children":["8BHBFT"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8BHBFT":{"name":["黄田","Huangtian"],"secondaryName":false,"num":"00","services":["local"],"parents":["wi1FPS"],"children":["c_3l2O"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"c_3l2O":{"name":["兴围","Xingwei"],"secondaryName":false,"num":"00","services":["local"],"parents":["8BHBFT"],"children":["cMIv4I"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cMIv4I":{"name":["机场东","Airport East"],"secondaryName":false,"num":"00","services":["local"],"parents":["c_3l2O"],"children":["dSV-PG"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz1","#00B140","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dSV-PG":{"name":["福围","Fuwei"],"secondaryName":false,"num":"00","services":["local"],"parents":["cMIv4I"],"children":["uZeRpG"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"uZeRpG":{"name":["怀德","Huaide"],"secondaryName":false,"num":"00","services":["local"],"parents":["dSV-PG"],"children":["isA6nW"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"isA6nW":{"name":["福永","Fuyong"],"secondaryName":false,"num":"00","services":["local"],"parents":["uZeRpG"],"children":["3HKQBS"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz11","#672146","#fff","11号线","Line 11"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3HKQBS":{"name":["桥头西","Qiaotou West"],"secondaryName":false,"num":"00","services":["local"],"parents":["isA6nW"],"children":["VeRr02"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VeRr02":{"name":["福海西","Fuhai West"],"secondaryName":false,"num":"00","services":["local"],"parents":["3HKQBS"],"children":["cn7Pcb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cn7Pcb":{"name":["国展","Shenzhen World"],"secondaryName":false,"num":"00","services":["local"],"parents":["VeRr02"],"children":["yLxVg4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz20","#88DBDF","#fff","20号线","Line 20"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yLxVg4":{"name":["国展北","Shenzhen World North"],"secondaryName":false,"num":"00","services":["local"],"parents":["cn7Pcb"],"children":["iHmMR2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz20","#88DBDF","#fff","20号线","Line 20"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iHmMR2":{"name":["海上田园南","haishangtianyuan South"],"secondaryName":false,"num":"00","services":["local"],"parents":["yLxVg4"],"children":["Dkz-gd"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Dkz-gd":{"name":["海上田园东","Haishangtianyuan East"],"secondaryName":false,"num":"00","services":["local"],"parents":["iHmMR2"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by s1s1s1s1s1s** [comment]
开发者不知道在忙什么，我的issue发了一个月没人理

**Comment by 52PD** [comment]
> 开发者不知道在忙什么，我的issue发了一个月没人理

抱歉，我最近一直在忙期末考试😂。如果不出意外的话下周就能回来参与审核了

**Comment by wongchito** [comment]
Hi @zyx19851218 ,

由於閣下所提交之範本與 #207 重複，我們現關閉該Issue。如閣下認為所提交之範本優於現有的，請重新開啟該Issue並於正文移除不相關的範本。多謝！
