### ISSUE TITLE
Resources: New templates of Taichung MRT

### ISSUE THREAD

**Issue by Benson20110806** [railmapgen/rmg-templates#266]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 沒有台中捷運

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tcmrt" line="00config"><summary>New company: Taichung MRT</summary><details type="name">{"en":"Taichung MRT","zh-Hans":"台中捷運","zh-Hant":"台中捷運","ko":"타이중 MRT"}</details></details>

<details repo="rmg-templates" company="tcmrt" line="1" major="false"><summary>tcmrt/1</summary><details type="name">{"en":"Green Line","zh-Hans":"台中捷運","zh-Hant":"綠線","ko":"녹색 선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1500,"indoor":1200},"svg_height":450,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["taichung","tc1","#8ec31c","#fff"],"line_name":["綠線","Green Line"],"current_stn_idx":"ykv21r","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["zGDDEK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zGDDEK":{"name":["北屯總站","Beitun Main Station"],"secondaryName":false,"num":"03a","services":["local"],"parents":["linestart"],"children":["PYCk1g"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PYCk1g":{"name":["舊社","Jiushe"],"secondaryName":false,"num":"03","services":["local"],"parents":["zGDDEK"],"children":["ykv21r"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Be1CWB"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Be1CWB":{"name":["高鐵台中站","HSR Taichung Station"],"secondaryName":false,"num":"19","services":["local"],"parents":["AF_9aA"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AF_9aA":{"name":["烏日","Wuri"],"secondaryName":false,"num":"18","services":["local"],"parents":["QcuI7R"],"children":["Be1CWB"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QcuI7R":{"name":["九德","Jiude"],"secondaryName":false,"num":"17","services":["local"],"parents":["4eU2sp"],"children":["AF_9aA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4eU2sp":{"name":["九張犁","Jiuzhangli"],"secondaryName":false,"num":"16","services":["local"],"parents":["yArz7h"],"children":["QcuI7R"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yArz7h":{"name":["大慶","Daqing"],"secondaryName":false,"num":"15","services":["local"],"parents":["DCgWGp"],"children":["4eU2sp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DCgWGp":{"name":["豐樂公園","Feng-le Park"],"secondaryName":false,"num":"14","services":["local"],"parents":["Qmlck0"],"children":["yArz7h"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Qmlck0":{"name":["南屯","Nantun"],"secondaryName":false,"num":"13","services":["local"],"parents":["025Yqr"],"children":["DCgWGp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"025Yqr":{"name":["文心森林公園","Wenxin Forest Park"],"secondaryName":false,"num":"12","services":["local"],"parents":["eZiLid"],"children":["Qmlck0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eZiLid":{"name":["水安宮","Shui-an Temple"],"secondaryName":false,"num":"11","services":["local"],"parents":["9UWs_O"],"children":["025Yqr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9UWs_O":{"name":["市政府","Taichung City Hall"],"secondaryName":false,"num":"10","services":["local"],"parents":["Z_TXLj"],"children":["eZiLid"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Z_TXLj":{"name":["文心櫻花","Wenxin Yinghua"],"secondaryName":false,"num":"09","services":["local"],"parents":["n1K7d3"],"children":["9UWs_O"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"n1K7d3":{"name":["文華高中","Wenhua Senior High School"],"secondaryName":false,"num":"08","services":["local"],"parents":["uG9rxq"],"children":["Z_TXLj"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"uG9rxq":{"name":["文心中清","Wenxin Zhongqing"],"secondaryName":false,"num":"07","services":["local"],"parents":["WBxOjR"],"children":["n1K7d3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WBxOjR":{"name":["文心崇德","Wenxin Chongde"],"secondaryName":false,"num":"06","services":["local"],"parents":["lCIQTW"],"children":["uG9rxq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lCIQTW":{"name":["四維國小","Unnamed lCIQTW"],"secondaryName":false,"num":"05","services":["local"],"parents":["ykv21r"],"children":["WBxOjR"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ykv21r":{"name":["松竹","Songzhu"],"secondaryName":false,"num":"04","services":["local"],"parents":["PYCk1g"],"children":["lCIQTW"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
經檢查，您所提交的範本包含但不限於以下問題：

- 四維國小站英文名稱錯誤（此外考慮到您所使用的線路圖風格為廣州地鐵風格，該站第二名稱「二分埔」缺失）
- 和四維國小站一樣，文心中清站的第二名稱「天津商圈」，南屯站的第二名稱「文心五權西」和大慶站的第二名稱「中山醫大」缺失。

請修正後再次提交。多謝！

（請您在收到本條消息後盡快及時回復，超過一個月未回復的問題稿件我們將會直接拒絕匯入）

**Comment by Benson20110806** [comment]
**Justification:** 台中捷運綠線-修改版



**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="Taichung" line="00config"><summary>New company: Taichung MRT</summary><details type="name">{"en":"Taichung MRT","zh-Hans":"台中捷運","zh-Hant":"台中捷運","ko":"타이중 MRT"}</details></details>

<details repo="rmg-templates" company="Taichung" line="綠線" major="false"><summary>Taichung/綠線</summary><details type="name">{"en":"Green Line","zh-Hans":"绿线","zh-Hant":"綠線","ko":"녹색 선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1500,"indoor":1200},"svg_height":450,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["taichung","tc1","#8ec31c","#fff"],"line_name":["綠線","Green Line"],"current_stn_idx":"ykv21r","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["zGDDEK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zGDDEK":{"name":["北屯總站","Beitun Main Station"],"secondaryName":false,"num":"03a","services":["local"],"parents":["linestart"],"children":["PYCk1g"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PYCk1g":{"name":["舊社","Jiushe"],"secondaryName":false,"num":"03","services":["local"],"parents":["zGDDEK"],"children":["ykv21r"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Be1CWB"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Be1CWB":{"name":["高鐵台中站","HSR Taichung Station"],"secondaryName":false,"num":"19","services":["local"],"parents":["AF_9aA"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AF_9aA":{"name":["烏日","Wuri"],"secondaryName":false,"num":"18","services":["local"],"parents":["QcuI7R"],"children":["Be1CWB"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QcuI7R":{"name":["九德","Jiude"],"secondaryName":false,"num":"17","services":["local"],"parents":["4eU2sp"],"children":["AF_9aA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4eU2sp":{"name":["九張犁","Jiuzhangli"],"secondaryName":false,"num":"16","services":["local"],"parents":["yArz7h"],"children":["QcuI7R"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yArz7h":{"name":["大慶","Daqing"],"secondaryName":false,"num":"15","services":["local"],"parents":["DCgWGp"],"children":["4eU2sp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DCgWGp":{"name":["豐樂公園","Feng-le Park"],"secondaryName":false,"num":"14","services":["local"],"parents":["Qmlck0"],"children":["yArz7h"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Qmlck0":{"name":["南屯","Nantun"],"secondaryName":false,"num":"13","services":["local"],"parents":["025Yqr"],"children":["DCgWGp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"025Yqr":{"name":["文心森林公園","Wenxin Forest Park"],"secondaryName":false,"num":"12","services":["local"],"parents":["eZiLid"],"children":["Qmlck0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eZiLid":{"name":["水安宮","Shui-an Temple"],"secondaryName":false,"num":"11","services":["local"],"parents":["9UWs_O"],"children":["025Yqr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9UWs_O":{"name":["市政府","Taichung City Hall"],"secondaryName":false,"num":"10","services":["local"],"parents":["Z_TXLj"],"children":["eZiLid"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Z_TXLj":{"name":["文心櫻花","Wenxin Yinghua"],"secondaryName":false,"num":"09","services":["local"],"parents":["n1K7d3"],"children":["9UWs_O"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"n1K7d3":{"name":["文華高中","Wenhua Senior High School"],"secondaryName":false,"num":"08","services":["local"],"parents":["uG9rxq"],"children":["Z_TXLj"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"uG9rxq":{"name":["文心中清","Wenxin Zhongqing"],"secondaryName":false,"num":"07","services":["local"],"parents":["WBxOjR"],"children":["n1K7d3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WBxOjR":{"name":["文心崇德","Wenxin Chongde"],"secondaryName":false,"num":"06","services":["local"],"parents":["lCIQTW"],"children":["uG9rxq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lCIQTW":{"name":["四維國小","Sihwei Elementary Schoool"],"secondaryName":false,"num":"05","services":["local"],"parents":["ykv21r"],"children":["WBxOjR"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ykv21r":{"name":["松竹","Songzhu"],"secondaryName":false,"num":"04","services":["local"],"parents":["PYCk1g"],"children":["lCIQTW"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
Closed as the new updated version is issued in #270 .
