### ISSUE TITLE
Resources: New templates of Changzhou Metro

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-templates#290]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** https://en.m.wikipedia.org/wiki/Changzhou_Metro
线路图参考英文维基百科中的图

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="czmetro" line="00config"><summary>New company: Changzhou Metro</summary><details type="name">{"en":"Changzhou Metro","zh-Hans":"常州轨道交通","zh-Hant":"常州軌道交通","ko":"창저우 지하철"}</details></details>

<details repo="rmg-templates" company="czmetro" line="cz1" major="false"><summary>czmetro/cz1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":2000},"svg_height":350,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["changzhou","cz1","#cd5c5c","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"-zguF6","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["-zguF6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"-zguF6":{"name":["森林公园","Forest Park"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["G93nJx"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"nqYpH8":{"name":["南夏墅","Nanxiashu"],"secondaryName":false,"num":"02","services":["local"],"parents":["uElyvm"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["nqYpH8"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"G93nJx":{"name":["新龙","Xinlong"],"secondaryName":false,"num":"00","services":["local"],"parents":["-zguF6"],"children":["-wA_fI"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"-wA_fI":{"name":["旅游学校","Tourism and Commerce Institute"],"secondaryName":false,"num":"00","services":["local"],"parents":["G93nJx"],"children":["6hzfz1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"6hzfz1":{"name":["新桥","Xinqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["-wA_fI"],"children":["XN_wQ8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"XN_wQ8":{"name":["常州北站","Changzhou North\\ Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["6hzfz1"],"children":["FNhVJA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"FNhVJA":{"name":["北郊中学","Beijiao High School"],"secondaryName":false,"num":"00","services":["local"],"parents":["XN_wQ8"],"children":["Im0hI9"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"Im0hI9":{"name":["外国语学校","Foreign Language School"],"secondaryName":false,"num":"00","services":["local"],"parents":["FNhVJA"],"children":["SlsEMV"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"SlsEMV":{"name":["环球港","Global Harbor"],"secondaryName":false,"num":"00","services":["local"],"parents":["Im0hI9"],"children":["7hjL2N"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"7hjL2N":{"name":["新区公园","Xinqu Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["SlsEMV"],"children":["C5ry2K"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"C5ry2K":{"name":["河海","Hehai"],"secondaryName":false,"num":"00","services":["local"],"parents":["7hjL2N"],"children":["3LdTeQ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"3LdTeQ":{"name":["奥体中心","Olympic Sports Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["C5ry2K"],"children":["dar8V1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"dar8V1":{"name":["市民广场","Citizens' Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["3LdTeQ"],"children":["zIy6eH"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"zIy6eH":{"name":["翠竹","Cuizhu"],"secondaryName":false,"num":"00","services":["local"],"parents":["dar8V1"],"children":["J1ihI8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"J1ihI8":{"name":["常州火车站","Changzhou Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["zIy6eH"],"children":["LUNUqB"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"LUNUqB":{"name":["博爱路","Boai Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["J1ihI8"],"children":["QaXvYQ"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"QaXvYQ":{"name":["文化宫","Cultural Palace"],"secondaryName":false,"num":"00","services":["local"],"parents":["LUNUqB"],"children":["cowFrn"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["changzhou","cz2","#529fc9","#fff","2号线","Line 2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"cowFrn":{"name":["通济桥","Tongjiqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["QaXvYQ"],"children":["69_9lt"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"69_9lt":{"name":["清凉寺","Qingliang Temple"],"secondaryName":false,"num":"00","services":["local"],"parents":["cowFrn"],"children":["B6_Gh3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"B6_Gh3":{"name":["茶山","Chashan"],"secondaryName":false,"num":"00","services":["local"],"parents":["69_9lt"],"children":["o8mAHo"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"o8mAHo":{"name":["聚湖路","Juhu Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["B6_Gh3"],"children":["8_zCXi"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"8_zCXi":{"name":["湖塘","Hutang"],"secondaryName":false,"num":"00","services":["local"],"parents":["o8mAHo"],"children":["cutMWo"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"cutMWo":{"name":["新天地公园","Xintiandi Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["8_zCXi"],"children":["1GZamU"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"1GZamU":{"name":["长虹路","Changhong Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["cutMWo"],"children":["XKUgNR"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"XKUgNR":{"name":["延政大道","Yanzheng Dadao"],"secondaryName":false,"num":"00","services":["local"],"parents":["1GZamU"],"children":["qNwSg0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"qNwSg0":{"name":["科教城北","Kejiaocheng Bei"],"secondaryName":false,"num":"00","services":["local"],"parents":["XKUgNR"],"children":["U-hPvD"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"U-hPvD":{"name":["科教城南","Kejiaocheng Nan"],"secondaryName":false,"num":"00","services":["local"],"parents":["qNwSg0"],"children":["DTESXU"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"DTESXU":{"name":["武进沿江城际","Wujin Yanjiang Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["U-hPvD"],"children":["uElyvm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"uElyvm":{"name":["阳湖路","Yanghu Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["DTESXU"],"children":["nqYpH8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="czmetro" line="cz2" major="false"><summary>czmetro/cz2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線","ko":"2호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":350,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["changzhou","cz2","#529fc9","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"PE_hrE","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["PE_hrE"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"PE_hrE":{"name":["青枫公园","Qingfeng Park"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["dshPe1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"kOzc9s":{"name":["五一路","Wuyi Lu"],"secondaryName":false,"num":"02","services":["local"],"parents":["E3fgUD"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["kOzc9s"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"dshPe1":{"name":["海棠路","Haitang Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["PE_hrE"],"children":["brRZr6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"brRZr6":{"name":["五星","Wuxing"],"secondaryName":false,"num":"00","services":["local"],"parents":["dshPe1"],"children":["oPJxTk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"oPJxTk":{"name":["勤业","Qinye"],"secondaryName":false,"num":"00","services":["local"],"parents":["brRZr6"],"children":["K2pCuY"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"K2pCuY":{"name":["怀德","Huaide"],"secondaryName":false,"num":"00","services":["local"],"parents":["oPJxTk"],"children":["wGExYO"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"wGExYO":{"name":["南大街","Nandajie"],"secondaryName":false,"num":"00","services":["local"],"parents":["K2pCuY"],"children":["jNfxgo"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"jNfxgo":{"name":["文化宫","Cultural Palace"],"secondaryName":false,"num":"00","services":["local"],"parents":["wGExYO"],"children":["H2-Yxu"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["changzhou","cz1","#cd5c5c","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"H2-Yxu":{"name":["红梅公园","Hongmei Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["jNfxgo"],"children":["Nm1cbp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"Nm1cbp":{"name":["五角场","Wujiaochang"],"secondaryName":false,"num":"00","services":["local"],"parents":["H2-Yxu"],"children":["BDPZ2V"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"BDPZ2V":{"name":["三角场","Sanjiaochang"],"secondaryName":false,"num":"00","services":["local"],"parents":["Nm1cbp"],"children":["lOK5jT"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lOK5jT":{"name":["紫云","Ziyun"],"secondaryName":false,"num":"00","services":["local"],"parents":["BDPZ2V"],"children":["6CoCLt"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"6CoCLt":{"name":["青洋路","Qingyang Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["lOK5jT"],"children":["2Pl7q5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"2Pl7q5":{"name":["丁堰","Dingyan"],"secondaryName":false,"num":"00","services":["local"],"parents":["6CoCLt"],"children":["E3fgUD"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"E3fgUD":{"name":["潞城","Lucheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["2Pl7q5"],"children":["kOzc9s"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好。经检查，您所提交的模版包含但不限于以下问题：

- 1号线博爱路站英文名中的"o"和"a"之间应该有分隔符号。

考虑到本问题仅为细节问题，我们已经对其进行修正，因此您无需做出额外处理。希望下次投稿时能注意这些细节，谢谢。

再次感谢您对本项目作出的贡献！
