### ISSUE TITLE
部分线路模版

### ISSUE THREAD

**Issue by xiany114514** [railmapgen/rmg-templates#3]
[rmg.param.2021-12-18T13_36_15.906Z.zip](https://github.com/wongchito/RailMapGenerator/files/7740250/rmg.param.2021-12-18T13_36_15.906Z.zip)-深圳20
[吉隆坡7.zip](https://github.com/wongchito/RailMapGenerator/files/7740251/7.zip)-吉隆坡机场支线
[吉隆坡6.zip](https://github.com/wongchito/RailMapGenerator/files/7740252/6.zip)-吉隆坡机场快线

**Comment by 52PD** [comment]
Closed as no response over 1 month.
