### ISSUE TITLE
Resources: New templates of Shanghai Metro

### ISSUE THREAD

**Issue by Yexiaowei11** [railmapgen/rmg-templates#300]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** 加入

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="shmetro" line="浦江线" major="false"><summary>shmetro/浦江线</summary><details type="name">{"en":"pjl","zh-Hans":"浦江线","zh-Hant":"浦江綫","ko":"푸장선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["other","other","#c0c0c0","#fff"],"line_name":["浦江线","Pujiang Line"],"current_stn_idx":"3J3cKt","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["FnqpKU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FnqpKU":{"name":["沈杜公路","Shendu Highway"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["3J3cKt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[["other","other","#4a86e8","#fff","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3J3cKt":{"name":["三鲁公路","三鲁公路"],"secondaryName":false,"num":"02","services":["local"],"parents":["FnqpKU"],"children":["hNpzac"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["cWAkQU"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hNpzac":{"name":["闵瑞路","Min Rui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["3J3cKt"],"children":["Kki6jW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Kki6jW":{"name":["浦航路","Puhang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["hNpzac"],"children":["EDJaZn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EDJaZn":{"name":["东城一路","Dongchengyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Kki6jW"],"children":["cWAkQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cWAkQU":{"name":["汇臻路","Huizhen Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EDJaZn"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。但需要您将浦江线的颜色选为palette中的颜色才可以体验到rmg针对浦江线的特别适配，请更新完模板后重开issue，谢谢 :)

**Comment by Yexiaowei11** [comment]
我已经完成修改
https://github.com/railmapgen/rmg-templates/issues/305
