### ISSUE TITLE
Resources: New templates of Shanghai Metro

### ISSUE THREAD

**Issue by Yexiaowei11** [railmapgen/rmg-templates#305]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

我已完成修改

**Justification:** 修改

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="shmetro" line="pjl" major="false"><summary>shmetro/pjl</summary><details type="name">{"en":"Pujiang Line","zh-Hans":"浦江线","zh-Hant":"浦江線","ko":"푸장선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":15,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["shanghai","pjl","#B5B5B6","#fff"],"line_name":["浦江线","Pujiang Line"],"current_stn_idx":"3J3cKt","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["cWAkQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FnqpKU":{"name":["沈杜公路","Shendu Highway"],"secondaryName":false,"num":"01","services":["local"],"parents":["3J3cKt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#4a86e8","#fff"],"name":["8号线","Line 8"]}]}],"info":[[["shanghai","sh8","#0094D8","#fff","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3J3cKt":{"name":["三鲁公路","三鲁公路"],"secondaryName":false,"num":"02","services":["local"],"parents":["hNpzac"],"children":["FnqpKU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["FnqpKU"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hNpzac":{"name":["闵瑞路","Min Rui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Kki6jW"],"children":["3J3cKt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Kki6jW":{"name":["浦航路","Puhang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EDJaZn"],"children":["hNpzac"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EDJaZn":{"name":["东城一路","Dongchengyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["cWAkQU"],"children":["Kki6jW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cWAkQU":{"name":["汇臻路","Huizhen Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["EDJaZn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Yexiaowei11** [comment]
**Justification:** 修改了



**Do not edit lines below, they are meant for bots only!!!**



<details repo="rmg-templates" company="shmetro" line="pjl" major="false"><summary>shmetro/pjl</summary><details type="name">{"en":"Pujiang Line","zh-Hans":"浦江线","zh-Hant":"浦江線","ko":"푸장선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":15,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["shanghai","pjl","#B5B5B6","#fff"],"line_name":["浦江线","Pujiang Line"],"current_stn_idx":"3J3cKt","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["cWAkQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FnqpKU":{"name":["沈杜公路","Shendu Highway"],"secondaryName":false,"num":"01","services":["local"],"parents":["3J3cKt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#4a86e8","#fff"],"name":["8号线","Line 8"]}]}],"info":[[["other","other","#4a86e8","#fff","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3J3cKt":{"name":["三鲁公路","三鲁公路"],"secondaryName":false,"num":"02","services":["local"],"parents":["hNpzac"],"children":["FnqpKU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["FnqpKU"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hNpzac":{"name":["闵瑞路","Min Rui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Kki6jW"],"children":["3J3cKt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Kki6jW":{"name":["浦航路","Puhang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EDJaZn"],"children":["hNpzac"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EDJaZn":{"name":["东城一路","Dongchengyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["cWAkQU"],"children":["Kki6jW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cWAkQU":{"name":["汇臻路","Huizhen Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["EDJaZn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Yexiaowei11** [comment]
![RQ5~RXJP8%RBG5E 1{P$0](https://github.com/railmapgen/rmg-templates/assets/102587532/2c05468b-0937-4285-934b-4b5501ed65eb)

**Comment by 52PD** [comment]
您好，请您删除(REPLACE ME/代替我)使bot识别此issue。感谢。

**Comment by Yexiaowei11** [comment]
> 您好，请您删除（REPLACE ME/代替我）使bot识别此issue。感谢。
> 
> （请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

已修改

**Comment by 52PD** [comment]
您好。经检查，您所提交的模版包含但不限于以下问题：

- 三鲁公路站英文名（Sanlu Highway）错写成了“三鲁公路”😂😂😂。
- 闵瑞路站英文名（Minrui Road）错写成了“Min Rui Road”。

请修正后再次提交，多谢。（考虑到上述问题并非涉及现有城市名称或者未开通线路的修改，您可以直接将修改后的稿件提交到本issue中，我们会负责将修正后的稿件替换掉原有问题稿件。）

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路模版问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
