### ISSUE TITLE
Resources: New templates of Taizhou Changxing Rail Transit Operation Management Co., Ltd

### ISSUE THREAD

**Issue by AnthonyScottTong** [railmapgen/rmg-templates#309]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** 来源：实地采集数据

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tzcxgdjt" line="00config"><summary>New company: Taizhou Changxing Rail Transit Operation Management Co., Ltd</summary><details type="name">{"en":"Taizhou Changxing Rail Transit Operation Management Co., Ltd","zh-Hans":"台州畅行轨道交通运营管理有限公司","zh-Hant":"台州暢行軌道交通運營管理有限公司","ko":"타이저우 스무스 철도 운송 운영 관리 유한 공사"}</details></details>

<details repo="rmg-templates" company="tzcxgdjt" line="tzs1" major="false"><summary>tzcxgdjt/tzs1</summary><details type="name">{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1線","ko":"S1 라인"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2000,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":16,"branchSpacingPct":0,"direction":"r","platform_num":"","theme":["other","other","#22b9ec","#fff"],"line_name":["S1线","Line S1"],"current_stn_idx":"xC3YXZ","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["xC3YXZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"W_FVML":{"name":["城南","Chennan"],"secondaryName":false,"num":"01","services":["local"],"parents":["Za-Ynk"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xC3YXZ":{"name":["台州火车站","Taizhou Railway Station"],"secondaryName":false,"num":"02","services":["local"],"parents":["linestart"],"children":["32wwOc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["W_FVML"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Za-Ynk":{"name":["南屏","Nanping"],"secondaryName":false,"num":"00","services":["local"],"parents":["nHO3lo"],"children":["W_FVML"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nHO3lo":{"name":["万昌路","Wanchang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["wXj0-_"],"children":["Za-Ynk"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wXj0-_":{"name":["九龙大道","Jiulong Avenue"],"secondaryName":false,"num":"00","services":["local"],"parents":["-d6idF"],"children":["nHO3lo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-d6idF":{"name":["温岭第一人民医院","Wenling NO.1 People's Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["eMt1Gp"],"children":["wXj0-_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eMt1Gp":{"name":["汇川王","Huichuanwang"],"secondaryName":false,"num":"00","services":["local"],"parents":["rbKNRH"],"children":["-d6idF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rbKNRH":{"name":["温岭火车站","Wenling Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["iahGry"],"children":["eMt1Gp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"iahGry":{"name":["泽国","Zeguo"],"secondaryName":false,"num":"00","services":["local"],"parents":["L4_0bi"],"children":["rbKNRH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"L4_0bi":{"name":["台州汽车南站","Taizhou Southern Bus Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["tLKfRY"],"children":["iahGry"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"tLKfRY":{"name":["恩泽医院","Enze Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["zGeFnB"],"children":["L4_0bi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zGeFnB":{"name":["锦泰","Jintai"],"secondaryName":false,"num":"00","services":["local"],"parents":["XjBQ89"],"children":["tLKfRY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XjBQ89":{"name":["汇丰路","Huifeng Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["6DyL9s"],"children":["zGeFnB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6DyL9s":{"name":["国博中心","International Expo Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["32wwOc"],"children":["XjBQ89"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"32wwOc":{"name":["学院路","Xueyuan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["xC3YXZ"],"children":["6DyL9s"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by langonginc** [comment]
您好，您可能需要修改您提交的issue的内容以使bot识别：

- 删除 `(REPLACE ME/替代我)` 。

感谢。

**Comment by 52PD** [comment]
> 您好，您可能需要修改您提交的issue的内容以使bot识别：
> 
> * 删除 `(REPLACE ME/替代我)` 。
> 
> 感谢。

感谢上面补充修正问题。

此外，您在来源中所提到的“实地采集数据“我们是视为无效来源的。因此我们在检查内容的时候会以维基百科为准。谢谢。
