### ISSUE TITLE
Resources: New templates of Chengdu Metro

### ISSUE THREAD

**Issue by AnthonyScottTong** [railmapgen/rmg-templates#317]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)

**Justification:** It's the latest update of cd 18

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="chengdumetro" line="cd18" major="false"><summary>chengdumetro/cd18</summary><details type="name">{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線","ko":"라인 18"}</details><details type="param">{"svgWidth":{"destination":1700,"runin":1500,"railmap":1700,"indoor":2000},"svg_height":500,"style":"shmetro","y_pc":50,"padding":16,"branchSpacingPct":0,"direction":"l","platform_num":"1","theme":["chengdu","cd18","#006271","#fff"],"line_name":["18号线","Line 18"],"current_stn_idx":"TiZirL","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["h9Feg7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"0somHh":{"name":["孵化园","Incubation Park"],"secondaryName":false,"num":"01","services":["local","express"],"parents":["_SbglK"],"children":["gt10V6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chengdu","cd1","#10069F","#fff","1号线","Line 1"],["chengdu","cd9","#FFB81C","#fff","9号线","Line 9"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"gt10V6":{"name":["火车南站","South Railway Station"],"secondaryName":false,"num":"02","services":["local","express"],"parents":["0somHh"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chengdu","cd1","#10069F","#fff","1号线","Line 1"],["chengdu","cd7","#59CBE8","#fff","7号线","Line 7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["gt10V6"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"_SbglK":{"name":["锦城广场东","Jincheng Plaza East"],"secondaryName":false,"num":"00","services":["local"],"parents":["RYNdrs"],"children":["0somHh"],"branch":{"left":[],"right":[]},"transfer":{"info":[[],[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"RYNdrs":{"name":["世纪城","Century City"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["2ITCrY"],"children":["_SbglK"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chengdu","cd1","#10069F","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"2ITCrY":{"name":["海昌路","Haichang Road"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["KMWaF4"],"children":["RYNdrs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chengdu","cd1","#10069F","#fff","1号线","Line 1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"KMWaF4":{"name":["西博城","Western China Int'l Expo City"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["rJ_eZr"],"children":["2ITCrY"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["chengdu","cd1","#10069F","#fff","1号线","Line 1"],["chengdu","cd6","#B36924","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"rJ_eZr":{"name":["兴隆","Xinglong"],"secondaryName":false,"num":"00","services":["local"],"parents":["jw5qf_"],"children":["KMWaF4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"jw5qf_":{"name":["天府新站","Tianfu Xinzhan"],"secondaryName":false,"num":"00","services":["local"],"parents":["tDl2ve"],"children":["rJ_eZr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"tDl2ve":{"name":["三岔","Sancha"],"secondaryName":false,"num":"00","services":["local"],"parents":["TiZirL"],"children":["jw5qf_"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"qtggmP":{"name":["天府机场3号4号航站楼","Tianfu Airport Terminal Buildings No.3 and No.4"],"secondaryName":false,"num":"00","services":["local"],"parents":["h9Feg7"],"children":["TiZirL"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"airport","loop_pivot":false,"one_line":true,"int_padding":300},"h9Feg7":{"name":["天府机场1号2号航站楼","Tianfu Airport Terminal Buildings No.1 and No.2"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["linestart"],"children":["qtggmP"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"airport","loop_pivot":false,"one_line":true,"int_padding":300},"TiZirL":{"name":["福田","Futian"],"secondaryName":false,"num":"00","services":["local"],"parents":["qtggmP"],"children":["tDl2ve"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，请您删除```Replace Me/代替我```使bot识别此issue。感谢。

**Comment by 52PD** [comment]
> 您好，请您删除`(REPLACE ME/代替我)`使bot识别此issue。感谢。

此外，请不要擅自更改Issue名称，谢谢。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及本issue无法被识别后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
