### ISSUE TITLE
请求加入一些成都地铁线路

### ISSUE THREAD

**Issue by Jay20081229** [railmapgen/rmg-templates#32]
我已经做好了成都地铁1、2、5、6号线的线路图模板了。
线路模板：[成都地铁l1,l2,l5,l6.zip](https://github.com/railmapgen/rmg-templates/files/8875032/l1.l2.l5.l6.zip)

**Comment by 52PD** [comment]
您好，目前3/4/7/8/9/10/17/18号线的线路模版仍然未见提交，所以就像@thekingofcity 在#3 中所说的，建议您将剩余八条线制作完成后与已经上传的四条线一起打包上传，这样也方便我们将所有线路汇入到项目中。

再次感谢您对本项目的支持！

**Comment by 52PD** [comment]
Closed due to contents transferred to a new issue.
The issue now continues in https://github.com/railmapgen/rmg-templates/issues/54 .
