### ISSUE TITLE
Resources: New templates of Xi’an Metro

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#332]
**Justification:** 提供西安地铁5号线的RMG模版。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="西安地铁" line="00config"><summary>New company: Xi’an Metro</summary><details type="name">{"en":"Xi’an Metro","zh-Hans":"西安地铁","zh-Hant":"西安地鐵","ko":"서안 지하철"}</details></details>

<details repo="rmg-templates" company="西安地铁" line="西安地铁 5号线" major="false"><summary>西安地铁/西安地铁 5号线</summary><details type="name">{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線","ko":"5호선"}</details><details type="param">{"svgWidth":{"destination":1300,"runin":1300,"railmap":2500,"indoor":4500},"svg_height":380,"style":"shmetro","y_pc":50,"padding":5,"branchSpacingPct":33,"direction":"l","platform_num":"3","theme":["xian","xa5","#A6E35F","#fff"],"line_name":["5号线","Line 5"],"current_stn_idx":"lj42CP","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["AvIAsT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lj42CP":{"name":["马腾空","MATENGKONG"],"secondaryName":false,"num":"01","services":["local"],"parents":["PTt3MP"],"children":["ubNHog"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ubNHog":{"name":["月登阁","YUEDENGGE"],"secondaryName":false,"num":"02","services":["local"],"parents":["lj42CP"],"children":["05hur0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["fq4Zh_"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"05hur0":{"name":["雁鸣湖","YANMINGHU"],"secondaryName":false,"num":"00","services":["local"],"parents":["ubNHog"],"children":["fq4Zh_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fq4Zh_":{"name":["西安东站","XI’AN DONGZHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["05hur0"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"PTt3MP":{"name":["黄渠头","HUANGQUTOU"],"secondaryName":false,"num":"00","services":["local"],"parents":["9RtiHI"],"children":["lj42CP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9RtiHI":{"name":["理工大曲江校区","LIGONGDA QUJIANGXIAOQU"],"secondaryName":false,"num":"00","services":["local"],"parents":["Hw7SML"],"children":["PTt3MP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Hw7SML":{"name":["青龙寺","QINGLONGSI"],"secondaryName":false,"num":"00","services":["local"],"parents":["YkKemf"],"children":["9RtiHI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xian","xa3","#CE70CC","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"YkKemf":{"name":["雁翔路北口","YANXIANGLU BEIKOU"],"secondaryName":false,"num":"00","services":["local"],"parents":["JOmcyG"],"children":["Hw7SML"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JOmcyG":{"name":["太乙路","TAIYILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["n3N-B7"],"children":["YkKemf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"n3N-B7":{"name":["建筑科技大学·李家村","JIANZHUKEJIDAXUE\\LIJIACUN"],"secondaryName":false,"num":"00","services":["local"],"parents":["7ojpLx"],"children":["JOmcyG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#39b09e","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":260},"7ojpLx":{"name":["文艺路","WENYILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["vwDbbO"],"children":["n3N-B7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vwDbbO":{"name":["南稍门","NANSHAOMEN"],"secondaryName":false,"num":"00","services":["local"],"parents":["78Q2JM"],"children":["7ojpLx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff0000","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"78Q2JM":{"name":["省人民医院·黄雁村","SHENGRENMINYIYUAN\\HUANGYANCUN"],"secondaryName":false,"num":"00","services":["local"],"parents":["caLh5i"],"children":["vwDbbO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"caLh5i":{"name":["边家村","BIANJIACUN"],"secondaryName":false,"num":"00","services":["local"],"parents":["T-rOC2"],"children":["78Q2JM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"T-rOC2":{"name":["西北工业大学","XIBEI GONGYEDAXUE"],"secondaryName":false,"num":"00","services":["local"],"parents":["jj9nqP"],"children":["caLh5i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#7c80b0","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"jj9nqP":{"name":["丰庆公园","FENGQING GONGYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["jXmqDd"],"children":["T-rOC2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jXmqDd":{"name":["金光门","JINGUANGMEN"],"secondaryName":false,"num":"00","services":["local"],"parents":["0jq0kl"],"children":["jj9nqP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0jq0kl":{"name":["汉城南路","HANCHENG NANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["kOtzt_"],"children":["jXmqDd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kOtzt_":{"name":["西窑头","XIYAOTOU"],"secondaryName":false,"num":"00","services":["local"],"parents":["kwfF56"],"children":["0jq0kl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kwfF56":{"name":["石桥立交","SHIQIAO LIJIAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["JgFeJ6"],"children":["kOtzt_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JgFeJ6":{"name":["阿房宫南","E’PANGGONG NAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["OzO7XL"],"children":["kwfF56"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["other","other","#72217c","#fff"],"name":["西户线","Xihu Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"OzO7XL":{"name":["王寺","WANGSI"],"secondaryName":false,"num":"00","services":["local"],"parents":["oNmpsA"],"children":["JgFeJ6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"oNmpsA":{"name":["斗门","DOUMEN"],"secondaryName":false,"num":"00","services":["local"],"parents":["fwDc8V"],"children":["OzO7XL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["other","other","#b5222c","#fff"],"name":["西咸智轨1号线","Xixian ART Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"fwDc8V":{"name":["复兴大道南","FUXINGDADAO NAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["L0J_EO"],"children":["oNmpsA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"L0J_EO":{"name":["镐京","HAOJING"],"secondaryName":false,"num":"00","services":["local"],"parents":["zLFl0i"],"children":["fwDc8V"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zLFl0i":{"name":["欢乐谷","HUANLEGU"],"secondaryName":false,"num":"00","services":["local"],"parents":["h3Jbld"],"children":["L0J_EO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#f48852","#fff"],"name":["16号线","Line 16"]}]},{"lines":[{"theme":["other","other","#b5222c","#fff"],"name":["西咸智轨1号线","Xixian ART Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":240},"h3Jbld":{"name":["文教园","WENJIAOYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["NOpGkQ"],"children":["zLFl0i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NOpGkQ":{"name":["高桥","GAOQIAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["KXPJoe"],"children":["h3Jbld"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KXPJoe":{"name":["东马坊","DONGMAFANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["17d-MO"],"children":["NOpGkQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"17d-MO":{"name":["沣西文化公园","FENGXI WENHUAGONGYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["XvdF_X"],"children":["KXPJoe"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XvdF_X":{"name":["钓台","DIAOTAI"],"secondaryName":false,"num":"00","services":["local"],"parents":["M_jA2e"],"children":["17d-MO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"M_jA2e":{"name":["翱翔小镇","AOXIANG XIAOZHEN"],"secondaryName":false,"num":"00","services":["local"],"parents":["5QdiTi"],"children":["XvdF_X"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5QdiTi":{"name":["创新港东","CHUANGXINGANG DONG"],"secondaryName":false,"num":"00","services":["local"],"parents":["AvIAsT"],"children":["M_jA2e"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AvIAsT":{"name":["创新港","CHUANGXINGANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["5QdiTi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好，我们注意到您所提交的线路编号和地区/公司编号均采用了中文，然而为了保证项目导入模版时检索名称的准确性，线路编号与地区/公司编号均需采用英文（如西安地铁的地区/公司编号应为xi'an，1号线的线路编号应为xa1）。

因此，很抱歉，我们无法接受您的投稿。请您正确填写线路编号和地区/公司编号后重新提交一遍。

另外，如果您提交的线路模版均来自同一个地区的话，请将所有线路模版放入同一个issue中提交，不要多开issue。
