### ISSUE TITLE
Resources: New templates of Xi’an Metro

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#334]
**Justification:** 提供西安地铁9号线的RMG模版。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="西安地铁" line="00config"><summary>New company: Xi’an Metro</summary><details type="name">{"en":"Xi’an Metro","zh-Hans":"西安地铁","zh-Hant":"西安地鐵","ko":"서안 지하철"}</details></details>

<details repo="rmg-templates" company="西安地铁" line="西安地铁 9号线" major="false"><summary>西安地铁/西安地铁 9号线</summary><details type="name">{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線","ko":"9호선"}</details><details type="param">{"svgWidth":{"destination":1300,"runin":1300,"railmap":1800,"indoor":2000},"svg_height":350,"style":"shmetro","y_pc":50,"padding":9,"branchSpacingPct":33,"direction":"l","platform_num":"3","theme":["xian","xa9","#FF9E1B","#fff"],"line_name":["9号线","Line 9"],"current_stn_idx":"gXqv1O","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["wAQLiB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PAzLBt":{"name":["香王","XIANGWANG"],"secondaryName":false,"num":"01","services":["local"],"parents":["6BWRoX"],"children":["gXqv1O"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gXqv1O":{"name":["纺织城","FANGZHICHENG"],"secondaryName":false,"num":"02","services":["local"],"parents":["PAzLBt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xian","xa1","#0077C8","#fff"],"name":["1号线","Line 1"]},{"theme":["other","other","#7c80b0","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["gXqv1O"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6BWRoX":{"name":["灞柳二路","BALIU 2 LU"],"secondaryName":false,"num":"00","services":["local"],"parents":["xbQtBy"],"children":["PAzLBt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xbQtBy":{"name":["田王","TIANWANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["UGXBXL"],"children":["6BWRoX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UGXBXL":{"name":["洪庆","HONGQING"],"secondaryName":false,"num":"00","services":["local"],"parents":["lCRHv1"],"children":["xbQtBy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lCRHv1":{"name":["紫霞三路","ZIXIA 3 LU"],"secondaryName":false,"num":"00","services":["local"],"parents":["ABd3XU"],"children":["UGXBXL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ABd3XU":{"name":["凤凰池","FENGHUANGCHI"],"secondaryName":false,"num":"00","services":["local"],"parents":["UZAkux"],"children":["lCRHv1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UZAkux":{"name":["鹦鹉寺公园","YINGWUSI GONGYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["fdbng1"],"children":["ABd3XU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fdbng1":{"name":["芷阳广场","ZHIYANG GUANGCHANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["hLcuKZ"],"children":["UZAkux"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hLcuKZ":{"name":["西工程大·西科大 (临潼校区)","XIGONGCHENGDA\\XIKEDA (LINTONGXIAOQU)"],"secondaryName":false,"num":"00","services":["local"],"parents":["SHwONR"],"children":["fdbng1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SHwONR":{"name":["西花园","XIHUAYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["Brkwg6"],"children":["hLcuKZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Brkwg6":{"name":["华清池","HUAQINGCHI"],"secondaryName":false,"num":"00","services":["local"],"parents":["3Lz7kq"],"children":["SHwONR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3Lz7kq":{"name":["东三岔","DONGSANCHA"],"secondaryName":false,"num":"00","services":["local"],"parents":["UqEvLH"],"children":["Brkwg6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UqEvLH":{"name":["银桥大道","YINQIAO DADAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["wAQLiB"],"children":["3Lz7kq"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wAQLiB":{"name":["秦陵西","QINLINGXI"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["UqEvLH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好，我们注意到您所提交的线路编号和地区/公司编号均采用了中文，然而为了保证项目导入模版时检索名称的准确性，线路编号与地区/公司编号均需采用英文（如西安地铁的地区/公司编号应为xi'an，1号线的线路编号应为xa1）。

因此，很抱歉，我们无法接受您的投稿。请您正确填写线路编号和地区/公司编号后重新提交一遍。

另外，如果您提交的线路模版均来自同一个地区的话，请将所有线路模版放入同一个issue中提交，不要多开issue。
