### ISSUE TITLE
Resources: New templates of Beijing Subway

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-templates#343]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 把房山线9号线优化了一下，现在更美观了

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="bjsubway" line="fsl" major="false"><summary>bjsubway/fsl</summary><details type="name">{"en":"Fangshan Line (Through to Line 9)","zh-Hans":"房山线（跨线至9号线）","zh-Hant":"房山線（跨線至9號線）","ko":"팡산선 (9호선으로 직통과)"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":2500,"indoor":2500},"svg_height":600,"style":"shmetro","y_pc":50,"padding":5,"branchSpacingPct":31,"direction":"r","platform_num":"","theme":["beijing","bj25fs","#e46022","#fff"],"line_name":["房山线","Fangshan Line"],"current_stn_idx":"0Ap8oX","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["VkKadY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":200},"VkKadY":{"name":["阎村东","Yancun Dong (E)"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["wqS1zN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj25fs","#e46022","#fff"],"name":["燕房线","Yanfang Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":150},"SRCtCJ":{"name":["东管头南","Dongguantou Nan (S)"],"secondaryName":false,"num":"02","services":["local"],"parents":["-WCFzD"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj16","#76a32e","#fff"],"name":["16号线","Line 16"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["SRCtCJ","O5PGjN"],"children":[],"branch":{"left":["through","O5PGjN"],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":200},"0Ap8oX":{"name":["郭公庄","Guogongzhuang"],"secondaryName":false,"num":"00","services":["local"],"parents":["c27nZT"],"children":["OVJR-5","6CKIES"],"branch":{"left":[],"right":["through","6CKIES"]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"OVJR-5":{"name":["白盆窑","Baipenyao"],"secondaryName":false,"num":"00","services":["local"],"parents":["0Ap8oX"],"children":["Rv7qbR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"O5PGjN":{"name":["国家图书馆","Guojia Tushuguan \\(National Library)"],"secondaryName":false,"num":"00","services":["local"],"parents":["FNFw_M"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj4","#008e9c","#fff"],"name":["4号线","Line 4"]},{"theme":["beijing","bj16","#76a32e","#fff"],"name":["16号线","Line 16"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"6CKIES":{"name":["丰台科技园","Fengtai Science Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["0Ap8oX"],"children":["EB82D4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"wqS1zN":{"name":["苏庄","Suzhuang"],"secondaryName":false,"num":"00","services":["local"],"parents":["VkKadY"],"children":["nn-FKH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"nn-FKH":{"name":["良乡南关","Liangxiang Nanguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["wqS1zN"],"children":["v_UtZ5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"v_UtZ5":{"name":["良乡大学城西","Liangxiang Univ. Town West"],"secondaryName":false,"num":"00","services":["local"],"parents":["nn-FKH"],"children":["5UfPbG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"5UfPbG":{"name":["良乡大学城","Liangxiang Univ. Town"],"secondaryName":false,"num":"00","services":["local"],"parents":["v_UtZ5"],"children":["v3Eioi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"v3Eioi":{"name":["良乡大学城北","Liangxiang Univ. Town North"],"secondaryName":false,"num":"00","services":["local"],"parents":["5UfPbG"],"children":["aYjP9k"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"aYjP9k":{"name":["广阳城","Guangyang Cheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["v3Eioi"],"children":["GKUVR6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"GKUVR6":{"name":["篱笆房","Libafang"],"secondaryName":false,"num":"00","services":["local"],"parents":["aYjP9k"],"children":["KcF13h"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"KcF13h":{"name":["长阳","Changyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["GKUVR6"],"children":["dUQ54u"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"dUQ54u":{"name":["稻田","Daotian"],"secondaryName":false,"num":"00","services":["local"],"parents":["KcF13h"],"children":["c27nZT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"c27nZT":{"name":["大葆台","Dabaotai"],"secondaryName":false,"num":"00","services":["local"],"parents":["dUQ54u"],"children":["0Ap8oX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"Rv7qbR":{"name":["花乡东桥","Huaxiang Dongqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["OVJR-5"],"children":["-WCFzD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"-WCFzD":{"name":["首经贸","Capital Univ. of Economics &amp; Business"],"secondaryName":false,"num":"00","services":["local"],"parents":["Rv7qbR"],"children":["SRCtCJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"EB82D4":{"name":["科怡路","Keyi Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["6CKIES"],"children":["-EdxQq"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"-EdxQq":{"name":["丰台南路","Fengtai Nanlu"],"secondaryName":false,"num":"00","services":["local"],"parents":["EB82D4"],"children":["Q4sMb7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj16","#76a32e","#fff"],"name":["16号线","Line 16"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"Q4sMb7":{"name":["丰台东大街","Fengtai Dongdajie"],"secondaryName":false,"num":"00","services":["local"],"parents":["-EdxQq"],"children":["UVZlfi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"UVZlfi":{"name":["七里庄","Qilizhuang"],"secondaryName":false,"num":"00","services":["local"],"parents":["Q4sMb7"],"children":["WvPVRL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj14","#d5a7a1","#000"],"name":["14号线","Line 14"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"WvPVRL":{"name":["六里桥","Liuli Qiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["UVZlfi"],"children":["GsoSpE"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"GsoSpE":{"name":["六里桥东","Liuliqiao Dong (E)"],"secondaryName":false,"num":"00","services":["local"],"parents":["WvPVRL"],"children":["isDD6N"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"isDD6N":{"name":["北京西站","Beijingxi Zhan\\(Beijing West Railway Station)"],"secondaryName":false,"num":"00","services":["local"],"parents":["GsoSpE"],"children":["tfRvya"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj7","#f6c582","#000"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"tfRvya":{"name":["军事博物馆","Military Museum"],"secondaryName":false,"num":"00","services":["local"],"parents":["isDD6N"],"children":["Szusgv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj1","#c23a30","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"Szusgv":{"name":["白堆子","Baiduizi"],"secondaryName":false,"num":"00","services":["local"],"parents":["tfRvya"],"children":["FNFw_M"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"FNFw_M":{"name":["白石桥南","Baishiqiaonan"],"secondaryName":false,"num":"00","services":["local"],"parents":["Szusgv"],"children":["O5PGjN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["beijing","bj6","#d29700","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{"rkJ_":{"from":"0Ap8oX","to":"O5PGjN","colors":[["beijing","bj9","#8fc31f","#000","9号线","Line 9"]],"display":true},"zUwm":{"from":"VkKadY","to":"0Ap8oX","colors":[["beijing","bj9","#8fc31f","#000","9号线","Line 9"]],"display":true}},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by langonginc** [comment]
这边看没什么问题，等待管理员最终确认并汇入，感谢您的贡献。
