### ISSUE TITLE
Resources: New templates of Urumqi Metro

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg-templates#350]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** https://www.urumqimtr.com/DTXLT/5402.aspx

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="urumqimtr " line="00config"><summary>New company: Urumqi Metro</summary><details type="name">{"en":"Urumqi Metro","zh-Hans":"乌鲁木齐地铁","zh-Hant":"烏魯木齊地鐵","ko":"우루무치 지하철"}</details></details>

<details repo="rmg-templates" company="urumqimtr " line="ur1" major="false"><summary>urumqimtr /ur1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1400,"indoor":1200},"svg_height":300,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["urumqi","urumqi1","#10069f","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"wxrVnF","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["wxrVnF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wxrVnF":{"name":["国际机场","International Airport"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["iCGl8F"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iCGl8F":{"name":["大地窝堡","Dadiwopu"],"secondaryName":false,"num":"02","services":["local"],"parents":["wxrVnF"],"children":["IT_N8l"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["bF401M"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IT_N8l":{"name":["宣仁墩","Xuanrendun"],"secondaryName":false,"num":"03","services":["local"],"parents":["iCGl8F"],"children":["ljPDwo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ljPDwo":{"name":["三工","Sangong"],"secondaryName":false,"num":"04","services":["local"],"parents":["IT_N8l"],"children":["CQcmxx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CQcmxx":{"name":["迎宾路口","Yingbin Road Crossing"],"secondaryName":false,"num":"05","services":["local"],"parents":["ljPDwo"],"children":["p_nVgY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"p_nVgY":{"name":["植物园","Botanical Garden"],"secondaryName":false,"num":"06","services":["local"],"parents":["CQcmxx"],"children":["w5VSRs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"w5VSRs":{"name":["体育中心","Sports Center"],"secondaryName":false,"num":"07","services":["local"],"parents":["p_nVgY"],"children":["1K1xoL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1K1xoL":{"name":["铁路局","Tieluju"],"secondaryName":false,"num":"08","services":["local"],"parents":["w5VSRs"],"children":["fQkrra"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fQkrra":{"name":["小西沟","Xiaoxigou"],"secondaryName":false,"num":"09","services":["local"],"parents":["1K1xoL"],"children":["hvpX_1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hvpX_1":{"name":["中营工","Zhongyinggong"],"secondaryName":false,"num":"10","services":["local"],"parents":["fQkrra"],"children":["TlUgil"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"TlUgil":{"name":["新疆图书馆","Xinjiang Library"],"secondaryName":false,"num":"11","services":["local"],"parents":["hvpX_1"],"children":["AXt773"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AXt773":{"name":["八楼","Balou"],"secondaryName":false,"num":"12","services":["local"],"parents":["TlUgil"],"children":["SSIjVd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SSIjVd":{"name":["王家梁","Wangjialiang"],"secondaryName":false,"num":"13","services":["local"],"parents":["AXt773"],"children":["AeXXsN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AeXXsN":{"name":["南湖北路","Nanhu North Road"],"secondaryName":false,"num":"14","services":["local"],"parents":["SSIjVd"],"children":["Kaf3dZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Kaf3dZ":{"name":["南湖公园","Nanhu Park"],"secondaryName":false,"num":"15","services":["local"],"parents":["AeXXsN"],"children":["sNCrzb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"sNCrzb":{"name":["新兴街","Xinxing Street"],"secondaryName":false,"num":"16","services":["local"],"parents":["Kaf3dZ"],"children":["29cYC5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"29cYC5":{"name":["北门","Beimen"],"secondaryName":false,"num":"17","services":["local"],"parents":["sNCrzb"],"children":["hvrVYu"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hvrVYu":{"name":["南门","Nanmen"],"secondaryName":false,"num":"18","services":["local"],"parents":["29cYC5"],"children":["UWqiWW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UWqiWW":{"name":["二道桥","Erdaoqiao"],"secondaryName":false,"num":"19","services":["local"],"parents":["hvrVYu"],"children":["UH1MpQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UH1MpQ":{"name":["新疆大学","Xinjiang University"],"secondaryName":false,"num":"20","services":["local"],"parents":["UWqiWW"],"children":["bF401M"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bF401M":{"name":["三屯碑","Santunbei"],"secondaryName":false,"num":"21","services":["local"],"parents":["UH1MpQ"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gzgf","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
Hello, please remove ```(REPLACE ME代替我)``` so that the bot can identify this issue, thanks!
