### ISSUE TITLE
Resources: New templates of Hohhot Metro

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-templates#359]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** https://en.wikipedia.org/wiki/Hohhot_Metro

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hhhtmetro" line="00config"><summary>New company: Hohhot Metro</summary><details type="name">{"en":"Hohhot Metro","zh-Hans":"呼和浩特地铁","zh-Hant":"呼和浩特地鐵","ko":"후허하오터 지하철"}</details></details>

<details repo="rmg-templates" company="hhhtmetro" line="hhht1" major="false"><summary>hhhtmetro/hhht1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1500},"svg_height":350,"style":"shmetro","y_pc":50,"padding":7,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["hohhot","hhht1","#e82311","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"BQP-HG","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["zzsqzh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"zzsqzh":{"name":["伊利健康谷","Yili Health Valley"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["ACPkZW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"BQP-HG":{"name":["坝堰（机场）","Bayan (Airport)"],"secondaryName":false,"num":"02","services":["local"],"parents":["RCBSPb"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"airport","loop_pivot":false,"one_line":false,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["BQP-HG"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"ACPkZW":{"name":["西二环路","Xi'erhuanlu"],"secondaryName":false,"num":"00","services":["local"],"parents":["zzsqzh"],"children":["c1Vsx9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"c1Vsx9":{"name":["孔家营","Kongjiaying"],"secondaryName":false,"num":"00","services":["local"],"parents":["ACPkZW"],"children":["MxiKlj"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"MxiKlj":{"name":["呼钢东路","Hugangdonglu"],"secondaryName":false,"num":"00","services":["local"],"parents":["c1Vsx9"],"children":["9gvPqp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"9gvPqp":{"name":["西龙王庙","Xilongwangmiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["MxiKlj"],"children":["RRfAUZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"RRfAUZ":{"name":["乌兰夫纪念馆","Wulanfu Memorial Hall"],"secondaryName":false,"num":"00","services":["local"],"parents":["9gvPqp"],"children":["YgTQyA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"YgTQyA":{"name":["附属医院","Affiliated Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["RRfAUZ"],"children":["0yUqon"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"0yUqon":{"name":["新华广场","Xinhua Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["YgTQyA"],"children":["W7tk33"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hohhot","hhht2","#005bac","#fff"],"name":["2号线",""]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"W7tk33":{"name":["人民会堂","People's Hall"],"secondaryName":false,"num":"00","services":["local"],"parents":["0yUqon"],"children":["ndx5NM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"ndx5NM":{"name":["将军衙署","Jiangjunyashu"],"secondaryName":false,"num":"00","services":["local"],"parents":["W7tk33"],"children":["AR9_Hr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"AR9_Hr":{"name":["艺术学院","Arts College"],"secondaryName":false,"num":"00","services":["local"],"parents":["ndx5NM"],"children":["w38lbM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"w38lbM":{"name":["东影路","Dongyinglu"],"secondaryName":false,"num":"00","services":["local"],"parents":["AR9_Hr"],"children":["2o8KqX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"2o8KqX":{"name":["内蒙古展览馆","Inner Mongolia Exhibition Hall"],"secondaryName":false,"num":"00","services":["local"],"parents":["w38lbM"],"children":["wsNRDx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"wsNRDx":{"name":["内蒙古博物院","Inner Mongolia Museum"],"secondaryName":false,"num":"00","services":["local"],"parents":["2o8KqX"],"children":["7kVpSc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"7kVpSc":{"name":["市政府","City Government"],"secondaryName":false,"num":"00","services":["local"],"parents":["wsNRDx"],"children":["dFkaqw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"dFkaqw":{"name":["呼和浩特东站","Hohhot East Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["7kVpSc"],"children":["Hij3ng"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":300},"Hij3ng":{"name":["后不塔气","Houbutaqi"],"secondaryName":false,"num":"00","services":["local"],"parents":["dFkaqw"],"children":["ivTytI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"ivTytI":{"name":["什兰岱","Shilandai"],"secondaryName":false,"num":"00","services":["local"],"parents":["Hij3ng"],"children":["RCBSPb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"RCBSPb":{"name":["白塔西","Baita West"],"secondaryName":false,"num":"00","services":["local"],"parents":["ivTytI"],"children":["BQP-HG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="hhhtmetro" line="hhht2" major="false"><summary>hhhtmetro/hhht2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線","ko":"2호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1800},"svg_height":350,"style":"shmetro","y_pc":50,"padding":4,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["hohhot","hhht2","#005bac","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"iip6i7","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["HMB8GY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"HMB8GY":{"name":["塔利东路","Talidonglu"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["OLJRPy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"iip6i7":{"name":["阿尔山路","A'ershanlu"],"secondaryName":false,"num":"02","services":["local"],"parents":["K7kL1Z"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["iip6i7"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"OLJRPy":{"name":["新店","Xindian"],"secondaryName":false,"num":"00","services":["local"],"parents":["HMB8GY"],"children":["MC0UAq"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"MC0UAq":{"name":["百合路","Baihelu"],"secondaryName":false,"num":"00","services":["local"],"parents":["OLJRPy"],"children":["FJAbGg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"FJAbGg":{"name":["新城图书馆","Xincheng Library"],"secondaryName":false,"num":"00","services":["local"],"parents":["MC0UAq"],"children":["-wqZxQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"-wqZxQ":{"name":["东二环路","Dongerhuanlu"],"secondaryName":false,"num":"00","services":["local"],"parents":["FJAbGg"],"children":["y9Jkmz"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"y9Jkmz":{"name":["一家村","Yijiacun"],"secondaryName":false,"num":"00","services":["local"],"parents":["-wqZxQ"],"children":["Py_EWc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"Py_EWc":{"name":["成吉思汗公园","Genghis Khan Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["y9Jkmz"],"children":["EeuIBP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"EeuIBP":{"name":["豪沁营","Haoqinying"],"secondaryName":false,"num":"00","services":["local"],"parents":["Py_EWc"],"children":["h6IBa1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"h6IBa1":{"name":["成吉思汗广场","Genghis Khan Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["EeuIBP"],"children":["b_Z7Or"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"b_Z7Or":{"name":["内蒙古体育馆","Inner Mongolia Gymnasium"],"secondaryName":false,"num":"00","services":["local"],"parents":["h6IBa1"],"children":["gbUivl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"gbUivl":{"name":["呼和浩特体育场","Hohhot Stadium"],"secondaryName":false,"num":"00","services":["local"],"parents":["b_Z7Or"],"children":["0f0c4J"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"0f0c4J":{"name":["公主府","Gongzhufu"],"secondaryName":false,"num":"00","services":["local"],"parents":["gbUivl"],"children":["uIZAT9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"uIZAT9":{"name":["呼和浩特站","Hohhot Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["0f0c4J"],"children":["5PyBl_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"5PyBl_":{"name":["新华广场","Xinhua Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["uIZAT9"],"children":["gO_3jN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hohhot","hhht1","#e82311","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"gO_3jN":{"name":["中山路","Zhongshanlu"],"secondaryName":false,"num":"00","services":["local"],"parents":["5PyBl_"],"children":["wQT0XZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"wQT0XZ":{"name":["大学西街","Daxuexijie"],"secondaryName":false,"num":"00","services":["local"],"parents":["gO_3jN"],"children":["kIg2Fk"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"kIg2Fk":{"name":["诺和木勒","Nuohemule"],"secondaryName":false,"num":"00","services":["local"],"parents":["wQT0XZ"],"children":["QVvIPg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"QVvIPg":{"name":["水上公园","Shuishang Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["kIg2Fk"],"children":["DyttsK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"DyttsK":{"name":["五里营","Wuliying"],"secondaryName":false,"num":"00","services":["local"],"parents":["QVvIPg"],"children":["JJ238i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"JJ238i":{"name":["锡林公园","Xilin Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["DyttsK"],"children":["09XVsn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"09XVsn":{"name":["内大南校区","Neida Nanxiaoqu"],"secondaryName":false,"num":"00","services":["local"],"parents":["JJ238i"],"children":["ZEUvsE"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"ZEUvsE":{"name":["帅家营","Shuaijiaying"],"secondaryName":false,"num":"00","services":["local"],"parents":["09XVsn"],"children":["K7kL1Z"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300},"K7kL1Z":{"name":["喇嘛营","Lamaying"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZEUvsE"],"children":["iip6i7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":300}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by langonginc** [comment]
您好，我这边看没问题，请等待管理员最终确认并汇入，感谢您的贡献。
