### ISSUE TITLE
Resources: New templates of Nantong Rail Transit

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-templates#367]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 加南通轨道交通1号线模版

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="ntrailway" line="00config"><summary>New company: Nantong Rail Transit</summary><details type="name">{"en":"Nantong Rail Transit","zh-Hans":"南通轨道交通","zh-Hant":"南通軌道交通","ko":"난퉁 지하철"}</details></details>

<details repo="rmg-templates" company="ntrailway" line="nt1" major="false"><summary>ntrailway/nt1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1500,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":3,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["nantong","nt1","#e60012","#fff"],"line_name":["地鐵線","Metro Line"],"current_stn_idx":"39gN6Y","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["39gN6Y"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"39gN6Y":{"name":["平潮","Pingchao"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["QuI8ca"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Jh3MKo":{"name":["振兴路","Zhenxing Lu"],"secondaryName":false,"num":"02","services":["local"],"parents":["27Uzm4"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Jh3MKo"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QuI8ca":{"name":["南通西站","Nantongxi Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["39gN6Y"],"children":["B04PeH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"B04PeH":{"name":["集成村","Jichengcun"],"secondaryName":false,"num":"00","services":["local"],"parents":["QuI8ca"],"children":["3a2yC_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3a2yC_":{"name":["河口","Hekou"],"secondaryName":false,"num":"00","services":["local"],"parents":["B04PeH"],"children":["9xMEJn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9xMEJn":{"name":["唐闸公园","Tangzha Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["3a2yC_"],"children":["srWfLo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"srWfLo":{"name":["普贤路","Puxian Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["9xMEJn"],"children":["7ur-wV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7ur-wV":{"name":["十里坊","Shilifang"],"secondaryName":false,"num":"00","services":["local"],"parents":["srWfLo"],"children":["1TcLn1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1TcLn1":{"name":["城港路","Chenggang Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["7ur-wV"],"children":["M9EEwB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"M9EEwB":{"name":["曙光","Shuguang"],"secondaryName":false,"num":"00","services":["local"],"parents":["1TcLn1"],"children":["VILDxG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VILDxG":{"name":["茶庵殿","Cha'an Dian"],"secondaryName":false,"num":"00","services":["local"],"parents":["M9EEwB"],"children":["HELEYa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HELEYa":{"name":["孩儿巷","Hai'er Xiang"],"secondaryName":false,"num":"00","services":["local"],"parents":["VILDxG"],"children":["SHLspF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SHLspF":{"name":["和平桥","Hepingqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["HELEYa"],"children":["o-Qvtl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"o-Qvtl":{"name":["友谊桥","Youyiqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["SHLspF"],"children":["m3mvz-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"m3mvz-":{"name":["学田","Xuetian"],"secondaryName":false,"num":"00","services":["local"],"parents":["o-Qvtl"],"children":["t4gJ4l"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"t4gJ4l":{"name":["文峰","Wenfeng"],"secondaryName":false,"num":"00","services":["local"],"parents":["m3mvz-"],"children":["nYWZWJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nYWZWJ":{"name":["慈善博物馆","Charity Museum"],"secondaryName":false,"num":"00","services":["local"],"parents":["t4gJ4l"],"children":["GD7eX-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GD7eX-":{"name":["政务中心","Government Affairs Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["nYWZWJ"],"children":["rMyhsU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rMyhsU":{"name":["世纪大道","Shiji Dadao"],"secondaryName":false,"num":"00","services":["local"],"parents":["GD7eX-"],"children":["UxyCmG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UxyCmG":{"name":["图书馆","Nantong Library"],"secondaryName":false,"num":"00","services":["local"],"parents":["rMyhsU"],"children":["8PqDms"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8PqDms":{"name":["南通大学","Nantong University"],"secondaryName":false,"num":"00","services":["local"],"parents":["UxyCmG"],"children":["qCpZsV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qCpZsV":{"name":["盘香路","Panxiang Lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["8PqDms"],"children":["91b644"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"91b644":{"name":["崇州大道","Chongzhou Dadao"],"secondaryName":false,"num":"00","services":["local"],"parents":["qCpZsV"],"children":["CwCYTg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CwCYTg":{"name":["静海大道","Jinghai Dadao"],"secondaryName":false,"num":"00","services":["local"],"parents":["91b644"],"children":["BF73kN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"BF73kN":{"name":["大剧院","Grand Theatre"],"secondaryName":false,"num":"00","services":["local"],"parents":["CwCYTg"],"children":["3do-OT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3do-OT":{"name":["紫琅湖","Zilang Lake"],"secondaryName":false,"num":"00","services":["local"],"parents":["BF73kN"],"children":["s0tV3s"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"s0tV3s":{"name":["能达商务区","NETDA Business District"],"secondaryName":false,"num":"00","services":["local"],"parents":["3do-OT"],"children":["27Uzm4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"27Uzm4":{"name":["航运学院","Shipping College"],"secondaryName":false,"num":"00","services":["local"],"parents":["s0tV3s"],"children":["Jh3MKo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by langonginc** [comment]
您好，我这边看没有问题，请等候管理员确认并汇入，感谢您的贡献。
