### ISSUE TITLE
拉合尔轨道交通橙线 Lahore Metro Orange Line لاہور میٹرو‎‎

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmg-templates#37]
拉合尔轨道交通
Lahore Metro
لاہور میٹرو‎‎
橙线
ORANGE LINE

[(橙线)拉合尔轨道交通_(ORANGE)Lahore Metro_لاہور میٹرو‎‎.zip](https://github.com/railmapgen/rmg-templates/files/9198882/_.ORANGE.Lahore.Metro_.zip)

**Comment by 52PD** [comment]
您好，首先感谢您对本项目的支持与贡献。

不过考虑到拉合尔轨道交通在本项目中仍然算是新加入的一个轨交系统，故能否请您参考[How to add line templates](https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates)中第五步的内容提交相应所需文件呢，谢谢。

**Comment by Dingdong2334** [comment]
您好，根据步骤内的要求，我写了相关的json文件，想请问下这样写对不对：

[(橙线)拉合尔轨道交通_(ORANGE)Lahore Metro_لاہور میٹرو‎‎.zip](https://github.com/railmapgen/rmg-templates/files/9386650/_.ORANGE.Lahore.Metro_.zip)


` {
     "id": "lahoremetro",
     "name": {
         "en": "Lahore Metro",
         "ur": "لاہور میٹرو",
         "zh-Hans": "拉合尔地铁",
         "zh-Hant": "拉合爾地鐵"
     }
 }
 
 {
    "lahoremetro": [
        {
            "filename": "lhrorange",
            "name": {
                "en": "Orange Line",
                "ur": "اورنج لائن",
                "zh-Hans": "橙线",
                "zh-Hant": "橙線"
            }
        }
    ]
}
`

**Comment by 52PD** [comment]
OK，看起来应该没什么问题了

**Comment by Raupe114514** [comment]
[拉合尔轨道交通橙线.zip](https://github.com/railmapgen/rmg-templates/files/9449419/default.zip)

**Comment by Raupe114514** [comment]
> 您好，首先感谢您对本项目的支持与贡献。
> 
> 不过考虑到拉合尔轨道交通在本项目中仍然算是新加入的一个轨交系统，故能否请您参考[如何添加行模板](https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates)中第五步的内容提交相应所需文件呢，谢谢。

[拉合尔轨道交通橙线.zip](https://github.com/railmapgen/rmg-templates/files/9449421/default.zip)

**Comment by 52PD** [comment]
收到，感谢！
