### ISSUE TITLE
Resources: New templates of East Japan Railway Company

### ISSUE THREAD

**Issue by eason2141** [railmapgen/rmg-templates#371]
Hi RMG team! I would like to contribute the templates below.

**Justification:** I added the company and a new line in JR East, thanks.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="JR East" line="00config"><summary>New company: East Japan Railway Company</summary><details type="name">{"en":"East Japan Railway Company","zh-Hans":" 东日本旅客铁道","zh-Hant":"東日本旅客鐵道","ko":"동일본 여객 철도"}</details></details>

<details repo="rmg-templates" company="JR East" line="JK" major="false"><summary>JR East/JK</summary><details type="name">{"en":"Keihin-Tohoku Line","zh-Hans":"京濱東北線","zh-Hant":"京濱東北線","ko":"게이힌 토호쿠선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":4600,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["tokyo","jk","#1DAED1","#fff"],"line_name":["地鐵線","Metro Line"],"current_stn_idx":"V8nrMr","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["FYa84J"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FYa84J":{"name":["大船","Ōfuna"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["wVeDLg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["横須賀線","Yokosuka Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wVeDLg":{"name":["\t本郷台","Hongōdai"],"secondaryName":false,"num":"02","services":["local"],"parents":["FYa84J"],"children":["cjyO_l"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["V8nrMr"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Z_y9Kw":{"name":["根岸","Negishi"],"secondaryName":false,"num":"14","services":["local"],"parents":["u1nJvB"],"children":["NvM1F7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"u1nJvB":{"name":["磯子","Isogo"],"secondaryName":false,"num":"00","services":["local"],"parents":["1aFnPZ"],"children":["Z_y9Kw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1aFnPZ":{"name":["新杉田\t","Shin-Sugita"],"secondaryName":false,"num":"00","services":["local"],"parents":["gQgZNr"],"children":["u1nJvB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","kk","#00BFFF","#fff"],"name":["京浜本線","Keikyu Main Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gQgZNr":{"name":["洋光台","Yōkōdai"],"secondaryName":false,"num":"00","services":["local"],"parents":["cjyO_l"],"children":["1aFnPZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cjyO_l":{"name":["港南台","Kōnandai\t"],"secondaryName":false,"num":"00","services":["local"],"parents":["wVeDLg"],"children":["gQgZNr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZLDFmm":{"name":["高輪\\ートウェイ","Takannawa Gateway"],"secondaryName":false,"num":"00","services":["local"],"parents":["cqbVO1"],"children":["Vjcwaz"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","a","#ec6e65","#fff"],"name":["都営浅草線","Toei Asakusa Line"]},{"theme":["tokyo","kk","#00BFFF","#fff"],"name":["京急本線","Keikyu Main Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cqbVO1":{"name":["品川","Shinagawa"],"secondaryName":false,"num":"00","services":["local"],"parents":["yD6PH3"],"children":["ZLDFmm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線 ","Yamanote Line"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["other","other","#808080","#fff"],"name":["新幹線","Shinkansen"]},{"theme":["tokyo","kk","#00BFFF","#fff"],"name":["京浜本線","Keikyu Main Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yD6PH3":{"name":["大井町","Ōimachi"],"secondaryName":false,"num":"00","services":["local"],"parents":["3UAxeb"],"children":["cqbVO1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","r","#00418e","#fff"],"name":["りんかい線","Rinkai Line"]},{"theme":["tokyo","om","#F18C43","#fff"],"name":["大井町線","Ōimachi Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3UAxeb":{"name":["大森","Ōmori"],"secondaryName":false,"num":"00","services":["local"],"parents":["XEBHmJ"],"children":["yD6PH3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XEBHmJ":{"name":["\t蒲田","Kamata"],"secondaryName":false,"num":"00","services":["local"],"parents":["G40lL4"],"children":["3UAxeb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","ik","#EE86A8","#fff"],"name":["池上線","Ikegami Line"]},{"theme":["tokyo","tm","#AE0079","#fff"],"name":["多摩川線","Tamagawa Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"G40lL4":{"name":["川崎","Kawasaki"],"secondaryName":false,"num":"00","services":["local"],"parents":["GgNE8D"],"children":["XEBHmJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","jn","#F2D01F","#fff"],"name":["南武線","Nambu Line"]},{"theme":["tokyo","kk","#00BFFF","#fff"],"name":["京浜本線","Keikyu Main Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GgNE8D":{"name":["鶴見","Tsurumi"],"secondaryName":false,"num":"00","services":["local"],"parents":["Xnm421"],"children":["G40lL4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","ji","#F2D01F","#fff"],"name":["鶴見線","Tsurumi Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Xnm421":{"name":["新子安","Shin-Koyasu"],"secondaryName":false,"num":"00","services":["local"],"parents":["jj37F2"],"children":["GgNE8D"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jj37F2":{"name":["東神奈川","Higashi-Kanagawa"],"secondaryName":false,"num":"00","services":["local"],"parents":["dm2B8G"],"children":["Xnm421"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jh","#B1CB39","#fff"],"name":["横浜線","Yokohama Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dm2B8G":{"name":["横浜","Yokohama"],"secondaryName":false,"num":"00","services":["local"],"parents":["n2MXj9"],"children":["jj37F2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","om","#F18C43","#fff"],"name":["東横線","Minatomiral Line"]},{"theme":["tokyo","yb","#2F56A5","#fff"],"name":["京浜本線","Keikyu Main Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"n2MXj9":{"name":["桜木町","Sakuragichō"],"secondaryName":false,"num":"00","services":["local"],"parents":["51idIp"],"children":["dm2B8G"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"51idIp":{"name":["関内","Kannai"],"secondaryName":false,"num":"00","services":["local"],"parents":["NvM1F7"],"children":["n2MXj9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","yb","#2F56A5","#fff"],"name":["ブルー\\ライン","Blue Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NvM1F7":{"name":["石川町","Ishikawachō"],"secondaryName":false,"num":"00","services":["local"],"parents":["Z_y9Kw"],"children":["51idIp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"B6hM5g":{"name":["北浦和","Kita-Urawa"],"secondaryName":false,"num":"00","services":["local"],"parents":["JWFhrH"],"children":["HvjkB1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-b2g5B":{"name":["日暮里","Nippori"],"secondaryName":false,"num":"00","services":["local"],"parents":["SnREPU"],"children":["2krWzG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","jj","#1DAF7E","#fff"],"name":["常磐線（快速）","Joban Line (Rapid)"]},{"theme":["tokyo","ks","#005AAA","#fff"],"name":["京成本線","Keisei Main Line"]},{"theme":["tokyo","nt","#D53A77","#fff"],"name":["日暮里・舎人ライナー","Nippori-toneri Liner"]}]}],"tick_direc":"l","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SnREPU":{"name":["\t鶯谷","Uguisudani"],"secondaryName":false,"num":"00","services":["local"],"parents":["eex0RF"],"children":["-b2g5B"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eex0RF":{"name":["上野","Ueno"],"secondaryName":false,"num":"00","services":["local"],"parents":["mWDIow"],"children":["SnREPU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["宇都宮線","Utsunomiya Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["高崎線","Takasaki Line"]},{"theme":["tokyo","jj","#1DAF7E","#fff"],"name":["常磐線（快速）","Joban Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["上野東京ライン","Ueno-Tokyo Line"]},{"theme":["tokyo","g","#ff9500","#fff"],"name":["銀座線","Ginza Line"]},{"theme":["tokyo","h","#b5b5ac","#fff"],"name":["日比谷線","Hibiya Line"]}]},{"lines":[{"theme":["tokyo","ks","#005AAA","#fff"],"name":["京成本線","Keisei Main Line"]}],"name":["京成上野","Keisei Ueno"]}],"tick_direc":"l","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mWDIow":{"name":["御徒町","Okachimachi"],"secondaryName":false,"num":"00","services":["local"],"parents":["nuPIYP"],"children":["eex0RF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]}]},{"lines":[{"theme":["tokyo","o","#ce045b","#fff"],"name":["都営大江戸線","Toei Oedo Line"]},{"theme":["tokyo","g","#ff9500","#fff"],"name":["銀座線","Toei Oedo Line"]},{"theme":["tokyo","h","#b5b5ac","#fff"],"name":["日比谷線","Toei Oedo Line"]}],"name":["上野御徒町","Ueno-okachimachi"]},{"lines":[],"name":["",""]}],"tick_direc":"l","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nuPIYP":{"name":["\t秋葉原","Akihabara"],"secondaryName":false,"num":"00","services":["local"],"parents":["Rf8ur9"],"children":["mWDIow"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","jb","#F2D01F","#fff"],"name":["総武線（各駅停車）","Sōbu Line (Local)"]},{"theme":["tokyo","h","#b5b5ac","#fff"],"name":["日比谷線","Hibiya Line"]},{"theme":["tokyo","s","#b0bf1e","#fff"],"name":["都営新宿線","Toei Shinjuku Line"]},{"theme":["tokyo","mg","#009CD3","#fff"],"name":["つくばエクスプレス ","Tsukuba Express"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Rf8ur9":{"name":["神田","Kanda"],"secondaryName":false,"num":"00","services":["local"],"parents":["5cYW6h"],"children":["nuPIYP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","g","#ff9500","#fff"],"name":["銀座線","Ginza Line"]},{"theme":["tokyo","jc","#DD6935","#fff"],"name":["中央線 (快速)","Chūō Line (Rapid)"]},{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5cYW6h":{"name":["東京","Tōkyō"],"secondaryName":false,"num":"00","services":["local"],"parents":["lOE1xx"],"children":["Rf8ur9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線"," Tōkaidō Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["上野東京ライン","Ueno-Tōkyō Line"]},{"theme":["tokyo","jc","#DD6935","#fff"],"name":["中央線 (快速) ","Chūō Line (Rapid)"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["総武線（快速）"," Sōbu Line (Rapid)"]},{"theme":["tokyo","je","#D01827","#fff"],"name":["京葉線","Keiyō Line"]}]},{"lines":[{"theme":["tokyo","m","#f62e36","#fff"],"name":["丸ノ内線","Marunochi Line"]},{"theme":["tokyo","t","#009bbf","#fff"],"name":["東西線","Tozai Line"]},{"theme":["tokyo","c","#00bb85","#fff"],"name":["千代田線","Chiyoda Line"]},{"theme":["tokyo","z","#8f76d6","#fff"],"name":["半蔵門線","Hanzōmon Line"]},{"theme":["tokyo","i","#006ab8","#fff"],"name":["都営三田線","Toei Mito Line"]}],"name":["大手町","Ōtemachi"]}],"tick_direc":"r","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lOE1xx":{"name":["有楽町","Yūrakuchō"],"secondaryName":false,"num":"00","services":["local"],"parents":["XWaY5P"],"children":["5cYW6h"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","y","#c1a470","#fff"],"name":["有楽町線","Yūrakuchō Line"]}]},{"lines":[{"theme":["tokyo","c","#00bb85","#fff"],"name":["千代田線","Chiyoda Line"]},{"theme":["tokyo","h","#b5b5ac","#fff"],"name":["日比谷線","Hibiya Line"]},{"theme":["tokyo","i","#006ab8","#fff"],"name":["都営三田線","Toei Mito Line"]}],"name":["日比谷","Hibiya"]}],"tick_direc":"l","paid_area":false},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XWaY5P":{"name":["新橋","Shimbashi"],"secondaryName":false,"num":"00","services":["local"],"parents":["exuKD-"],"children":["lOE1xx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jt","#F0862B","#fff"],"name":["東海道線","Tōkaidō Line"]},{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","jo","#1069B4","#fff"],"name":["横須賀線","Yokosuka Line"]},{"theme":["tokyo","g","#ff9500","#fff"],"name":["銀座線","Ginza Line"]},{"theme":["tokyo","a","#ec6e65","#fff"],"name":["都営浅草線","Toei Asakusa Line"]},{"theme":["tokyo","u","#1662B8","#fff"],"name":["臨海線","Rinkai Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"exuKD-":{"name":["浜松町","Hamamatsuchō"],"secondaryName":false,"num":"00","services":["local"],"parents":["Vjcwaz"],"children":["XWaY5P"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","mo","#26326A","#fff"],"name":["東京モノレール","Tokyo Monorail"]},{"theme":["tokyo","a","#ec6e65","#fff"],"name":["都営浅草線","Toei Asakusa Line"]},{"theme":["tokyo","o","#ce045b","#fff"],"name":["都営大江戸線","Toei Oedo Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Vjcwaz":{"name":["田町","Tamachi"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZLDFmm"],"children":["exuKD-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]},{"theme":["tokyo","a","#ec6e65","#fff"],"name":["都営浅草線","Yamanote Line"]},{"theme":["tokyo","i","#006ab8","#fff"],"name":["都営三田線","Yamanote Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JWFhrH":{"name":["\t浦和","Urawa"],"secondaryName":false,"num":"00","services":["local"],"parents":["z-8L8W"],"children":["B6hM5g"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"z-8L8W":{"name":["南浦和","Minami-Urawa"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZJ2DcG"],"children":["JWFhrH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jm","#EB5A28","#fff"],"name":["武蔵野線","Musashino Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZJ2DcG":{"name":["蕨","Warabi"],"secondaryName":false,"num":"00","services":["local"],"parents":["zohOfN"],"children":["z-8L8W"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zohOfN":{"name":["西川口","Nishi-Kawaguchi"],"secondaryName":false,"num":"00","services":["local"],"parents":["7kovNF"],"children":["ZJ2DcG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7kovNF":{"name":["川口","Kawaguchi"],"secondaryName":false,"num":"00","services":["local"],"parents":["P-Ty2i"],"children":["zohOfN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"P-Ty2i":{"name":["赤羽","Akabane"],"secondaryName":false,"num":"00","services":["local"],"parents":["cj6Jl1"],"children":["7kovNF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","ju","#F18E41","#fff"],"name":["高崎線","Takasaki Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["宇都宮線","Utsunomiya Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ja","#14A676","#fff"],"name":["埼京線"," Saikyō Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cj6Jl1":{"name":["東十条","Higashi-Jūjō"],"secondaryName":false,"num":"00","services":["local"],"parents":["nug0uR"],"children":["P-Ty2i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nug0uR":{"name":["王子","Ōji"],"secondaryName":false,"num":"00","services":["local"],"parents":["-b-IT0"],"children":["cj6Jl1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-b-IT0":{"name":["上中里","Kami-Nakazato"],"secondaryName":false,"num":"00","services":["local"],"parents":["gROTTD"],"children":["nug0uR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gROTTD":{"name":["\t田端","Tabata"],"secondaryName":false,"num":"00","services":["local"],"parents":["2krWzG"],"children":["-b-IT0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"2krWzG":{"name":["西日暮里\t","Nishi-Nippori"],"secondaryName":false,"num":"00","services":["local"],"parents":["-b2g5B"],"children":["gROTTD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","jy","#B1CB39","#fff"],"name":["山手線","Yamanote Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"V8nrMr":{"name":["大宮","Ōmiya"],"secondaryName":false,"num":"00","services":["local"],"parents":["NPIcPP"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","ju","#F18E41","#fff"],"name":["宇都宮線","Utsunomiya Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["高崎線","Takasaki Line"]},{"theme":["tokyo","js","#DB2027","#fff"],"name":["湘南新宿ライン","Shōnan-Shinjuku Line"]},{"theme":["tokyo","ja","#14A676","#fff"],"name":["埼京線","Saikyō Line"]},{"theme":["tokyo","td","#40B4E5","#fff"],"name":["東武アーバンパークライン","Tobu Urban Park Line Ina Line (New Shuttle)"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NPIcPP":{"name":["さいたま新都心","Saitama-Shintoshin"],"secondaryName":false,"num":"00","services":["local"],"parents":["HvjkB1"],"children":["V8nrMr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["tokyo","ju","#F18E41","#fff"],"name":["宇都宮線","Utsunomiya Line"]},{"theme":["tokyo","ju","#F18E41","#fff"],"name":["高崎線","Takasaki Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HvjkB1":{"name":["与野","Yono"],"secondaryName":false,"num":"00","services":["local"],"parents":["B6hM5g"],"children":["NPIcPP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

1. 如下图，您所提交的模版中线路名称并不是京滨东北线（Keihin-Tohoku Line）。
   ![Screenshot 2023-07-20 at 10 58 06 PM](https://github.com/railmapgen/rmg-templates/assets/98044618/032585ce-20ae-4131-8a90-bf8ca6b82c5c)
2. 高轮Gateway站的日文名称（高輪ートウェイ）错写成了“高輪\ートウェイ”。
3. 线路后半段（根岸线）中位于石川町站和根岸站之间的山手站缺失。
4. 大部分车站的换乘线路都不完整（其中上野东京线缺失的问题极为严重）。
5. 如下面的内容，在您提交的Issue名称中，本线路的简体中文名区域填写的仍然为繁体名称。
   > {"en":"Keihin-Tohoku Line","zh-Hans":"京濱東北線","zh-Hant":"京濱東北線","ko":"게이힌 토호쿠선"}

由于上面提及的内容中，第3-5点为严重问题，因此在修复上述问题后，请重新打开一个新的Issue提交，并在新Issue中附上本Issue的编号，谢谢。
