### ISSUE TITLE
【资源】【线路】宁波轨道交通

### ISSUE THREAD

**Issue by feitongxiaok** [railmapgen/rmg-templates#38]
{
"id": "nbrt",
"name": {
"en": "Ningbo Rail Transit ”,
"zh-Hans": "宁波轨道交通",
"zh-Hant": "寜波軌道交通"
}
}
{
"nbrt": [
{
"filename": "nbrt1",
"name": {
"en": "Line 1",
"zh-Hans": "1号线",
"zh-Hant": "1號線"
}
},
{
"filename": "nbrt2",
"name": {
"en": "Line 2”,
"zh-Hans": "2号线",
"zh-Hant": "2號線"
}
},
{
{
"filename": "nbrt3",
"name": {
"en": "Line 3/Ningbo-Fenghua Intercity Railway",
"zh-Hans": "3号线/宁奉城际",
"zh-Hant": "3號線/寜奉城際"
}
},
{
"filename": "nbrt4",
"name": {
"en": "Line 4",
"zh-Hans": "4号线",
"zh-Hant": "4號線"
}
},
{
{
"filename": "nbrt5",
"name": {
"en":"Line 5"
"zh-Hans": "5号线",
"zh-Hant": "5號線"
}
},
{
]
}

**Comment by feitongxiaok** [comment]
[Uploading nbrt.zip…]()

**Comment by feitongxiaok** [comment]
呃，文件忘传了，补一下
[Uploading nbrt.zip…]()

**Comment by Dingdong2334** [comment]
> 呃，文件忘传了，补一下 Uploading nbrt.zip…

我不是团队成员，但是您这个文件是没有传完的，别人是下载不了的😂拖文件到框内后直接发送，文件是传不上去的。您要等一会儿，当文件显示上传成功（文字框下方提示），就可以提交了

**Comment by feitongxiaok** [comment]
感谢3楼的提醒，我现在重新上传一下文件。文件中我新增了一条宁绍城际，虽然使用了国铁的制式，但我觉得可以同时融入甬、绍两地的地铁系统。信息如下：
          "fliename":"nbrt宁绍"
           "name":(
           "en":"Ningbo-Shaoxing Intercity Raliway"
           "zh-Hans":"宁绍城际"
           "zh-Hant":"寜紹城際"
如有错误请指出，感谢！
[nbrt.zip](https://github.com/railmapgen/rmg-templates/files/9237673/nbrt.zip)

**Comment by Dingdong2334** [comment]
> 感谢3楼的提醒

😁

**Comment by thekingofcity** [comment]
嗨，感谢您对于项目的支持与贡献。新模板已经被加入资源库中，您稍后可以在宁波地铁中看到并选择它。不过宁绍城际未合入，目前我们暂不考虑跨地区间的国铁线路，即使可能已经到达公交化密度。
