### ISSUE TITLE
Resources: New templates of Wuhan Metro

### ISSUE THREAD

**Issue by s1s1s1s1s1s** [railmapgen/rmg-templates#381]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 2

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="wh2" major="false"><summary>whrt/wh2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線","ko":"라인 2"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":1200,"railmap":3000,"indoor":1200},"svg_height":300,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["wuhan","wh2","#EB7CAF","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"bBGOwx","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["t5_mVQ"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"JM4pQu":{"name":["宏图大道","Hongtu Boulevard"],"secondaryName":false,"num":"06","services":["local"],"parents":["wERvZ1"],"children":["CmFZC6"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh3","#D9B966","#fff"],"name":["3号线","Line 3"]},{"theme":["wuhan","wh8","#98ACAB","#fff"],"name":["8号线","Line 8"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"CmFZC6":{"name":["盘龙城","Panlongcheng"],"secondaryName":false,"num":"05","services":["local"],"parents":["JM4pQu"],"children":["Nrtkgj"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["bBGOwx"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"t5_mVQ":{"name":["佛祖岭","Fozuling"],"secondaryName":false,"num":"38","services":["local"],"parents":["linestart"],"children":["UVxJ6w"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"wbkTPj":{"name":["宝通寺","Baotong Temple"],"secondaryName":false,"num":"23","services":["local"],"parents":["tLbQD9"],"children":["F9tPHg"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"F9tPHg":{"name":["中南路","Zhongnan Road"],"secondaryName":false,"num":"22","services":["local"],"parents":["wbkTPj"],"children":["kGUFNW"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh4","#8EC720","#fff"],"name":["4号线","Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"kGUFNW":{"name":["洪山广场","Hongshan Square"],"secondaryName":false,"num":"21","services":["local"],"parents":["F9tPHg"],"children":["q4xBNp"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh4","#8EC720","#fff"],"name":["4号线","Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"q4xBNp":{"name":["小龟山","Xiaoguishan"],"secondaryName":false,"num":"20","services":["local"],"parents":["kGUFNW"],"children":["YDMo1u"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"YDMo1u":{"name":["螃蟹岬","Pangxiejia"],"secondaryName":false,"num":"19","services":["local"],"parents":["q4xBNp"],"children":["Rsw2eo"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh7","#EB7900","#fff"],"name":["7号线","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"Rsw2eo":{"name":["积玉桥","Jiyuqiao"],"secondaryName":false,"num":"18","services":["local"],"parents":["YDMo1u"],"children":["KYuFE9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh5","#E63F00","#fff"],"name":["5号线","Line 5"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"KYuFE9":{"name":["江汉路","Jianghan Road"],"secondaryName":false,"num":"17","services":["local"],"parents":["Rsw2eo"],"children":["xsQQXB"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh6","#008536","#fff"],"name":["6号线","Line 6"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"xsQQXB":{"name":["循礼门","Xunlimen"],"secondaryName":false,"num":"16","services":["local"],"parents":["KYuFE9"],"children":["omAxqz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh1","#3D84C6","#fff"],"name":["1号线","Line 1"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"omAxqz":{"name":["中山公园","Zhongshan Park"],"secondaryName":false,"num":"15","services":["local"],"parents":["xsQQXB"],"children":["9w51Ve"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"9w51Ve":{"name":["青年路","Qingnian Road"],"secondaryName":false,"num":"14","services":["local"],"parents":["omAxqz"],"children":["7AX4x7"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"7AX4x7":{"name":["王家墩东","Wangjiadun East"],"secondaryName":false,"num":"13","services":["local"],"parents":["9w51Ve"],"children":["T5VNLS"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh7","#EB7900","#fff"],"name":["7号线","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"T5VNLS":{"name":["范湖","Fanhu"],"secondaryName":false,"num":"12","services":["local"],"parents":["7AX4x7"],"children":["DNlpMK"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh3","#D9B966","#fff"],"name":["3号线","Line 3"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"DNlpMK":{"name":["汉口火车站","Hankou Railway Station"],"secondaryName":false,"num":"11","services":["local"],"parents":["T5VNLS"],"children":["6onHe_"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"fNQiDx":{"name":["常青花园","Changqing Huayuan"],"secondaryName":false,"num":"09","services":["local"],"parents":["6onHe_"],"children":["QUNfxA"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh6","#008536","#fff"],"name":["6号线","Line 6"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"QUNfxA":{"name":["金银潭","Jinyintan"],"secondaryName":false,"num":"08","services":["local"],"parents":["fNQiDx"],"children":["wERvZ1"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"wERvZ1":{"name":["常青城","Changqingcheng"],"secondaryName":false,"num":"07","services":["local"],"parents":["QUNfxA"],"children":["JM4pQu"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"UVxJ6w":{"name":["藏龙东街","Canglong East Street"],"secondaryName":false,"num":"37","services":["local"],"parents":["t5_mVQ"],"children":["kROexz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"kROexz":{"name":["秀湖","Xiuhu"],"secondaryName":false,"num":"36","services":["local"],"parents":["UVxJ6w"],"children":["pCwPMn"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"pCwPMn":{"name":["金融港北","Jinronggang North"],"secondaryName":false,"num":"35","services":["local"],"parents":["kROexz"],"children":["qc57j3"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"qc57j3":{"name":["黄龙山路","Huanglongshan Road"],"secondaryName":false,"num":"34","services":["local"],"parents":["pCwPMn"],"children":["EzJSgC"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"EzJSgC":{"name":["武汉东站","Wuhandong Railway Station"],"secondaryName":false,"num":"33","services":["local"],"parents":["qc57j3"],"children":["vHJyqk"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh11","#F2CF01","#fff"],"name":["11号线","Line 11"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"vHJyqk":{"name":["佳园路","Jiayuan Road"],"secondaryName":false,"num":"32","services":["local"],"parents":["EzJSgC"],"children":["ZATm8r"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"ZATm8r":{"name":["光谷大道","Guanggu Boulevard"],"secondaryName":false,"num":"31","services":["local"],"parents":["vHJyqk"],"children":["6PDRxq"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"6PDRxq":{"name":["华中科技大学","Huazhong University of Sci.&amp;Tech."],"secondaryName":false,"num":"30","services":["local"],"parents":["ZATm8r"],"children":["0um3Eq"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"0um3Eq":{"name":["珞雄路","Luoxiong Road"],"secondaryName":false,"num":"29","services":["local"],"parents":["6PDRxq"],"children":["EBS3Kx"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"EBS3Kx":{"name":["光谷广场","Optics Valley Square"],"secondaryName":false,"num":"28","services":["local"],"parents":["0um3Eq"],"children":["Y18CA_"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"Y18CA_":{"name":["杨家湾","Yangjiawan"],"secondaryName":false,"num":"27","services":["local"],"parents":["EBS3Kx"],"children":["nqIQtc"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"nqIQtc":{"name":["虎泉","Huquan"],"secondaryName":false,"num":"26","services":["local"],"parents":["Y18CA_"],"children":["2e3dux"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"2e3dux":{"name":["广埠屯","Guangbutun"],"secondaryName":false,"num":"25","services":["local"],"parents":["nqIQtc"],"children":["tLbQD9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"tLbQD9":{"name":["街道口","Jiedaokou"],"secondaryName":false,"num":"24","services":["local"],"parents":["2e3dux"],"children":["wbkTPj"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh8","#98ACAB","#fff"],"name":["8号线","Line 8"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"6onHe_":{"name":["长港路","Changgang Road"],"secondaryName":false,"num":"10","services":["local"],"parents":["DNlpMK"],"children":["fNQiDx"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"bBGOwx":{"name":["天河机场","Tianhe International Airport"],"secondaryName":false,"num":"01","services":["local"],"parents":["apd6Dt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"apd6Dt":{"name":["航空总部","Hangkongzongbu"],"secondaryName":false,"num":"02","services":["local"],"parents":["jAzHws"],"children":["bBGOwx"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"jAzHws":{"name":["宋家岗","Songjiagang"],"secondaryName":false,"num":"03","services":["local"],"parents":["Nrtkgj"],"children":["apd6Dt"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275},"Nrtkgj":{"name":["巨龙大道","Julong Boulevard"],"secondaryName":false,"num":"04","services":["local"],"parents":["CmFZC6"],"children":["jAzHws"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuhan","wh7","#EB7900","#fff"],"name":["7号线","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":275}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"2","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by langonginc** [comment]
您好，为这边看没有问题，请等待管理员最终确认并汇入，感谢您的贡献。
