### ISSUE TITLE
Resources: New templates of Lanzhou Rail Transit

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-templates#390]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 增加兰州地铁1号线模版

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="lzgdjt" line="00config"><summary>New company: Lanzhou Rail Transit</summary><details type="name">{"en":"Lanzhou Rail Transit","zh-Hans":"兰州轨道交通","zh-Hant":"蘭州軌道交通","ko":"란저우 궤도교통","ja":"蘭州軌道交通"}</details></details>

<details repo="rmg-templates" company="lzgdjt" line="lz1" major="false"><summary>lzgdjt/lz1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선","ja":"1号線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1500},"svg_height":350,"style":"shmetro","y_pc":50,"padding":4,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["lanzhou","lz1","#0080bc","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"qYisbX","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["CFGqP0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CFGqP0":{"name":["陈官营","Chenguanying"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["POhrQD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"qYisbX":{"name":["东岗","Donggang"],"secondaryName":false,"num":"02","services":["local"],"parents":["zdvYDJ"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["qYisbX"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"POhrQD":{"name":["深安大桥南","South Shen'an Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["CFGqP0"],"children":["SfKzmR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"SfKzmR":{"name":["兰州城市学院（省科技馆）","Lanzhou City University\\ (Gansu Science &amp; Technology Museum)"],"secondaryName":false,"num":"00","services":["local"],"parents":["POhrQD"],"children":["FRNvsd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"FRNvsd":{"name":["兰州海关","Lanzhou Customs"],"secondaryName":false,"num":"00","services":["local"],"parents":["SfKzmR"],"children":["7V_BjC"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"7V_BjC":{"name":["马滩","Matan"],"secondaryName":false,"num":"00","services":["local"],"parents":["FRNvsd"],"children":["hOvAJJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"hOvAJJ":{"name":["土门墩","Tumendun"],"secondaryName":false,"num":"00","services":["local"],"parents":["7V_BjC"],"children":["I47zqz"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"I47zqz":{"name":["兰州西站北广场","North Square of Lanzhou \\West Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["hOvAJJ"],"children":["8iO0_Z"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355},"8iO0_Z":{"name":["西站什字","Xizhanshizi"],"secondaryName":false,"num":"00","services":["local"],"parents":["I47zqz"],"children":["k3MWGV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"k3MWGV":{"name":["七里河","Qilihe"],"secondaryName":false,"num":"00","services":["local"],"parents":["8iO0_Z"],"children":["R30IFm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"R30IFm":{"name":["小西湖","Xiaoxihu Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["k3MWGV"],"children":["t5lBms"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"t5lBms":{"name":["文化宫","Cultural Palace"],"secondaryName":false,"num":"00","services":["local"],"parents":["R30IFm"],"children":["gTL6kb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"gTL6kb":{"name":["西关","Xiguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["t5lBms"],"children":["Agc7KR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"Agc7KR":{"name":["省政府","Gansu Provincial Government"],"secondaryName":false,"num":"00","services":["local"],"parents":["gTL6kb"],"children":["-CU_iZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"-CU_iZ":{"name":["东方红广场","Dongfanghong Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["Agc7KR"],"children":["C7YOZT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"C7YOZT":{"name":["兰州大学","Lanzhou University"],"secondaryName":false,"num":"00","services":["local"],"parents":["-CU_iZ"],"children":["lyz04X"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"lyz04X":{"name":["五里铺","Wulipu"],"secondaryName":false,"num":"00","services":["local"],"parents":["C7YOZT"],"children":["HLwyVD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"HLwyVD":{"name":["省气象局","Gansu Meteorological Bureau"],"secondaryName":false,"num":"00","services":["local"],"parents":["lyz04X"],"children":["h7wRzZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"h7wRzZ":{"name":["拱星墩","Gongxingdun"],"secondaryName":false,"num":"00","services":["local"],"parents":["HLwyVD"],"children":["zdvYDJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"zdvYDJ":{"name":["焦家湾","Jiaojiawan"],"secondaryName":false,"num":"00","services":["local"],"parents":["h7wRzZ"],"children":["qYisbX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您提交的模板包括但不限于以下问题：

- 陈官营站、深安大桥南站、马滩站、土门墩站、西站什字站、七里河站、小西湖站、西关站、东方红广场站、五里铺站、拱星墩站、焦家湾站、东岗站英文站名错误（根据兰州地铁线路图和屏蔽门盖板，兰州地铁英文名为音译车站的英文线路名应当为全大写无空格拼音）

_（如您有异议，请在评论区留下您的证明来源）_

考虑到上述问题并非严重问题，您可以在修正后将修改的代码直接提交到本issue下，我们的审核员在检查确认无问题后会将修正的内容汇入到项目中。

**Comment by 28yfang** [comment]
兰州2号线马上就要通车了，我等开通之后再重新发一个带兰州2号线的新issue吧。这个问题会改的

**Comment by 28yfang** [comment]
请关闭 #391
