### ISSUE TITLE
Resources: New templates of Wuhan Metro

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmg-templates#397]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 9

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="wh11" major="false"><summary>whrt/wh11</summary><details type="name">{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}</details><details type="param">{"svgWidth":{"destination":2200,"runin":2200,"railmap":2200,"indoor":2200},"svg_height":500,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["wuhan","wh11","#F2CF01","#fff"],"line_name":["11号线","Line 11"],"current_stn_idx":"28I8_m","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["NG2Cl0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NG2Cl0":{"name":["武汉东站","Wuhan East Railway Station"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["t880Fs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh2","#EB7CAF","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"28I8_m":{"name":["葛店南站","Gedian South Railway Station"],"secondaryName":false,"num":"02","services":["local"],"parents":["z8qFMw"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["28I8_m"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"t880Fs":{"name":["湖口","Hukou"],"secondaryName":false,"num":"00","services":["local"],"parents":["NG2Cl0"],"children":["6VMu-D"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6VMu-D":{"name":["光谷同济医院","Tongji Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["t880Fs"],"children":["pBjyT_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pBjyT_":{"name":["光谷生物园","Guanggushengwuyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["6VMu-D"],"children":["L14rJy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"L14rJy":{"name":["光谷四路","Guanggu 4th Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["pBjyT_"],"children":["1FcisE"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1FcisE":{"name":["光谷五路","Guanggu 5th Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["L14rJy"],"children":["q0dMoA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"q0dMoA":{"name":["光谷六路","Guanggu 6th Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["1FcisE"],"children":["FCc9O-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FCc9O-":{"name":["豹澥","Baoxie"],"secondaryName":false,"num":"00","services":["local"],"parents":["q0dMoA"],"children":["0mAYP3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0mAYP3":{"name":["光谷七路","Guanggu 7th Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["FCc9O-"],"children":["oYZ-Dp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"oYZ-Dp":{"name":["长岭山","Changlingshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["0mAYP3"],"children":["KjGQf8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KjGQf8":{"name":["未来一路","Weilai 1st Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["oYZ-Dp"],"children":["mL0-d5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mL0-d5":{"name":["未来三路","Weilai 3rd Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["KjGQf8"],"children":["z8qFMw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"z8qFMw":{"name":["左岭","Zuoling"],"secondaryName":false,"num":"00","services":["local"],"parents":["mL0-d5"],"children":["28I8_m"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="whrt" line="wh8" major="false"><summary>whrt/wh8</summary><details type="name">{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}</details><details type="param">{"svgWidth":{"destination":2200,"runin":2200,"railmap":2200,"indoor":2200},"svg_height":500,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["wuhan","wh8","#98ACAB","#fff"],"line_name":["8号线","Line 8"],"current_stn_idx":"Jk_E3f","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["S-4lUK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"S-4lUK":{"name":["金潭路","Jintan Road"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["QKA5nH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Jk_E3f":{"name":["军运村","Military Athletes’Village"],"secondaryName":false,"num":"02","services":["local"],"parents":["SHAnAQ"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Jk_E3f"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QKA5nH":{"name":["宏图大道","Hongtu Boulevard"],"secondaryName":false,"num":"00","services":["local"],"parents":["S-4lUK"],"children":["iyOU1U"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh2","#EB7CAF","#fff"],"name":["2号线","Line 2"]},{"theme":["wuhan","wh3","#D9B966","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iyOU1U":{"name":["塔子湖","Tazihu"],"secondaryName":false,"num":"00","services":["local"],"parents":["QKA5nH"],"children":["dRoZlv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dRoZlv":{"name":["中一路","Zhongyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["iyOU1U"],"children":["trLK2C"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"trLK2C":{"name":["竹叶山","Zhuyeshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["dRoZlv"],"children":["XvPabw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XvPabw":{"name":["赵家条","Zhaojiatiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["trLK2C"],"children":["B4gDp4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh3","#D9B966","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"B4gDp4":{"name":["黄浦路","Huangpu Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["XvPabw"],"children":["INzdMg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh1","#3D84C6","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"INzdMg":{"name":["徐家棚","Xujiapeng"],"secondaryName":false,"num":"00","services":["local"],"parents":["B4gDp4"],"children":["SU6hXf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh5","#a62e37","#fff"],"name":["5号线","Line 5"]},{"theme":["wuhan","wh7","#EB7900","#fff"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SU6hXf":{"name":["徐东","Xudong"],"secondaryName":false,"num":"00","services":["local"],"parents":["INzdMg"],"children":["DD0vHA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DD0vHA":{"name":["汪家墩","Wangjiadun"],"secondaryName":false,"num":"00","services":["local"],"parents":["SU6hXf"],"children":["lt-lLd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lt-lLd":{"name":["岳家嘴","Yuejiazui"],"secondaryName":false,"num":"00","services":["local"],"parents":["DD0vHA"],"children":["wk39Yt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh4","#8EC720","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wk39Yt":{"name":["梨园","Liyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["lt-lLd"],"children":["_KAg4J"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_KAg4J":{"name":["省博湖北日报","Hubei Museum &amp; Hubei Daily"],"secondaryName":false,"num":"00","services":["local"],"parents":["wk39Yt"],"children":["phD65l"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"phD65l":{"name":["中南医院","Zhongnan Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["_KAg4J"],"children":["EmEe8c"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EmEe8c":{"name":["水果湖","Shuiguohu"],"secondaryName":false,"num":"00","services":["local"],"parents":["phD65l"],"children":["Z-I9ff"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Z-I9ff":{"name":["洪山路","Hongshan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EmEe8c"],"children":["L8IWjG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"L8IWjG":{"name":["小洪山","Xiaohongshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["Z-I9ff"],"children":["hUzbK8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hUzbK8":{"name":["街道口","Jiedaokou"],"secondaryName":false,"num":"00","services":["local"],"parents":["L8IWjG"],"children":["08OcqT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh2","#EB7CAF","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"08OcqT":{"name":["马房山","Mafangshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["hUzbK8"],"children":["7m0AK9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7m0AK9":{"name":["文治街","Wenzhi Street"],"secondaryName":false,"num":"00","services":["local"],"parents":["08OcqT"],"children":["7s3lJB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7s3lJB":{"name":["文昌路","Wenchang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["7m0AK9"],"children":["TQT8jl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"TQT8jl":{"name":["省农科院","Hubei Academy of Agricultural Sciences"],"secondaryName":false,"num":"00","services":["local"],"parents":["7s3lJB"],"children":["0pctPe"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0pctPe":{"name":["马湖","Mahu"],"secondaryName":false,"num":"00","services":["local"],"parents":["TQT8jl"],"children":["bg1vfG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bg1vfG":{"name":["野芷湖","Yezhihu"],"secondaryName":false,"num":"00","services":["local"],"parents":["0pctPe"],"children":["SHAnAQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh7","#EB7900","#fff"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SHAnAQ":{"name":["黄家湖地铁小镇","Huangjiahu Ditiexiaozhen"],"secondaryName":false,"num":"00","services":["local"],"parents":["bg1vfG"],"children":["Jk_E3f"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="whrt" line="wh16" major="false"><summary>whrt/wh16</summary><details type="name">{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":500,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["wuhan","wh16","#CC0256","#fff"],"line_name":["16号线","Line 16"],"current_stn_idx":"ANAxL8","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["3y9Uxf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3y9Uxf":{"name":["国博中心南","Sorth Interational Expo Center"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["He0uKg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh6","#008536","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ANAxL8":{"name":["通航机场","Tonghang General Airport"],"secondaryName":false,"num":"02","services":["local"],"parents":["9JVmCS"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["ANAxL8"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9JVmCS":{"name":["纱帽","Shamao"],"secondaryName":false,"num":"00","services":["local"],"parents":["yaVRAM"],"children":["ANAxL8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"He0uKg":{"name":["老关村","Laoguancun"],"secondaryName":false,"num":"00","services":["local"],"parents":["3y9Uxf"],"children":["imRHl4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh6","#008536","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"imRHl4":{"name":["南太子湖","South Taizihu"],"secondaryName":false,"num":"00","services":["local"],"parents":["He0uKg"],"children":["CApMSl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CApMSl":{"name":["沌口","Zhuankou"],"secondaryName":false,"num":"00","services":["local"],"parents":["imRHl4"],"children":["gyPyL-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gyPyL-":{"name":["小军山","Xiaojunshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["CApMSl"],"children":["qKnYxS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qKnYxS":{"name":["枫林","Fenglin"],"secondaryName":false,"num":"00","services":["local"],"parents":["gyPyL-"],"children":["jbDsB6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jbDsB6":{"name":["大军山","Dajunshan"],"secondaryName":false,"num":"00","services":["local"],"parents":["qKnYxS"],"children":["iOsLRZ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iOsLRZ":{"name":["桂子湖","Guizihu"],"secondaryName":false,"num":"00","services":["local"],"parents":["jbDsB6"],"children":["0DeTnr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0DeTnr":{"name":["马影河","Mayinghe"],"secondaryName":false,"num":"00","services":["local"],"parents":["iOsLRZ"],"children":["0N_Kg3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0N_Kg3":{"name":["协子河","Xiezihe"],"secondaryName":false,"num":"00","services":["local"],"parents":["0DeTnr"],"children":["-k0dID"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-k0dID":{"name":["湾湖","Wanhu"],"secondaryName":false,"num":"00","services":["local"],"parents":["0N_Kg3"],"children":["yaVRAM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yaVRAM":{"name":["周家河","Zhoujiahe"],"secondaryName":false,"num":"00","services":["local"],"parents":["-k0dID"],"children":["9JVmCS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="whrt" line="wh21" major="false"><summary>whrt/wh21</summary><details type="name">{"en":"Line 21","zh-Hans":"21号线","zh-Hant":"21號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":500,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["wuhan","wh21","#CF0192","#fff"],"line_name":["阳逻线","Yangluo Line"],"current_stn_idx":"JkGjZF","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["JiDDNW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JiDDNW":{"name":["后湖大道","Houhu Boulevard"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["SSPw-X"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh3","#D9B966","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JkGjZF":{"name":["金台","Jintai"],"secondaryName":false,"num":"02","services":["local"],"parents":["QK4qLx"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["JkGjZF"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SSPw-X":{"name":["百步亭花园路","Baibutinghuayuan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["JiDDNW"],"children":["orfeDW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"orfeDW":{"name":["新荣","Xinrong"],"secondaryName":false,"num":"00","services":["local"],"parents":["SSPw-X"],"children":["kuWYWx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["wuhan","wh1","#3D84C6","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kuWYWx":{"name":["幸福湾","Xingfuwan"],"secondaryName":false,"num":"00","services":["local"],"parents":["orfeDW"],"children":["Gtxr3N"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Gtxr3N":{"name":["朱家河","Zhujiahe"],"secondaryName":false,"num":"00","services":["local"],"parents":["kuWYWx"],"children":["GPkgVw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GPkgVw":{"name":["谌家矶","Shenjiaji"],"secondaryName":false,"num":"00","services":["local"],"parents":["Gtxr3N"],"children":["7fsoBQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7fsoBQ":{"name":["青龙","Qinglong"],"secondaryName":false,"num":"00","services":["local"],"parents":["GPkgVw"],"children":["w2M77B"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"w2M77B":{"name":["高车","Gaoche"],"secondaryName":false,"num":"00","services":["local"],"parents":["7fsoBQ"],"children":["7lQwiY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7lQwiY":{"name":["武湖","Wuhu"],"secondaryName":false,"num":"00","services":["local"],"parents":["w2M77B"],"children":["gWL0Rq"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gWL0Rq":{"name":["沙口","Shakou"],"secondaryName":false,"num":"00","services":["local"],"parents":["7lQwiY"],"children":["vm3TpH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vm3TpH":{"name":["军民村","Junmincun"],"secondaryName":false,"num":"00","services":["local"],"parents":["gWL0Rq"],"children":["ZJF_LU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZJF_LU":{"name":["武生院","Wuhan Bioengineering Institule"],"secondaryName":false,"num":"00","services":["local"],"parents":["vm3TpH"],"children":["rC1YIx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rC1YIx":{"name":["阳逻","Yangluo"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZJF_LU"],"children":["Y5t-CY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Y5t-CY":{"name":["阳逻开发区","Yangluo Development Zone"],"secondaryName":false,"num":"00","services":["local"],"parents":["rC1YIx"],"children":["QK4qLx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QK4qLx":{"name":["施岗","Shigang"],"secondaryName":false,"num":"00","services":["local"],"parents":["Y5t-CY"],"children":["JkGjZF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，请您删除```(REPLACE ME/代替我)```是bot识别，感谢！
