### ISSUE TITLE
北京地铁最新线路（所有）

### ISSUE THREAD

**Issue by HaidianHuangzhuangZhan** [railmapgen/rmg-templates#4]
[BJsubway.zip](https://github.com/wongchito/RailMapGenerator/files/7902110/BJsubway.zip)
另建议增加北京地铁风格和环线功能

**Comment by 52PD** [comment]
您好，

由于本线路模版我们一直未将其汇入到项目中，而北京地铁亦于近期更新了部分线路内容，
因此考虑到该模版内容已经过时，我们将不会将其汇入到项目中。在此我们表示非常抱歉
