### ISSUE TITLE
武汉地铁1号线 Wuhan Metro Line 1

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmg-templates#40]
[wh1.zip](https://github.com/railmapgen/rmg-templates/files/9274946/wh1.zip)

😀

_BELOW CONTENT IS ADDED BY @wongchito ON BEHALF OF @Dingdong2334_

**Justification:** Hey

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="_config"><summary>New company: Wuhan Metro</summary><details type="name">{"en":"Wuhan Metro","zh-Hans":"武汉地铁","zh-Hant":"武漢地鐵"}</details></details>

<details repo="rmg-templates" company="whrt" line="wh1"><summary>whrt/wh1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2200,"indoor":1200},"svg_height":300,"style":"gzmtr","y_pc":50,"padding":3,"direction":"r","platform_num":"1","theme":["wuhan","wh1","#3D84C6","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"rZGc8R","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["rZGc8R"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ok-Z2P":{"name":["新荣","Xinrong"],"secondaryName":false,"num":"28","services":["local"],"parents":["AD4UNp"],"children":["1PAvcM"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh21","#CF0192","#fff","阳逻线","Yangluo Line"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1PAvcM":{"name":["堤角","Dijiao"],"secondaryName":false,"num":"29","services":["local"],"parents":["ok-Z2P"],"children":["Aqfh9d"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["UPigIX"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"rZGc8R":{"name":["径河","Jinghe"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["pGFYM6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pGFYM6":{"name":["三店","Sandian"],"secondaryName":false,"num":"02","services":["local"],"parents":["rZGc8R"],"children":["pk0S3s"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pk0S3s":{"name":["码头潭公园","Matoutan Park"],"secondaryName":false,"num":"03","services":["local"],"parents":["pGFYM6"],"children":["vsF0Ft"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh6","#008536","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vsF0Ft":{"name":["东吴大道","Dongwu Boulevard"],"secondaryName":false,"num":"04","services":["local"],"parents":["pk0S3s"],"children":["82KNr0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"82KNr0":{"name":["五环大道","Wuhuan Boulevard"],"secondaryName":false,"num":"05","services":["local"],"parents":["vsF0Ft"],"children":["YD_9ft"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"YD_9ft":{"name":["额头湾","Etouwan"],"secondaryName":false,"num":"06","services":["local"],"parents":["82KNr0"],"children":["14a9rz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"14a9rz":{"name":["竹叶海","Zhuyehai"],"secondaryName":false,"num":"07","services":["local"],"parents":["YD_9ft"],"children":["RNPM2K"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"RNPM2K":{"name":["舵落口","Duoluokou"],"secondaryName":false,"num":"08","services":["local"],"parents":["14a9rz"],"children":["e-8usH"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"e-8usH":{"name":["古田一路","Gutian 1st Road"],"secondaryName":false,"num":"09","services":["local"],"parents":["RNPM2K"],"children":["41Wngm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"41Wngm":{"name":["古田二路","Gutian 2nd Road"],"secondaryName":false,"num":"10","services":["local"],"parents":["e-8usH"],"children":["gwV3Vi"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gwV3Vi":{"name":["古田三路","Gutian 3rd Road"],"secondaryName":false,"num":"11","services":["local"],"parents":["41Wngm"],"children":["hnqThA"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hnqThA":{"name":["古田四路","Gutian 4th Road"],"secondaryName":false,"num":"12","services":["local"],"parents":["gwV3Vi"],"children":["GiIK7a"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GiIK7a":{"name":["汉西一路","Hanxi 1st Road"],"secondaryName":false,"num":"13","services":["local"],"parents":["hnqThA"],"children":["hEVD6w"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hEVD6w":{"name":["宗关","Zongguan"],"secondaryName":false,"num":"14","services":["local"],"parents":["GiIK7a"],"children":["QT5FZM"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh3","#D9B966","#fff","3号线","Line 3"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QT5FZM":{"name":["太平洋","Taipingyang"],"secondaryName":false,"num":"15","services":["local"],"parents":["hEVD6w"],"children":["bntEyI"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bntEyI":{"name":["硚口路","Qiaokou Road"],"secondaryName":false,"num":"16","services":["local"],"parents":["QT5FZM"],"children":["BqeKle"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"BqeKle":{"name":["崇仁路","Chongren Road"],"secondaryName":false,"num":"17","services":["local"],"parents":["bntEyI"],"children":["lPqMl1"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lPqMl1":{"name":["利济北路","Liji North Road"],"secondaryName":false,"num":"18","services":["local"],"parents":["BqeKle"],"children":["wHKgM6"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wHKgM6":{"name":["友谊路","Youyi Road"],"secondaryName":false,"num":"19","services":["local"],"parents":["lPqMl1"],"children":["WB5ubs"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WB5ubs":{"name":["循礼门","Xunlimen"],"secondaryName":false,"num":"20","services":["local"],"parents":["wHKgM6"],"children":["ssEXMt"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh2","#EB7CAF","#fff","2号线","Line 2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ssEXMt":{"name":["大智路","Dazhi Road"],"secondaryName":false,"num":"21","services":["local"],"parents":["WB5ubs"],"children":["remQRz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh6","#008536","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"remQRz":{"name":["三阳路","Sanyang Road"],"secondaryName":false,"num":"22","services":["local"],"parents":["ssEXMt"],"children":["VFeT4_"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh7","#EB7900","#fff","7号线","Line 7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VFeT4_":{"name":["黄浦路","Huanpu Road"],"secondaryName":false,"num":"23","services":["local"],"parents":["remQRz"],"children":["nZJWFI"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["wuhan","wh8","#98ACAB","#fff","8号线","Line 8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nZJWFI":{"name":["头道街","Toudao Street"],"secondaryName":false,"num":"24","services":["local"],"parents":["VFeT4_"],"children":["pCRfJC"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"pCRfJC":{"name":["二七路","Erqi Road"],"secondaryName":false,"num":"25","services":["local"],"parents":["nZJWFI"],"children":["bpiKB7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bpiKB7":{"name":["徐州新村","Xuzhouxincun"],"secondaryName":false,"num":"26","services":["local"],"parents":["pCRfJC"],"children":["AD4UNp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AD4UNp":{"name":["丹水池","Danshuichi"],"secondaryName":false,"num":"27","services":["local"],"parents":["bpiKB7"],"children":["ok-Z2P"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UPigIX":{"name":["汉口北","Hankou North"],"secondaryName":false,"num":"32","services":["local"],"parents":["YLwmi9"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"YLwmi9":{"name":["滠口新城","Shekouxincheng"],"secondaryName":false,"num":"31","services":["local"],"parents":["Aqfh9d"],"children":["UPigIX"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Aqfh9d":{"name":["藤子岗","Tengzigang"],"secondaryName":false,"num":"30","services":["local"],"parents":["1PAvcM"],"children":["YLwmi9"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":7}</details></details>

**Comment by 52PD** [comment]
您好，首先感谢您对本项目的支持与贡献。

不过考虑到拉合尔轨道交通在本项目中仍然算是新加入的一个轨交系统，故能否请您参考[How to add line templates](https://github.com/railmapgen/rmg-templates/wiki/How-to-add-line-templates)中第五步的内容提交相应所需文件呢？

此外，目前2/3/4/5/6/7/8/11/16号线阳逻线的线路模版仍然未见提交，所以就像@thekingofcity 在https://github.com/railmapgen/rmg-templates/issues/3 中所说的，建议您将剩余十条线制作完成后与已经上传的1号线一起打包上传，这样也方便我们将所有线路汇入到项目中。

**Comment by Dingdong2334** [comment]
> 此外，目前2/3/4/5/6/7/8/11/16号线阳逻线的线路模版仍然未见提交，所以就像@thekingofcity 在#3 中所说的，建议您将剩余十条线制作完成后与已经上传的1号线一起打包上传，这样也方便我们将所有线路汇入到项目中。

ok

**Comment by wongchito** [comment]
Hi @Dingdong2334 ,

This template has been added to RMG project with the help from bot. Thanks for your contribution!
