### ISSUE TITLE
Resources: New templates of Xi'an Metro

### ISSUE THREAD

**Issue by ChinaNorthernAirlines** [railmapgen/rmg-templates#404]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(**Justification:** 西安地铁16号线开通在即，本网站上并没有该线路官方的规划图。
规划来自360百科上公开的西安地铁规划

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="xianrail" line="Line 16" major="false"><summary>xianrail/Line 16</summary><details type="name">{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16号线"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1900,"indoor":2100},"svg_height":340,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["other","other","#ff9900","#fff"],"line_name":["16号线","Line 16"],"current_stn_idx":"8gxknT","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["8gxknT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8gxknT":{"name":["秦创源中心","QinChuangYuanZhongXin"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["0DU393"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"0DU393":{"name":["西咸大厦","XiXianDaSha"],"secondaryName":false,"num":"02","services":["local"],"parents":["8gxknT"],"children":["COH13i"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["X9uMwS"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"COH13i":{"name":["上林路","ShangLinLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["0DU393"],"children":["yCa0nT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xian","xa1","#0077C8","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yCa0nT":{"name":["复兴大道北","FuXingDaDaoBei"],"secondaryName":false,"num":"00","services":["local"],"parents":["COH13i"],"children":["KV8WrV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KV8WrV":{"name":["西安国际足球中心","XianGuoJiZuQiuZhongXin"],"secondaryName":false,"num":"00","services":["local"],"parents":["yCa0nT"],"children":["5t_T8E"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5t_T8E":{"name":["细柳营","XiLiuYing"],"secondaryName":false,"num":"00","services":["local"],"parents":["KV8WrV"],"children":["W3InTS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"W3InTS":{"name":["沣东城市广场","FengDongChengShiSquare"],"secondaryName":false,"num":"00","services":["local"],"parents":["5t_T8E"],"children":["B5Q5Lc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"B5Q5Lc":{"name":["欢乐谷","HuanLeGu"],"secondaryName":false,"num":"00","services":["local"],"parents":["W3InTS"],"children":["X9uMwS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xian","xa5","#A6E35F","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"X9uMwS":{"name":["\t 诗经里","ShiJingLi"],"secondaryName":false,"num":"00","services":["local"],"parents":["B5Q5Lc"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>)

**Comment by 28yfang** [comment]
您好，在此感谢您的贡献。
想请问一下西安地铁16号线何时开通呢？若时间过长，需在线路开通后再上传

**Comment by 52PD** [comment]
Closed since the line not operate.
