### ISSUE TITLE
Resources: New templates of Xi'an Metro

### ISSUE THREAD

**Issue by ChinaNorthernAirlines** [railmapgen/rmg-templates#406]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(**Justification:** 西安地铁10号线已经开工建设，预计将于2026年前完工，本网站上仍然没有关于西安地铁10号线的线路规划图
来源于360百科上公开的线路规划信息

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="xianrail" line="Line 10" major="false"><summary>xianrail/Line 10</summary><details type="name">{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10号线"}</details><details type="param">{"svgWidth":{"destination":1400,"runin":1400,"railmap":1800,"indoor":2000},"svg_height":350,"style":"shmetro","y_pc":50,"padding":12,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["other","other","#4dac7b","#fff"],"line_name":["10号线","Line 10"],"current_stn_idx":"X2lGtF","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["X2lGtF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"X2lGtF":{"name":["杨家庄","YangJiaZhuang"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["RYBbLj"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"RYBbLj":{"name":["环园中路","HuanYuanZhongLu"],"secondaryName":false,"num":"02","services":["local"],"parents":["X2lGtF"],"children":["jI6vQw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["UGoHdI"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jI6vQw":{"name":["团结村","TuanJieCun"],"secondaryName":false,"num":"00","services":["local"],"parents":["RYBbLj"],"children":["NKUxGi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NKUxGi":{"name":["红旗","HongQi"],"secondaryName":false,"num":"00","services":["local"],"parents":["jI6vQw"],"children":["ewEp3F"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ewEp3F":{"name":["西安工大·武德路","XianGongDa·WuDeLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["NKUxGi"],"children":["xcCvPS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#00ffff","#fff"],"name":["14号线","Line 14"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xcCvPS":{"name":["东风路","DongFengLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["ewEp3F"],"children":["Pon_5w"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Pon_5w":{"name":["未央湖","WeiYangHu"],"secondaryName":false,"num":"00","services":["local"],"parents":["xcCvPS"],"children":["5P200W"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5P200W":{"name":["\t 杏渭路","XingWeiLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["Pon_5w"],"children":["UF5rqm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UF5rqm":{"name":["水流路","ShuiLiuLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["5P200W"],"children":["2TJPh3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"2TJPh3":{"name":["泾渭","JingWei"],"secondaryName":false,"num":"00","services":["local"],"parents":["UF5rqm"],"children":["ybmc54"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ybmc54":{"name":["\t 绳刘村","ShengLiuCun"],"secondaryName":false,"num":"00","services":["local"],"parents":["2TJPh3"],"children":["sHOBPb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"sHOBPb":{"name":["\t 桑家村","SangJiaCun"],"secondaryName":false,"num":"00","services":["local"],"parents":["ybmc54"],"children":["MXjTon"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"MXjTon":{"name":["泾环北路","JingHuanBeiLu"],"secondaryName":false,"num":"00","services":["local"],"parents":["sHOBPb"],"children":["gAcKwz"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gAcKwz":{"name":["榆楚西","YuChuXi"],"secondaryName":false,"num":"00","services":["local"],"parents":["MXjTon"],"children":["pt-5P7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"pt-5P7":{"name":["榆楚","YuChu"],"secondaryName":false,"num":"00","services":["local"],"parents":["gAcKwz"],"children":["PKWPk1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PKWPk1":{"name":["\t 杏王村","XingWangCun"],"secondaryName":false,"num":"00","services":["local"],"parents":["pt-5P7"],"children":["UGoHdI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UGoHdI":{"name":["\t 水景公园","ShuiJingGongYuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["PKWPk1"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>)

**Comment by 28yfang** [comment]
您好，在此感谢您的贡献。
由于RMG模版不收录任何未开通的线路，请您在线路开通后再上传，感谢！

**Comment by ChinaNorthernAirlines** [comment]
好的，谢谢您的提醒
