### ISSUE TITLE
【修正】宁波地铁

### ISSUE THREAD

**Issue by feitongxiaok** [railmapgen/rmg-templates#41]
这几天我重新检查了一遍作品，结合管理员的评论，我发现上一个版本有以下问题：
1.宁绍城际使用国铁制式，不支持上传
2.上次我使用的是手机取色，没法用数字坐标，所以取出来和官方配色有较大的差异。现在我有条件进行电脑端的数字坐标取色，新版本与官方配色一致
3.通过参考其他使用上海地铁模式的模板，发现站台号可不使用。宁波1-5号线目前未启用站台号，所以我删除了站台号，使线路图更接近于实际情况。希望程序员大哥允许我上传更准确的版本，感谢！
[nbrt.zip](https://github.com/railmapgen/rmg-templates/files/9276040/nbrt.zip)

**Comment by thekingofcity** [comment]
嗨，感谢您对于项目的支持与贡献。新模板已经被加入资源库中，您稍后可以在宁波地铁中看到并选择它。
