### ISSUE TITLE
Resources: New templates of Nanjing Metro

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmg-templates#427]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 新建滁宁城际铁路/宁滁线模板

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="njmetro" line="nc" major="false"><summary>njmetro/nc</summary><details type="name">{"en":"宁滁线","zh-Hans":"Nanjing-Chuzhou Line","zh-Hant":"寧滁綫"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#ff6314","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"kZb1lt","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["Gx1FoX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-p2Vy3":{"name":["北斗产业园","Beidou Industrial Park"],"secondaryName":false,"num":"01","services":["local"],"parents":["Ouo_HI"],"children":["iqRh8m"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iqRh8m":{"name":["南京北站","Nanjing North Railway Station"],"secondaryName":false,"num":"02","services":["local"],"parents":["-p2Vy3"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["nanjing","nj3","#009a44","#fff"],"name":["3号线","Line 3"]},{"theme":["nanjing","nj4","#7d55c7","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"hsr","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["iqRh8m"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Gx1FoX":{"name":["滁州高铁站","Chuzhou Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["BAURw9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"hsr","loop_pivot":false,"one_line":true,"int_padding":355},"BAURw9":{"name":["腰铺","Yaopu"],"secondaryName":false,"num":"00","services":["local"],"parents":["Gx1FoX"],"children":["f0WaZf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"f0WaZf":{"name":["花博园","Huaboyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["BAURw9"],"children":["JaQdeo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JaQdeo":{"name":["琅琊山","Langyashan"],"secondaryName":false,"num":"00","services":["local"],"parents":["f0WaZf"],"children":["NYRuQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NYRuQU":{"name":["滁州政务中心","Chuzhou Government Affairs Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["JaQdeo"],"children":["UTXRV7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UTXRV7":{"name":["担子","Danzi"],"secondaryName":false,"num":"00","services":["local"],"parents":["NYRuQU"],"children":["8gOYuA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8gOYuA":{"name":["苏滁商务中心","Suchu Business Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["UTXRV7"],"children":["2ZUlVO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"2ZUlVO":{"name":["大王郢","Dawangying"],"secondaryName":false,"num":"00","services":["local"],"parents":["8gOYuA"],"children":["emJ3re"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"emJ3re":{"name":["林楼","Linlou"],"secondaryName":false,"num":"00","services":["local"],"parents":["2ZUlVO"],"children":["9pHZCk"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9pHZCk":{"name":["水口","Shuikou"],"secondaryName":false,"num":"00","services":["local"],"parents":["emJ3re"],"children":["Hs2Ph3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Hs2Ph3":{"name":["十二里半","Shierliban"],"secondaryName":false,"num":"00","services":["local"],"parents":["9pHZCk"],"children":["i_xfQK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"i_xfQK":{"name":["相官","Xiangguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["Hs2Ph3"],"children":["jIb8S5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jIb8S5":{"name":["汊河新城","Chahexincheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["i_xfQK"],"children":["kZb1lt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kZb1lt":{"name":["汊河","Chahe"],"secondaryName":false,"num":"00","services":["local"],"parents":["jIb8S5"],"children":["Ouo_HI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Ouo_HI":{"name":["张堡","Zhangbao"],"secondaryName":false,"num":"00","services":["local"],"parents":["kZb1lt"],"children":["-p2Vy3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板包括但不限于以下问题：
- 线路名称应为“S4号线”
- 张堡-南京北站区间暂未开通
- 腰铺站暂未开通
- 该线所有英文均为全大写（例子：CHUZHOU RAILWAY STATION）
__（如您有异议，请留下您的证明来源）__
请修改后重新提交至***本issue***中，感谢您的贡献。

**Comment by 52PD** [comment]
Closed as the issue fixed in #430 .
