### ISSUE TITLE
Resources: New templates of Shenzhen Metro(Not yet in service)

### ISSUE THREAD

**Issue by 233GB** [railmapgen/rmg-templates#429]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** 即将开通的深圳地铁13号线，已标注未开通字样

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmetro" line="gz13" major="false"><summary>szmetro/gz13</summary><details type="name">{"en":"Line 13(Not yet in service)","zh-Hans":"13号线（暂未开通）","zh-Hant":"13號線（未開通）","ko":"13호선(열리지 않음)"}</details><details type="param">{"svgWidth":{"destination":2500,"runin":1200,"railmap":2500,"indoor":1200},"svg_height":400,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["shenzhen","sz13","#DE7C00","#fff"],"line_name":["13号线","Line 13"],"current_stn_idx":"CIawJ0","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["CIawJ0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CIawJ0":{"name":["深圳湾口岸","Shenzhen bay checkpoint"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["0Hd6Ms"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0Hd6Ms":{"name":["人才公园","Talent park"],"secondaryName":false,"num":"02","services":["local"],"parents":["CIawJ0"],"children":["icXz27"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["kYayU5"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"icXz27":{"name":["后海","Houhai"],"secondaryName":false,"num":"03","services":["local"],"parents":["0Hd6Ms"],"children":["9397U9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz2","#B94700","#fff"],"name":["2号线","Line 2"]},{"theme":["shenzhen","sz11","#672146","#fff"],"name":["11号线","Line 11"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9397U9":{"name":["科苑","Keyuan"],"secondaryName":false,"num":"04","services":["local"],"parents":["icXz27"],"children":["_zc8UO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz2","#B94700","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_zc8UO":{"name":["粤海门","Yuehaimen"],"secondaryName":false,"num":"05","services":["local"],"parents":["9397U9"],"children":["Rwner0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz9","#7B6469","#fff"],"name":["9号线","Line 9"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Rwner0":{"name":["深大","Shenzhen University"],"secondaryName":false,"num":"06","services":["local"],"parents":["_zc8UO"],"children":["Jx9o73"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz1","#00B140","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Jx9o73":{"name":["高新中","Hi-Teach Center"],"secondaryName":false,"num":"07","services":["local"],"parents":["Rwner0"],"children":["PxWcxU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PxWcxU":{"name":["高新北","Hi-Teach North"],"secondaryName":false,"num":"08","services":["local"],"parents":["Jx9o73"],"children":["OaKG3r"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"OaKG3r":{"name":["西丽高铁站","Xili High-Speed Railway Station"],"secondaryName":false,"num":"09","services":["local"],"parents":["PxWcxU"],"children":["V9yQmD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"hsr","loop_pivot":false,"one_line":true,"int_padding":355},"V9yQmD":{"name":["石鼓","Shigu"],"secondaryName":false,"num":"10","services":["local"],"parents":["OaKG3r"],"children":["SoBtSr"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SoBtSr":{"name":["留仙洞","Liuxiandong"],"secondaryName":false,"num":"11","services":["local"],"parents":["V9yQmD"],"children":["JcCWJb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz5","#A05EB5","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JcCWJb":{"name":["百旺港大","Baiwang-HKU"],"secondaryName":false,"num":"12","services":["local"],"parents":["SoBtSr"],"children":["-7plW7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-7plW7":{"name":["应人石","Yingrenshi"],"secondaryName":false,"num":"13","services":["local"],"parents":["JcCWJb"],"children":["LgN2bS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LgN2bS":{"name":["罗租","Luozu"],"secondaryName":false,"num":"14","services":["local"],"parents":["-7plW7"],"children":["CBznZB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CBznZB":{"name":["石岩","Shiyan"],"secondaryName":false,"num":"15","services":["local"],"parents":["LgN2bS"],"children":["kYayU5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kYayU5":{"name":["上屋","Shangwu"],"secondaryName":false,"num":"16","services":["local"],"parents":["CBznZB"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shenzhen","sz6","#00C7B1","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":45,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，RMG模版不会汇入未开通线路的模版，感谢您的贡献。
