### ISSUE TITLE
Resources: New templates of Nanjing Metro

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmg-templates#430]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 南京地铁S4号线已开通，请求增加该线路模板

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="njmetro" line="njs4" major="false"><summary>njmetro/njs4</summary><details type="name">{"en":"Line S4","zh-Hans":"S4号线","zh-Hant":"S4號綫"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#ff6314","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"kZb1lt","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["Gx1FoX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["kZb1lt"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Gx1FoX":{"name":["滁州高铁站","CHUZHOU RAILWAY STATION"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["f0WaZf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"hsr","loop_pivot":false,"one_line":true,"int_padding":355},"f0WaZf":{"name":["花博园","HUABOYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["Gx1FoX"],"children":["JaQdeo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JaQdeo":{"name":["琅琊山","LANGYASHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["f0WaZf"],"children":["NYRuQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NYRuQU":{"name":["滁州政务中心","CHUZHOU GOVERNMENT AFFAIRS CENTER"],"secondaryName":false,"num":"00","services":["local"],"parents":["JaQdeo"],"children":["8gOYuA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8gOYuA":{"name":["苏滁商务中心","SUCHU BUSINESS CENTER"],"secondaryName":false,"num":"00","services":["local"],"parents":["NYRuQU"],"children":["2ZUlVO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"2ZUlVO":{"name":["大王郢","DAWANGYING"],"secondaryName":false,"num":"00","services":["local"],"parents":["8gOYuA"],"children":["emJ3re"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"emJ3re":{"name":["林楼","LINLOU"],"secondaryName":false,"num":"00","services":["local"],"parents":["2ZUlVO"],"children":["Hs2Ph3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Hs2Ph3":{"name":["十二里半","SHIERLIBAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["emJ3re"],"children":["jIb8S5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jIb8S5":{"name":["汊河新城","CHAHEXINCHENG"],"secondaryName":false,"num":"00","services":["local"],"parents":["Hs2Ph3"],"children":["kZb1lt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kZb1lt":{"name":["汊河","CHAHE"],"secondaryName":false,"num":"00","services":["local"],"parents":["jIb8S5"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 52PD** [comment]
您好，经检查我们发现了以下新问题：

1. 汊河站列车运行方向错误。

由于上面提及的内容为严重问题，因此在修复上述问题后，请重新打开一个新的Issue提交，并在新Issue中附上本Issue的编号，谢谢。
