### ISSUE TITLE
广州地铁广州南站应为四线换乘车站

### ISSUE THREAD

**Issue by Raupe114514** [railmapgen/rmg-templates#44]
广州地铁中，广州南站应为四线换乘车站，而模板中仍然只显示2号线和7号线，实际广州南站为**2、7、22和佛山2号线**的换乘车站。麻烦那边更正一下模板...
![wenti](https://user-images.githubusercontent.com/105926987/187205777-7a08640d-1fc1-45cf-ab25-119ff3a3ec5b.png)
![wenti2](https://user-images.githubusercontent.com/105926987/187205789-0fb14f4b-15a7-4578-b864-22dd00e556a4.png)

**Comment by 52PD** [comment]
额。。。如果你发现某条线路需要更新的话你是可以亲自制作线路模版然后提交上来的。。。不用发个issue告诉我们那条线路需要更新。。。

**Comment by Raupe114514** [comment]
ok
