### ISSUE TITLE
Wrong Station Name : Guangzhou Line 13

### ISSUE THREAD

**Issue by Dingdong2334** [railmapgen/rmg-templates#484]
![image](https://github.com/railmapgen/rmg/assets/79365860/cd61ca85-a318-4f3e-8bb2-424c643c3e1b)
It should be "**南海神庙**", not "南海神殿".

[gz13.zip](https://github.com/railmapgen/rmg/files/12051006/gz13.zip)

I'm sorry for my mistake.

**Comment by 52PD** [comment]
您好，很抱歉由于我们已经启用了新的提交工具，因此目前我们已经不再接受传统的打包提交形式。

请通过https://railmapgen.github.io/?app=rmg-templates-upload 重新提交一遍，谢谢。

**Comment by wongchito** [comment]
Covered in #497
