### ISSUE TITLE
Resources: New templates of Hangzhou MTR

### ISSUE THREAD

**Issue by HangzhouMetroXianingBridge** [railmapgen/rmg-templates#495]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 本次增加了來自我大杭州鴿鐵的線路，以求錦上添花

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hzmtr" line="00config"><summary>New company: Hangzhou MTR</summary><details type="name">{"en":"Hangzhou MTR","zh-Hans":"杭港地铁","zh-Hant":"杭港地鐵"}</details></details>

<details repo="rmg-templates" company="hzmtr" line="hz1" major="false"><summary>hzmtr/hz1</summary><details type="name">{"en":"Hangzhou Metro Line1","zh-Hans":"杭州地铁1号线","zh-Hant":"杭州地鐵1號線","ja":"杭州地下鉄1号線"}</details><details type="param">{"style":"shmetro","svg_height":400,"padding":8.750201061605276,"y_pc":40,"theme":["hangzhou","hz1","#DF4661","#fff"],"direction":"r","current_stn_idx":"jjh7","platform_num":"","stn_list":{"8141":{"name":["萧山国际机场","Xiaoshan Interational Airport"],"secondaryName":false,"num":"00","services":["local"],"parents":["j9w2"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz7","#87189D","#fff","7号线","Line7"],["hangzhou","hz19","#05c3de","#fff","19号线","Line19"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"linestart":{"parents":[],"children":["9cyo"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"num":"00","facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"lineend":{"parents":["8141"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"num":"00","facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"l1mz":{"parents":["qzjx"],"children":["iwf6"],"name":["云水","Yunshui"],"branch":{"left":[],"right":[]},"num":"02","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"iwf6":{"children":["bi85"],"parents":["l1mz"],"name":["下沙江滨","Xiashajiangbin"],"branch":{"left":[],"right":[]},"num":"01","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"jsat":{"parents":["srpy"],"children":["qzjx"],"branch":{"left":[],"right":[]},"name":["文泽路","Wenze Road"],"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"srpy":{"parents":["x9gu"],"children":["jsat"],"branch":{"left":[],"right":[]},"name":["高沙路","Gaosha Road"],"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[],[],[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"x9gu":{"parents":["k9k5"],"children":["srpy"],"branch":{"left":[],"right":[]},"name":["金沙湖","Jinshahu"],"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"k9k5":{"parents":["j2kn"],"children":["x9gu"],"branch":{"left":[],"right":[]},"name":["下沙西","West Xiasha"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"j2kn":{"parents":["lcgp"],"children":["k9k5"],"branch":{"left":[],"right":[]},"name":["客运中心","Coach Center"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["hangzhou","hz9","#BE4D00","#fff","9号线","Line9"]]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"kaxg":{"parents":["7x7k"],"children":["wbtv"],"branch":{"left":[],"right":[]},"name":["火车东站","East Railway Station"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["hangzhou","hz4","#6CC24A","#fff","4号线","Line4"],["hangzhou","hz19","#05c3de","#fff","19号线","Line19"]],[["hangzhou","hz6","#0072CE","#fff","6号线","Line6"]],[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"sd6y":{"parents":["1fdr"],"children":["qnbj"],"branch":{"left":[],"right":[]},"name":["西湖文化广场","West Lake Cultural Square"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[["車站名","Stn Name"]],"info":[[["hangzhou","hz3","#FAC62B","#fff","3号线","Line 3"],["hangzhou","hz19","#05c3de","#fff","19号线"," Line19"]],[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"9cyo":{"parents":["linestart"],"children":["8hte"],"branch":{"left":[],"right":[]},"name":["湘湖","Xianghu"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"hhar":{"children":["qgae"],"parents":["nhrh"],"branch":{"left":[],"right":[]},"name":["近江","Jinjiang"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["hangzhou","hz4","#6CC24A","#fff","4号线","Line4"]]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"jjh7":{"children":["h3vs"],"parents":["wbtv"],"branch":{"left":[],"right":[]},"name":["七堡","Qibao"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"7x7k":{"children":["kaxg"],"parents":["qnbj"],"branch":{"left":[],"right":[]},"name":["闸弄口","Zhalongkou"],"num":"00","services":["local"],"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":250},"qnbj":{"name":["打铁关","Datieguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["sd6y"],"children":["7x7k"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz5","#00AEC7","#fff","5号线","Line5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"1fdr":{"name":["武林广场","Wulin Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["wai3"],"children":["sd6y"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz3","#FAC62B","#fff","3号线","Line3"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"lcgp":{"name":["九堡","Jiubao"],"secondaryName":false,"num":"00","services":["local"],"parents":["h3vs"],"children":["j2kn"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"wbtv":{"name":["彭埠","Pengbu"],"secondaryName":false,"num":"00","services":["local"],"parents":["kaxg"],"children":["jjh7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz4","#6CC24A","#fff","4号线","Line4"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"wai3":{"name":["凤起路","Fengqi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["naz0"],"children":["1fdr"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz2","#DE7C00","#fff","2号线","Line2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"naz0":{"name":["龙翔桥","Longxiangqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["y6id"],"children":["wai3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"y6id":{"name":["定安路","Dingan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["ekdv"],"children":["naz0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"exax":{"name":["滨和路","Binhe Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["yrlx"],"children":["nhrh"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"qzjx":{"name":["文海南路","South Wenhai Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["jsat"],"children":["l1mz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz8","#AC145A","#fff","8号线","Line8"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"8hte":{"name":["滨康路","Binkang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["9cyo"],"children":["yrlx"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz5","#00AEC7","#fff","5号线","Line5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"yrlx":{"name":["西兴","Xixing"],"secondaryName":false,"num":"00","services":["local"],"parents":["8hte"],"children":["exax"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"nhrh":{"name":["江陵路","Jiangling Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["exax"],"children":["hhar"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz6","#0072CE","#fff","6号线","Line6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"qgae":{"name":["婺江路","Wujiang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["hhar"],"children":["ekdv"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"ekdv":{"name":["城站","Chengzhan"],"secondaryName":false,"num":"00","services":["local"],"parents":["qgae"],"children":["y6id"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz5","#00AEC7","#fff","5号线","Line5"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"h3vs":{"name":["九和路","Jiuhe Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["jjh7"],"children":["lcgp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"bi85":{"name":["杭州大会展中心","Hangzhou Grand Convention \\and Exhibition Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["iwf6"],"children":["qm0n"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"qm0n":{"name":["港城大道","Gangcheng Avenue"],"secondaryName":false,"num":"00","services":["local"],"parents":["bi85"],"children":["jgb4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"jgb4":{"name":["南阳","Nanyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["qm0n"],"children":["j9w2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250},"j9w2":{"name":["向阳路","Xangyang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["jgb4"],"children":["8141"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":250}},"line_name":["1号线","Line 1"],"psd_num":"1","line_num":"01","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1600,"runin":1200,"railmap":2000,"indoor":2500},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":34}</details></details>

<details repo="rmg-templates" company="hzmtr" line="hz5" major="false"><summary>hzmtr/hz5</summary><details type="name">{"en":"Hangzhou Metro Line5","zh-Hans":"杭州地铁5号线","zh-Hant":"杭州地鐵56號線","ja":"杭州地下鉄5号線"}</details><details type="param">{"style":"shmetro","svg_height":360,"padding":5,"y_pc":40,"theme":["hangzhou","hz5","#00AEC7","#fff"],"direction":"r","current_stn_idx":"wq23","platform_num":"","stn_list":{"3571":{"name":["金鸡路","Jinji Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["hjkm"],"children":["hzdb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"linestart":{"parents":[],"children":["03nu"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"lineend":{"parents":["ezsk"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"03nu":{"name":["姑娘桥","Guniangqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["sjxa"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hsic","#C5003E","#fff","绍兴1号线","Shaoxing Line1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":150},"zen7":{"name":["城站","Chengzhan"],"secondaryName":false,"num":"00","services":["local"],"parents":["wq23"],"children":["babk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz1","#DF4661","#fff","1号线","Line1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"babk":{"name":["万安桥","Wan’an Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["zen7"],"children":["htpm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"htpm":{"name":["建国北路","North Jianguo Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["babk"],"children":["jupa"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz2","#DE7C00","#fff","2号线","Line2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"jupa":{"name":["宝善桥","Baoshan Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["htpm"],"children":["vk94"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"vk94":{"name":["打铁关","Datieguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["jupa"],"children":["nvk7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz1","#DF4661","#fff","1号线","Line1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"nvk7":{"name":["杭氧","Hangyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["vk94"],"children":["8w81"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"8w81":{"name":["东新园","Dongxinyuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["nvk7"],"children":["42cb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"42cb":{"name":["西文街","Xiwen Street"],"secondaryName":false,"num":"00","services":["local"],"parents":["8w81"],"children":["kqy3"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"kqy3":{"name":["善贤","Shanxian"],"secondaryName":false,"num":"00","services":["local"],"parents":["42cb"],"children":["iemw"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz3","#FAC62B","#fff","3号线","Line3"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"iemw":{"name":["拱宸桥东","East Gongchen Bridge"],"secondaryName":false,"num":"00","services":["local"],"parents":["kqy3"],"children":["arhq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"lk29":{"name":["良睦路","Liangmu"],"secondaryName":false,"num":"00","services":["local"],"parents":["1h04"],"children":["0351"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"wq23":{"name":["江城路","Jiangcheng Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["y1v4"],"children":["zen7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz7","#87189D","#fff","7号线","Line7"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"y1v4":{"name":["侯潮门","Houchaomen"],"secondaryName":false,"num":"00","services":["local"],"parents":["sudp"],"children":["wq23"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"sudp":{"name":["南星桥","Nanxingqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["yxa5"],"children":["y1v4"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz4","#6CC24A","#fff","4号线","Line4"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"yxa5":{"name":["长河","Changhe"],"secondaryName":false,"num":"00","services":["local"],"parents":["1emf"],"children":["sudp"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz6","#0072CE","#fff","6号线","Line6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"1emf":{"name":["聚财路","Jucai Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["30s2"],"children":["yxa5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"30s2":{"name":["江晖路","Jianghui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["9any"],"children":["1emf"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"9any":{"name":["滨康路","Bingkang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["hzdb"],"children":["30s2"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz1","#DF4661","#fff","1号线","Line1"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"hzdb":{"name":["博奥路","Bo’ao Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["3571"],"children":["9any"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"hjkm":{"name":["人民广场","People's Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["3giq"],"children":["3571"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz2","#DE7C00","#fff","2号线","Line2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"3giq":{"name":["育才北路","North Yucai Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["hkqm"],"children":["hjkm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"jpq5":{"name":["火车南站","South Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["sjxa"],"children":["hkqm"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"sjxa":{"name":["双桥","Shuangqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["03nu"],"children":["jpq5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"arhq":{"name":["大运河","The Grand Canal"],"secondaryName":false,"num":"00","services":["local"],"parents":["iemw"],"children":["p9um"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"p9um":{"name":["和睦","Hemu"],"secondaryName":false,"num":"00","services":["local"],"parents":["arhq"],"children":["9bfq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz10","#AA8A00","#fff","10号线","Line10"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"9bfq":{"name":["萍水街","Pingshui Street"],"secondaryName":false,"num":"00","services":["local"],"parents":["p9um"],"children":["s8vt"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"s8vt":{"name":["三坝","Sanba"],"secondaryName":false,"num":"00","services":["local"],"parents":["9bfq"],"children":["466g"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz2","#DE7C00","#fff","2号线","Line2"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"466g":{"name":["浙大紫金港","Zijingang Campus\\Zhejiang University"],"secondaryName":false,"num":"00","services":["local"],"parents":["s8vt"],"children":["g8yv"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"g8yv":{"name":["蒋村","Jiangcun"],"secondaryName":false,"num":"00","services":["local"],"parents":["466g"],"children":["7lb8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"7lb8":{"name":["五常","Wuchang"],"secondaryName":false,"num":"00","services":["local"],"parents":["g8yv"],"children":["kjfk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"kjfk":{"name":["永福","Yongfu"],"secondaryName":false,"num":"00","services":["local"],"parents":["7lb8"],"children":["1h04"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"1h04":{"name":["杭师大仓前","Cangqian Campus \\Hangzhou Normal University"],"secondaryName":false,"num":"00","services":["local"],"parents":["kjfk"],"children":["lk29"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"hkqm":{"name":["通惠中路","Middle Tonghui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["jpq5"],"children":["3giq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"0351":{"name":["创景路","Chuangjing Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["lk29"],"children":["nk5w"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz19","#05c3de","#fff","19号线","Line19"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"nk5w":{"name":["葛巷","Gexiang"],"secondaryName":false,"num":"00","services":["local"],"parents":["0351"],"children":["gn7y"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"gn7y":{"name":["绿汀路","Lvting Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["nk5w"],"children":["6y9z"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["hangzhou","hz16","#FFB25B","#fff","16号线","Line16"],["hangzhou","hz3","#FAC62B","#fff","3号线","Line3"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"6y9z":{"name":["金星","Jinxing"],"secondaryName":false,"num":"00","services":["local"],"parents":["gn7y"],"children":["ezsk"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"ezsk":{"name":["南湖东","East Nanhu"],"secondaryName":false,"num":"00","services":["local"],"parents":["6y9z"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200}},"line_name":["5号线","Line 5"],"psd_num":"1","line_num":"9","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1200,"runin":1500,"railmap":2600,"indoor":2500},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":34}</details></details>

**Comment by 52PD** [comment]
您好，由于目前杭州的轨道交通由多家运营公司管理，为了方便整理，请将杭州所有地铁线路全部统一至“杭州地铁”这一名字下后重新提交，谢谢。
