### ISSUE TITLE
Resources: New templates of Hangzhou-Haining Intercity Rail

### ISSUE THREAD

**Issue by HangzhouMetroXianingBridge** [railmapgen/rmg-templates#500]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 增加一些城际线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zjrt" line="00config"><summary>New company: Hangzhou-Haining Intercity Rail</summary><details type="name">{"en":"Hangzhou-Haining Intercity Rail","zh-Hans":"杭海城际","zh-Hant":"杭海城際"}</details></details>

<details repo="rmg-templates" company="zjrt" line="hanghaiic" major="false"><summary>h-hIr/h-hIr</summary><details type="name">{"en":"Hangzhou-Haining Intercity Rail","zh-Hans":"杭海城际","zh-Hant":"杭海城際","ja":"杭州-海寧都市間鉄道"}</details><details type="param">{"style":"shmetro","svg_height":300,"padding":15.73,"y_pc":40,"theme":["hangzhou","hhic","#0077c8","#fff"],"direction":"r","current_stn_idx":"l1mz","platform_num":"","stn_list":{"linestart":{"parents":[],"children":["l1mz"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"lineend":{"parents":["ngy0"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"l1mz":{"parents":["linestart"],"children":["iwf6"],"name":["临平南高铁站","Linpingnan \\Railway Station"],"branch":{"left":[],"right":[]},"num":"02","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["hangzhou","hz9","#BE4D00","#fff","9号线","Line9"]],[],[]]},"services":["local"],"facility":"railway","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"iwf6":{"children":["b21t"],"parents":["l1mz"],"name":["许村","Xucun"],"branch":{"left":[],"right":[]},"num":"01","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":200},"b21t":{"name":["海宁高铁西站","Hainingxi Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["iwf6"],"children":["97am"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":200},"97am":{"name":["长安（东方学院）","Chang'an(Dongfang College)"],"secondaryName":false,"num":"00","services":["local"],"parents":["b21t"],"children":["a0lb"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"a0lb":{"name":["长安东","Chang'an East"],"secondaryName":false,"num":"00","services":["local"],"parents":["97am"],"children":["00ez"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"00ez":{"name":["周王庙","Zhouwangmiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["a0lb"],"children":["swpi"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"swpi":{"name":["盐官","Yanguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["00ez"],"children":["mp7w"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"mp7w":{"name":["桐九公路","Tongjiu Highway"],"secondaryName":false,"num":"00","services":["local"],"parents":["swpi"],"children":["2bxz"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"2bxz":{"name":["斜桥","Xieqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["mp7w"],"children":["w7n5"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"w7n5":{"name":["皮革城","Leather City"],"secondaryName":false,"num":"00","services":["local"],"parents":["2bxz"],"children":["se27"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"se27":{"name":["海昌路","Haichang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["w7n5"],"children":["ngy0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200},"ngy0":{"name":["浙大国际校区","International Campus,ZJU"],"secondaryName":false,"num":"00","services":["local"],"parents":["se27"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":200}},"line_name":["杭海城际","Hangzhou-Haining Intercity Rail"],"psd_num":"1","line_num":"TW","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1000,"runin":1000,"railmap":1000,"indoor":1000},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":44}</details></details>

**Comment by polygon827** [comment]
您好！
