### ISSUE TITLE
Resources: New templates of [浦江线 Pujiang Line]

### ISSUE THREAD

**Issue by Yexiaowei11** [railmapgen/rmg-templates#508]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

{"svgWidth":{"destination":1300,"runin":1300,"railmap":1300,"indoor":1900},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["shanghai","pjl","#B5B5B6","#fff"],"line_name":["浦江线","Pujiang Line"],"current_stn_idx":"3J3cKt","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["cWAkQU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FnqpKU":{"name":["沈杜公路","Shendu Highway"],"secondaryName":false,"num":"01","services":["local"],"parents":["3J3cKt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#4a86e8","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3J3cKt":{"name":["三鲁公路","Sanlu Highway"],"secondaryName":false,"num":"02","services":["local"],"parents":["hNpzac"],"children":["FnqpKU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["FnqpKU"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hNpzac":{"name":["闵瑞路","Min Rui Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Kki6jW"],"children":["3J3cKt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Kki6jW":{"name":["浦航路","Puhang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["EDJaZn"],"children":["hNpzac"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EDJaZn":{"name":["东城一路","Dongchengyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["cWAkQU"],"children":["Kki6jW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"cWAkQU":{"name":["汇臻路","Huizhen Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["EDJaZn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}

**Comment by 52PD** [comment]
您好，很抱歉由于您提交线路稿件时的格式错误，导致我们无法创建相对应的pull request，因此您需要重新提交。
