### ISSUE TITLE
Resources: New templates of Taoyuan Metro

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg-templates#514]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/road.html

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tymtr" line="00config"><summary>New company: Taoyuan Metro</summary><details type="name">{"en":"Taoyuan Metro","zh-Hans":"桃园捷运","zh-Hant":"桃園捷運"}</details></details>

<details repo="rmg-templates" company="tymtr" line="tyap" major="false"><summary>tymtr/tyap</summary><details type="name">{"en":"Taoyuan Airport MRT","zh-Hans":"桃园机场捷运","zh-Hant":"桃園機場捷運"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1400,"railmap":2300,"indoor":5750},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["taoyuan","taoyuanairport","#8246af","#fff"],"line_name":["桃园机场捷运","Taoyuan Airport MRT"],"current_stn_idx":"vCJFS-","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["wN6TS0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LDXRuN":{"name":["環北","Huanbei"],"secondaryName":false,"num":"21","services":["local"],"parents":["0oSh_L"],"children":["jX5N-w"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"jX5N-w":{"name":["老街溪","Laojie River"],"secondaryName":false,"num":"22","services":["local"],"parents":["LDXRuN"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["jX5N-w"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0oSh_L":{"name":["興南","Xingnan"],"secondaryName":false,"num":"20","services":["local"],"parents":["5eOIPT"],"children":["LDXRuN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"5eOIPT":{"name":["桃園體育園區","Taoyuan Sports Park"],"secondaryName":false,"num":"19","services":["local"],"parents":["A7SPi5"],"children":["0oSh_L"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"A7SPi5":{"name":["高鐵桃園站","Taoyuan HSR Station"],"secondaryName":false,"num":"18","services":["local"],"parents":["PDnJU2"],"children":["5eOIPT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355},"PDnJU2":{"name":["領航","Linghang"],"secondaryName":false,"num":"17","services":["local"],"parents":["jQgRUi"],"children":["A7SPi5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"jQgRUi":{"name":["橫山","Hengshan"],"secondaryName":false,"num":"16","services":["local"],"parents":["imkBfO"],"children":["PDnJU2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"imkBfO":{"name":["大園","Dayuan"],"secondaryName":false,"num":"15","services":["local"],"parents":["XPnmZc"],"children":["jQgRUi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"XPnmZc":{"name":["機場旅店","Airport Hotel"],"secondaryName":false,"num":"14a","services":["local"],"parents":["vCJFS-"],"children":["imkBfO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"vCJFS-":{"name":["機場第二航廈","Airport Terminal 2 "],"secondaryName":false,"num":"13","services":["local","direct","express"],"parents":["KJ-c3b"],"children":["XPnmZc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"airport","loop_pivot":false,"one_line":false,"int_padding":355},"KJ-c3b":{"name":["機場第一航廈","Airport Terminal 1"],"secondaryName":false,"num":"12","services":["local","direct","express"],"parents":["wk0slH"],"children":["vCJFS-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"airport","loop_pivot":false,"one_line":false,"int_padding":355},"wk0slH":{"name":["坑口","Kengkou"],"secondaryName":false,"num":"11","services":["local"],"parents":["OejQ3p"],"children":["KJ-c3b"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"OejQ3p":{"name":["山鼻","Shanbi"],"secondaryName":false,"num":"10","services":["local"],"parents":["Y42m-N"],"children":["wk0slH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"Y42m-N":{"name":["林口","Linkou"],"secondaryName":false,"num":"9","services":["local"],"parents":["GuknSg"],"children":["OejQ3p"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"GuknSg":{"name":["長庚醫院","Chang Gung Memorial Hospital"],"secondaryName":false,"num":"8","services":["local","direct","express"],"parents":["YGOKDh"],"children":["Y42m-N"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"YGOKDh":{"name":["體育大學","National Taiwan Sport University"],"secondaryName":false,"num":"7","services":["local"],"parents":["82dJst"],"children":["GuknSg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"82dJst":{"name":["泰山貴和","Taishan Guihe"],"secondaryName":false,"num":"6","services":["local"],"parents":["NIQvnx"],"children":["YGOKDh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"NIQvnx":{"name":["泰山","Taishan"],"secondaryName":false,"num":"5","services":["local"],"parents":["20oyAM"],"children":["82dJst"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"20oyAM":{"name":["新莊副都心","Xinzhuang Fuduxin"],"secondaryName":false,"num":"4","services":["local"],"parents":["417SVX"],"children":["NIQvnx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"417SVX":{"name":["新北產業園區","New Taipei Industrial Park"],"secondaryName":false,"num":"3","services":["local","direct","express"],"parents":["UfIwSs"],"children":["20oyAM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["taipei","y","#fedb00","#000"],"name":["環狀線","Circular Line"]}]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"UfIwSs":{"name":["三重","Sanchong"],"secondaryName":false,"num":"00","services":["local"],"parents":["wN6TS0"],"children":["417SVX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["taipei","o","#f8b61c","#000"],"name":["中和新蘆線","Zhonghe-Xinlu Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"wN6TS0":{"name":["台北車站","Taipei Main Station"],"secondaryName":false,"num":"00","services":["local","direct","express"],"parents":["linestart"],"children":["UfIwSs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["taipei","g","#008659","#fff"],"name":["松山新店線","Songshan-Xindian Line"]},{"theme":["taipei","bl","#0070bd","#fff"],"name":["板南線","Bannan Line"]},{"theme":["taipei","r","#e3002c","#fff"],"name":["淡水信義線","Tamsui-Xinyi Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"A","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @polygon827 ,

請將桃機捷運「直達車 (Express)」停靠站標註為「快速/大站快車 (Express)」，使其於上海地鐵及廣州地鐵風格均可正確顯示。多謝！

**Comment by polygon827** [comment]
**Justification:** https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/road.html



**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tymtr" line="00config"><summary>New company: Taoyuan Metro</summary><details type="name">{"en":"Taoyuan Metro","zh-Hans":"桃园捷运","zh-Hant":"桃園捷運"}</details></details>

<details repo="rmg-templates" company="tymtr" line="tyap" major="false"><summary>tymtr/tyap</summary><details type="name">{"en":"Taoyuan Airport MRT","zh-Hans":"桃园机场捷运","zh-Hant":"桃園機場捷運"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1400,"railmap":2300,"indoor":5750},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["taoyuan","taoyuanairport","#8246af","#fff"],"line_name":["桃园机场捷运","Taoyuan Airport MRT"],"current_stn_idx":"vCJFS-","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["wN6TS0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LDXRuN":{"name":["環北","Huanbei"],"secondaryName":false,"num":"21","services":["local"],"parents":["0oSh_L"],"children":["jX5N-w"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"jX5N-w":{"name":["老街溪","Laojie River"],"secondaryName":false,"num":"22","services":["local"],"parents":["LDXRuN"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["jX5N-w"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0oSh_L":{"name":["興南","Xingnan"],"secondaryName":false,"num":"20","services":["local"],"parents":["5eOIPT"],"children":["LDXRuN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"5eOIPT":{"name":["桃園體育園區","Taoyuan Sports Park"],"secondaryName":false,"num":"19","services":["local"],"parents":["A7SPi5"],"children":["0oSh_L"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"A7SPi5":{"name":["高鐵桃園站","Taoyuan HSR Station"],"secondaryName":false,"num":"18","services":["local"],"parents":["PDnJU2"],"children":["5eOIPT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355},"PDnJU2":{"name":["領航","Linghang"],"secondaryName":false,"num":"17","services":["local"],"parents":["jQgRUi"],"children":["A7SPi5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"jQgRUi":{"name":["橫山","Hengshan"],"secondaryName":false,"num":"16","services":["local"],"parents":["imkBfO"],"children":["PDnJU2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"imkBfO":{"name":["大園","Dayuan"],"secondaryName":false,"num":"15","services":["local"],"parents":["XPnmZc"],"children":["jQgRUi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"XPnmZc":{"name":["機場旅店","Airport Hotel"],"secondaryName":false,"num":"14a","services":["local"],"parents":["vCJFS-"],"children":["imkBfO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"vCJFS-":{"name":["機場第二航廈","Airport Terminal 2 "],"secondaryName":false,"num":"13","services":["local","direct","express"],"parents":["KJ-c3b"],"children":["XPnmZc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"airport","loop_pivot":false,"one_line":false,"int_padding":355},"KJ-c3b":{"name":["機場第一航廈","Airport Terminal 1"],"secondaryName":false,"num":"12","services":["local","direct","express"],"parents":["wk0slH"],"children":["vCJFS-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"airport","loop_pivot":false,"one_line":false,"int_padding":355},"wk0slH":{"name":["坑口","Kengkou"],"secondaryName":false,"num":"11","services":["local"],"parents":["OejQ3p"],"children":["KJ-c3b"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"OejQ3p":{"name":["山鼻","Shanbi"],"secondaryName":false,"num":"10","services":["local"],"parents":["Y42m-N"],"children":["wk0slH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"Y42m-N":{"name":["林口","Linkou"],"secondaryName":false,"num":"9","services":["local"],"parents":["GuknSg"],"children":["OejQ3p"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"GuknSg":{"name":["長庚醫院","Chang Gung Memorial Hospital"],"secondaryName":false,"num":"8","services":["local","direct","express"],"parents":["YGOKDh"],"children":["Y42m-N"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"YGOKDh":{"name":["體育大學","National Taiwan Sport University"],"secondaryName":false,"num":"7","services":["local"],"parents":["82dJst"],"children":["GuknSg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"82dJst":{"name":["泰山貴和","Taishan Guihe"],"secondaryName":false,"num":"6","services":["local"],"parents":["NIQvnx"],"children":["YGOKDh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"NIQvnx":{"name":["泰山","Taishan"],"secondaryName":false,"num":"5","services":["local"],"parents":["20oyAM"],"children":["82dJst"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"20oyAM":{"name":["新莊副都心","Xinzhuang Fuduxin"],"secondaryName":false,"num":"4","services":["local"],"parents":["417SVX"],"children":["NIQvnx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"417SVX":{"name":["新北產業園區","New Taipei Industrial Park"],"secondaryName":false,"num":"3","services":["local","direct","express"],"parents":["UfIwSs"],"children":["20oyAM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["taipei","y","#fedb00","#000"],"name":["環狀線","Circular Line"]}]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"UfIwSs":{"name":["三重","Sanchong"],"secondaryName":false,"num":"00","services":["local"],"parents":["wN6TS0"],"children":["417SVX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["taipei","o","#f8b61c","#000"],"name":["中和新蘆線","Zhonghe-Xinlu Line"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"wN6TS0":{"name":["台北車站","Taipei Main Station"],"secondaryName":false,"num":"00","services":["local","direct","express"],"parents":["linestart"],"children":["UfIwSs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["taipei","g","#008659","#fff"],"name":["松山新店線","Songshan-Xindian Line"]},{"theme":["taipei","bl","#0070bd","#fff"],"name":["板南線","Bannan Line"]},{"theme":["taipei","r","#e3002c","#fff"],"name":["淡水信義線","Tamsui-Xinyi Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"A","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by polygon827** [comment]
已修改
