### ISSUE TITLE
Resources: New templates of Wuxi Metro

### ISSUE THREAD

**Issue by Hefenglu780JIiangdadongmen** [railmapgen/rmg-templates#525]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(**Justification:** 未发现模板中有无锡地铁

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="wxmetro" line="00config"><summary>New company: Wuxi Metro</summary><details type="name">{"en":"Wuxi Metro","zh-Hans":"无锡地铁","zh-Hant":"無锡地铁"}</details></details>

<details repo="rmg-templates" company="wxmetro" line="wx3" major="false"><summary>wxmetro/wx3</summary><details type="name">{"en":"Wuxi Metro Line3","zh-Hans":"无锡地铁3号线","zh-Hant":"無锡地铁3號线"}</details><details type="param">{"style":"shmetro","svg_height":450,"padding":3,"y_pc":40,"theme":["wuxi","wx3","#00A9E0","#fff"],"direction":"r","current_stn_idx":"ZfMmuA","platform_num":"","stn_list":{"linestart":{"parents":[],"children":["ZfMmuA","l1mz"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":["through","ZfMmuA"]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["etryB2"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["linestart"],"children":["5qhf"],"name":["唐平湖","Tangpinghu"],"branch":{"left":[],"right":[]},"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["etryB2"],"parents":["3jml"],"name":["南星苑","Nanxingyuan"],"branch":{"left":[],"right":[]},"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"qg34":{"name":["硕放机场","Shuofang Airport"],"secondaryName":false,"num":"00","services":["local"],"parents":["vifb"],"children":["3jml"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx4","#93328E","#fff"],"name":["4号线","Line 4"]},{"theme":["suzhou","sz3","#F88211","#fff"],"name":["苏州3号线","Line 3"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"3jml":{"name":["硕放镇","Shuofang"],"secondaryName":false,"num":"00","services":["local"],"parents":["qg34"],"children":["iwf6"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]},{"lines":[]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"vifb":{"name":["长江南路","South Changjiang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["a9xr"],"children":["qg34"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"a9xr":{"name":["无锡新区站","Wuxi New District"],"secondaryName":false,"num":"00","services":["local"],"parents":["mrhv"],"children":["vifb"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx4","#93328E","#fff"],"name":["4","Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"mrhv":{"name":["周泾巷","Zhoujingxiang"],"secondaryName":false,"num":"00","services":["local"],"parents":["zv8o"],"children":["a9xr"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"zv8o":{"name":["高浪东路","East Gaolang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["gwtu"],"children":["mrhv"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"gwtu":{"name":["黄山路","Huangshan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["yec8"],"children":["zv8o"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"yec8":{"name":["旺庄路","Wangzhuang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["v44x"],"children":["gwtu"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx5","#FFB81C","#fff"],"name":["5号线","Line 5"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"v44x":{"name":["新光路","Xingunag Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["g9l3"],"children":["yec8"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"g9l3":{"name":["太湖花园","Taihuhuayuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["wyk2"],"children":["v44x"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#6db5d9","#fff"],"name":["7","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"wyk2":{"name":["叙丰","Xufeng"],"secondaryName":false,"num":"00","services":["local"],"parents":["oua9"],"children":["g9l3"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"oua9":{"name":["东风","Dongfeng"],"secondaryName":false,"num":"00","services":["local"],"parents":["9lmq"],"children":["wyk2"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#ff00ff","#fff"],"name":["6号线","Line 6"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"9lmq":{"name":["靖海","Jinghai"],"secondaryName":false,"num":"00","services":["local"],"parents":["48po"],"children":["oua9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx2","#00B140","#fff"],"name":["2号线","Line 2"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"48po":{"name":["广瑞","Guangrui"],"secondaryName":false,"num":"00","services":["local"],"parents":["16qe"],"children":["9lmq"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"16qe":{"name":["无锡火车站","Wuxi Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["zqho"],"children":["48po"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx1","#EE2737","#fff"],"name":["1号线","Line 1"]}]}]},"facility":"railway","loop_pivot":false,"one_line":false,"int_padding":355},"zqho":{"name":["北栅口","Beizhakou"],"secondaryName":false,"num":"00","services":["local"],"parents":["2i8c"],"children":["16qe"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"2i8c":{"name":["吴桥","Wuqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["ltqr"],"children":["zqho"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"ltqr":{"name":["盛岸","Sheng'an"],"secondaryName":false,"num":"00","services":["local"],"parents":["3j1w"],"children":["2i8c"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx4","#93328E","#fff"],"name":["4","Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"3j1w":{"name":["石门路","Shimen Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["epvt"],"children":["ltqr"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"epvt":{"name":["龙山梢","Longshanshao"],"secondaryName":false,"num":"00","services":["local"],"parents":["mb4g"],"children":["3j1w"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#C6AFD4","#fff"],"name":["11","Line 11"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"mb4g":{"name":["钱桥","Qianqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["26gh"],"children":["epvt"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"26gh":{"name":["苏庙","Sumiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["96rp"],"children":["mb4g"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"96rp":{"name":["锦溢路","Jinyi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["SQCIYv","j0f3"],"children":["26gh"],"branch":{"left":["through","SQCIYv"],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"j0f3":{"name":["藕塘","Shanghai University"],"secondaryName":false,"num":"00","services":["local"],"parents":["ljq6"],"children":["96rp"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"ljq6":{"name":["无锡西","WuxiXi"],"secondaryName":false,"num":"00","services":["local"],"parents":["g7x1"],"children":["j0f3"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"g7x1":{"name":["张镇","Zhangzhen"],"secondaryName":false,"num":"00","services":["local"],"parents":["6iy3"],"children":["ljq6"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"6iy3":{"name":["洛社","Luoshe"],"secondaryName":false,"num":"00","services":["local"],"parents":["qfyk"],"children":["g7x1"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#C6AFD4","#fff"],"name":["11","Line 11"]}]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"qfyk":{"name":["城铁惠山","Huishan Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["5qhf"],"children":["6iy3"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#C6AFD4","#fff"],"name":["11","Line 11"]}]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"5qhf":{"name":["西塘","Xitang"],"secondaryName":false,"num":"00","services":["local"],"parents":["l1mz"],"children":["qfyk"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"ZfMmuA":{"name":["胡埭","Hudai"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["tU2E04"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"tU2E04":{"name":["胡埭公园","Hudai Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZfMmuA"],"children":["hotDGX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hotDGX":{"name":["张舍","Zhangshe"],"secondaryName":false,"num":"00","services":["local"],"parents":["tU2E04"],"children":["33JBvi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"33JBvi":{"name":["刘塘","Liutang"],"secondaryName":false,"num":"00","services":["local"],"parents":["hotDGX"],"children":["g7zUJn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"g7zUJn":{"name":["钱藕路","Qianou Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["33JBvi"],"children":["kNiQdc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kNiQdc":{"name":["显山路","Xianshan Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["g7zUJn"],"children":["SQCIYv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SQCIYv":{"name":["溪南","Xinan"],"secondaryName":false,"num":"00","services":["local"],"parents":["kNiQdc"],"children":["96rp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"etryB2":{"name":["长江东路","East Cangjiang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["iwf6"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["苏州3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"line_name":["3号线","Line 3"],"psd_num":"1","line_num":"7","info_panel_type":"sh","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1500,"runin":1500,"railmap":2000,"indoor":3300},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":41}</details></details>)

**Comment by wongchito** [comment]
Hi @Hefenglu780JIiangdadongmen ,

對不起，另一作者 @28yfang 已在閣下提交Issue前上載無錫地鐵的範本，因此現關閉該Issue。如閣下認為所閣下的範本更優，歡迎重新開啟該Issue並繼續審核流程。

無論如何，我們感謝閣下的貢獻，亦多謝閣下對RMG的關注！
