### ISSUE TITLE
Resources: New templates of Wuxi Metro

### ISSUE THREAD

**Issue by Hefenglu780JIiangdadongmen** [railmapgen/rmg-templates#528]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(**Justification:** 无

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="wxmetro" line="00config"><summary>New company: Wuxi Metro</summary><details type="name">{"en":"Wuxi Metro","zh-Hans":"无锡地铁","zh-Hant":"無锡地铁"}</details></details>

<details repo="rmg-templates" company="wxmetro" line="wx31" major="false"><summary>wxmetro/wx31</summary><details type="name">{"en":"Wuxi Metro Line1","zh-Hans":"无锡地铁1号线","zh-Hant":"無锡地铁1號线"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2800,"indoor":2000},"svg_height":700,"style":"shmetro","y_pc":50,"padding":4,"branchSpacingPct":68,"direction":"r","platform_num":"","theme":["wuxi","wx1","#EE2737","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"-zguF6","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["-zguF6"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"-zguF6":{"name":["江阴外滩","Jiangyin Bund"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["-wA_fI"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"nqYpH8":{"name":["南方泉","Nanfangquan"],"secondaryName":false,"num":"02","services":["local"],"parents":["eE0BdK"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["nqYpH8"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"-wA_fI":{"name":["中山公园","Zhongshan Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["-zguF6"],"children":["6hzfz1"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"6hzfz1":{"name":["南门","Nanmen"],"secondaryName":false,"num":"00","services":["local"],"parents":["-wA_fI"],"children":["XN_wQ8"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"XN_wQ8":{"name":["江阴中医院","Jiangyin Hospital"],"secondaryName":false,"num":"00","services":["local"],"parents":["6hzfz1"],"children":["FNhVJA"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"FNhVJA":{"name":["江阴高铁站","Jiangyin Railway station"],"secondaryName":false,"num":"00","services":["local"],"parents":["XN_wQ8"],"children":["Im0hI9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":300},"Im0hI9":{"name":["南闸","Nanzha"],"secondaryName":false,"num":"00","services":["local"],"parents":["FNhVJA"],"children":["7hjL2N"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"7hjL2N":{"name":["峭岐","Qiaoqi"],"secondaryName":false,"num":"00","services":["local"],"parents":["Im0hI9"],"children":["C5ry2K"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"C5ry2K":{"name":["青阳","Qingyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["7hjL2N"],"children":["3LdTeQ"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"3LdTeQ":{"name":["霞客湾","Xiakewan"],"secondaryName":false,"num":"00","services":["local"],"parents":["C5ry2K"],"children":["dar8V1"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"dar8V1":{"name":["马镇","Mazhen"],"secondaryName":false,"num":"00","services":["local"],"parents":["3LdTeQ"],"children":["zIy6eH"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx1","#EE2737","#fff"],"name":["9","Line 9"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"zIy6eH":{"name":["堰桥","Yanqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["dar8V1"],"children":["J1ihI8"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#8d8f24","#fff"],"name":["8","Line 8"]}]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"J1ihI8":{"name":["锡北运河","Xibei Canal"],"secondaryName":false,"num":"00","services":["local"],"parents":["zIy6eH"],"children":["LUNUqB"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"LUNUqB":{"name":["西漳","Xizhang"],"secondaryName":false,"num":"00","services":["local"],"parents":["J1ihI8"],"children":["QaXvYQ"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"QaXvYQ":{"name":["天一","Tianyi"],"secondaryName":false,"num":"00","services":["local"],"parents":["LUNUqB"],"children":["cowFrn"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"cowFrn":{"name":["刘潭","Liutan"],"secondaryName":false,"num":"00","services":["local"],"parents":["QaXvYQ"],"children":["69_9lt"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx4","#93328E","#fff"],"name":["4"," Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"69_9lt":{"name":["庄前","Zhuangqian"],"secondaryName":false,"num":"00","services":["local"],"parents":["cowFrn"],"children":["B6_Gh3"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#8d8f24","#fff"],"name":["8","Line 8"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"B6_Gh3":{"name":["民丰","Minfeng"],"secondaryName":false,"num":"00","services":["local"],"parents":["69_9lt"],"children":["o8mAHo"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"o8mAHo":{"name":["无锡火车站","Wuxi Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["B6_Gh3"],"children":["8_zCXi"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx3","#00A9E0","#fff"],"name":["3","Line 3"]}]}]},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":300},"8_zCXi":{"name":["胜利门","Shenglimen"],"secondaryName":false,"num":"00","services":["local"],"parents":["o8mAHo"],"children":["cutMWo"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"cutMWo":{"name":["三阳广场","Sanyang Plaza"],"secondaryName":false,"num":"00","services":["local"],"parents":["8_zCXi"],"children":["1GZamU"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx2","#00B140","#fff"],"name":["2","Line 2"]},{"theme":["other","other","#ff00ff","#fff"],"name":["6","Line 6"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"1GZamU":{"name":["南禅寺","Nanchan Temple"],"secondaryName":false,"num":"00","services":["local"],"parents":["cutMWo"],"children":["XKUgNR"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wuxi","wx5","#FFB81C","#fff"],"name":["5","Line 5"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"XKUgNR":{"name":["谈渡桥","Tanduqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["1GZamU"],"children":["qNwSg0"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"qNwSg0":{"name":["太湖广场","Taihu Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["XKUgNR"],"children":["U-hPvD"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"U-hPvD":{"name":["清明桥","Qingmingqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["qNwSg0"],"children":["DTESXU"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"DTESXU":{"name":["人民医院","People's Hospital "],"secondaryName":false,"num":"00","services":["local"],"parents":["U-hPvD"],"children":["uElyvm"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#6db5d9","#fff"],"name":["7","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"uElyvm":{"name":["华清大桥","Huaqingdaqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["DTESXU"],"children":["HXyny5"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"eE0BdK":{"name":["葛埭桥","Gedaiqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["FyGsAB"],"children":["nqYpH8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ED6F00","#fff"],"name":["10","Line 10"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FyGsAB":{"name":["雪浪","Xuelang"],"secondaryName":false,"num":"00","services":["local"],"parents":["GcTM0f"],"children":["eE0BdK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"GcTM0f":{"name":["长广溪","Changguangxi"],"secondaryName":false,"num":"00","services":["local"],"parents":["dwpkoc"],"children":["FyGsAB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dwpkoc":{"name":["江南大学","Jiangnan University"],"secondaryName":false,"num":"00","services":["local"],"parents":["dYogIw"],"children":["GcTM0f"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dYogIw":{"name":["文化宫","Culture Palace"],"secondaryName":false,"num":"00","services":["local"],"parents":["3nnpSG"],"children":["dwpkoc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff00ff","#fff"],"name":["6","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3nnpSG":{"name":["市民中心","Civic Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["Sah5HF"],"children":["dYogIw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Sah5HF":{"name":["金匮公园","Jinkui Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["zSYWTA"],"children":["3nnpSG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zSYWTA":{"name":["塘铁桥","Tangtieqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["LbP9lc"],"children":["Sah5HF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LbP9lc":{"name":["南湖家园","Nanhujiayuan"],"secondaryName":false,"num":"00","services":["local"],"parents":["HXyny5"],"children":["zSYWTA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HXyny5":{"name":["扬名","Yangming"],"secondaryName":false,"num":"00","services":["local"],"parents":["uElyvm"],"children":["LbP9lc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#C6AFD4","#fff"],"name":["11","Line 11"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{"g4-u":{"from":"-zguF6","to":"nqYpH8","colors":[["wuxi","","#AAAAAA","#fff","",""]],"display":true}},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>)

**Comment by wongchito** [comment]
Hi @Hefenglu780JIiangdadongmen ,

對不起，另一作者 @28yfang 已在閣下提交Issue前上載無錫地鐵的範本，因此現關閉該Issue。如閣下認為所閣下的範本更優，歡迎重新開啟該Issue並繼續審核流程。

無論如何，我們感謝閣下的貢獻，亦多謝閣下對RMG的關注！
