### ISSUE TITLE
Resources: New templates of XuzhouMetro

### ISSUE THREAD

**Issue by Yangxiaoyang-Moye** [railmapgen/rmg-templates#556]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 这是我家乡的地铁，希望成功

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="xzmetro" line="00config"><summary>New company: XuzhouMetro</summary><details type="name">{"en":"XuzhouMetro","zh-Hans":"徐州地铁","zh-Hant":"徐州捷運"}</details></details>

<details repo="rmg-templates" company="xzmetro" line="xz1" major="false"><summary>xzmetro/xz1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ja":"1号線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["xuzhou","xz1","#a43337","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"wOnYXo","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["zugxh_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"r2vReD":{"name":["路窝","Luwo"],"secondaryName":false,"num":"02","services":["local"],"parents":["zugxh_"],"children":["vArFIq"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wOnYXo":{"name":["徐州东站","Xuzhoudong Railway Station"],"secondaryName":false,"num":"19","services":["local"],"parents":["Q2Kbhf"],"children":["mYXpKQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#9900ff","#fff"],"name":["6号线","Line 6"]},{"theme":["other","other","#980000","#fff"],"name":["7号线","Line 7"]}]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["12w5b-"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vArFIq":{"name":["杏山子","Xingshanzi"],"secondaryName":false,"num":"03","services":["local"],"parents":["r2vReD"],"children":["SrIbrV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SrIbrV":{"name":["韩山","Hanshan"],"secondaryName":false,"num":"04","services":["local"],"parents":["vArFIq"],"children":["zewT0w"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zewT0w":{"name":["工农路","Gongnonglu"],"secondaryName":false,"num":"05","services":["local"],"parents":["SrIbrV"],"children":["hrtpD2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hrtpD2":{"name":["人民广场","Renminguangchang"],"secondaryName":false,"num":"06","services":["local"],"parents":["zewT0w"],"children":["vqZIes"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff00ff","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"vqZIes":{"name":["苏堤路","Sudilu"],"secondaryName":false,"num":"07","services":["local"],"parents":["hrtpD2"],"children":["6xLCRU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6xLCRU":{"name":["徐医附院","The Affiliated Hospital of Xuzhou Medical University"],"secondaryName":false,"num":"08","services":["local"],"parents":["vqZIes"],"children":["tIggzY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"tIggzY":{"name":["彭城广场","Pengchengguangchang"],"secondaryName":false,"num":"09","services":["local"],"parents":["6xLCRU"],"children":["eHdb23"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xuzhou","xz2","#f08300","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eHdb23":{"name":["民主北路","Minzhubeilu"],"secondaryName":false,"num":"10","services":["local"],"parents":["tIggzY"],"children":["uIvbQp"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"uIvbQp":{"name":["徐州火车站","Xuzhou Railway Station"],"secondaryName":false,"num":"11","services":["local"],"parents":["eHdb23"],"children":["JOqk45"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xuzhou","xz3","#008cd7","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":355},"JOqk45":{"name":["子房山","Zifangshan"],"secondaryName":false,"num":"12","services":["local"],"parents":["uIvbQp"],"children":["qe_3TV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qe_3TV":{"name":["铜山路","Tongshanlu"],"secondaryName":false,"num":"13","services":["local"],"parents":["JOqk45"],"children":["dhuqP_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dhuqP_":{"name":["黄山垅","Huangshanlong"],"secondaryName":false,"num":"14","services":["local"],"parents":["qe_3TV"],"children":["Ucf2iX"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff00ff","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Ucf2iX":{"name":["庆丰路","Qingfenglu"],"secondaryName":false,"num":"15","services":["local"],"parents":["dhuqP_"],"children":["Y25XZP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Y25XZP":{"name":["医科大学","Xuzhou Medical University"],"secondaryName":false,"num":"16","services":["local"],"parents":["Ucf2iX"],"children":["jc19CJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jc19CJ":{"name":["乔家湖","Qiaojiahu"],"secondaryName":false,"num":"17","services":["local"],"parents":["Y25XZP"],"children":["Q2Kbhf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#00ff00","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Q2Kbhf":{"name":["金龙湖","Jinlonghu"],"secondaryName":false,"num":"18","services":["local"],"parents":["jc19CJ"],"children":["wOnYXo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zugxh_":{"name":["汉王新城","Hanwangxincheng"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["r2vReD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mYXpKQ":{"name":["小山","Xiaoshan"],"secondaryName":false,"num":"20","services":["local"],"parents":["wOnYXo"],"children":["3yfeFx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3yfeFx":{"name":["孤山","Gushan"],"secondaryName":false,"num":"21","services":["local"],"parents":["mYXpKQ"],"children":["BeYejI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"BeYejI":{"name":["大庙","Damiao"],"secondaryName":false,"num":"22","services":["local"],"parents":["3yfeFx"],"children":["TjC1Ul"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["xuzhou","xz2","#f08300","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"TjC1Ul":{"name":["安然片区","Anranpianqu"],"secondaryName":false,"num":"23","services":["local"],"parents":["BeYejI"],"children":["qZEfHG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qZEfHG":{"name":["夏庄村","Xiazhuangcun"],"secondaryName":false,"num":"24","services":["local"],"parents":["TjC1Ul"],"children":["0xf8el"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0xf8el":{"name":["大吴镇","Dawuzhen"],"secondaryName":false,"num":"25","services":["local"],"parents":["qZEfHG"],"children":["QLbUw2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QLbUw2":{"name":["前张村","Qianzhangcun"],"secondaryName":false,"num":"26","services":["local"],"parents":["0xf8el"],"children":["12w5b-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"12w5b-":{"name":["旗山","Qishan"],"secondaryName":false,"num":"27","services":["local"],"parents":["QLbUw2"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @Yangxiaoyang-Moye ,

我們不接納尚未開通的路線。請閣下移除相關轉乘路線後重新提交。多謝閣下的貢獻！
