### ISSUE TITLE
Resources: New templates of Hangzhou Metro

### ISSUE THREAD

**Issue by bobo45-1** [railmapgen/rmg-templates#563]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 缺少杭州地铁（此处提交的线路为1号线）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hzmetro" line="00config"><summary>New company: Hangzhou Metro</summary><details type="name">{"en":"Hangzhou Metro","zh-Hans":"杭州地铁","zh-Hant":"杭州地鐵"}</details></details>

<details repo="rmg-templates" company="hzmetro" line="hz1" major="false"><summary>hzmetro/hz1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號綫"}</details><details type="param">{"svgWidth":{"destination":1600,"runin":1600,"railmap":2400,"indoor":2400},"svg_height":500,"style":"shmetro","y_pc":50,"padding":11,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hangzhou","hz1","#DF4661","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"8SbDRF","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["x8zF5E"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"x8zF5E":{"name":["湘湖","Xianghu"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["gD_klu"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gD_klu":{"name":["滨康路","Binkang Road"],"secondaryName":false,"num":"02","services":["local"],"parents":["x8zF5E"],"children":["juaSmG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["5NKitR"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"juaSmG":{"name":["西兴","Xixing"],"secondaryName":false,"num":"00","services":["local"],"parents":["gD_klu"],"children":["ezqEf1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ezqEf1":{"name":["滨和路","Binhe Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["juaSmG"],"children":["_Y_qJv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_Y_qJv":{"name":["江陵路","Jiangling Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["ezqEf1"],"children":["Efyr_b"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz6","#0072CE","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Efyr_b":{"name":["近江","Jinjiang"],"secondaryName":false,"num":"00","services":["local"],"parents":["_Y_qJv"],"children":["P-NWd6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz4","#6CC24A","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"P-NWd6":{"name":["婺江路","Wujiang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Efyr_b"],"children":["jfy7Jo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"jfy7Jo":{"name":["城站","Chengzhan"],"secondaryName":false,"num":"00","services":["local"],"parents":["P-NWd6"],"children":["ZB5_3d"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZB5_3d":{"name":["定安路","Ding'an Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["jfy7Jo"],"children":["Upmw1k"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Upmw1k":{"name":["龙翔桥","Longxiangqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZB5_3d"],"children":["svSQo6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"svSQo6":{"name":["凤起路","Fengqi Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["Upmw1k"],"children":["mY8Cq6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz2","#f1803a","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mY8Cq6":{"name":["武林广场","Wulin Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["svSQo6"],"children":["wAuhsw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz3","#ffcd00","#000"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wAuhsw":{"name":["西湖文化广场","West Lake Cultural Square"],"secondaryName":false,"num":"00","services":["local"],"parents":["mY8Cq6"],"children":["HwJ3C2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz3","#ffcd00","#000"],"name":["3号线","Line 3"]},{"theme":["hangzhou","hz19","#05c3de","#fff"],"name":["机场快线","Airport Express"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HwJ3C2":{"name":["打铁关","Datieguan"],"secondaryName":false,"num":"00","services":["local"],"parents":["wAuhsw"],"children":["kN3ig6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kN3ig6":{"name":["闸弄口","Zhalongkou"],"secondaryName":false,"num":"00","services":["local"],"parents":["HwJ3C2"],"children":["8SbDRF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8SbDRF":{"name":["火车东站","East Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["kN3ig6"],"children":["ivAuwU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz4","#6CC24A","#fff"],"name":["4号线","Line 4"]},{"theme":["hangzhou","hz6","#0072CE","#fff"],"name":["6号线","Line 6"]},{"theme":["hangzhou","hz19","#05c3de","#fff"],"name":["机场快线","Airport Express"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ivAuwU":{"name":["彭埠","Pengbu"],"secondaryName":false,"num":"00","services":["local"],"parents":["8SbDRF"],"children":["w4L7cb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz4","#6CC24A","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"w4L7cb":{"name":["七堡","Qibao"],"secondaryName":false,"num":"00","services":["local"],"parents":["ivAuwU"],"children":["41aeIl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"41aeIl":{"name":["九和路","Jiuhe Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["w4L7cb"],"children":["EkNIP1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EkNIP1":{"name":["九堡","Jiubao"],"secondaryName":false,"num":"00","services":["local"],"parents":["41aeIl"],"children":["HpoYZC"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HpoYZC":{"name":["客运中心","Coach Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["EkNIP1"],"children":["X4Yg5S"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz9","#BE4D00","#fff"],"name":["9号线","Line 9"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"X4Yg5S":{"name":["下沙西","West Xiasha"],"secondaryName":false,"num":"00","services":["local"],"parents":["HpoYZC"],"children":["aHN6jo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"aHN6jo":{"name":["金沙湖","Jinshahu"],"secondaryName":false,"num":"00","services":["local"],"parents":["X4Yg5S"],"children":["9o2ZJD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9o2ZJD":{"name":["高沙路","Gaosha Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["aHN6jo"],"children":["575Dap"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"575Dap":{"name":["文泽路","Wenze Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["9o2ZJD"],"children":["5T7qU3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5T7qU3":{"name":["文海南路","South Wenhai Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["575Dap"],"children":["DyFx0C"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz8","#AC145A","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DyFx0C":{"name":["云水","Yunshui"],"secondaryName":false,"num":"00","services":["local"],"parents":["5T7qU3"],"children":["yHJXvt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yHJXvt":{"name":["下沙江滨","Xiashajiangbin"],"secondaryName":false,"num":"00","services":["local"],"parents":["DyFx0C"],"children":["dUnk9O"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dUnk9O":{"name":["杭州大会展中心","Hangzhou Grand Convension\\and Exhibition Center"],"secondaryName":false,"num":"00","services":["local"],"parents":["yHJXvt"],"children":["PzsWE2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"PzsWE2":{"name":["港城大道","Gangcheng Avenue"],"secondaryName":false,"num":"00","services":["local"],"parents":["dUnk9O"],"children":["fHitb7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fHitb7":{"name":["南阳","Nanyang"],"secondaryName":false,"num":"00","services":["local"],"parents":["PzsWE2"],"children":["R1nIu2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"R1nIu2":{"name":["向阳路","Xiangyang Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["fHitb7"],"children":["5NKitR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"5NKitR":{"name":["萧山国际机场","Xiaoshan International Airport"],"secondaryName":false,"num":"00","services":["local"],"parents":["R1nIu2"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz7","#87189D","#fff"],"name":["7号线","Line 7"]},{"theme":["hangzhou","hz19","#05c3de","#fff"],"name":["机场快线","Airport Express"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
您的模版包含但不限于以下问题：
1. 杭州大会展中心站英文名中的Convention错拼成Convension，请改正
2. 建议给城站站、火车东站站加火车站标识，萧山国际机场站加机场标识。
请在修正后重新提交并附上本issue号（#563），感谢！

**Comment by wongchito** [comment]
Hi @bobo45-1 ,

由於 #512 早於閣下提交並已通過檢查，因此現關閉該Issue。如閣下認為閣下提交的更優，歡迎再次開啟該Issue並提供理由。多謝閣下的貢獻！
