### ISSUE TITLE
Resources: New templates of Beijing Subway

### ISSUE THREAD

**Issue by qianchang1028** [railmapgen/rmg-templates#579]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)**Justification:** 架空

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="bjsubway" line="bj1" major="false"><summary>bjsubway/bj1</summary><details type="name">{"en":"Line 1/Batong Line","zh-Hans":"1号线/八通线","zh-Hant":"1號線/八通線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hongkong","twl","#E2231A","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"-2YHxm","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["FcOql-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"FcOql-":{"name":["未命名 FcOql-","Unnamed FcOql-"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["-2YHxm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"-2YHxm":{"name":["未命名 -2YHxm","Unnamed -2YHxm"],"secondaryName":false,"num":"02","services":["local"],"parents":["FcOql-"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["-2YHxm"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by linchen1965** [comment]
您好，很抱歉我们不接受架空模板投稿
