### ISSUE TITLE
Resources: New templates of [Suzhou Rail Transit]

### ISSUE THREAD

**Issue by Qingyiwinm** [railmapgen/rmg-templates#589]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 来自苏州轨道交通运营公司

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="sumetro" line="00config"><summary>New company: Suzhou Rail Transit</summary><details type="name">{"en":"Suzhou Rail Transit","zh-Hans":"苏州轨道交通","zh-Hant":"蘇州軌道交通"}</details></details>

<details repo="rmg-templates" company="sumetro" line="su1" major="false"><summary>sumetro/su1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1号线"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":2000,"railmap":2000,"indoor":2000},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#76bb40","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"AUTO4V","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["R9g7qQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"R9g7qQ":{"name":["木渎","Mudu"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["AUTO4V"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AUTO4V":{"name":["金枫路","Jinfeng lu"],"secondaryName":false,"num":"02","services":["local"],"parents":["R9g7qQ"],"children":["Y5XKTa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["VWD0OQ"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Y5XKTa":{"name":["汾湖路","Fenhu lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["AUTO4V"],"children":["f4zJVP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"f4zJVP":{"name":["玉山路","Yushan lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["Y5XKTa"],"children":["nrpzvW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nrpzvW":{"name":["狮子山","Shizishan"],"secondaryName":false,"num":"00","services":["local"],"parents":["f4zJVP"],"children":["Rg6PVH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#f88211","#fff"],"name":["3号线","Line 3"]}]},{"lines":[{"theme":["other","other","#b1dd8b","#fff"],"name":["有轨电车T1","Tram 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Rg6PVH":{"name":["塔园路","Tayuan lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["nrpzvW"],"children":["kGQKDh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"kGQKDh":{"name":["滨河路","Binhe lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["Rg6PVH"],"children":["JyUuAB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JyUuAB":{"name":["西环路","Xihuan lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["kGQKDh"],"children":["AHn4qB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AHn4qB":{"name":["桐泾北路","Tongjingbei lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["JyUuAB"],"children":["dVFZov"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dVFZov":{"name":["广济南路","Guangjinan lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["AHn4qB"],"children":["wAWC_M"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#ed3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wAWC_M":{"name":["养育巷","Yangyuxiang"],"secondaryName":false,"num":"00","services":["local"],"parents":["dVFZov"],"children":["IFyscV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IFyscV":{"name":["乐桥","Leqiao"],"secondaryName":false,"num":"00","services":["local"],"parents":["wAWC_M"],"children":["7JpoRP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#196eae","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7JpoRP":{"name":["临顿路","Lindun lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["IFyscV"],"children":["SHo3pC"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#41b6e6","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SHo3pC":{"name":["相门","Xiangmen"],"secondaryName":false,"num":"00","services":["local"],"parents":["7JpoRP"],"children":["UYUn_X"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UYUn_X":{"name":["东环路","Donghuan lu"],"secondaryName":false,"num":"00","services":["local"],"parents":["SHo3pC"],"children":["t9CIXm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"t9CIXm":{"name":["中央公园","Zhongyang park"],"secondaryName":false,"num":"00","services":["local"],"parents":["UYUn_X"],"children":["hbJYcg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#a77bca","#fff"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hbJYcg":{"name":["星海广场","Xinghai square"],"secondaryName":false,"num":"00","services":["local"],"parents":["t9CIXm"],"children":["wKLKhn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wKLKhn":{"name":["东方之门","Dongfangzhimen"],"secondaryName":false,"num":"00","services":["local"],"parents":["hbJYcg"],"children":["d1v9a7"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#f88211","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"d1v9a7":{"name":["文化博览中心","Wenhuabolanzhongxin"],"secondaryName":false,"num":"00","services":["local"],"parents":["wKLKhn"],"children":["e4PzLS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"e4PzLS":{"name":["时代广场","Shidai square"],"secondaryName":false,"num":"00","services":["local"],"parents":["d1v9a7"],"children":["c0m7eh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#a09200","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"c0m7eh":{"name":["星湖街","Xinhu jie"],"secondaryName":false,"num":"00","services":["local"],"parents":["e4PzLS"],"children":["w_ZTql"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"w_ZTql":{"name":["南施街","Nanshi jie"],"secondaryName":false,"num":"00","services":["local"],"parents":["c0m7eh"],"children":["F_qaA-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"F_qaA-":{"name":["星塘街","Xintang jie"],"secondaryName":false,"num":"00","services":["local"],"parents":["w_ZTql"],"children":["VWD0OQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#e63a9a","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VWD0OQ":{"name":["钟南街","Zhongnan jie"],"secondaryName":false,"num":"00","services":["local"],"parents":["F_qaA-"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Qingyiwinm** [comment]
各位开发者接到了消息请及时回复！谢谢

**Comment by wongchito** [comment]
Hi @Qingyiwinm ,

由於 #569 已早於閣下提交蘇州地鐵路線範本，因此現關閉該 Issue。如閣下認為閣下所提交的優於現有的，歡迎重新開啟 Issue。多謝閣下的貢獻！
