### ISSUE TITLE
Resources: New templates of Suzhou  Rail Transit

### ISSUE THREAD

**Issue by Qingyiwinm** [railmapgen/rmg-templates#591]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)

**Comment by Qingyiwinm** [comment]
（将会修复）：在二号线中，高铁苏州北站站和苏州火车站站未添加火车站标签

**Comment by Qingyiwinm** [comment]
请各位开发者们尽快回复

**Comment by langonginc** [comment]
您好，您需要粘贴 RMG-templates 上传时弹出窗口的内容至issue本体并替换掉“请替换我”那行文字，感谢您的贡献。
