### ISSUE TITLE
Questions for NEW TEMPLATES

### ISSUE THREAD

**Issue by Bobrenxin** [railmapgen/rmg-templates#592]
Hey RMG team! Here's a question for me:
Why there's A LOT OF templates that haven't been added to the application?
Please reply soon. We can't wait for the update!

**Comment by Bobrenxin** [comment]
correction: "for me"→"from me"

**Comment by LittleLing03** [comment]
您好，由于我们的审核员大多是正在上学的学生，可能因为学业或工作问题无法及时的审核模板，在这里我们深表歉意。感谢您的贡献。
Hello, since most of our auditors are students who are in school, we may not be able to review the template in time due to academic or work problems, here we apologize. Thank you for your contribution.

**Comment by Bobrenxin** [comment]
哦哦这样，表示理解，毕竟同为学生……那就不多打扰了，感谢百忙之中抽出时间回复~
