### ISSUE TITLE
Resources: New templates of Zhengzhou Metro

### ISSUE THREAD

**Issue by zhengzhou3245** [railmapgen/rmg-templates#593]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** 没人做

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zzmetro" line="ZZ7" major="false"><summary>zzmetro/ZZ7</summary><details type="name">{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7号线","de":"Linie 7"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1700,"railmap":3000,"indoor":1200},"svg_height":365,"style":"gzmtr","y_pc":50,"padding":5,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["zhengzhou","zz7","#C0955A","#fff"],"line_name":["7号线","Line 7"],"current_stn_idx":"G19xf_","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["Zug17H"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"4afX_R":{"name":["南环公园","NANHUANGONGYUAN"],"secondaryName":false,"num":"19","services":["local"],"parents":["Jj3rVf"],"children":["dfJtJF"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"dfJtJF":{"name":["南岗刘","NANGANGLIU"],"secondaryName":false,"num":"20","services":["local"],"parents":["4afX_R"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["dfJtJF"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"Zug17H":{"name":["东赵","DONGZHAO"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["OM56Sw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"OM56Sw":{"name":["黄河迎宾馆","HUANGHEYINGBINGGUAN"],"secondaryName":false,"num":"02","services":["local"],"parents":["Zug17H"],"children":["8bCj71"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz2","#D28F00","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"8bCj71":{"name":["英才西","YINCAIXI"],"secondaryName":false,"num":"03","services":["local"],"parents":["OM56Sw"],"children":["weybL9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"weybL9":{"name":["琉璃寺","LIULISI"],"secondaryName":false,"num":"04","services":["local"],"parents":["8bCj71"],"children":["O-A77r"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"O-A77r":{"name":["张家村","ZHANGJIACUN"],"secondaryName":false,"num":"05","services":["local"],"parents":["weybL9"],"children":["C2hCKY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz4","#3792D6","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"C2hCKY":{"name":["陈寨","CHENZHAI"],"secondaryName":false,"num":"06","services":["local"],"parents":["O-A77r"],"children":["G19xf_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"G19xf_":{"name":["科技市场","KEJISHICHANG"],"secondaryName":false,"num":"07","services":["local"],"parents":["C2hCKY"],"children":["Ecn-eT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz8","#E6E394","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"Ecn-eT":{"name":["河南博物馆","HENAN Museum"],"secondaryName":false,"num":"08","services":["local"],"parents":["G19xf_"],"children":["u6-qYc"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"u6-qYc":{"name":["郑州人民医院","ZHENZHOU People's Hospital"],"secondaryName":false,"num":"09","services":["local"],"parents":["Ecn-eT"],"children":["IdV4Wk"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"IdV4Wk":{"name":["大石桥","DASHIQIAO"],"secondaryName":false,"num":"10","services":["local"],"parents":["u6-qYc"],"children":["vBdMWR"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz3","#CB5100","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"vBdMWR":{"name":["河医立交","HEYILIJIAO"],"secondaryName":false,"num":"11","services":["local"],"parents":["IdV4Wk"],"children":["inNtQP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"inNtQP":{"name":["医学院","YIXUEYUAN"],"secondaryName":false,"num":"12","services":["local"],"parents":["vBdMWR"],"children":["C94kDB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz1","#D20200","#fff"],"name":["1号线","Line 1"]},{"theme":["zhengzhou","zz10","#B15F56","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"X-AHSs":{"name":["古玩城","GUWANCHENG"],"secondaryName":false,"num":"13","services":["local"],"parents":["C94kDB"],"children":["ozvQJ6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz6","#852081","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"ozvQJ6":{"name":["市第二人民医院","ZHENGZHOU No.2 Peopie Hospital"],"secondaryName":false,"num":"14","services":["local"],"parents":["X-AHSs"],"children":["-nOLSa"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"-nOLSa":{"name":["王胡砦","WANGHUZHAI"],"secondaryName":false,"num":"16","services":["local"],"parents":["ozvQJ6"],"children":["44Ok5X"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"44Ok5X":{"name":["郑寨","ZHENGZHAI"],"secondaryName":false,"num":"17","services":["local"],"parents":["-nOLSa"],"children":["Jj3rVf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"Jj3rVf":{"name":["荆胡","JINGHU"],"secondaryName":false,"num":"18","services":["local"],"parents":["44Ok5X"],"children":["4afX_R"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":290},"C94kDB":{"name":["建中街","JIANZONGJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["inNtQP"],"children":["X-AHSs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"7","psd_num":"1","info_panel_type":"gz28","notesGZMTR":[],"direction_gz_x":39,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by LittleLing03** [comment]
您好，由于郑州7号线暂未开通，我们暂时不会汇入您的模板，感谢您的贡献。

**Comment by zhengzhou3245** [comment]
好，谢谢

**Comment by zhengzhou3245** [comment]
![郑州地铁](https://github.com/railmapgen/rmg-templates/assets/142479419/301588ce-404d-4e90-b2f0-ec95e447e993)

**Comment by zhengzhou3245** [comment]
可以借鉴一下这个
