### ISSUE TITLE
Resources: New templates of Zhengzhou Metro

### ISSUE THREAD

**Issue by zhengzhou3245** [railmapgen/rmg-templates#594]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 有几站他没写上去

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zzmetro" line="zz6" major="false"><summary>zzmetro/zz6</summary><details type="name">{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}</details><details type="param">{"style":"gzmtr","svg_height":350,"padding":3,"y_pc":47,"theme":["other","other","#852081","#fff"],"direction":"r","current_stn_idx":"q9b3","platform_num":"2","stn_list":{"linestart":{"parents":[],"children":["q9b3"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["j_dE4m"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","num":"11","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["vcfk"],"children":["iwf6"],"name":["奥体中心","Zhengzhou \\Olympic Sports Center"],"branch":{"left":[],"right":[]},"num":"09","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#844F7C","#fff"],"name":["14号线","Line 14"]}]}]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["t8uXqA"],"parents":["l1mz"],"name":["常庄","Chang Zhuang"],"branch":{"left":[],"right":[]},"num":"10","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"q9b3":{"name":["贾峪","Jia Yu"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["w6w7"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"w6w7":{"name":["洞林湖","Donglin Lake"],"secondaryName":false,"num":"02","services":["local"],"parents":["q9b3"],"children":["0c7a"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"0c7a":{"name":["洞林寺","Dong Lin Si"],"secondaryName":false,"num":"03","services":["local"],"parents":["w6w7"],"children":["77vp"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"77vp":{"name":["安宁路","Anning Road"],"secondaryName":false,"num":"04","services":["local"],"parents":["0c7a"],"children":["tko1"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"tko1":{"name":["马寨","Ma Zhai"],"secondaryName":false,"num":"05","services":["local"],"parents":["77vp"],"children":["63sm"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"63sm":{"name":["河南建院","Henan Technical College \\Of Construction"],"secondaryName":false,"num":"06","services":["local"],"parents":["tko1"],"children":["briz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"briz":{"name":["金桢路","Jinzhen Road"],"secondaryName":false,"num":"07","services":["local"],"parents":["63sm"],"children":["vcfk"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"vcfk":{"name":["奥体中心西","Zhengzhou \\Olympic Sports Center(W)"],"secondaryName":false,"num":"08","services":["local"],"parents":["briz"],"children":["l1mz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"AFHJiL":{"name":["清华附中","High School affiliated to \\Tsinghua University"],"secondaryName":false,"num":"28","services":["local"],"parents":["SUSiuD"],"children":["ughubK"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz4","#3792D6","#fff"],"name":["4号线","Line 4"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"SUSiuD":{"name":["金融岛西","Zhengzhou Long Lake \\Finance Island (W)"],"secondaryName":false,"num":"27","services":["local"],"parents":["JvdE7F"],"children":["AFHJiL"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"JvdE7F":{"name":["小营","Xiao Ying"],"secondaryName":false,"num":"26","services":["local"],"parents":["on6nDd"],"children":["SUSiuD"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#e6e394","#fff"],"name":["8号线","Line 8"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"on6nDd":{"name":["金汇桥","Jinhui Brige"],"secondaryName":false,"num":"25","services":["local"],"parents":["ND3kU9"],"children":["JvdE7F"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"ND3kU9":{"name":["姚砦","Yao Zhai"],"secondaryName":false,"num":"24","services":["local"],"parents":["SvJWky"],"children":["on6nDd"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"SvJWky":{"name":["燕庄","Yan Zhuang"],"secondaryName":false,"num":"23","services":["local"],"parents":["kauZTY"],"children":["ND3kU9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz1","#D20200","#fff"],"name":["1号线","Line 1"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"kauZTY":{"name":["博览中心","Zhongyuan International\\Expo Center"],"secondaryName":false,"num":"22","services":["local"],"parents":["6iU2sg"],"children":["SvJWky"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz3","#CB5100","#fff"],"name":["3号线","Line 3"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"6iU2sg":{"name":["凤凰台南","Feng Huang Tai(S)"],"secondaryName":false,"num":"21","services":["local"],"parents":["Ab6-4H"],"children":["kauZTY"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"Ab6-4H":{"name":["二里岗东","Er Li Gang(E)"],"secondaryName":false,"num":"20","services":["local"],"parents":["j4o8kj"],"children":["6iU2sg"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"j4o8kj":{"name":["二里岗","Er Li Gang"],"secondaryName":false,"num":"19","services":["local"],"parents":["TdxZN9"],"children":["Ab6-4H"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz2","#D28F00","#fff"],"name":["2号线","Line2"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"TdxZN9":{"name":["陇秀公园","Longxiu Park"],"secondaryName":false,"num":"18","services":["local"],"parents":["5Oyo1I"],"children":["j4o8kj"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"5Oyo1I":{"name":["火车头体育场","Huochetou Stadium"],"secondaryName":false,"num":"17","services":["local"],"parents":["fegKlF"],"children":["TdxZN9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"fegKlF":{"name":["大学中路","University Road"],"secondaryName":false,"num":"16","services":["local"],"parents":["jllemm"],"children":["5Oyo1I"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["other","other","#c0955a","#fff"],"name":["7号线","Line 7"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"jllemm":{"name":["嵩淮","Song Huai"],"secondaryName":false,"num":"15","services":["local"],"parents":["FFx5o8"],"children":["fegKlF"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"FFx5o8":{"name":["桐淮","Tong Huai"],"secondaryName":false,"num":"14","services":["local"],"parents":["K0i38Y"],"children":["jllemm"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"K0i38Y":{"name":["卧龙岗","Wo Long Gang"],"secondaryName":false,"num":"13","services":["local"],"parents":["VC0YcM"],"children":["FFx5o8"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"VC0YcM":{"name":["李江沟","Li Jiang Gou"],"secondaryName":false,"num":"12","services":["local"],"parents":["t8uXqA"],"children":["K0i38Y"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"t8uXqA":{"name":["冯湾","Feng Wan"],"secondaryName":false,"num":"11","services":["local"],"parents":["iwf6"],"children":["VC0YcM"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":false,"int_padding":355},"j_dE4m":{"name":["京水","Jing Shui"],"secondaryName":false,"num":"31","services":["local"],"parents":["MDh7Vd"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"MDh7Vd":{"name":["大河村","Dahe Cun"],"secondaryName":false,"num":"30","services":["local"],"parents":["ughubK"],"children":["j_dE4m"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ughubK":{"name":["小河村","Xiaohe Cun"],"secondaryName":false,"num":"29","services":["local"],"parents":["AFHJiL"],"children":["MDh7Vd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"line_name":["6号线","Line 6"],"psd_num":"1","line_num":"6","info_panel_type":"gz1421","direction_gz_x":50,"direction_gz_y":85,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1500,"runin":1500,"railmap":2500,"indoor":2500},"notesGZMTR":[["本站及后续站点尚未开通","The opening of this station and subsequent stations is under construction.",39,20,true],["7号线、8号线尚未开通。","Line 7, Line 8 are under constructions.",0,5,false]],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":26}</details></details>

**Comment by wongchito** [comment]
Hi @zhengzhou3245 ,

我們不接納尚未開通的路段。歡迎閣下協助我們移除現存未通車路段。多謝！
