### ISSUE TITLE
Resources: New templates of Jinan Metro

### ISSUE THREAD

**Issue by XMJjs** [railmapgen/rmg-templates#595]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Justification:** 添加新城市地铁

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="jnmetro" line="00config"><summary>New company: Jinan Metro</summary><details type="name">{"en":"Jinan Metro","zh-Hans":"济南地铁","zh-Hant":"濟南地鐵"}</details></details>

<details repo="rmg-templates" company="jnmetro" line="jn1" major="false"><summary>jnmetro/jn1</summary><details type="name">{"en":"Jinan Metro Line 1","zh-Hans":"济南地铁1号线","zh-Hant":"濟南地鐵1號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["jinan","jn1","#BE1FA1","#fff"],"line_name":["济南地铁1号线","Jinan Metro Line 1"],"current_stn_idx":"stn_Cu0hCAtZT4","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["stn_Cu0hCAtZT4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["stn_-xzTeC-nMD"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_-xzTeC-nMD":{"name":["工研院","GONGYANYUAN"],"secondaryName":false,"num":"5","services":["local"],"parents":["stn_IHiSLoABd8"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_IHiSLoABd8":{"name":["创新谷","CHUANGXINGU"],"secondaryName":false,"num":"4","services":["local"],"parents":["stn_gAlEvxCxeP"],"children":["stn_-xzTeC-nMD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_gAlEvxCxeP":{"name":["园博园","YUANBOYUAN"],"secondaryName":false,"num":"3","services":["local"],"parents":["stn_BkJ5dY9CIy"],"children":["stn_IHiSLoABd8"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_BkJ5dY9CIy":{"name":["王府庄","WANGFUZHUANG"],"secondaryName":false,"num":"2","services":["local"],"parents":["stn_Cu0hCAtZT4"],"children":["stn_gAlEvxCxeP"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["jinan","jn2","#FFB620","#fff"],"name":["jn2","jn2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_Cu0hCAtZT4":{"name":["方特","FANGTE"],"secondaryName":false,"num":"1","services":["local"],"parents":["linestart"],"children":["stn_BkJ5dY9CIy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="jnmetro" line="jn2" major="false"><summary>jnmetro/jn2</summary><details type="name">{"en":"Jinan Metro Line 2","zh-Hans":"济南地铁2号线","zh-Hant":"濟南地鐵2號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["jinan","jn2","#FFB620","#fff"],"line_name":["济南地铁2号线","Jinan Metro Line 2"],"current_stn_idx":"stn_SlVQRxtj3-","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["stn_SlVQRxtj3-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["stn_BkJ5dY9CIy"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_BkJ5dY9CIy":{"name":["王府庄","WANGFUZHUANG"],"secondaryName":false,"num":"6","services":["local"],"parents":["stn_Lc4XHrJh45"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["jinan","jn1","#BE1FA1","#fff"],"name":["jn1","jn1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_Lc4XHrJh45":{"name":["老屯","LAOTUN"],"secondaryName":false,"num":"5","services":["local"],"parents":["stn_We8qFMw2Kw"],"children":["stn_BkJ5dY9CIy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_We8qFMw2Kw":{"name":["济洛路","JILUOLU"],"secondaryName":false,"num":"4","services":["local"],"parents":["stn_pSmB9qkLsQ"],"children":["stn_Lc4XHrJh45"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_pSmB9qkLsQ":{"name":["祝甸","ZHUDIAN"],"secondaryName":false,"num":"3","services":["local"],"parents":["stn_ddVpXLfrCw"],"children":["stn_We8qFMw2Kw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_ddVpXLfrCw":{"name":["八涧堡","BAJIANPU"],"secondaryName":false,"num":"2","services":["local"],"parents":["stn_SlVQRxtj3-"],"children":["stn_pSmB9qkLsQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["jinan","jn3","#0073CE","#fff"],"name":["jn3","jn3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_SlVQRxtj3-":{"name":["彭家庄","PENGJIAZHUANG"],"secondaryName":false,"num":"1","services":["local"],"parents":["linestart"],"children":["stn_ddVpXLfrCw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"2","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="jnmetro" line="jn3" major="false"><summary>jnmetro/jn3</summary><details type="name">{"en":"Jinan Metro Line 3","zh-Hans":"济南地铁3号线","zh-Hant":"濟南地鐵3號線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["jinan","jn3","#0073CE","#fff"],"line_name":["济南地铁3号线","Jinan Metro Line 3"],"current_stn_idx":"stn_SB3kEC2J2B","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["stn_SB3kEC2J2B"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["stn_pXJtpiY9w2"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_pXJtpiY9w2":{"name":["龙洞","LONGDONG"],"secondaryName":false,"num":"6","services":["local"],"parents":["stn_ddVpXLfrCw"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_ddVpXLfrCw":{"name":["八涧堡","BAJIANPU"],"secondaryName":false,"num":"5","services":["local"],"parents":["stn_W3PTpLdnA-"],"children":["stn_pXJtpiY9w2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["jinan","jn2","#FFB620","#fff"],"name":["jn2","jn2"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_W3PTpLdnA-":{"name":["张马屯","ZHANGMATUN"],"secondaryName":false,"num":"4","services":["local"],"parents":["stn_HMpQ1OSTWO"],"children":["stn_ddVpXLfrCw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_HMpQ1OSTWO":{"name":["王舍人","WANGSHEREN"],"secondaryName":false,"num":"3","services":["local"],"parents":["stn_8XYDlALC6f"],"children":["stn_W3PTpLdnA-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_8XYDlALC6f":{"name":["济南东站","JINANDONG RAILWAY STATION"],"secondaryName":false,"num":"2","services":["local"],"parents":["stn_SB3kEC2J2B"],"children":["stn_HMpQ1OSTWO"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_SB3kEC2J2B":{"name":["滩头","TANTOU"],"secondaryName":false,"num":"1","services":["local"],"parents":["linestart"],"children":["stn_8XYDlALC6f"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"3","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by 28yfang** [comment]
您好，RMG先已更新提交模版的标准，请您根据新标准重新提交，感谢。

**Comment by 28yfang** [comment]
另外，提交模版时需删除(REPLACE ME/替代我)才能触发bot。
