### ISSUE TITLE
TGM1、TNH1、F3、APM线路图

### ISSUE THREAD

**Issue by clearng-kly** [railmapgen/rmg-templates#6]
TGM1、TNH1、F3、APM线路图

- [x] [TGM1.zip](https://github.com/wongchito/RailMapGenerator/files/8032654/TGM1.zip)
- [x] [TNH1.zip](https://github.com/wongchito/RailMapGenerator/files/8032656/TNH1.zip)
- [x] [佛山3号线.zip](https://github.com/wongchito/RailMapGenerator/files/8032659/3.zip)
- [x] ~[APM.zip](https://github.com/wongchito/RailMapGenerator/files/8032660/APM.zip) (Covered by railmapgen/rmg#233 )~

**Comment by wongchito** [comment]
佛山3號線車站名稱及編碼與實際不符。已由 #61 代替。
