### ISSUE TITLE
添加深圳地铁12、14、16号线

### ISSUE THREAD

**Issue by SujiaL816** [railmapgen/rmg-templates#60]
[szmc121416.zip](https://github.com/railmapgen/rmg-templates/files/10345403/szmc121416.zip)

**Comment by SujiaL816** [comment]
最新版（有港铁、上海地铁、广州地铁三种风格）
[szmc121416.zip](https://github.com/railmapgen/rmg-templates/files/10357143/szmc121416.zip)
辛苦各位了🙂

**Comment by SujiaL816** [comment]
最新版（有港铁、上海地铁、广州地铁三种风格）
[szmc121416.zip](https://github.com/railmapgen/rmg-templates/files/10366656/szmc121416.zip)
辛苦各位了🙂

**Comment by 52PD** [comment]
您好，经检查目前你提交的模版有以下问题：

* 14号线沙田站往岗厦北方向站台编号错误。

请在对照以上内容进行修改后将修改的模版提交至本issue下。

感谢您对本项目的支持与贡献！

**Comment by SujiaL816** [comment]
您好，开发者，这是修正版🙂
[szmc121416新.zip](https://github.com/railmapgen/rmg-templates/files/10517759/szmc121416.zip)

**Comment by 52PD** [comment]
OK，没问题了👍

**Comment by 52PD** [comment]
您好，14号线已经没有问题。
然而经复查，目前还有以下问题需要解决：

- 16号线田心站往大运站方向站台无站台编号，因此请将该线路站台号留空。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路模版问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
