### ISSUE TITLE
Resources: New templates of Nanjing Tram

### ISSUE THREAD

**Issue by MYWBB1314** [railmapgen/rmg-templates#607]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 来自高德地图和作者实际考察

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="南京新城现代有轨电车有限公司" line="00config"><summary>New company: Nanjing Tram</summary><details type="name">{"en":"Nanjing Tram","zh-Hans":"南京新城现代有轨电车有限公司","zh-Hant":"南京新城現代有軌電車有限公司"}</details></details>

<details repo="rmg-templates" company="南京新城现代有轨电车有限公司" line="南京有轨电车" major="false"><summary>南京新城现代有轨电车有限公司/南京有轨电车</summary><details type="name">{"en":"Nanjing Tram","zh-Hans":"南京有轨电车","zh-Hant":"南京有軌電車"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["other","other","#00fdff","#fff"],"line_name":["南京有轨电车","Nanjing Tram"],"current_stn_idx":"stn_A4HKh-dRYv","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["stn_A4HKh-dRYv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["stn_CZNe3E_zB5"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_CZNe3E_zB5":{"name":["鱼嘴站",""],"secondaryName":false,"num":"13","services":["local"],"parents":["stn_wVFQO5NCmv"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_wVFQO5NCmv":{"name":["保双街东",""],"secondaryName":false,"num":"12","services":["local"],"parents":["stn_nBedcWePO0"],"children":["stn_CZNe3E_zB5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_nBedcWePO0":{"name":["保双街",""],"secondaryName":false,"num":"11","services":["local"],"parents":["stn_IZAp3tVAhy"],"children":["stn_wVFQO5NCmv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_IZAp3tVAhy":{"name":["天保街",""],"secondaryName":false,"num":"10","services":["local"],"parents":["stn_UjqjutzlWi"],"children":["stn_nBedcWePO0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_UjqjutzlWi":{"name":["龙王大街",""],"secondaryName":false,"num":"9","services":["local"],"parents":["stn_wtyNSw-LeA"],"children":["stn_IZAp3tVAhy"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_wtyNSw-LeA":{"name":["吴侯街",""],"secondaryName":false,"num":"8","services":["local"],"parents":["stn_T0NcAXeDVg"],"children":["stn_UjqjutzlWi"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_T0NcAXeDVg":{"name":["平良大街",""],"secondaryName":false,"num":"7","services":["local"],"parents":["stn_mPw2qwXQa_"],"children":["stn_wtyNSw-LeA"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_mPw2qwXQa_":{"name":["友谊街",""],"secondaryName":false,"num":"6","services":["local"],"parents":["stn_Pyofo3IuI3"],"children":["stn_T0NcAXeDVg"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_Pyofo3IuI3":{"name":["江山大街",""],"secondaryName":false,"num":"5","services":["local"],"parents":["stn_3tbx4FJAcU"],"children":["stn_mPw2qwXQa_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_3tbx4FJAcU":{"name":["博览中心东门",""],"secondaryName":false,"num":"4","services":["local"],"parents":["stn_Lwnqmqkx2T"],"children":["stn_Pyofo3IuI3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_Lwnqmqkx2T":{"name":["元通站",""],"secondaryName":false,"num":"3","services":["local"],"parents":["stn_nV2PI6EG_o"],"children":["stn_3tbx4FJAcU"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_nV2PI6EG_o":{"name":["富春江西街",""],"secondaryName":false,"num":"2","services":["local"],"parents":["stn_A4HKh-dRYv"],"children":["stn_Lwnqmqkx2T"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_A4HKh-dRYv":{"name":["奥体中心东门",""],"secondaryName":false,"num":"1","services":["local"],"parents":["linestart"],"children":["stn_nV2PI6EG_o"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @MYWBB1314 ,

經檢查，閣下提交的範本存在但不限於以下問題：

- 缺少車站英文名稱
- 缺少地鐵轉乘路線
- 路線顏色使用有誤

請閣下修正後重新上載。多謝！
