### ISSUE TITLE
Resources: New templates of Chongqing Rail Transit

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#622]
**Justification:** 补充重庆云巴的RMG模板。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="crt" line="cqyb" major="false"><summary>crt/cqyb</summary><details type="name">{"en":"Chongqing SkyShuttle","zh-Hans":"重庆云巴","zh-Hant":"重慶雲巴","ko":"충칭 윈바"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1280,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":46,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["other","other","#0095fa","#fff"],"line_name":["重庆云巴示范线","Chongqing SkyShuttle"],"current_stn_idx":"VFDEvI","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["7GDBt-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Ck4Vvt":{"name":["科创小镇","Kechuang Town"],"secondaryName":false,"num":"01","services":["local"],"parents":["X_1FrV"],"children":["VFDEvI"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"VFDEvI":{"name":["一号地铁站","Subway Line 1"],"secondaryName":false,"num":"02","services":["local"],"parents":["Ck4Vvt"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]},{"lines":[{"theme":["chongqing","cq1","#E4002B","#fff"],"name":["轨道交通1号线","Rail Transit Line 1"]}],"name":["璧山","Bishan"]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["VFDEvI"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"X_1FrV":{"name":["景山路","Jingshanlu"],"secondaryName":false,"num":"00","services":["local"],"parents":["UbKC7z"],"children":["Ck4Vvt"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"UbKC7z":{"name":["千层岩","Qiancengyan"],"secondaryName":false,"num":"00","services":["local"],"parents":["OdmvMo"],"children":["X_1FrV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"OdmvMo":{"name":["秀湖公园","Xiuhu Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["SFxI5I"],"children":["UbKC7z"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SFxI5I":{"name":["秀水湾","Xiushuiwan"],"secondaryName":false,"num":"00","services":["local"],"parents":["_i5b9V"],"children":["OdmvMo"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_i5b9V":{"name":["东岳公园","Dongyue Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["LfqzUV"],"children":["SFxI5I"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"LfqzUV":{"name":["儿童公园","Children’s Park"],"secondaryName":false,"num":"00","services":["local"],"parents":["JHoF8C"],"children":["_i5b9V"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"JHoF8C":{"name":["聚金大道","Jujin Avenue"],"secondaryName":false,"num":"00","services":["local"],"parents":["Hv1GrB"],"children":["LfqzUV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Hv1GrB":{"name":["双鱼","Shuangyu"],"secondaryName":false,"num":"00","services":["local"],"parents":["dRW8yS"],"children":["JHoF8C"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"dRW8yS":{"name":["莲花湖","Lianhuahu"],"secondaryName":false,"num":"00","services":["local"],"parents":["nd_PD0"],"children":["Hv1GrB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"nd_PD0":{"name":["刘家嘴","Liujiazui"],"secondaryName":false,"num":"00","services":["local"],"parents":["7ips-o"],"children":["dRW8yS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7ips-o":{"name":["高观音","Gaoguanyin"],"secondaryName":false,"num":"00","services":["local"],"parents":["XD72yV"],"children":["nd_PD0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"XD72yV":{"name":["沙坡","Shapo"],"secondaryName":false,"num":"00","services":["local"],"parents":["7GDBt-"],"children":["7ips-o"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7GDBt-":{"name":["成渝高铁站","Chengyu Railway"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["XD72yV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"hsr","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。

**_（ 审核来源：
https://zh.wikipedia.org/wiki/重庆云巴 ）_**
