### ISSUE TITLE
Resources: New templates of Wuhu Rail Transit

### ISSUE THREAD

**Issue by TPCpp** [railmapgen/rmg-templates#624]
**Justification:** 芜湖建了轻轨，我来加一下

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="00config"><summary>New company: Wuhu Rail Transit</summary><details type="name">{"en":"Wuhu Rail Transit","zh-Hans":"芜湖轨道交通","zh-Hant":"蕪湖軌道交通"}</details></details>

<details repo="rmg-templates" company="whrt" line="wh1" major="false"><summary>whrt/wh1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2000,"indoor":2400},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":100,"direction":"r","platform_num":"1","theme":["hongkong","twl","#E2231A","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"tio9gn","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["tio9gn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"tio9gn":{"name":["保顺路","BAOSHUNLU"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["6HGe-e"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"6HGe-e":{"name":["华山路","HUASHANLU"],"secondaryName":false,"num":"02","services":["local"],"parents":["tio9gn"],"children":["IJwtP-"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["FJpedn"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"IJwtP-":{"name":["泰山路","TAISHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["6HGe-e"],"children":["CtcEZT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"CtcEZT":{"name":["衡山路","HENGSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["IJwtP-"],"children":["he-kCh"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"he-kCh":{"name":["龙山路","LONGSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["CtcEZT"],"children":["T2Y-be"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"T2Y-be":{"name":["鞍山路","ANSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["he-kCh"],"children":["iNA7vj"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"iNA7vj":{"name":["港湾路","GANGWANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["T2Y-be"],"children":["-u3Stx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"-u3Stx":{"name":["裕安路","YU'ANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["iNA7vj"],"children":["RzgI-o"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"RzgI-o":{"name":["武夷山路","WUYISHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["-u3Stx"],"children":["aXqOoE"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"aXqOoE":{"name":["港一路","GANGYILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["RzgI-o"],"children":["g52YjD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"g52YjD":{"name":["天柱山路","TIANZHUSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["aXqOoE"],"children":["uRVzUb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"uRVzUb":{"name":["天门山路","TIANMENSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["g52YjD"],"children":["jfQ5OB"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"jfQ5OB":{"name":["赤铸山路","CHIZHUSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["uRVzUb"],"children":["R-KYiL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"R-KYiL":{"name":["赭山路","ZHESHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["jfQ5OB"],"children":["HJEm0K"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"HJEm0K":{"name":["赭山公园","ZHESHANGONGYUAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["R-KYiL"],"children":["joTBGT"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"joTBGT":{"name":["中山北路","ZHONGSHANBEILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["HJEm0K"],"children":["ApymwY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"ApymwY":{"name":["鸠兹广场","JIUZIGUANGCHANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["joTBGT"],"children":["mpmq7J"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#4a86e8","#fff"],"name":["2号线","Line 2"]}]},{"lines":[]},{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":250},"mpmq7J":{"name":["环城北路","HUANCHENGBEILU"],"secondaryName":false,"num":"00","services":["local"],"parents":["ApymwY"],"children":["lc-NI1"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"lc-NI1":{"name":["奥体中心","AOTIZHONGXIN"],"secondaryName":false,"num":"00","services":["local"],"parents":["mpmq7J"],"children":["4w1Wml"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"4w1Wml":{"name":["红花山路","HONGHUASHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["lc-NI1"],"children":["sBjNpd"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"sBjNpd":{"name":["博览中心","BOLANZHONGXIN"],"secondaryName":false,"num":"00","services":["local"],"parents":["4w1Wml"],"children":["5Gtig2"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"5Gtig2":{"name":["文津东路","WENJINDONGLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["sBjNpd"],"children":["pbl0nC"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"pbl0nC":{"name":["珩琅山路","HENGLANSHANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["5Gtig2"],"children":["qDXjRv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300},"qDXjRv":{"name":["芜湖南站","Wuhunan Railway Station"],"secondaryName":false,"num":"00","services":["local"],"parents":["pbl0nC"],"children":["FJpedn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":300},"FJpedn":{"name":["白马山","BAIMASHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["qDXjRv"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":300}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":66,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。

**Comment by wongchito** [comment]
Hi @TPCpp ,

蕪湖軌道交通範本已於 #467 中提供 。如閣下認為閣下所提供範本更佳，請選擇正確的鐵路公司、路線代碼，並提供適當的理由。多謝！
