### ISSUE TITLE
Resources: New templates of Wuhu Rail Transit

### ISSUE THREAD

**Issue by TPCpp** [railmapgen/rmg-templates#626]
**Justification:** 芜湖建了轻轨，我来加2号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="whrt" line="00config"><summary>New company: Wuhu Rail Transit</summary><details type="name">{"en":"Wuhu Rail Transit","zh-Hans":"芜湖轨道交通","zh-Hant":"蕪湖軌道交通"}</details></details>

<details repo="rmg-templates" company="whrt" line="wh1" major="false"><summary>whrt/wh1</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2000,"indoor":2400},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["other","other","#4a86e8","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"stn_IU95Yx_2Sf","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["stn_IU95Yx_2Sf"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["stn_TMwLKjVxof"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_TMwLKjVxof":{"name":["鸠兹广场","JIUZIGUANGCHANG"],"secondaryName":false,"num":"11","services":["local"],"parents":["stn_-sFXhVt84v"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["other","other","#e3002b","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_-sFXhVt84v":{"name":["文化路","WENHUALU"],"secondaryName":false,"num":"10","services":["local"],"parents":["stn_ZS72cPe4R6"],"children":["stn_TMwLKjVxof"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_ZS72cPe4R6":{"name":["神山口","SHENSHANKOU"],"secondaryName":false,"num":"9","services":["local"],"parents":["stn_YAKtr3Cky0"],"children":["stn_-sFXhVt84v"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_YAKtr3Cky0":{"name":["芜湖火车站","Wuhu Railway Station"],"secondaryName":false,"num":"8","services":["local"],"parents":["stn_sMv7zDCgzL"],"children":["stn_ZS72cPe4R6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_sMv7zDCgzL":{"name":["神山公园","SHENSHANGONGYUAN"],"secondaryName":false,"num":"7","services":["local"],"parents":["stn_QZjMiavyIw"],"children":["stn_YAKtr3Cky0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_QZjMiavyIw":{"name":["云从路","YUNCONGLU1"],"secondaryName":false,"num":"6","services":["local"],"parents":["stn_U8N_6Xru-9"],"children":["stn_sMv7zDCgzL"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_U8N_6Xru-9":{"name":["政务中心","ZHENGWUZHONGXIN"],"secondaryName":false,"num":"5","services":["local"],"parents":["stn_567zv3FLxN"],"children":["stn_QZjMiavyIw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_567zv3FLxN":{"name":["海晏路","HAIYANLU"],"secondaryName":false,"num":"4","services":["local"],"parents":["stn_UuRFSHxsGu"],"children":["stn_U8N_6Xru-9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_UuRFSHxsGu":{"name":["红花山路","HONGHUASHANLU"],"secondaryName":false,"num":"3","services":["local"],"parents":["stn_a7MnDv272P"],"children":["stn_567zv3FLxN"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_a7MnDv272P":{"name":["徽州路","HUIZHOULU"],"secondaryName":false,"num":"2","services":["local"],"parents":["stn_IU95Yx_2Sf"],"children":["stn_UuRFSHxsGu"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"stn_IU95Yx_2Sf":{"name":["万春湖路","WANCHUNHULU\\"],"secondaryName":false,"num":"1","services":["local"],"parents":["linestart"],"children":["stn_a7MnDv272P"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"2","psd_num":"1","info_panel_type":"sh","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，请不要删除原有的1号线，谢谢:)

**Comment by wongchito** [comment]
Hi @TPCpp ,

蕪湖軌道交通範本已於 #457 中提供 。如閣下認為閣下所提供範本更佳，請選擇正確的鐵路公司、路線代碼，並提供適當的理由。多謝！
