### ISSUE TITLE
Resources: New templates of Wenzhou Rail Transit

### ISSUE THREAD

**Issue by FLYER2048** [railmapgen/rmg-templates#629]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 近期温州S2线开通，新增该线路。
参考资料：www.wzmtr.com

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="wzmtr" line="00config"><summary>New company: Wenzhou Rail Transit</summary><details type="name">{"en":"Wenzhou Rail Transit","zh-Hans":"温州轨道交通","zh-Hant":"溫州軌道交通"}</details></details>

<details repo="rmg-templates" company="wzmtr" line="wzs2" major="false"><summary>wzmtr/wzs2</summary><details type="name">{"en":"Line S2","zh-Hans":"S2线","zh-Hant":"S2綫"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":16,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["wenzhou","wzs2","#e4002b","#fff"],"line_name":["S2线","Line S2"],"current_stn_idx":"fK1mzz","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["72OI-L"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"72OI-L":{"name":["清东路","Qingdong Road"],"secondaryName":false,"num":"01","services":["local","express"],"parents":["linestart"],"children":["p-64UV"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]},{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"p-64UV":{"name":["旭阳路","Xuyang Road"],"secondaryName":false,"num":"02","services":["local","express"],"parents":["72OI-L"],"children":["ae2hfC"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["fK1mzz"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ae2hfC":{"name":["万岙","Wan'ao"],"secondaryName":false,"num":"00","services":["local"],"parents":["p-64UV"],"children":["6TO0I_"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"fK1mzz":{"name":["东山","Dongshan"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["7pU9vy"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"7pU9vy":{"name":["上东路","Shangdong Road"],"secondaryName":false,"num":"00","services":["local"],"parents":["xW3n0R"],"children":["fK1mzz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"xW3n0R":{"name":["上望","Shangwang"],"secondaryName":false,"num":"00","services":["local"],"parents":["mYqlH9"],"children":["7pU9vy"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"mYqlH9":{"name":["莘塍","Xincheng"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["_Xy_h6"],"children":["xW3n0R"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"_Xy_h6":{"name":["汀田","Tingtian"],"secondaryName":false,"num":"00","services":["local"],"parents":["QwUdeS"],"children":["mYqlH9"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QwUdeS":{"name":["大典下","Dadianxia"],"secondaryName":false,"num":"00","services":["local"],"parents":["KzEc2k"],"children":["_Xy_h6"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"KzEc2k":{"name":["鲍田","Baotian"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["wPRYGV"],"children":["QwUdeS"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"wPRYGV":{"name":["海城","Haicheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["qUCkhz"],"children":["KzEc2k"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qUCkhz":{"name":["天河","Tianhe"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["NN8HB_"],"children":["wPRYGV"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"NN8HB_":{"name":["沙城","Shacheng"],"secondaryName":false,"num":"00","services":["local"],"parents":["IdyuhA"],"children":["qUCkhz"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IdyuhA":{"name":["永兴","Yongxing"],"secondaryName":false,"num":"00","services":["local"],"parents":["Jsrd6O"],"children":["NN8HB_"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Jsrd6O":{"name":["机场","Airport"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["SDU2Qs"],"children":["IdyuhA"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wenzhou","wzs1","#0061ae","#fff"],"name":["S1线","Line S1"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SDU2Qs":{"name":["灵昆","Lingkun"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["I1Xrlr"],"children":["Jsrd6O"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["wenzhou","wzs1","#0061ae","#fff"],"name":["S1线","Line S1"]}]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"I1Xrlr":{"name":["柳市东","Liushi East"],"secondaryName":false,"num":"00","services":["local"],"parents":["3xgAho"],"children":["SDU2Qs"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"3xgAho":{"name":["翁垟","Wengyang"],"secondaryName":false,"num":"00","services":["local","express"],"parents":["EUbVdF"],"children":["I1Xrlr"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"EUbVdF":{"name":["新望","Xinwang"],"secondaryName":false,"num":"00","services":["local"],"parents":["6TO0I_"],"children":["3xgAho"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"6TO0I_":{"name":["盐盆","Yanpen"],"secondaryName":false,"num":"00","services":["local"],"parents":["ae2hfC"],"children":["EUbVdF"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[]}]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1}}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板包括但不限于以下问题：
- 2号线其中一站站名应为 **柳市东** 站，而不为 **黄华** 站

_**（如您有异议，请留下您的证明来源）**_

请您修改后 **更新此issue正文（无需新开issue）** ，感谢您的贡献。
_（审核来源：
https://zh.wikipedia.org/wiki/温州市域铁路S2线 ）_

**Comment by FLYER2048** [comment]
已修正“黄华”站的问题，感谢您的仔细审核！
