### ISSUE TITLE
Resources: New templates of MTR

### ISSUE THREAD

**Issue by Takagi-Misae** [railmapgen/rmg-templates#645]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 新增北環線路線圖（該路線尚未開通，請保留至開通後上載至範本，謝謝🙏）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mtr" line="NTL" major="false"><summary>mtr/NTL</summary><details type="name">{"en":"Northern Link","zh-Hans":"北环线","zh-Hant":"北環線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1000,"railmap":2000,"indoor":1200},"svg_height":400,"style":"mtr","y_pc":50,"padding":19,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["hongkong","nol","#a1208a","#fff"],"line_name":["北環線","Northern Link"],"current_stn_idx":"hrDxrW","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["hrDxrW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"hrDxrW":{"name":["錦上路","Kam Sheung Road"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["Ixm0f6"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hongkong","mol","#9A3820","#fff"],"name":["屯馬線","Tuen Ma Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Ixm0f6":{"name":["凹頭","Au Tau"],"secondaryName":false,"num":"02","services":["local"],"parents":["hrDxrW"],"children":["QKpOx0"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["gGpnp9"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"QKpOx0":{"name":["牛潭尾","Ngau Tam Mei"],"secondaryName":false,"num":"03","services":["local"],"parents":["Ixm0f6"],"children":["u1kgJ4"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"u1kgJ4":{"name":["新田","San Tin"],"secondaryName":false,"num":"04","services":["local"],"parents":["QKpOx0"],"children":["gGpnp9"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"gGpnp9":{"name":["古洞","Kwu Tung"],"secondaryName":false,"num":"05","services":["local"],"parents":["u1kgJ4"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["hongkong","eal","#61B4E4","#fff"],"name":["東鐵線","East Rail Line"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"N","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by wongchito** [comment]
Hi @Takagi-Misae ,

由於行政會議尚未通過北環綫的財務安排，該綫尚存較大變數。請於路綫開通後（或車站名稱刊憲後）再次提交。多謝！
