### ISSUE TITLE
Resources: New templates of Shijiazhuang Metro

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#691]
**Justification:** 补充石家庄地铁剩余线路的RMG模版。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="sjzmetro" line="sjz2" major="false"><summary>sjzmetro/sjz2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線","ko":"2호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1600,"indoor":1200},"svg_height":320,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["shijiazhuang","sjz2","#fec30a","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"iNynkk","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["9f5HFw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qQaHfx":{"name":["庄窠·铁道大学","ZHUANGKE·TIEDAODAXUE"],"secondaryName":false,"num":"02","services":["local"],"parents":["ggZTbm"],"children":["iNynkk"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iNynkk":{"name":["柳辛庄","LIUXINZHUANG"],"secondaryName":false,"num":"01","services":["local"],"parents":["qQaHfx"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["iNynkk"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ggZTbm":{"name":["义堂","YITANG"],"secondaryName":false,"num":"03","services":["local"],"parents":["DqlSjC"],"children":["qQaHfx"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"DqlSjC":{"name":["建和桥","JIANHEQIAO"],"secondaryName":false,"num":"04","services":["local"],"parents":["bJx-df"],"children":["ggZTbm"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"bJx-df":{"name":["长安公园","CHANG’ANGONGYUAN"],"secondaryName":false,"num":"05","services":["local"],"parents":["8lEVED"],"children":["DqlSjC"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"8lEVED":{"name":["北国商城","BEIGUOSHANGCHENG"],"secondaryName":false,"num":"06","services":["local"],"parents":["qUu4vG"],"children":["bJx-df"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shijiazhuang","sjz1","#e53e30","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"qUu4vG":{"name":["裕华路","YUHUALU"],"secondaryName":false,"num":"07","services":["local"],"parents":["e-Pl2N"],"children":["8lEVED"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"e-Pl2N":{"name":["槐中路","HUAIZHONGLU"],"secondaryName":false,"num":"08","services":["local"],"parents":["lzVh_M"],"children":["qUu4vG"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lzVh_M":{"name":["欧韵公园","OUYUNGONGYUAN"],"secondaryName":false,"num":"09","services":["local"],"parents":["1rH6Xw"],"children":["e-Pl2N"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1rH6Xw":{"name":["元村","YUANCUN"],"secondaryName":false,"num":"10","services":["local"],"parents":["yzmBUJ"],"children":["lzVh_M"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yzmBUJ":{"name":["石家庄站","SHIJIAZHUANGZHAN"],"secondaryName":false,"num":"11","services":["local"],"parents":["iir3uD"],"children":["1rH6Xw"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shijiazhuang","sjz3","#00a1e0","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"iir3uD":{"name":["塔坛","TATAN"],"secondaryName":false,"num":"12","services":["local"],"parents":["0g62mb"],"children":["yzmBUJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"0g62mb":{"name":["仓丰路留村","CANGFENGLULIUCUN"],"secondaryName":false,"num":"13","services":["local"],"parents":["Zo_Ghs"],"children":["iir3uD"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Zo_Ghs":{"name":["南位","NANWEI"],"secondaryName":false,"num":"14","services":["local"],"parents":["9f5HFw"],"children":["0g62mb"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"9f5HFw":{"name":["嘉华路","JIAHUALU"],"secondaryName":false,"num":"15","services":["local"],"parents":["linestart"],"children":["Zo_Ghs"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"2","psd_num":"","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":76,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

<details repo="rmg-templates" company="sjzmetro" line="sjz3" major="false"><summary>sjzmetro/sjz3</summary><details type="name">{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線","ko":"3호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1800,"indoor":2200},"svg_height":340,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["shijiazhuang","sjz3","#00a1e0","#fff"],"line_name":["3号线","Line 3"],"current_stn_idx":"moQ34B","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["TnCjzS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"2PD9NQ":{"name":["高柱","GAOZHU"],"secondaryName":false,"num":"01","services":["local"],"parents":["Fc0tkW"],"children":["moQ34B"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"moQ34B":{"name":["西三庄","XISANZHUANG"],"secondaryName":false,"num":"02","services":["local"],"parents":["2PD9NQ"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["moQ34B"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Fc0tkW":{"name":["柏林庄","BAILINZHUANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["ZFlA5P"],"children":["2PD9NQ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ZFlA5P":{"name":["市庄","SHIZHUANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["HU-bwu"],"children":["Fc0tkW"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"HU-bwu":{"name":["市二中","SHIERZHONG"],"secondaryName":false,"num":"00","services":["local"],"parents":["f_AFgv"],"children":["ZFlA5P"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"f_AFgv":{"name":["新百广场","XINBAIGUANGCHANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["zzvBhK"],"children":["HU-bwu"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shijiazhuang","sjz1","#e53e30","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":210},"zzvBhK":{"name":["东里","DONGLI"],"secondaryName":false,"num":"00","services":["local"],"parents":["oPct5c"],"children":["f_AFgv"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"oPct5c":{"name":["槐安桥","HUAI’ANQIAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["IxTYXH"],"children":["zzvBhK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"IxTYXH":{"name":["西三教","XISANJIAO"],"secondaryName":false,"num":"00","services":["local"],"parents":["izP9CS"],"children":["oPct5c"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"izP9CS":{"name":["石家庄站","SHIJIAZHUANGZHAN"],"secondaryName":false,"num":"00","services":["local"],"parents":["jTD9sn"],"children":["IxTYXH"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[{"theme":["shijiazhuang","sjz2","#fec30a","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"facility":"railway","loop_pivot":false,"one_line":true,"int_padding":210},"jTD9sn":{"name":["汇通路","HUITONGLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["zElzHY"],"children":["izP9CS"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zElzHY":{"name":["孙村","SUNCUN"],"secondaryName":false,"num":"00","services":["local"],"parents":["eIG7A5"],"children":["jTD9sn"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"eIG7A5":{"name":["塔冢","TAZHONG"],"secondaryName":false,"num":"00","services":["local"],"parents":["AN_t8I"],"children":["zElzHY"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"AN_t8I":{"name":["东王","DONGWANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["Mi4wI3"],"children":["eIG7A5"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Mi4wI3":{"name":["南王","NANWANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["SH0HRJ"],"children":["AN_t8I"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"SH0HRJ":{"name":["位同","WEITONG"],"secondaryName":false,"num":"00","services":["local"],"parents":["WI9uZM"],"children":["Mi4wI3"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"WI9uZM":{"name":["东二环南路","DONG’ERHUANNANLU"],"secondaryName":false,"num":"00","services":["local"],"parents":["yAq6Nl"],"children":["SH0HRJ"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"yAq6Nl":{"name":["西仰陵","XIYANGLING"],"secondaryName":false,"num":"00","services":["local"],"parents":["CYCMVK"],"children":["WI9uZM"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"CYCMVK":{"name":["中仰陵","ZHONGYANGLING"],"secondaryName":false,"num":"00","services":["local"],"parents":["4db3qV"],"children":["yAq6Nl"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"4db3qV":{"name":["南豆","NANDOU"],"secondaryName":false,"num":"00","services":["local"],"parents":["obTVr_"],"children":["CYCMVK"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"obTVr_":{"name":["太行南大街","TAIHANGNANDAJIE"],"secondaryName":false,"num":"00","services":["local"],"parents":["TnCjzS"],"children":["4db3qV"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"TnCjzS":{"name":["乐乡","LEXIANG"],"secondaryName":false,"num":"00","services":["local"],"parents":["linestart"],"children":["obTVr_"],"branch":{"left":[],"right":[]},"transfer":{"groups":[{"lines":[]}],"tick_direc":"r","paid_area":true},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

**Comment by Takagi-Misae** [comment]
您好，您所提交的範本沒有問題，請等待管理員加入至範本，謝謝🙏

審核來源：
https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Shijiazhuang_Metro_System_Map.svg/1920px-Shijiazhuang_Metro_System_Map.svg.png
