### ISSUE TITLE
Templates of Harbin Metro

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [railmapgen/rmg-templates#7]
[hrbmetro.zip](https://github.com/railmapgen/rmg/files/8502648/hrbmetro.zip)

**Comment by AnDanJuneUnderline** [comment]
Three lines(Line 1,Line 2 and Line 3) in Harbin are open. It is three templates in the zipped. Also there is another text in it to call the templates of Harbin Metro.

**Comment by thekingofcity** [comment]
Thank your contribution. They are merged! 🎉
