### ISSUE TITLE
Resources: New templates of Shaoxing Rail Transit

### ISSUE THREAD

**Issue by HangzhouMetroXianingBridge** [railmapgen/rmg-templates#713]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 本人已刪除支線。請通過！

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="sxsmtr" line="sx1" major="false"><summary>sxsmtr/sx1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ja":"1号線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1600,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":6,"branchSpacingPct":37,"direction":"r","platform_num":"","theme":["shaoxing","sx1","#c5003e","#fff"],"line_name":["1号线","Shaoxing Line 1"],"current_stn_idx":"sX780y","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["sX780y"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"sX780y":{"name":["姑娘桥","Guniangqiao"],"num":"01","services":["local"],"parents":["linestart"],"children":["oQIdSj"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hangzhou","hz5","#00afc8","#fff"],"name":["杭5","Hangzhou Line5"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":150},"oCAu-k":{"name":["明珠广场","Mingzhu Square"],"num":"02","services":["local"],"parents":["YACbxd"],"children":["dsreRE"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["Qf54Su"],"children":[],"branch":{},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"oQIdSj":{"name":["衙前","Yaqian"],"num":"00","services":["local"],"parents":["sX780y"],"children":["H2xQna"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"H2xQna":{"name":["杨汛桥","Yangxunqiao"],"num":"00","services":["local"],"parents":["oQIdSj"],"children":["00QexF"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"00QexF":{"name":["前梅","Qianmei"],"num":"00","services":["local"],"parents":["H2xQna"],"children":["MBT1Rl"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"MBT1Rl":{"name":["钱清","Qianqing"],"num":"00","services":["local"],"parents":["00QexF"],"children":["ekFMI8"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"ekFMI8":{"name":["西沙路","Xisha Road"],"num":"00","services":["local"],"parents":["MBT1Rl"],"children":["k3fDsO"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"k3fDsO":{"name":["临杭大道","Linhang Avenue"],"num":"00","services":["local"],"parents":["ekFMI8"],"children":["sM6YPW"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"sM6YPW":{"name":["鉴水路","Jianshui Road"],"num":"00","services":["local"],"parents":["k3fDsO"],"children":["-wB0ck"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"-wB0ck":{"name":["越州大道","Yuezhou Avenue"],"num":"00","services":["local"],"parents":["sM6YPW"],"children":["YACbxd"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"YACbxd":{"name":["中国轻纺城","China Textile City"],"num":"00","services":["local"],"parents":["-wB0ck"],"children":["oCAu-k"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":355},"dsreRE":{"name":["瓜渚湖","Guazhuhu"],"num":"00","services":["local"],"parents":["oCAu-k"],"children":["03PdRF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"03PdRF":{"name":["镜水路","Jingshui Road"],"num":"00","services":["local"],"parents":["dsreRE"],"children":["5PzAMz"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5PzAMz":{"name":["黄酒小镇","Huangjiu Town"],"num":"00","services":["local"],"parents":["03PdRF"],"children":["E_N-03"],"branch":{},"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cH8_Sf":{"name":["奥体中心","Olympic Sports Center"],"num":"00","services":["local"],"parents":["E_N-03"],"children":["0p5vPG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"E_N-03":{"name":["张墅","Zhangshu"],"num":"00","services":["local"],"parents":["5PzAMz"],"children":["cH8_Sf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"0p5vPG":{"name":["梅山广场","Meishan Square"],"num":"00","services":["local"],"parents":["cH8_Sf"],"children":["yXlooX"],"transfer":{"groups":[{"lines":[{"theme":["shaoxing","sx2","#307fe2","#fff"],"name":["2号线","Line2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":150},"yXlooX":{"name":["凤林","fenglin"],"num":"00","services":["local"],"parents":["0p5vPG"],"children":["YuVNRR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YuVNRR":{"name":["大滩","Datan"],"num":"00","services":["local"],"parents":["yXlooX"],"children":["q9qonN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"q9qonN":{"name":["火车站","Railway Station"],"num":"00","services":["local"],"parents":["YuVNRR"],"children":["mLrUAs"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"mLrUAs":{"name":["城市广场","City Square"],"num":"00","services":["local"],"parents":["q9qonN"],"children":["2dutV6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2dutV6":{"name":["鲁迅故里","Luxun Native Place"],"num":"00","services":["local"],"parents":["mLrUAs"],"children":["x-z4Fk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"x-z4Fk":{"name":["城南大道","Chengnan Avenue"],"num":"00","services":["local"],"parents":["2dutV6"],"children":["ZZLsOl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ZZLsOl":{"name":["凤凰山","Fenghuangshan"],"num":"00","services":["local"],"parents":["x-z4Fk"],"children":["XZzBlK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"XZzBlK":{"name":["劳家葑","Laojiafeng"],"num":"00","services":["local"],"parents":["ZZLsOl"],"children":["hs-CxM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hs-CxM":{"name":["南池","Nanchi"],"num":"00","services":["local"],"parents":["XZzBlK"],"children":["isyoe-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"isyoe-":{"name":["栖湖","Qihu"],"num":"00","services":["local"],"parents":["hs-CxM"],"children":["Qf54Su"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Qf54Su":{"name":["芳泉","Fangquan"],"num":"00","services":["local"],"parents":["isyoe-"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.9"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您為什麼要刪除支線呢？一號線支線還在營運哦。

**Comment by 28yfang** [comment]
您好 @Charlis-Wong ，
我查询了多个资料，均显示支线未开通。请问您的依据是什么？
![image](https://github.com/railmapgen/rmg-templates/assets/123239445/f3fb5912-48f9-46c6-b49a-48dfe71f1dc7)
![image](https://github.com/railmapgen/rmg-templates/assets/123239445/84999c80-7f7e-4d33-a5f7-d14bf13ebac7)
![image](https://github.com/railmapgen/rmg-templates/assets/123239445/86e0fcd3-614e-4cc9-b999-043294f5fec1)
![image](https://github.com/railmapgen/rmg-templates/assets/123239445/c025f6aa-fb8d-42e5-9d4e-11328ba62699)

**Comment by Charlis-Wong** [comment]
您好，我已經刪除評論，是我的疏忽，請您見諒。

**Comment by Charlis-Wong** [comment]
您好，您所提交的模板沒有問題，請等待管理員加入至範本，謝謝🙏
