### ISSUE TITLE
Resources: New templates of Nanjing Metro

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-templates#719]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 添加一条线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="njmetro" line="njs9" major="false"><summary>njmetro/njs9</summary><details type="name">{"en":"Line S9","zh-Hans":"S9号线","zh-Hant":"S9號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["nanjing","s9","#f1b434","#fff"],"line_name":["S9号线","Line S9"],"current_stn_idx":"ccku0V","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["ccku0V"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8d2Nbb":{"name":["团结圩","TUANJIEWEI"],"num":"01","services":["local"],"parents":["RBkbnl"],"children":["bnjQZd"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"bnjQZd":{"name":["高淳","GAOCHUN"],"num":"02","services":["local"],"parents":["8d2Nbb"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["bnjQZd"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RBkbnl":{"name":["明觉","MINGJUE"],"num":"00","services":["local"],"parents":["U0y3Ij"],"children":["8d2Nbb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"U0y3Ij":{"name":["石湫","SHIQIU"],"num":"00","services":["local"],"parents":["5BOiLc"],"children":["RBkbnl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5BOiLc":{"name":["铜山","TONGSHAN"],"num":"00","services":["local"],"parents":["ccku0V"],"children":["U0y3Ij"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ccku0V":{"name":["翔宇路南","XIANGYULUNAN"],"num":"00","services":["local"],"parents":["linestart"],"children":["5BOiLc"],"transfer":{"groups":[{"lines":[{"theme":["nanjing","s1","#00b2a9","#fff"],"name":["S1号线","Line S1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.11"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，請等待管理員合拼至範本。感謝您的貢獻🙏

審核來源：https://zh.wikipedia.org/wiki/%E5%8D%97%E4%BA%AC%E5%9C%B0%E9%93%81S9%E5%8F%B7%E7%BA%BF

**Comment by 28yfang** [comment]
> 您好，您所提交的範本沒有問題，請等待管理員合拼至範本。感謝您的貢獻🙏
@Charlis-Wong 您好，RMG模版不会收录未开通线路的模版。
请作者等待线路开通之后再进行上传，感谢您的贡献。
