### ISSUE TITLE
Resources: New templates of Tokyo Metro

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-templates#743]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** https://railmapgen.github.io/rmp-gallery/resources/thumbnails/tokyo.png
添加一条线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tyometro" line="do qdtx" major="false"><summary>tyometro/do qdtx</summary><details type="name">{"en":"Chiyoda Line","zh-Hans":"千代田线","zh-Hant":"千代田線","ja":"千代田線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2500,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["tokyo","c","#1bb267","#fff"],"line_name":["千代田線","Chiyoda Line"],"current_stn_idx":"KgVpo3","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":[],"children":["KgVpo3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1aaMf3":{"name":["北綾瀬","Kita-ayase"],"num":"09","services":["local"],"parents":["bbzyAf"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"bbzyAf":{"name":["綾瀬","Ayase"],"num":"08","services":["local"],"parents":["ZPQMw7"],"children":["1aaMf3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":["1aaMf3"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ZPQMw7":{"name":["北千住","Kita-sanju"],"num":"07","services":["local"],"parents":["9hM_EB"],"children":["bbzyAf"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","h","#c7beb3","#fff"],"name":["日比谷線","Hibiya Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"9hM_EB":{"name":["町屋","Machiya"],"num":"06","services":["local"],"parents":["5rpLUm"],"children":["ZPQMw7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5rpLUm":{"name":["西日暮里","Nishi- nippori"],"num":"05","services":["local"],"parents":["ivu4t7"],"children":["9hM_EB"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ivu4t7":{"name":["千駄木","Sendagi"],"num":"04","services":["local"],"parents":["gXH7Tf"],"children":["5rpLUm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"gXH7Tf":{"name":["根津","Nezu"],"num":"03","services":["local"],"parents":["o-p2Ip"],"children":["ivu4t7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"o-p2Ip":{"name":["湯島","Yushima"],"num":"02","services":["local"],"parents":["-UTlSt"],"children":["gXH7Tf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"-UTlSt":{"name":["新御茶ノ水","Shin-ochanomico"],"num":"01","services":["local"],"parents":["6FzOjv"],"children":["o-p2Ip"],"transfer":{"groups":[{},{"lines":[{"theme":["tokyo","s","#abba41","#fff"],"name":["新宿線","Shinjuku Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["丸之內線","Marunouchi Line"]}],"name":["小川町 淡路町","Ogawamachi Awajicho"]},{"name":["",""]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6FzOjv":{"name":["大手町","Otemachi"],"num":"00","services":["local"],"parents":["d6KGkJ"],"children":["-UTlSt"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","i","#0068a5","#fff"],"name":["三田線","Mita Line"]},{"theme":["tokyo","t","#00a4db","#fff"],"name":["東西線","Tōzai Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["丸之內線","Marunouchi Line"]},{"theme":["tokyo","z","#8c7dba","#fff"],"name":["半藏門線","Hanzōmon Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"d6KGkJ":{"name":["二重橋前〈丸の内〉","Nijubashimae (Marunouchi)"],"num":"00","services":["local"],"parents":["kw-1rh"],"children":["6FzOjv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kw-1rh":{"name":["日比谷","Hibiya"],"num":"00","services":["local"],"parents":["E7S5Fy"],"children":["d6KGkJ"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","i","#0068a5","#fff"],"name":["三田線","Mita Line"]},{"theme":["tokyo","h","#c7beb3","#fff"],"name":["日比谷線","Hibiya Line"]}]},{"lines":[{"theme":["tokyo","y","#d1a662","#fff"],"name":["有樂町線","Yūrakuchō Line"]}],"name":["有楽町","Yurakocho"]}],"tick_direc":"r","paid_area":false},"loop_pivot":false,"one_line":true,"int_padding":355},"E7S5Fy":{"name":["霞ケ関","Kusumigaseki"],"num":"00","services":["local"],"parents":["sT9jI1"],"children":["kw-1rh"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","h","#c7beb3","#fff"],"name":["日比谷線","Hibiya Line"]},{"theme":["tokyo","m","#d92c2f","#fff"],"name":["丸之內線","Marunouchi Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sT9jI1":{"name":["国会議事堂前","Kokkai-gijidomae 【National Diet Bldg.】"],"num":"00","services":["local"],"parents":["Q_gf80"],"children":["E7S5Fy"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","m","#d92c2f","#fff"],"name":["丸之內線","Marunouchi Line"]}]},{"lines":[{"theme":["tokyo","g","#f9a328","#fff"],"name":["銀座線","Ginza Line"]},{"theme":["tokyo","n","#02b69b","#fff"],"name":["南北線","Namboku Line"]}],"name":["溜池山王","Tameike-Sanno"]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Q_gf80":{"name":["赤坂","Akasaka"],"num":"00","services":["local"],"parents":["vzyjcn"],"children":["sT9jI1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vzyjcn":{"name":["乃木坂","Nogizaka"],"num":"00","services":["local"],"parents":["OlPWQN"],"children":["Q_gf80"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"OlPWQN":{"name":["表参道","Omote-sando"],"num":"00","services":["local"],"parents":["gq8Lgb"],"children":["vzyjcn"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","z","#8c7dba","#fff"],"name":["半藏門線","Hanzōmon Line"]},{"theme":["tokyo","g","#f9a328","#fff"],"name":["銀座線","Ginza Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"gq8Lgb":{"name":["明治神宮前〈原宿〉","Meiji-jingumae (Harajuku)"],"num":"00","services":["local"],"parents":["UW8MzO"],"children":["OlPWQN"],"transfer":{"groups":[{"lines":[{"theme":["tokyo","f","#9c5e31","#fff"],"name":["副都心線","Fukutoshin Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"UW8MzO":{"name":["代々木公園","Yoyogi-koen 【Yoyogi Park】"],"num":"00","services":["local"],"parents":["KgVpo3"],"children":["gq8Lgb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"KgVpo3":{"name":["代々木上原","Yoyogi-uehara"],"num":"00","services":["local"],"parents":["linestart"],"children":["UW8MzO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不接受来自画廊的数据，因为它们可能已经过时或有错误，请您选择官方网站（推荐）或维基百科（不推荐）作为参考来源，感谢您的贡献。
