### ISSUE TITLE
Resources: New templates of Nagoya shiei chikatetsu

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-templates#749]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 来源：https://railmapgen.github.io/rmp-gallery/resources/thumbnails/nagoya.png
理由：添加线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mgwsydxt" line="00config"><summary>New company: Nagoya shiei chikatetsu</summary><details type="name">{"en":"Nagoya shiei chikatetsu","zh-Hans":"名古屋市营地下铁","zh-Hant":"名古屋市營地下鐵"}</details></details>

<details repo="rmg-templates" company="mgwsydxt" line="mgw mcx" major="false"><summary>mgwsydxt/mgw mcx</summary><details type="name">{"en":"Meijo Line","zh-Hans":"名城线","zh-Hant":"名城線","ja":"名城線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":3500,"indoor":1200},"svg_height":350,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["nagoya","m","#b074d6","#fff"],"line_name":["名城線","Meijo Line"],"current_stn_idx":"i7Ajtn","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["i7Ajtn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"i7Ajtn":{"name":["金山","Kanayama"],"num":"01","services":["local"],"parents":["linestart"],"children":["ke1Fq_"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","e","#b074d6","#fff"],"name":["名港線","Meiko Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ke1Fq_":{"name":["東別院","Higashi Betsuin"],"num":"02","services":["local"],"parents":["i7Ajtn"],"children":["FepVVT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["5lzBEq"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"FepVVT":{"name":["上前津","Kamimaezu"],"num":"03","services":["local"],"parents":["ke1Fq_"],"children":["WVZvDT"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","t","#009bbf","#fff"],"name":["鶴舞線","Tsurumai Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WVZvDT":{"name":["矢場町","Yaba-cho"],"num":"04","services":["local"],"parents":["FepVVT"],"children":["yEacIw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"yEacIw":{"name":["栄","Sakae"],"num":"05","services":["local"],"parents":["WVZvDT"],"children":["7AUr-5"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","h","#fab123","#fff"],"name":["東山線","Higashiyama Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7AUr-5":{"name":["久屋大通","Hisaya-odori"],"num":"06","services":["local"],"parents":["yEacIw"],"children":["A_f_fu"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","s","#c92f44","#fff"],"name":["桜通線","Sakura-dori Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"A_f_fu":{"name":["名古屋城","Nagoyajo (Nagoya Castle)"],"num":"07","services":["local"],"parents":["7AUr-5"],"children":["cATe5A"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cATe5A":{"name":["名城公園","Meijo Koen"],"num":"08","services":["local"],"parents":["A_f_fu"],"children":["vv5FiJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vv5FiJ":{"name":["黒川","Kurokawa"],"num":"09","services":["local"],"parents":["cATe5A"],"children":["iSRvZA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"iSRvZA":{"name":["志賀本通","Shiga-hondori"],"num":"10","services":["local"],"parents":["vv5FiJ"],"children":["uG44jT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"uG44jT":{"name":["平安通","Heian-dori"],"num":"11","services":["local"],"parents":["iSRvZA"],"children":["D-6O06"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","k","#fc78b4","#fff"],"name":["上飯田線","Kamiiida Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"D-6O06":{"name":["大曽根","Ozone"],"num":"12","services":["local"],"parents":["uG44jT"],"children":["seD2zN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"seD2zN":{"name":["ナゴヤドーム前矢田","Nagoya Dome-mae Yada"],"num":"13","services":["local"],"parents":["D-6O06"],"children":["C2jdbj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"C2jdbj":{"name":["砂田橋","Sunada-bashi"],"num":"14","services":["local"],"parents":["seD2zN"],"children":["m5t3JR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"m5t3JR":{"name":["茶屋ヶ坂","Chayagasaka"],"num":"15","services":["local"],"parents":["C2jdbj"],"children":["aMyDw4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aMyDw4":{"name":["自由ヶ丘","Jiyugaoka"],"num":"16","services":["local"],"parents":["m5t3JR"],"children":["Yx8SDa"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Yx8SDa":{"name":["本山","Motoyama"],"num":"17","services":["local"],"parents":["aMyDw4"],"children":["DfOQN6"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","h","#fab123","#fff"],"name":["東山線","Higashiyama Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"DfOQN6":{"name":["名古屋大学","Nagoya Daigaku"],"num":"18","services":["local"],"parents":["Yx8SDa"],"children":["2w1t2Q"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2w1t2Q":{"name":["八事日赤","Yagoto Nisseki"],"num":"19","services":["local"],"parents":["DfOQN6"],"children":["bmnjT1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"bmnjT1":{"name":["八事","Yagoto"],"num":"20","services":["local"],"parents":["2w1t2Q"],"children":["s83lvz"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","t","#009bbf","#fff"],"name":["鶴舞線","Tsurumai Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"s83lvz":{"name":["総合リハビリセンター","Sogo Rihabiri Center"],"num":"21","services":["local"],"parents":["bmnjT1"],"children":["GdTCsb"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GdTCsb":{"name":["瑞穂運動場東","Mizuho Undojo Higashi"],"num":"22","services":["local"],"parents":["s83lvz"],"children":["zNvDcN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zNvDcN":{"name":["新瑞橋","Aratama-bashi"],"num":"23","services":["local"],"parents":["GdTCsb"],"children":["3ki3Ue"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","s","#c92f44","#fff"],"name":["桜通線","Sakura-dori Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3ki3Ue":{"name":["妙音通","Myoon-dori"],"num":"24","services":["local"],"parents":["zNvDcN"],"children":["zCFBi-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zCFBi-":{"name":["堀田","Horita"],"num":"25","services":["local"],"parents":["3ki3Ue"],"children":["Ib9gEj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Ib9gEj":{"name":["熱田神宮伝馬町","Atsuta Jingu Temma-cho"],"num":"26","services":["local"],"parents":["zCFBi-"],"children":["6xqWrz"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6xqWrz":{"name":["熱田神宮西","Atsuta Jingu Nishi"],"num":"27","services":["local"],"parents":["Ib9gEj"],"children":["5lzBEq"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5lzBEq":{"name":["西高蔵","Nishi Takakura"],"num":"28","services":["local"],"parents":["6xqWrz"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"M","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

<details repo="rmg-templates" company="mgwsydxt" line="mgw mgx" major="false"><summary>mgwsydxt/mgw mgx</summary><details type="name">{"en":"Meiko Line","zh-Hans":"名港线","zh-Hant":"名港線","ja":"名港線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":350,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["nagoya","e","#b074d6","#fff"],"line_name":["名港線","Meiko Line"],"current_stn_idx":"Wm55mi","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["Wm55mi"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Wm55mi":{"name":["金山","Kanayama"],"num":"01","services":["local"],"parents":["linestart"],"children":["H17KJ5"],"transfer":{"groups":[{"lines":[{"theme":["nagoya","m","#b074d6","#fff"],"name":["名城線","Meijo Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"H17KJ5":{"name":["日比野","Hibino"],"num":"02","services":["local"],"parents":["Wm55mi"],"children":["pNXs9g"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["hfvdGr"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pNXs9g":{"name":["六番町","Rokuban-cho"],"num":"03","services":["local"],"parents":["H17KJ5"],"children":["O8aRUA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"O8aRUA":{"name":["東海通","Tokai-dori"],"num":"04","services":["local"],"parents":["pNXs9g"],"children":["GBk9ua"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GBk9ua":{"name":["港区役所","Minato Kuyakusho"],"num":"05","services":["local"],"parents":["O8aRUA"],"children":["zBb-mT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zBb-mT":{"name":["築地口","Tsukiji-guchi"],"num":"06","services":["local"],"parents":["GBk9ua"],"children":["hfvdGr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hfvdGr":{"name":["名古屋港","Nagoyako (Nagoya Port)"],"num":"07","services":["local"],"parents":["zBb-mT"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"E","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不接受来自画廊的数据，因为它们可能已经过时或有错误，请您选择官方网站（推荐）或维基百科（不推荐）作为参考来源，感谢您的贡献。
由于您已经在 #743 #753 中出现过相同的问题，在此我们再次提醒您不要选择画廊作为参考链接:)
