### ISSUE TITLE
Resources: New templates of Hangzhou Metro

### ISSUE THREAD

**Issue by bobo45-1** [railmapgen/rmg-templates#761]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 缺少杭州地铁2号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hzmetro" line="00config"><summary>New company: Hangzhou Metro</summary><details type="name">{"en":"Hangzhou Metro","zh-Hans":"杭州地铁","zh-Hant":"杭州地鐵"}</details></details>

<details repo="rmg-templates" company="hzmetro" line="hz2" major="false"><summary>hzmetro/hz2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號綫"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":2200,"indoor":2200},"svg_height":450,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["hangzhou","hz2","#f1803a","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"b8ys0z","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["wuryB8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wuryB8":{"name":["朝阳","Chaoyang"],"num":"01","services":["local"],"parents":["linestart"],"children":["b8ys0z"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"b8ys0z":{"name":["曹家桥","Caojiaqiao"],"num":"02","services":["local"],"parents":["wuryB8"],"children":["ojx4ww"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["hhFak1"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ojx4ww":{"name":["潘水","Panshui"],"num":"00","services":["local"],"parents":["b8ys0z"],"children":["rlvaIm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"rlvaIm":{"name":["人民路","Renmin Road"],"num":"00","services":["local"],"parents":["ojx4ww"],"children":["SXiL4H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"SXiL4H":{"name":["杭发厂","Hangfachang"],"num":"00","services":["local"],"parents":["rlvaIm"],"children":["a1Edjw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"a1Edjw":{"name":["人民广场","People's Square"],"num":"00","services":["local"],"parents":["SXiL4H"],"children":["TXtrZ2"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"TXtrZ2":{"name":["建设一路","Jiansheyi Road"],"num":"00","services":["local"],"parents":["a1Edjw"],"children":["CxAZdx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"CxAZdx":{"name":["建设三路","Jianshesan Road"],"num":"00","services":["local"],"parents":["TXtrZ2"],"children":["RPUJ9P"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz7","#87189D","#fff"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RPUJ9P":{"name":["振宁路","Zhenning Road"],"num":"00","services":["local"],"parents":["CxAZdx"],"children":["kjtpZz"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kjtpZz":{"name":["飞虹路","Feihong Road"],"num":"00","services":["local"],"parents":["RPUJ9P"],"children":["82noNM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"82noNM":{"name":["盈丰路","Yingfeng Road"],"num":"00","services":["local"],"parents":["kjtpZz"],"children":["3esRpK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3esRpK":{"name":["钱江世纪城","Qianjiang Century City"],"num":"00","services":["local"],"parents":["82noNM"],"children":["QF39go"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz6","#0072CE","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pbIvo7":{"name":["庆春广场","Qingchun Square"],"num":"00","services":["local"],"parents":["QF39go"],"children":["5o4D-A"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QF39go":{"name":["钱江路","Qianjiang Road"],"num":"00","services":["local"],"parents":["3esRpK"],"children":["pbIvo7"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz4","#6CC24A","#fff"],"name":["4号线","Line 4"]},{"theme":["hangzhou","hz9","#BE4D00","#fff"],"name":["9号线","Line 9"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5o4D-A":{"name":["庆菱路","Qingling Road"],"num":"00","services":["local"],"parents":["pbIvo7"],"children":["BNN1t8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"BNN1t8":{"name":["建国北路","North Jianguo Road"],"num":"00","services":["local"],"parents":["5o4D-A"],"children":["whzqke"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"whzqke":{"name":["中和北路","North Zhonghe Road"],"num":"00","services":["local"],"parents":["BNN1t8"],"children":["jDBuRM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"jDBuRM":{"name":["凤起路","Fengqi Road"],"num":"00","services":["local"],"parents":["whzqke"],"children":["pqdpR0"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz1","#DF4661","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pqdpR0":{"name":["武林门","Wulinmen"],"num":"00","services":["local"],"parents":["jDBuRM"],"children":["3v-gFt"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz3","#ffcd00","#000"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3v-gFt":{"name":["沈塘桥","Shentangqiao"],"num":"00","services":["local"],"parents":["pqdpR0"],"children":["4xJatp"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz19","#05c3de","#fff"],"name":["机场快线","Airport Express"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4xJatp":{"name":["下宁桥","Xianingqiao"],"num":"00","services":["local"],"parents":["3v-gFt"],"children":["1cXgE7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1cXgE7":{"name":["学院路","Xueyuan Road"],"num":"00","services":["local"],"parents":["4xJatp"],"children":["QncnEg"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz10","#daaa00","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QncnEg":{"name":["古翠路","Gucui Road"],"num":"00","services":["local"],"parents":["1cXgE7"],"children":["t8VjtR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"t8VjtR":{"name":["丰潭路","Fengtan Road"],"num":"00","services":["local"],"parents":["QncnEg"],"children":["Wup64k"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Wup64k":{"name":["文新","Wenxin"],"num":"00","services":["local"],"parents":["t8VjtR"],"children":["dCOrqC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"dCOrqC":{"name":["三坝","Sanba"],"num":"00","services":["local"],"parents":["Wup64k"],"children":["MbNeGT"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz5","#00AEC7","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"MbNeGT":{"name":["虾龙圩","Xialongwei"],"num":"00","services":["local"],"parents":["dCOrqC"],"children":["6ehDii"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6ehDii":{"name":["三墩","Sandun"],"num":"00","services":["local"],"parents":["MbNeGT"],"children":["mNzBUr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"mNzBUr":{"name":["墩祥街","Dunxiang Street"],"num":"00","services":["local"],"parents":["6ehDii"],"children":["rHWh64"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"rHWh64":{"name":["金家渡","Jinjiadu"],"num":"00","services":["local"],"parents":["mNzBUr"],"children":["oTwC_j"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz4","#6CC24A","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"oTwC_j":{"name":["白洋","Baiyang"],"num":"00","services":["local"],"parents":["rHWh64"],"children":["VeU34z"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"VeU34z":{"name":["杜甫村","Dufucun"],"num":"00","services":["local"],"parents":["oTwC_j"],"children":["hhFak1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hhFak1":{"name":["良渚","Liangzhu"],"num":"00","services":["local"],"parents":["VeU34z"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.11.#576-Configure-nameDirection-in-indoor-stations-of-shmetro.7657b7d"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，我这边看杭州地铁模板里是有2号线的哦，请问您是不是看错了😂
<img width="1792" alt="截屏2023-10-05 14 20 24" src="https://github.com/railmapgen/rmg-templates/assets/99594702/32273b3f-9a60-45f7-9b1b-6021f22d96c5">
