### ISSUE TITLE
Resources: New templates of Hangzhou Metro

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmg-templates#763]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 增加杭海城际线路图

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="hzmetro" line="hangzhouhainingintercityrail" major="false"><summary>hzmetro/hangzhouhainingintercityrail</summary><details type="name">{"en":"Hangzhou-Haining Intercity Rail","zh-Hans":"杭海城际","zh-Hant":"杭海城際"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1500,"railmap":1500,"indoor":1500},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["hangzhou","hangzhouhainingintercityrail","#0077c8","#fff"],"line_name":["杭海城际","Hangzhou-Haining Intercity Rail"],"current_stn_idx":"stn_MvMqZtE2W0","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["stn_MvMqZtE2W0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["stn_H4fkBusGQm"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_H4fkBusGQm":{"name":["浙大国际校区","International Campus, ZJU"],"num":"12","services":["local"],"parents":["stn_TdUBMpZS6j"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_TdUBMpZS6j":{"name":["海昌路","Haichang Road"],"num":"11","services":["local"],"parents":["stn_OKnZYzKjfr"],"children":["stn_H4fkBusGQm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_OKnZYzKjfr":{"name":["皮革城","Leather City"],"num":"10","services":["local"],"parents":["stn_GVDs-aaMkR"],"children":["stn_TdUBMpZS6j"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_GVDs-aaMkR":{"name":["斜桥","Xieqiao"],"num":"9","services":["local"],"parents":["stn_DY_aNBVfxo"],"children":["stn_OKnZYzKjfr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_DY_aNBVfxo":{"name":["桐九公路","Tongjiu Highway"],"num":"8","services":["local"],"parents":["stn_QjVwsq8N1T"],"children":["stn_GVDs-aaMkR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_QjVwsq8N1T":{"name":["盐官","Yanguan"],"num":"7","services":["local"],"parents":["stn_8_cijcKY3V"],"children":["stn_DY_aNBVfxo"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_8_cijcKY3V":{"name":["周王庙","Zhouwangmiao"],"num":"6","services":["local"],"parents":["stn_Z70pHhBvu2"],"children":["stn_QjVwsq8N1T"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_Z70pHhBvu2":{"name":["长安东","Chang'an East"],"num":"5","services":["local"],"parents":["stn_QSl7Wipp9-"],"children":["stn_8_cijcKY3V"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_QSl7Wipp9-":{"name":["长安（东方学院）","Chang'an(Oriental College)"],"num":"4","services":["local"],"parents":["stn_2ns-tlIdVA"],"children":["stn_Z70pHhBvu2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_2ns-tlIdVA":{"name":["海宁高铁西站","Hainingxi Railway Station"],"num":"3","services":["local"],"parents":["stn_OJ0BMEJxu8"],"children":["stn_QSl7Wipp9-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_OJ0BMEJxu8":{"name":["许村","Xucun"],"num":"2","services":["local"],"parents":["stn_MvMqZtE2W0"],"children":["stn_2ns-tlIdVA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"stn_MvMqZtE2W0":{"name":["临平南高铁站","Linpingnan Railway Station"],"num":"1","services":["local"],"parents":["linestart"],"children":["stn_OJ0BMEJxu8"],"transfer":{"groups":[{"lines":[{"theme":["hangzhou","hz9","#c45b03","#fff"],"name":["9号线","Line 9"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":150}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"","psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本有一個小問題
- 長安（東方學院）站的英文名字錯誤。該站加註名稱的英文應該是 Oriental College，並非 Dongfang College。

**Comment by Windows-Taskmgr** [comment]
已修复👍🏻

**Comment by Charlis-Wong** [comment]
好的，請等待管理員合拼
