### ISSUE TITLE
Resources: New templates of Beijing Subway

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmg-templates#767]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 增加北京地铁17北段templates

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="bjsubway" line="bj17n" major="false"><summary>bjsubway/bj17n</summary><details type="name">{"en":"Line 17 (North Section)","zh-Hans":"17号线（北段）","zh-Hant":"17號線（北段）"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":400,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["beijing","bj17","#00A9A9","#fff"],"line_name":["17号线","Line 17"],"current_stn_idx":"0r_lQ1","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["O9e43U"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"O9e43U":{"name":["工人体育场","Gongren Tiyuchang\\(Workers' Stadium)"],"num":"01","services":["local"],"parents":["linestart"],"children":["0r_lQ1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"0r_lQ1":{"name":["左家庄","Zuojiazhuang"],"num":"02","services":["local"],"parents":["O9e43U"],"children":["fXDfp0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["w5Y1vF"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"fXDfp0":{"name":["西坝河","Xibahe"],"num":"00","services":["local"],"parents":["0r_lQ1"],"children":["YrxdXu"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"YrxdXu":{"name":["太阳宫","Taiyanggong"],"num":"00","services":["local"],"parents":["fXDfp0"],"children":["_4kDOY"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"_4kDOY":{"name":["望京西","Wangjing Xi (W)"],"num":"00","services":["local"],"parents":["YrxdXu"],"children":["HZxlK6"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj13","#f9e700","#000"],"name":["13号线","Line 13"]},{"theme":["beijing","bj15","#5b2c68","#fff"],"name":["15号线","Line 15"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"HZxlK6":{"name":["红军营","Hongjunying"],"num":"00","services":["local"],"parents":["_4kDOY"],"children":["Gy45BN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"Gy45BN":{"name":["清河营","Qingheying"],"num":"00","services":["local"],"parents":["HZxlK6"],"children":["51l-CN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"51l-CN":{"name":["天通苑东","Tiantongyuan Dong (E)"],"num":"00","services":["local"],"parents":["Gy45BN"],"children":["ByLZrp"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"w5Y1vF":{"name":["未来科学城北","Weilai Kexuecheng Bei (N)\\(Science City of the Future North)"],"num":"00","services":["local"],"parents":["ByLZrp"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355,"branch":{}},"ByLZrp":{"name":["未来科学城","Weilai Kexuecheng\\(Science City of the Future)"],"num":"00","services":["local"],"parents":["51l-CN"],"children":["w5Y1vF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by langonginc** [comment]
- 工人体育场站应为 `Gongrentiyuchang\\(Workers' Stadium)`
- 望京西站应为 `Wangjingxi`
- 天通苑东 `Tiantongyuandong`
- 未来科学城 `Weilaikexuecheng\\(Future Science City)`
- 未来科学城北 `Weilaikexuechengbei\\(Future Science City North)`

参考 slack 频道图片。来自 b站。
