### ISSUE TITLE
Resources: New templates of Suzhou Rail Transit

### ISSUE THREAD

**Issue by beiguangrailtransit** [railmapgen/rmg-templates#794]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 1.理由：2023年8月，苏州高新有轨电车2号线的南京大学东方向支线开通了，对原有模板进行了更新。
2.参考资料：“苏州高新有轨电车”微信公众号，同时实地考察。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmtr" line="suzhoutram2" major="false"><summary>szmtr/suzhoutram2</summary><details type="name">{"en":"SND Tram Line 2","zh-Hans":"高新有轨电车2号线","zh-Hant":"高新有軌電車2號線","ko":"고신구 전차 2호선"}</details><details type="param">{"svgWidth":{"destination":1700,"runin":1300,"railmap":1900,"indoor":1300},"svg_height":500,"style":"shmetro","y_pc":50,"padding":9,"branchSpacingPct":42,"direction":"l","platform_num":"","theme":["other","other","#d85600","#fff"],"line_name":["高新有轨电车2号线","SND Tram Line 2"],"current_stn_idx":"J3d6jL","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["8ltzRJ","zgjeB_"],"branch":{"right":["through","8ltzRJ"]},"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"J3d6jL":{"name":["龙康路","Longkanglu"],"num":"02","services":["local"],"parents":["UqrKdO"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","tram","#d8e4c0","#fff"],"name":["有轨电车1号线","Tram Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["ednSB-","J3d6jL"],"children":[],"branch":{"left":["through","ednSB-"]},"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"CSLlrS":{"name":["漓江路","Lijianglu"],"num":"00","services":["local"],"parents":["L1SJEP"],"children":["UqrKdO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"L1SJEP":{"name":["恩顾山","Engushan"],"num":"00","services":["local"],"parents":["IBUswv"],"children":["CSLlrS"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"IBUswv":{"name":["白龙桥","Bailongqiao"],"num":"00","services":["local"],"parents":["m6nEP7"],"children":["L1SJEP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"m6nEP7":{"name":["树山","Shushan"],"num":"00","services":["local"],"parents":["SUeTWg"],"children":["IBUswv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"SUeTWg":{"name":["通安","Tongan"],"num":"00","services":["local"],"parents":["HbZ5d-"],"children":["m6nEP7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HbZ5d-":{"name":["华通花园南","Huatonghuayuan South"],"num":"00","services":["local"],"parents":["Xk3gm8"],"children":["SUeTWg"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Xk3gm8":{"name":["建通桥","Jiantongqiao"],"num":"00","services":["local"],"parents":["fEes6i"],"children":["HbZ5d-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fEes6i":{"name":["虎疁路","Huliulu"],"num":"00","services":["local"],"parents":["nz6DDH"],"children":["Xk3gm8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"nz6DDH":{"name":["兴贤桥北","Xingxianqiao North"],"num":"00","services":["local"],"parents":["v4Mg2o"],"children":["fEes6i"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"v4Mg2o":{"name":["鸿福路","Hongfulu"],"num":"00","services":["local"],"parents":["8ltzRJ","zgjeB_"],"children":["nz6DDH"],"branch":{"left":["through","8ltzRJ"]},"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zgjeB_":{"name":["苏州新区火车站","Suzhou Xinqu Railway Station"],"num":"00","services":["local"],"parents":["linestart"],"children":["v4Mg2o"],"transfer":{"groups":[{},{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["轨道交通3号线","Rail Transit Line 3"],"facility":"hsr"}],"name":["苏州新区火车站","Suzhou Xinqu Railway Station"]}],"tick_direc":"r","paid_area":false},"loop_pivot":false,"one_line":true,"int_padding":355},"8ltzRJ":{"name":["文昌路","Wenchanglu"],"num":"00","services":["local"],"parents":["linestart"],"children":["v4Mg2o"],"transfer":{"groups":[{},{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["轨道交通3号线","Rail Transit Line 3"]}],"name":["文昌路","Wenchanglu"]}],"tick_direc":"r","paid_area":false},"loop_pivot":false,"one_line":true,"int_padding":355},"UqrKdO":{"name":["航舶浜","Hongbobang"],"num":"00","services":["local"],"parents":["CSLlrS"],"children":["gvWvdu","J3d6jL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{"right":["through","gvWvdu"]}},"gvWvdu":{"name":["龙塘港路","Longtangganglu"],"num":"00","services":["local"],"parents":["UqrKdO"],"children":["ednSB-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ednSB-":{"name":["南京大学东","Nanjing University East"],"num":"00","services":["local"],"parents":["gvWvdu"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，請吧（Replace Me/替代我）刪除，以便bot識別，感謝您的配合🙏

**Comment by Charlis-Wong** [comment]
您好，如果此issue超過一個月不回覆，將會被刪除，敬請留意，謝謝🙏
