### ISSUE TITLE
Resources: New templates of Taizhou Rail Transit

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#819]
**Justification:** 提供台州轨道交通的RMG模板。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="taizhourail" line="00config"><summary>New company: Taizhou Rail Transit</summary><details type="name">{"en":"Taizhou Rail Transit","zh-Hans":"台州轨道交通","zh-Hant":"台州軌道交通"}</details></details>

<details repo="rmg-templates" company="taizhourail" line="tzs1" major="false"><summary>taizhourail/tzs1</summary><details type="name">{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1線","ko":"S1선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1400,"indoor":1200},"svg_height":330,"style":"gzmtr","y_pc":50,"padding":5,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["other","other","#2392e7","#fff"],"line_name":["S1线","Line S1"],"current_stn_idx":"jw-NXN","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["jw-NXN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"jw-NXN":{"name":["台州火车站","Taizhou Huochezhan"],"num":"01","services":["local"],"parents":["linestart"],"children":["qLKAs3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"qLKAs3":{"name":["学院路","Xueyuan Lu"],"num":"02","services":["local"],"parents":["jw-NXN"],"children":["w400yd"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["JP6tMt"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"w400yd":{"name":["国博中心","Guobo Zhongxin"],"num":"03","services":["local"],"parents":["qLKAs3"],"children":["4EAqSJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4EAqSJ":{"name":["汇丰路","Huifeng Lu"],"num":"04","services":["local"],"parents":["w400yd"],"children":["t2-pyI"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"t2-pyI":{"name":["锦泰","Jintai"],"num":"05","services":["local"],"parents":["4EAqSJ"],"children":["4b2yxF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"4b2yxF":{"name":["恩泽医院","Enze Yiyuan"],"num":"06","services":["local"],"parents":["t2-pyI"],"children":["CYwx6x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"CYwx6x":{"name":["台州汽车南站","Taizhou Qiche Nanzhan"],"num":"07","services":["local"],"parents":["4b2yxF"],"children":["W5xNWt"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"W5xNWt":{"name":["泽国","Zeguo"],"num":"08","services":["local"],"parents":["CYwx6x"],"children":["yxvK-t"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"yxvK-t":{"name":["温岭火车站","Wenling Huochezhan"],"num":"09","services":["local"],"parents":["W5xNWt"],"children":["1W9rd_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"1W9rd_":{"name":["汇川王","Huichuanwang"],"num":"10","services":["local"],"parents":["yxvK-t"],"children":["tf0NM8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"tf0NM8":{"name":["温岭第一人民医院","Wenling Diyi Renmin Yiyuan"],"num":"11","services":["local"],"parents":["1W9rd_"],"children":["KNUVVr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"KNUVVr":{"name":["九龙大道","Jiulong Dadao"],"num":"12","services":["local"],"parents":["tf0NM8"],"children":["tRxj6H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"tRxj6H":{"name":["万昌路","Wanchang Lu"],"num":"13","services":["local"],"parents":["KNUVVr"],"children":["MB2gjv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"MB2gjv":{"name":["南屏","Nanping"],"num":"14","services":["local"],"parents":["tRxj6H"],"children":["JP6tMt"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{}},"JP6tMt":{"name":["城南","Chengnan"],"num":"15","services":["local"],"parents":["MB2gjv"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"S1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":51,"direction_gz_y":79,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，請等待管理員合拼至範本。感謝您的貢獻🙏
