### ISSUE TITLE
Resources: New templates of Shenzhen Metro

### ISSUE THREAD

**Issue by 450481201110181493** [railmapgen/rmg-templates#82]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/rmg-templates/new and paste the palette data below_

**Justification:** 来源：http://map.baidu.com/?subwayShareId=shenzhen,340

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmetro" line="sz6z"><summary>szmetro/sz6z</summary><details type="name">{"en":"Branch Line 6","zh-Hans":"6号线支线","zh-Hant":"6號線支線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"1","theme":["shenzhen","sz6b","#168773","#fff"],"line_name":["6号线支线","Branch Line 1"],"current_stn_idx":"zNdKcE","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"secondaryName":false,"num":"00","services":["local"],"parents":[],"children":["zNdKcE"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"zNdKcE":{"name":["光明","Guangming"],"secondaryName":false,"num":"01","services":["local"],"parents":["linestart"],"children":["1hGIqE"],"branch":{"left":[],"right":[]},"transfer":{"info":[[["shenzhen","sz6","#00C7B1","#fff","6号线","Line 6"]]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"Dch3ok":{"name":["深理工","SIAT"],"secondaryName":false,"num":"02","services":["local"],"parents":["ij0yH8"],"children":["lineend"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"secondaryName":false,"num":"00","services":["local"],"parents":["Dch3ok"],"children":[],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"1hGIqE":{"name":["圳美","Zhenmei"],"secondaryName":false,"num":"00","services":["local"],"parents":["zNdKcE"],"children":["ij0yH8"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355},"ij0yH8":{"name":["中大","Sun Yat-sen University"],"secondaryName":false,"num":"00","services":["local"],"parents":["1hGIqE"],"children":["Dch3ok"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","notesGZMTR":[],"direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1}}</details></details>

陈允宸

**Comment by 52PD** [comment]
您好，经检查目前你提交的模版有以下问题：

* 光明站往深理大列车运行方向错误。

请在对照以上内容进行修改后将修改的模版提交至本issue下。

感谢您对本项目的支持与贡献！

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路模版问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
