### ISSUE TITLE
Resources: New templates of Busan Transportation Corporation

### ISSUE THREAD

**Issue by Hzr061534** [railmapgen/rmg-templates#823]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 更正换乘信息，部分车站中文译名，更新车站编号
详情：
https://namu.wiki/w/%EB%8F%99%ED%95%B4%EC%84%A0%20%EA%B4%91%EC%97%AD%EC%A0%84%EC%B2%A0

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="HUMetro" line="Donghae" major="false"><summary>HUMetro/Donghae</summary><details type="name">{"en":"Gwangyeok Jeoncheol Donghae Line","zh-Hans":"广域电铁东海线","zh-Hant":"廣域電鐵 東海線","ko":"광역전철 동해선"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":2000,"railmap":3000,"indoor":1200},"svg_height":500,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"2","theme":["busan","budh","#004ea3","#fff"],"line_name":["东海线","Donghae Line "],"current_stn_idx":"QJ0bpr","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":[],"children":["QJ0bpr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2LigoM":{"name":["巨堤迎日","Geojehaemaji\\거제해맞이"],"num":"11","services":["local"],"parents":["QJ0bpr"],"children":["o0sA7x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QJ0bpr":{"name":["釜田","Bujeon\\부전"],"num":"10","services":["local"],"parents":["linestart"],"children":["2LigoM"],"transfer":{"groups":[{"lines":[{"theme":["busan","bu1","#f06a00","#fff"],"name":["1号线","Line 1"]}]},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":90},"lineend":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":["esd3sc"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"o0sA7x":{"name":["巨堤","Geoje\\거제"],"num":"12","services":["local"],"parents":["2LigoM"],"children":["CiZgEZ"],"transfer":{"groups":[{"lines":[{"theme":["busan","bu3","#bb8c00","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":85},"CiZgEZ":{"name":["教大","Busan Nat'l Univ.of Edu.\\교대"],"num":"13","services":["local"],"parents":["o0sA7x"],"children":["XzgUUm"],"transfer":{"groups":[{"lines":[{"theme":["busan","bu1","#f06a00","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":155},"XzgUUm":{"name":["东莱","Dongnae\\동래"],"num":"14","services":["local"],"parents":["CiZgEZ"],"children":["55MLAc"],"transfer":{"groups":[{"lines":[{"theme":["busan","bu4","#217dcb","#fff"],"name":["4号线","Line 4"]}]},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":95},"55MLAc":{"name":["安乐","Allak\\안락"],"num":"15","services":["local"],"parents":["XzgUUm"],"children":["BMxaRr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"BMxaRr":{"name":["釜山院洞","Busanwondong\\부산원동"],"num":"16","services":["local"],"parents":["55MLAc"],"children":["Mq_n_p"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Mq_n_p":{"name":["栽松","Jaesong\\재송"],"num":"17","services":["local"],"parents":["BMxaRr"],"children":["OZ2TuZ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"OZ2TuZ":{"name":["Centum","Centum\\센텀"],"num":"18","services":["local"],"parents":["Mq_n_p"],"children":["KAcaSE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"KAcaSE":{"name":["釜山会展中心（BEXCO)","BEXCO\\벡스코"],"num":"19","services":["local"],"parents":["OZ2TuZ"],"children":["1Q16t5"],"transfer":{"groups":[{"lines":[{"theme":["busan","bu2","#81bf48","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":235},"1Q16t5":{"name":["新海云台","Sinhaeundae\\신해운대"],"num":"20","services":["local"],"parents":["KAcaSE"],"children":["HJ99Uh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HJ99Uh":{"name":["松亭","Songjeong\\송정"],"num":"21","services":["local"],"parents":["1Q16t5"],"children":["PztFe7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"PztFe7":{"name":["东釜山旅游区","OSIRIA\\오시리아"],"num":"22","services":["local"],"parents":["HJ99Uh"],"children":["O7hh8O"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"O7hh8O":{"name":["机张","Gijang\\기장"],"num":"23","services":["local"],"parents":["PztFe7"],"children":["wxVIYW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wxVIYW":{"name":["日光","Ilgwang\\일광"],"num":"24","services":["local"],"parents":["O7hh8O"],"children":["eTbL4E"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"eTbL4E":{"name":["佐川","Jwacheon\\좌천"],"num":"25","services":["local"],"parents":["wxVIYW"],"children":["tWYmX4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"tWYmX4":{"name":["月内","Wollae\\월내"],"num":"26","services":["local"],"parents":["eTbL4E"],"children":["oFu2fJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"oFu2fJ":{"name":["西生","Seosaeng\\서생"],"num":"27","services":["local"],"parents":["tWYmX4"],"children":["dTzmbX"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"dTzmbX":{"name":["南仓","Namchang\\남창"],"num":"28","services":["local"],"parents":["oFu2fJ"],"children":["HawQTx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HawQTx":{"name":["望阳","Mangyang\\망양"],"num":"29","services":["local"],"parents":["dTzmbX"],"children":["Z13Fnn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Z13Fnn":{"name":["德下","Deokha\\덕하"],"num":"30","services":["local"],"parents":["HawQTx"],"children":["vWRqKL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vWRqKL":{"name":["开云浦","Gaeunpo\\개운포"],"num":"31","services":["local"],"parents":["Z13Fnn"],"children":["DZYppr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"DZYppr":{"name":["太和江","Taehwagang\\태화강"],"num":"32","services":["local"],"parents":["vWRqKL"],"children":["esd3sc"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"esd3sc":{"name":["北蔚山","Bugulsan\\북울산"],"num":"33","services":["local"],"parents":["DZYppr"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"K1","psd_num":"15","info_panel_type":"gzgf","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，請等待管理員合拼至範本，感謝您的貢獻🙏
