### ISSUE TITLE
Resources: New templates of Gwangju Transit Corporation

### ISSUE THREAD

**Issue by Hzr061534** [railmapgen/rmg-templates#831]
Hi RMG team! I would like to contribute the templates below.

**Justification:** 新增光州都市铁道1号线的RMG模板
参考资料：
_https://namu.wiki/w/%EA%B4%91%EC%A3%BC%20%EB%8F%84%EC%8B%9C%EC%B2%A0%EB%8F%84%201%ED%98%B8%EC%84%A0_

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gjmetro" line="00config"><summary>New company: Gwangju Transit Corporation</summary><details type="name">{"en":"Gwangju Transit Corporation","zh-Hans":"光州交通公社","zh-Hant":"光州交通公社"}</details></details>

<details repo="rmg-templates" company="gjmetro" line="g1" major="false"><summary>gjmetro/g1</summary><details type="name">{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ko":"1호선"}</details><details type="param">{"svgWidth":{"destination":2000,"runin":2000,"railmap":3500,"indoor":1800},"svg_height":500,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#009088","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"nJsqZU","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["7ieY4s"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"gnWNJT":{"name":["所台","Sotae\\소태"],"num":"01","services":["local"],"parents":["_k7ZKy"],"children":["nJsqZU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"nJsqZU":{"name":["鹿洞","Nokdong\\녹동"],"num":"00","services":["local"],"parents":["gnWNJT"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["nJsqZU"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"_k7ZKy":{"name":["鹤洞·证心寺入口","Hakdong·Jeungsimsa\\학동·증심사입구"],"num":"02","services":["local"],"parents":["9MZyj6"],"children":["gnWNJT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"9MZyj6":{"name":["南光州","Namgwangju\\남광주"],"num":"03","services":["local"],"parents":["_rdxI3"],"children":["_k7ZKy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":125},"_rdxI3":{"name":["文化殿堂（旧道厅）","Asia Culture Center(Formerly Provincial Office)\\문화전당(구도청)"],"num":"04","services":["local"],"parents":["aXi0yA"],"children":["9MZyj6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aXi0yA":{"name":["锦南路四街","Geumnamno 4(sa)-ga\\금남로4가"],"num":"05","services":["local"],"parents":["EQP-ES"],"children":["_rdxI3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EQP-ES":{"name":["锦南路五街","Geumnamno 5(o)-ga\\금남로5가"],"num":"06","services":["local"],"parents":["e5d9-A"],"children":["aXi0yA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"e5d9-A":{"name":["良洞市场","Yangdong Market\\양동시장"],"num":"07","services":["local"],"parents":["qBN4n3"],"children":["EQP-ES"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"qBN4n3":{"name":["石脊","Dolgogae\\돌고개"],"num":"08","services":["local"],"parents":["QDxGFX"],"children":["e5d9-A"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QDxGFX":{"name":["农城","Nongseong\\농성"],"num":"09","services":["local"],"parents":["pJ3i52"],"children":["qBN4n3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pJ3i52":{"name":["花亭","Hwajeong\\화정"],"num":"10","services":["local"],"parents":["WUER1-"],"children":["QDxGFX"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WUER1-":{"name":["双村","Ssangchon\\쌍촌"],"num":"11","services":["local"],"parents":["wm4y2z"],"children":["pJ3i52"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wm4y2z":{"name":["云泉","Uncheon\\운천"],"num":"12","services":["local"],"parents":["2GrDKC"],"children":["WUER1-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2GrDKC":{"name":["尚武","Sangmu\\상무"],"num":"13","services":["local"],"parents":["rM7a4f"],"children":["wm4y2z"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":95},"rM7a4f":{"name":["金大中会展中心（马勒）","Kim Daejung Convention Center(Mareuk)\\김대중컨벤션센터(마륵)"],"num":"14","services":["local"],"parents":["BRwt0J"],"children":["2GrDKC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"BRwt0J":{"name":["机场","Airport\\공항"],"num":"15","services":["local"],"parents":["lY2W0k"],"children":["rM7a4f"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lY2W0k":{"name":["松汀公园","Songjeong Park\\송정공원"],"num":"16","services":["local"],"parents":["QUlDrD"],"children":["BRwt0J"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QUlDrD":{"name":["光州松汀站","Gwangju Songjeong Station\\광주송정역"],"num":"17","services":["local"],"parents":["Ip4v2C"],"children":["lY2W0k"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Ip4v2C":{"name":["道山","Dosan\\도산"],"num":"18","services":["local"],"parents":["7ieY4s"],"children":["QUlDrD"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7ieY4s":{"name":["平洞","Pyeongdong\\평동"],"num":"19","services":["local"],"parents":["linestart"],"children":["Ip4v2C"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"07","info_panel_type":"gzgf","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的來源連結並不是官方網站/維基百科的連結，請附上正確來源的連結，感謝您的配合🙏

**Comment by Hzr061534** [comment]
@Charlis-Wong 維基百科連結:
https://zh.m.wikipedia.org/wiki/%E5%85%89%E5%B7%9E%E9%83%BD%E5%B8%82%E9%93%81%E9%81%931%E5%8F%B7%E7%BA%BF

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本有以下的問題：
- 根據維基百科，石脊站的站名錯誤，應為石脊站，並非石嶺站

請編輯issue，以作修改。感謝您的貢獻與配合🙏

**Comment by Hzr061534** [comment]
> 您好，您所提交的範本有以下的問題：
> 
> * 根據維基百科，石脊站的站名錯誤，應為石脊站，並非石嶺站
> 
> 請編輯issue，以作修改。感謝您的貢獻與配合🙏 （補充：光州地鐵2號線還在興建階段，修改後的路線圖，將會在2號線完工後加入至範本，謝謝🙏）

@Charlis-Wong 感謝指正😃 光州都市鐵道2號線預計2026年開通，因此在重新上傳的模板內會暫時刪除與2號線的換乘信息

**Comment by Charlis-Wong** [comment]
@28yfang Please Close This Issue，Thanks
