### ISSUE TITLE
广州地铁8号线修正

### ISSUE THREAD

**Issue by s1s1s1s1s1s** [railmapgen/rmg-templates#84]
[gz8.zip](https://github.com/railmapgen/rmg-templates/files/10519146/gz8.zip)
8号线西村站已于2022.12.28开通

_BELOW CONTENT IS ADDED BY @wongchito ON BEHALF OF @s1s1s1s1s1s BASED ON THE LATEST UPDATE_

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="gzmtr" line="gz8"><summary>gzmtr/gz8</summary><details type="name">{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}</details><details type="param">{"style":"gzmtr","svg_height":300,"padding":2.300062293353778,"y_pc":40,"theme":["guangzhou","gz8","#008C95","#fff"],"direction":"l","current_stn_idx":"iwf6","platform_num":"3","stn_list":{"linestart":{"parents":[],"children":["9nrj"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["iwf6"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","num":"00","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["4e8p"],"children":["iwf6"],"name":["琶洲","Pazhou"],"branch":{"left":[],"right":[]},"num":"27","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["lineend"],"parents":["l1mz"],"name":["万胜围","Wanshengwei"],"branch":{"left":[],"right":[]},"num":"28","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz4","#00843D","#fff","4号线","Line 4"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"4e8p":{"parents":["i8pd"],"children":["l1mz"],"name":["新港东","Xingangdong"],"branch":{"left":[],"right":[]},"num":"26","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"i8pd":{"parents":["e3cn"],"children":["4e8p"],"name":["磨碟沙","Modiesha"],"branch":{"left":[],"right":[]},"num":"25","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz18","#0047BA","#fff","18号线","Line 18"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"e3cn":{"parents":["rltg"],"children":["i8pd"],"name":["赤岗","Chigang"],"branch":{"left":[],"right":[]},"num":"24","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"rltg":{"parents":["qbz7"],"children":["e3cn"],"name":["客村","Kecun"],"branch":{"left":[],"right":[]},"num":"23","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz3","#ECA154","#000","3号线","Line 3"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"qbz7":{"parents":["kmeu"],"children":["rltg"],"name":["鹭江","Lujiang"],"branch":{"left":[],"right":[]},"num":"22","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"kmeu":{"parents":["denz"],"children":["qbz7"],"name":["中大","Sun Yat-sen\\University"],"branch":{"left":[],"right":[]},"num":"21","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"denz":{"parents":["kuvx"],"children":["kmeu"],"name":["晓港","Xiaogang"],"branch":{"left":[],"right":[]},"num":"20","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"kuvx":{"parents":["lddl"],"children":["denz"],"name":["昌岗","Changgang"],"branch":{"left":[],"right":[]},"num":"19","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz2","#00629B","#fff","2号线","Line 2"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"lddl":{"parents":["bp86"],"children":["kuvx"],"name":["宝岗大道","Baogang Dadao"],"branch":{"left":[],"right":[]},"num":"18","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"bp86":{"parents":["6t9l"],"children":["lddl"],"name":["沙园","Shayuan"],"branch":{"left":[],"right":[]},"num":"17","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gfl","#C4D600","#fff","广佛线","Guangfo Line"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"6t9l":{"parents":["5eff"],"children":["bp86"],"name":["凤凰新村","Fenghuang Xincun"],"branch":{"left":[],"right":[]},"num":"16","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"5eff":{"parents":["788p"],"children":["6t9l"],"name":["同福西","Tongfuxi"],"branch":{"left":[],"right":[]},"num":"15","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"788p":{"parents":["i92z"],"children":["5eff"],"name":["文化公园","Cultural Park"],"branch":{"left":[],"right":[]},"num":"14","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz6","#80225F","#fff","6号线","Line 6"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"i92z":{"parents":["d7sq"],"children":["788p"],"name":["华林寺","Hualinsi\\Buddist Temple"],"branch":{"left":[],"right":[]},"num":"13","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"d7sq":{"parents":["cjU28a"],"children":["i92z"],"name":["陈家祠","Chen Clan Academy"],"branch":{"left":[],"right":[]},"num":"12","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz1","#F3D03E","#000","1号线","Line 1"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"yjqb":{"parents":["xbp3"],"children":["cjU28a"],"name":["西村","Xicun"],"branch":{"left":[],"right":[]},"num":"10","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz5","#C5003E","#fff","5号线","Line 5"]]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"xbp3":{"parents":["d0jg"],"children":["yjqb"],"name":["鹅掌坦","Ezhangtan"],"branch":{"left":[],"right":[]},"num":"09","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"d0jg":{"parents":["31cw"],"children":["xbp3"],"name":["同德","Tongde"],"branch":{"left":[],"right":[]},"num":"08","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"31cw":{"parents":["dsaz"],"children":["d0jg"],"name":["上步","Shangbu"],"branch":{"left":[],"right":[]},"num":"07","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"dsaz":{"parents":["2tdp"],"children":["31cw"],"name":["聚龙","Julong"],"branch":{"left":[],"right":[]},"num":"06","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"2tdp":{"parents":["uyzf"],"children":["dsaz"],"name":["石潭","Shitan"],"branch":{"left":[],"right":[]},"num":"05","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"uyzf":{"parents":["olyz"],"children":["2tdp"],"name":["小坪","Xiaoping"],"branch":{"left":[],"right":[]},"num":"04","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"olyz":{"parents":["77dn"],"children":["uyzf"],"name":["石井","Shijing"],"branch":{"left":[],"right":[]},"num":"03","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"77dn":{"parents":["9nrj"],"children":["olyz"],"name":["亭岗","Tinggang"],"branch":{"left":[],"right":[]},"num":"02","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"9nrj":{"parents":["linestart"],"children":["77dn"],"name":["滘心","Jiaoxin"],"branch":{"left":[],"right":[]},"num":"01","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false,"loop_pivot":false,"one_line":false,"int_padding":355},"cjU28a":{"name":["彩虹桥","Caihongqiao"],"secondaryName":false,"num":"11","services":["local"],"parents":["yjqb"],"children":["d7sq"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":"","loop_pivot":false,"one_line":true,"int_padding":355}},"line_name":["8号线","Line 8"],"psd_num":"20","line_num":"8","info_panel_type":"gz28","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":true,"terminal":false},"svgWidth":{"destination":1000,"runin":1000,"railmap":1800,"indoor":1800},"notesGZMTR":[],"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":30}</details></details>

**Comment by 52PD** [comment]
您好，经检查目前你提交的模版有以下问题：

- 万胜围站往滘心方向站台编号错误。

请在对照以上内容进行修改后将修改的模版提交至本issue下。

感谢您对本项目的支持与贡献！

**Comment by s1s1s1s1s1s** [comment]
[RMG_KNt5ugNZHYeJoDFFq76cR.zip](https://github.com/railmapgen/rmg-templates/files/10531607/RMG_KNt5ugNZHYeJoDFFq76cR.zip)

**Comment by 52PD** [comment]
没问题了，感谢您对本项目的支持！
