### ISSUE TITLE
Resources: New templates of Nantong Rail Transit

### ISSUE THREAD

**Issue by Bachongshenzi1453** [railmapgen/rmg-templates#860]
**Justification:** 【更改了幸福站与先锋站的位置】增加南通地铁2号线（暂未开通）。参考网站：https://service.ntrailway.com/#/Siteguides

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="ntrailway" line="nt2" major="false"><summary>ntrailway/nt2</summary><details type="name">{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線","ko":"2호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1400,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":4,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["nantong","nt2","#0072c8","#fff"],"line_name":["2号线","Line 2"],"current_stn_idx":"sRDyv-","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":[],"children":["kAVh9a"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sRDyv-":{"name":["先锋","Xianfeng"],"num":"01","services":["local"],"parents":["J_zp7d"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kAVh9a":{"name":["幸福","Xingfu"],"num":"02","services":["local"],"parents":["linestart"],"children":["-zWCQU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":["sRDyv-"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"-zWCQU":{"name":["南通火车站","Nantong Railway Station"],"num":"00","services":["local"],"parents":["kAVh9a"],"children":["pIcRR_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"hsr"},"pIcRR_":{"name":["长岸","Chang‘an"],"num":"00","services":["local"],"parents":["-zWCQU"],"children":["MR1KPV"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"MR1KPV":{"name":["北大街","Bei Dajie"],"num":"00","services":["local"],"parents":["pIcRR_"],"children":["8fjMv8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8fjMv8":{"name":["北城大桥","Beicheng Bridge"],"num":"00","services":["local"],"parents":["MR1KPV"],"children":["mdXTVH"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"mdXTVH":{"name":["钟秀西路","Zhongxiu Xilu"],"num":"00","services":["local"],"parents":["8fjMv8"],"children":["kcMtE-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kcMtE-":{"name":["和平桥","Hepingqiao"],"num":"00","services":["local"],"parents":["mdXTVH"],"children":["RKCqtO"],"transfer":{"groups":[{"lines":[{"theme":["nantong","nt1","#e60012","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RKCqtO":{"name":["体育公园","Sports Park"],"num":"00","services":["local"],"parents":["kcMtE-"],"children":["hMLpTz"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hMLpTz":{"name":["易家桥","Yijiaqiao"],"num":"00","services":["local"],"parents":["RKCqtO"],"children":["j0CY50"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"j0CY50":{"name":["文峰","Wenfeng"],"num":"00","services":["local"],"parents":["hMLpTz"],"children":["FFEXHa"],"transfer":{"groups":[{"lines":[{"theme":["nantong","nt1","#e60012","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"FFEXHa":{"name":["五一路","Wuyi Lu"],"num":"00","services":["local"],"parents":["j0CY50"],"children":["GZuVsW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GZuVsW":{"name":["园林路","Yuanlin Lu"],"num":"00","services":["local"],"parents":["FFEXHa"],"children":["N8hdr7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"N8hdr7":{"name":["汽车东站","East Coach Station"],"num":"00","services":["local"],"parents":["GZuVsW"],"children":["sltvfw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sltvfw":{"name":["通富北路","Tongfu Beilu"],"num":"00","services":["local"],"parents":["N8hdr7"],"children":["Q5GE8H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Q5GE8H":{"name":["观音山","Guanyinshan"],"num":"00","services":["local"],"parents":["sltvfw"],"children":["J_zp7d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"J_zp7d":{"name":["南通东站","Nantongdong Railway Station"],"num":"00","services":["local"],"parents":["Q5GE8H"],"children":["sRDyv-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"hsr"}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本有以下的問題
- 幸福站的位置錯誤，應在路線右端的終點站
- 先鋒站的位置錯誤，應在路線左端的終點站

請編輯本issue以作修改，感謝您的貢獻🙏
