### ISSUE TITLE
Resources: New templates of Fuzhou Metro

### ISSUE THREAD

**Issue by Bachongshenzi1453** [railmapgen/rmg-templates#864]
**Justification:** 增加福州地铁4号线一期首通段（凤凰池-帝封江）来源：http://www.fzmtr.com/html/fzdt/xlcx/index.html    【本线已于2023年8月27日开通】

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="fzmtr" line="fz4" major="false"><summary>fzmtr/fz4</summary><details type="name">{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號綫","ko":"4호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1800,"indoor":1750},"svg_height":450,"style":"shmetro","y_pc":50,"padding":9,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["fuzhou","fz4","#ff7f41","#fff"],"line_name":["4号线","Line 4"],"current_stn_idx":"K6mnMK","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["N1P8Mn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"N1P8Mn":{"name":["凤凰池","Fenghuangchi"],"num":"01","services":["local"],"parents":["linestart"],"children":["pDJ0w8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"K6mnMK":{"name":["帝封江","Difengjiang"],"num":"02","services":["local"],"parents":["i9U6er"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz5","#893b67","#fff"],"name":["5号线","Line 5"]},{"theme":["fuzhou","fzbh","#00adbb","#fff"],"name":["滨海快线","Binhai Express"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["K6mnMK"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"pDJ0w8":{"name":["陆庄","Luzhuang"],"num":"00","services":["local"],"parents":["N1P8Mn"],"children":["8d2dqg"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"8d2dqg":{"name":["西门","Ximen"],"num":"00","services":["local"],"parents":["pDJ0w8"],"children":["4TDxZE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"4TDxZE":{"name":["东街口","Dongjiekou"],"num":"00","services":["local"],"parents":["8d2dqg"],"children":["WX0e1F"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#d90010","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"WX0e1F":{"name":["省立医院","Provincial Hospital"],"num":"00","services":["local"],"parents":["4TDxZE"],"children":["rtQQX3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"rtQQX3":{"name":["东门","Dongmen"],"num":"00","services":["local"],"parents":["WX0e1F"],"children":["15MtqP"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fzbh","#00adbb","#fff"],"name":["滨海快线","Binhai Express"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"15MtqP":{"name":["三角池","Sanjiaochi"],"num":"00","services":["local"],"parents":["rtQQX3"],"children":["ne3_Tj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"ne3_Tj":{"name":["竹屿","Zhuyu"],"num":"00","services":["local"],"parents":["15MtqP"],"children":["YcqBlf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"YcqBlf":{"name":["横屿","Hengyu"],"num":"00","services":["local"],"parents":["ne3_Tj"],"children":["w2kse8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"w2kse8":{"name":["后屿","Houyu"],"num":"00","services":["local"],"parents":["YcqBlf"],"children":["yUerkm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"yUerkm":{"name":["前屿","Qianyu"],"num":"00","services":["local"],"parents":["w2kse8"],"children":["iYzOYm"],"transfer":{"groups":[{"lines":[{"theme":["fuzhou","fz2","#325928","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"iYzOYm":{"name":["光明港","Guangminggang"],"num":"00","services":["local"],"parents":["yUerkm"],"children":["mldXRO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"mldXRO":{"name":["鳌峰洲","Aofengzhou"],"num":"00","services":["local"],"parents":["iYzOYm"],"children":["xbP71L"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"xbP71L":{"name":["花海公园","Huahai Park"],"num":"00","services":["local"],"parents":["mldXRO"],"children":["at1Xph"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"at1Xph":{"name":["会展中心","Exhibition Center"],"num":"00","services":["local"],"parents":["xbP71L"],"children":["hh2_Ox"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"hh2_Ox":{"name":["林浦","Linpu"],"num":"00","services":["local"],"parents":["at1Xph"],"children":["OXZWWW"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#0861de","#fff"],"name":["6号线","Line 6"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"OXZWWW":{"name":["城门","Chengmen"],"num":"00","services":["local"],"parents":["hh2_Ox"],"children":["i9U6er"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#d90010","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200},"i9U6er":{"name":["螺洲温泉","Luozhou Hot Spring"],"num":"00","services":["local"],"parents":["OXZWWW"],"children":["K6mnMK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":200}},"namePosMTR":{"isStagger":true,"isFlip":false},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，由于有贡献者在 #633 里提交了福州4号线的模板，我们遵循“先到先得”原则，及先投稿的issue优先汇入，因此此issue不能被汇入，在此深表歉意，感谢您的贡献。
