### ISSUE TITLE
Resources: New templates of Tianjin Metro

### ISSUE THREAD

**Issue by Kevin0214Lmetro** [railmapgen/rmg-templates#866]
**Justification:** 添加津静线
原因津静线早已开工
来源wiki及百度百科、360百科

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tjrt" line="津静线" major="false"><summary>tjrt/津静线</summary><details type="name">{"en":"Jinjing Line","zh-Hans":"津静线","zh-Hant":"津靜線","ja":"津静線","ko":"진정선"}</details><details type="param">{"svgWidth":{"destination":2270,"runin":1200,"railmap":2000,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["other","other","#0090CE","#fff"],"line_name":["津静线","Jinjing Line"],"current_stn_idx":"Fe8OL2","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":[],"children":["cbeUkq","ZNAo2J"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{"right":["through","ZNAo2J"]}},"k6iyeZ":{"name":["紫金山路","Zijinshan Road"],"num":"01","services":["local"],"parents":["8nGxj1"],"children":["fEM-sN"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8nGxj1":{"name":["文化中心","Cultural Centre"],"num":"02","services":["local"],"parents":["3tiI_t"],"children":["k6iyeZ"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj5","#fb6f14","#fff"],"name":["",""]},{"theme":["tianjin","tj6","#9f216f","#fff"],"name":["",""]},{"theme":["tianjin","tj11","#ed0066","#fff"],"name":["",""]},{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":["Fe8OL2","DkeAbW"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{"left":["through","DkeAbW"]}},"wgDgt_":{"name":["团泊西","Tuanboxi"],"num":"00","services":["local"],"parents":["HYGhpo"],"children":["HFkwdo","-K5GrP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{"right":["through","-K5GrP"]}},"HYGhpo":{"name":["精武镇","Jingwuzhen"],"num":"00","services":["local"],"parents":["77q1Xc"],"children":["wgDgt_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"77q1Xc":{"name":["京华东道","Jinghua East Road"],"num":"00","services":["local"],"parents":["fEM-sN"],"children":["HYGhpo"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj5","#fb6f14","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fEM-sN":{"name":["于边邓路","Yubiandeng Road"],"num":"00","services":["local"],"parents":["k6iyeZ","Hz1yJR"],"children":["77q1Xc"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj13","#def148","#000"],"name":["",""]},{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"branch":{"left":["through","Hz1yJR"]}},"ZNAo2J":{"name":["南站","Tianjinnan Railway Station"],"num":"00","services":["local"],"parents":["linestart"],"children":["Hz1yJR"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj3","#128bbe","#fff"],"name":["",""]}]}],"tick_direc":"l","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Hz1yJR":{"name":["工西路","Gongxi Road"],"num":"00","services":["local"],"parents":["ZNAo2J"],"children":["fEM-sN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Fe8OL2":{"name":["子牙产业园","Ziya Chanyeyuan "],"num":"00","services":["local"],"parents":["cPt9JF"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"-K5GrP":{"name":["国际医学城","International Medical City"],"num":"00","services":["local"],"parents":["wgDgt_"],"children":["_9y0Er"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cPt9JF":{"name":["静海西站","Jinghai West Railway Station"],"num":"00","services":["local"],"parents":["HFkwdo"],"children":["Fe8OL2"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HFkwdo":{"name":["静海北站","Jinghai North Railway Station"],"num":"00","services":["local"],"parents":["wgDgt_"],"children":["cPt9JF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"DkeAbW":{"name":["大邱庄","Daqiuzhuang"],"num":"00","services":["local"],"parents":["_9y0Er"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"_9y0Er":{"name":["健康产业园","Health Industrial Park"],"num":"00","services":["local"],"parents":["-K5GrP"],"children":["DkeAbW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cbeUkq":{"name":["滨海国际机场  ","Binhai International Airport"],"num":"00","services":["local"],"parents":["linestart"],"children":["RS8rvg"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj2","#ece114","#000"],"name":["",""]},{"theme":["tianjin","z2","#1d6b9a","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RS8rvg":{"name":["新兴村"," Xinxingcun"],"num":"00","services":["local"],"parents":["cbeUkq"],"children":["O8Rr5l"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj4","#1c7736","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"O8Rr5l":{"name":[" 新立 "," Xinli"],"num":"00","services":["local"],"parents":["RS8rvg"],"children":["kWFAbB"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj9","#063a91","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kWFAbB":{"name":["海河南路 ","Haihe South Road"],"num":"00","services":["local"],"parents":["O8Rr5l"],"children":["yV5IKw"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"yV5IKw":{"name":["环宇道 ","Huanyu Road"],"num":"00","services":["local"],"parents":["kWFAbB"],"children":["3tiI_t"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj10","#b9cf09","#fff"],"name":["",""]},{"theme":["tianjin","tj11","#ed0066","#fff"],"name":["",""]},{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3tiI_t":{"name":["尖山路","Jianshan Road"],"num":"00","services":["local"],"parents":["yV5IKw"],"children":["8nGxj1"],"transfer":{"groups":[{"lines":[{"theme":["tianjin","tj6","#9f216f","#fff"],"name":["",""]},{"theme":["tianjin","z1","#626da7","#fff"],"name":["",""]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，我们不支持来自百度百科、360百科的数据，请您换一个可靠的来源再进行提交，感谢您的贡献。
（请您在收到此消息后一个月内及时回复，超过此时间我们会拒绝汇入，尽请谅解。）

**Comment by Charlis-Wong** [comment]
@Windows-Taskmgr 
TA不是説還有wiki的來源嗎？

**Comment by Kevin0214Lmetro** [comment]
有哪些支持的来源？

**Comment by 52PD** [comment]
> 您好，我们不支持来自百度百科、360百科的数据，请您换一个可靠的来源再进行提交，感谢您的贡献。

“仅限维基百科/官方来源”只针对线路颜色和国外的线路图，如果是国内的线路图用百度百科是可以使用的（尤其是车站名称这一块，如果线路是冷门线路（比如某些2010s新建的地铁系统）的话维基百科反而是不可靠来源）

当然无论是线路图还是颜色最好都是选官方资料（可以是官网或者政府文件或者实地拍摄）

**Comment by 52PD** [comment]
Closed as the issue discontinued and replaced by #876 .
