### ISSUE TITLE
Resources: New templates of SMRT

### ISSUE THREAD

**Issue by Bachongshenzi1453** [railmapgen/rmg-templates#896]
**Justification:** 增加新加坡地铁有限公司（SMRT）与新加坡地铁东西线，南北线，樟宜机场支线的模版。    来源：http://journey.smrt.com.sg/journey/mrt_network_map/

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="smrt" line="00config"><summary>New company: SMRT</summary><details type="name">{"en":"SMRT","zh-Hans":"新加坡地铁有限公司","zh-Hant":"新加坡捷運有限公司"}</details></details>

<details repo="rmg-templates" company="smrt" line="nsl" major="false"><summary>smrt/nsl</summary><details type="name">{"en":"North South Line","zh-Hans":"南北线","zh-Hant":"南北線","ko":"남북선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1400,"railmap":1800,"indoor":1200},"svg_height":400,"style":"gzmtr","y_pc":50,"padding":3,"branchSpacingPct":33,"direction":"l","platform_num":"01","theme":["singapore","nsl","#DA291C","#fff"],"line_name":["南北线","North South Line"],"current_stn_idx":"Np1r0D","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["38rGgm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"38rGgm":{"name":["裕廊东","Jurong East"],"num":"1","services":["local"],"parents":["linestart"],"children":["brYcnT"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ewl","#009739","#fff"],"name":["东西线","East West Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Np1r0D":{"name":["滨海南码头","Marina South Pier"],"num":"28","services":["local"],"parents":["LkWimI"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["Np1r0D"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"brYcnT":{"name":["武吉巴督","Bukit Batok"],"num":"2","services":["local"],"parents":["38rGgm"],"children":["00QdAa"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"00QdAa":{"name":["武吉甘柏","Bukit Gombak"],"num":"3","services":["local"],"parents":["brYcnT"],"children":["2muUmo"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2muUmo":{"name":["蔡厝港","Choa Chu Kang"],"num":"4","services":["local"],"parents":["00QdAa"],"children":["tWxJwr"],"transfer":{"groups":[{"lines":[{"theme":["singapore","lrt","#708573","#fff"],"name":["武吉班让轻轨","Bukit Panjang LRT"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"tWxJwr":{"name":["油地","Yew Tee"],"num":"5","services":["local"],"parents":["2muUmo"],"children":["wkPisT"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wkPisT":{"name":["克兰芝","Kranji"],"num":"7","services":["local"],"parents":["tWxJwr"],"children":["hAzfmy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"hAzfmy":{"name":["马西岭","Marsiling"],"num":"8","services":["local"],"parents":["wkPisT"],"children":["DtFxh8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"DtFxh8":{"name":["兀兰","Woodland"],"num":"9","services":["local"],"parents":["hAzfmy"],"children":["ffLag7"],"transfer":{"groups":[{"lines":[{"theme":["singapore","tel","#9B5A1A","#fff"],"name":["汤申-东海岸线","Thomsen-East Coast Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ffLag7":{"name":["海军部","Admiralty"],"num":"10","services":["local"],"parents":["DtFxh8"],"children":["OLrFi6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"OLrFi6":{"name":["三巴旺","Sembawang"],"num":"11","services":["local"],"parents":["ffLag7"],"children":["_hkcCJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"_hkcCJ":{"name":["坎贝拉","Camberra"],"num":"12","services":["local"],"parents":["OLrFi6"],"children":["BGNne0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"BGNne0":{"name":["义顺","Yishun"],"num":"13","services":["local"],"parents":["_hkcCJ"],"children":["zjZVRB"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zjZVRB":{"name":["卡迪","Khatib"],"num":"14","services":["local"],"parents":["BGNne0"],"children":["7n23UI"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7n23UI":{"name":["杨厝港","Yio Chu Kang"],"num":"15","services":["local"],"parents":["zjZVRB"],"children":["q5_edr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"q5_edr":{"name":["宏茂桥","Ang Mo Kio"],"num":"16","services":["local"],"parents":["7n23UI"],"children":["KV8RTG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"KV8RTG":{"name":["碧山","Bishan"],"num":"17","services":["local"],"parents":["q5_edr"],"children":["PfgY8p"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ccl","#FF9E1B","#000"],"name":["环线","Circle Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"PfgY8p":{"name":["布莱德","Braddell"],"num":"18","services":["local"],"parents":["KV8RTG"],"children":["l7SeDl"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"l7SeDl":{"name":["大巴窑","Toa Payoh"],"num":"19","services":["local"],"parents":["PfgY8p"],"children":["o-BmHR"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"o-BmHR":{"name":["诺维娜","Novena"],"num":"20","services":["local"],"parents":["l7SeDl"],"children":["Y3yKw9"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Y3yKw9":{"name":["纽顿","Newton"],"num":"21","services":["local"],"parents":["o-BmHR"],"children":["lZma1B"],"transfer":{"groups":[{"lines":[{"theme":["singapore","dtl","#0057B7","#fff"],"name":["滨海市区线","Downtown Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lZma1B":{"name":["乌节","Orchard"],"num":"22","services":["local"],"parents":["Y3yKw9"],"children":["2Rj1O6"],"transfer":{"groups":[{"lines":[{"theme":["singapore","tel","#9B5A1A","#fff"],"name":["汤申-东海岸线","Thomsen-East Coast Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"2Rj1O6":{"name":["索美塞","Somerset"],"num":"23","services":["local"],"parents":["lZma1B"],"children":["fIj-ED"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fIj-ED":{"name":["多美歌","Dhoby Ghaut"],"num":"24","services":["local"],"parents":["2Rj1O6"],"children":["fydpak"],"transfer":{"groups":[{"lines":[{"theme":["singapore","nel","#9B26B6","#fff"],"name":["东北线","North East Line"]},{"theme":["singapore","ccl","#FF9E1B","#000"],"name":["环线","Circle Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fydpak":{"name":["政府大厦","City Hall"],"num":"25","services":["local"],"parents":["fIj-ED"],"children":["aTOSKE"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ewl","#009739","#fff"],"name":["东西线","East West Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aTOSKE":{"name":["莱佛士坊","Raffles Place"],"num":"26","services":["local"],"parents":["fydpak"],"children":["LkWimI"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ewl","#009739","#fff"],"name":["东西线","East West Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"LkWimI":{"name":["滨海湾","Marina Bay"],"num":"27","services":["local"],"parents":["aTOSKE"],"children":["Np1r0D"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ccl","#FF9E1B","#000"],"name":["环线","Circle Line"]},{"theme":["singapore","tel","#9B5A1A","#fff"],"name":["汤申-东海岸线","Thomsen-East Coast Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"NS","psd_num":"1","info_panel_type":"gz1","direction_gz_x":6,"direction_gz_y":73,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

<details repo="rmg-templates" company="smrt" line="ewl" major="false"><summary>smrt/ewl</summary><details type="name">{"en":"East West Line","zh-Hans":"东西线","zh-Hant":"東西線","ko":"동서선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1400,"railmap":1800,"indoor":1200},"svg_height":400,"style":"gzmtr","y_pc":50,"padding":4,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["singapore","ewl","#009739","#fff"],"line_name":["东西线","East West Line"],"current_stn_idx":"-QuZE6","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["YSujgH"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YSujgH":{"name":["巴西立","Pasir Ris"],"num":"1","services":["local"],"parents":["linestart"],"children":["6YVKL4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"-QuZE6":{"name":["大士连路","Tuas Link"],"num":"33","services":["local"],"parents":["qQLAED"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["-QuZE6"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6YVKL4":{"name":["淡滨尼","Tampines"],"num":"2","services":["local"],"parents":["YSujgH"],"children":["ozmlga"],"transfer":{"groups":[{"lines":[{"theme":["singapore","dtl","#0057B7","#fff"],"name":["滨海市区线","Downtown Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ozmlga":{"name":["四美","Simei"],"num":"3","services":["local"],"parents":["6YVKL4"],"children":["UcABJ6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"UcABJ6":{"name":["丹那美拉","Tanah Menah"],"num":"4","services":["local"],"parents":["ozmlga"],"children":["Mxct5t"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ewl","#009739","#fff"],"name":["樟宜机场支线","Changi Airport Branch Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Mxct5t":{"name":["勿洛","Budok"],"num":"5","services":["local"],"parents":["UcABJ6"],"children":["M7nIdW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"M7nIdW":{"name":["景万岸","Kenbangan"],"num":"6","services":["local"],"parents":["Mxct5t"],"children":["y8IBBQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"y8IBBQ":{"name":["友诺士","Eunos"],"num":"7","services":["local"],"parents":["M7nIdW"],"children":["YoAc_S"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YoAc_S":{"name":["巴耶里峇","Paya Lebar"],"num":"8","services":["local"],"parents":["y8IBBQ"],"children":["fxfWN5"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ccl","#FF9E1B","#000"],"name":["环线","Circle Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fxfWN5":{"name":["阿裕尼","Aljunied"],"num":"9","services":["local"],"parents":["YoAc_S"],"children":["WG0htY"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WG0htY":{"name":["加冷","Kallang"],"num":"10","services":["local"],"parents":["fxfWN5"],"children":["TySxmQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"TySxmQ":{"name":["劳明达","Lavender"],"num":"11","services":["local"],"parents":["WG0htY"],"children":["o78nKW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"o78nKW":{"name":["武吉士","Bugis"],"num":"12","services":["local"],"parents":["TySxmQ"],"children":["RZcmWu"],"transfer":{"groups":[{"lines":[{"theme":["singapore","dtl","#0057B7","#fff"],"name":["滨海市区线","Downtown Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RZcmWu":{"name":["政府大厦","City Hall"],"num":"13","services":["local"],"parents":["o78nKW"],"children":["VD1_AJ"],"transfer":{"groups":[{"lines":[{"theme":["singapore","nsl","#DA291C","#fff"],"name":["南北线","North South Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"VD1_AJ":{"name":["莱佛士坊","Raffles Place"],"num":"14","services":["local"],"parents":["RZcmWu"],"children":["kdLGWl"],"transfer":{"groups":[{"lines":[{"theme":["singapore","nsl","#DA291C","#fff"],"name":["南北线","North South Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kdLGWl":{"name":["丹戎巴葛","Tanjong Pagar"],"num":"15","services":["local"],"parents":["VD1_AJ"],"children":["7gQ_QE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7gQ_QE":{"name":["欧南园","Outram Park"],"num":"16","services":["local"],"parents":["kdLGWl"],"children":["WZDanQ"],"transfer":{"groups":[{"lines":[{"theme":["singapore","nel","#9B26B6","#fff"],"name":["东北线","North East Line"]},{"theme":["singapore","tel","#9B5A1A","#fff"],"name":["汤申-东海岸线","Thomson-East Coast Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WZDanQ":{"name":["中峇鲁","Tiong Bahru"],"num":"17","services":["local"],"parents":["7gQ_QE"],"children":["Du7yVq"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Du7yVq":{"name":["红山","Redhill"],"num":"18","services":["local"],"parents":["WZDanQ"],"children":["08HjGg"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"08HjGg":{"name":["女皇镇","Queenstown"],"num":"19","services":["local"],"parents":["Du7yVq"],"children":["f8JG9_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4_B6-H":{"name":["波那维斯达","Buona Vista"],"num":"21","services":["local"],"parents":["f8JG9_"],"children":["G7lrSL"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ccl","#FF9E1B","#000"],"name":["环线","Circle Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"f8JG9_":{"name":["联邦","Commonwealth"],"num":"20","services":["local"],"parents":["08HjGg"],"children":["4_B6-H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"G7lrSL":{"name":["杜佛","Dover"],"num":"22","services":["local"],"parents":["4_B6-H"],"children":["41MsM-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"41MsM-":{"name":["金文泰","Clementi"],"num":"23","services":["local"],"parents":["G7lrSL"],"children":["w9gyGA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"w9gyGA":{"name":["裕廊东","Jurong East"],"num":"24","services":["local"],"parents":["41MsM-"],"children":["c3XYFz"],"transfer":{"groups":[{"lines":[{"theme":["singapore","nsl","#DA291C","#fff"],"name":["南北线","North South Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"c3XYFz":{"name":["裕华园","Chinese Garden"],"num":"25","services":["local"],"parents":["w9gyGA"],"children":["WECHJ7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WECHJ7":{"name":["湖畔","Lakeside"],"num":"26","services":["local"],"parents":["c3XYFz"],"children":["wVVwvV"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wVVwvV":{"name":["文礼","Boon lay"],"num":"27","services":["local"],"parents":["WECHJ7"],"children":["Rdt9DO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Rdt9DO":{"name":["先驱","Pioneer"],"num":"28","services":["local"],"parents":["wVVwvV"],"children":["3GvxSE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3GvxSE":{"name":["裕群","Joo Koon"],"num":"29","services":["local"],"parents":["Rdt9DO"],"children":["zGphKo"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zGphKo":{"name":["卡尔圈","Gul Circle"],"num":"30","services":["local"],"parents":["3GvxSE"],"children":["tzrl0n"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"tzrl0n":{"name":["大士湾","Tuas Crescent \t"],"num":"31","services":["local"],"parents":["zGphKo"],"children":["qQLAED"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"qQLAED":{"name":["大士西路","Tuan West Road"],"num":"32","services":["local"],"parents":["tzrl0n"],"children":["-QuZE6"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"EW","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":75,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

<details repo="rmg-templates" company="smrt" line="cgb" major="false"><summary>smrt/cgb</summary><details type="name">{"en":"Changi Airport Branch Line","zh-Hans":"樟宜机场支线","zh-Hant":"樟宜機場支線","ko":"창이공항지선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":400,"style":"gzmtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["singapore","ewl","#009739","#fff"],"line_name":["东西线（樟宜机场支线）","East West Line (Changi Airport Branch Line)"],"current_stn_idx":"ABME0v","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["7pUoOo"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7pUoOo":{"name":["丹那美拉","Tanah Merah"],"num":"0","services":["local"],"parents":["linestart"],"children":["d2BQ5i"],"transfer":{"groups":[{"lines":[{"theme":["singapore","ewl","#009739","#fff"],"name":["东西线","East West Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ABME0v":{"name":["樟宜机场","Changi Airport"],"num":"2","services":["local"],"parents":["d2BQ5i"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["ABME0v"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"d2BQ5i":{"name":["博览","Expo"],"num":"1","services":["local"],"parents":["7pUoOo"],"children":["ABME0v"],"transfer":{"groups":[{"lines":[{"theme":["singapore","dtl","#0057B7","#fff"],"name":["滨海市区线","Downtown Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"CG","psd_num":"1","info_panel_type":"gz1","direction_gz_x":13,"direction_gz_y":76,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.12"}</details></details>

**Comment by linchen1965** [comment]
您好，您提交的模板存在以下问题：

NSL：
兀兰站英文应为“Woodland**s**“
NS5站中文名应为“油池”

EWL：
丹那美拉站英文应为“Tanah Me**r**ah”
勿洛站英文应为“B**e**dok”
景万岸站英文应为“Ke**m**bangan”
文礼站英文应为“Boon **L**ay“
大士西路站英文应为“Tua**s** West Road”
EW8站中文名应为“巴耶利峇”
EW22站中文名应为“杜弗”
EW31站中文名应为“大士弯”

请在修改后重新打开issue提交，感谢您的贡献与合作。
