### ISSUE TITLE
佛山3号线

### ISSUE THREAD

**Issue by dfgjhgjdhgj** [railmapgen/rmg-templates#898]
**Justification:** 佛山3号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="fmetro" line="fs3" major="false"><summary>fmetro/fs3</summary><details type="name">{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}</details><details type="param">{"style":"gzmtr","svg_height":300,"padding":1.6100436053476448,"y_pc":43.51,"branch_spacing":45,"theme":["foshan","fs3","#002F87","#fff"],"direction":"l","current_stn_idx":"l1z2","platform_num":"1","stn_list":{"linestart":{"parents":[],"children":["x4mk"],"name":["路綫左端","LEFT END"],"branch":{"left":[],"right":[]},"num":"39","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"lineend":{"parents":["l1mz"],"children":[],"name":["路綫右端","RIGHT END"],"branch":{"left":[],"right":[]},"num":"00","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"l1mz":{"parents":["4yoy"],"children":["lineend"],"name":["顺德学院站","Shunde College Railway Station"],"branch":{"left":[],"right":[]},"num":"02","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"4yoy":{"branch":{"left":[],"right":[]},"parents":["e5aw"],"children":["l1mz"],"name":["顺德欢乐海岸","Shunde OCT Harbour PLUS"],"num":"03","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"e5aw":{"branch":{"left":[],"right":[]},"parents":["5hy5"],"children":["4yoy"],"name":["顺德一中","Shunde No.1 High School"],"num":"04","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"5hy5":{"branch":{"left":[],"right":[]},"parents":["9bwm"],"children":["e5aw"],"name":["驹荣北路","Jurong Beilu"],"num":"05","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"9bwm":{"branch":{"left":[],"right":[]},"parents":["huco"],"children":["5hy5"],"name":["东乐路","Dongle Lu"],"num":"06","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"huco":{"branch":{"left":[],"right":[]},"parents":["bmk1"],"children":["9bwm"],"name":["大良钟楼","Daliang Zhonglou"],"num":"07","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"bmk1":{"branch":{"left":[],"right":[]},"parents":["6uin"],"children":["huco"],"name":["环市北","Huangshi Bei"],"num":"08","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"6uin":{"branch":{"left":[],"right":[]},"parents":["6zky"],"children":["bmk1"],"name":["顺德人民医院","The First People's Hospital\\of Shunde"],"num":"09","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"6zky":{"branch":{"left":[],"right":[]},"parents":["9l7g"],"children":["6uin"],"name":["荔村","Licun"],"num":"10","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"9l7g":{"branch":{"left":[],"right":[]},"parents":["un8f"],"children":["6zky"],"name":["伦教","Lunjiao"],"num":"11","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"un8f":{"branch":{"left":[],"right":[]},"parents":["svif"],"children":["9l7g"],"name":["广教","Guangjiao"],"num":"12","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"svif":{"branch":{"left":[],"right":[]},"parents":["k6p4"],"children":["un8f"],"name":["北滘公园","Beijiao Park"],"num":"13","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["guangzhou","gz7","#97D700","#000","广州7号线","Guangzhou Line 7"]]]},"services":["local"],"facility":"","secondaryName":false},"k6p4":{"branch":{"left":[],"right":[]},"parents":["3yow"],"children":["svif"],"name":["高村","Gaocun"],"num":"14","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"3yow":{"branch":{"left":[],"right":[]},"parents":["6qq5"],"children":["k6p4"],"name":["北滘西站","Beijiao West Railway Station"],"num":"15","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"6qq5":{"branch":{"left":[],"right":[]},"parents":["oeq6"],"children":["3yow"],"name":["潭洲会展","Tanzhou Convention &amp;\\Exhibition Center"],"num":"16","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"oeq6":{"branch":{"left":[],"right":[]},"parents":["45g2"],"children":["6qq5"],"name":["岳步","Yuebu"],"num":"17","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"45g2":{"branch":{"left":[],"right":[]},"parents":["3ik5"],"children":["oeq6"],"name":["大墩","Dadun"],"num":"18","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"3ik5":{"branch":{"left":[],"right":[]},"parents":["inj5"],"children":["45g2"],"name":["东平","Dongping"],"num":"19","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["foshan","fs1","#C4D600","#000","广佛线","Guangfo Line"]]]},"services":["local"],"facility":"","secondaryName":false},"inj5":{"branch":{"left":[],"right":[]},"parents":["qfar"],"children":["3ik5"],"name":["湾华","Wanhua"],"num":"20","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["foshan","fs2","#F5333F","#fff","2号线","Line 2"]]]},"services":["local"],"facility":"","secondaryName":false},"qfar":{"branch":{"left":[],"right":[]},"parents":["hcfi"],"children":["inj5"],"name":["亚艺公园","Yayi Park"],"num":"21","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"hcfi":{"branch":{"left":[],"right":[]},"parents":["x4wt"],"children":["qfar"],"name":["季华六路","Jihua Liulu"],"num":"22","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"x4wt":{"branch":{"left":[],"right":[]},"parents":["l1z2"],"children":["hcfi"],"name":["镇安","Zhen'an"],"num":"23","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"l1z2":{"branch":{"left":[],"right":[]},"parents":["dul8"],"children":["x4wt"],"name":["桂城","Guicheng"],"num":"24","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[["foshan","fs1","#C4D600","#000","广佛线","Guangfo Line"]]]},"services":["local"],"facility":"","secondaryName":false},"dul8":{"branch":{"left":[],"right":[]},"parents":["7m99"],"children":["l1z2"],"name":["西约","Xiyue"],"num":"25","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"7m99":{"branch":{"left":[],"right":[]},"parents":["dz4j"],"children":["dul8"],"name":["叠滘","Diejiao"],"num":"26","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"dz4j":{"branch":{"left":[],"right":[]},"parents":["z1lf"],"children":["7m99"],"name":["中山公园","Zhongshan Park"],"num":"27","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"z1lf":{"branch":{"left":[],"right":[]},"parents":["wzas"],"children":["dz4j"],"name":["敦厚","Dunhou"],"num":"28","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"wzas":{"branch":{"left":[],"right":[]},"parents":["2n3c"],"children":["z1lf"],"name":["联和","Lianhe"],"num":"30","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"2n3c":{"branch":{"left":[],"right":[]},"parents":["7sli"],"children":["wzas"],"name":["孝德东","Xiaode Dong"],"num":"31","transfer":{"tick_direc":"r","paid_area":true,"osi_names":[],"info":[[]]},"services":["local"],"facility":"","secondaryName":false},"x4mk":{"name":["佛科院仙溪校区","Foshan University\\Xianxi Campus"],"secondaryName":false,"num":"38","services":["local"],"parents":["linestart"],"children":["4m7f"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"4m7f":{"name":["南海大学城","Nanhai University Town"],"secondaryName":false,"num":"37","services":["local"],"parents":["x4mk"],"children":["7lz7"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"7lz7":{"name":["博爱中路","Bo'ai Zhonglu"],"secondaryName":false,"num":"36","services":["local"],"parents":["4m7f"],"children":["fso9"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"fso9":{"name":["科盛路","Kesheng Lu"],"secondaryName":false,"num":"35","services":["local"],"parents":["7lz7"],"children":["e499"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"e499":{"name":["兴业东路","Xingye Donglu"],"secondaryName":false,"num":"34","services":["local"],"parents":["fso9"],"children":["xds0"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"xds0":{"name":["佛山西站","Foshan West Railway Station"],"secondaryName":false,"num":"33","services":["local"],"parents":["e499"],"children":["7sli"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""},"7sli":{"name":["罗村","Luocun"],"secondaryName":false,"num":"32","services":["local"],"parents":["xds0"],"children":["2n3c"],"branch":{"left":[],"right":[]},"transfer":{"info":[[]],"tick_direc":"r","paid_area":true,"osi_names":[]},"facility":""}},"line_name":["3号线","Line 3"],"psd_num":"12","line_num":"3","info_panel_type":"gz5","direction_gz_x":16.13,"direction_gz_y":78.63,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1000,"runin":1350,"railmap":2500,"indoor":2500},"notesGZMTR":[["镇安-佛科院仙溪校区尚未开通。","Zhen'an-Foshan University Xianxi Campus is under construction.",66.5,82,true]],"namePosMTR":{"isStagger":true,"isFlip":true}}</details></details>

**Comment by langonginc** [comment]
请不要随意修改议题标题。请您使用由 rmg-templates 生成议题框架，谢谢。
