### ISSUE TITLE
【新模板】部分东京都内轨交线路模板

### ISSUE THREAD

**Issue by e233-1000** [railmapgen/rmg-templates#9]
都营的线路我目前只做了浅草线：
[浅草線.zip](https://github.com/railmapgen/rmg/files/8528547/default.zip)

东京地下铁的我做到了东西线：
[日比谷線.zip](https://github.com/railmapgen/rmg/files/8528552/default.zip)
[銀座線.zip](https://github.com/railmapgen/rmg/files/8528560/default.zip)
[丸ノ内線.zip](https://github.com/railmapgen/rmg/files/8528563/default.zip)
[東西線.zip](https://github.com/railmapgen/rmg/files/8528570/default.zip)

新作品，几个东京地下铁的刚刚做完，后续还会更新完都营地下铁、东京地下铁、jr东日本（东京都内线路）以及一些大手私铁
望作者大大把它们加进去！

**Comment by Hayabusa-95** [comment]
非常感谢 @e233-1000 对日本模版的贡献！
但是这位最近好像没传模板了，所以我会进一步完善JR东日本的模版（只是随缘，不一定做完），同时已经做完仙台地铁（还在等审核），还有做完JR东海的计划（等东海道本线审好了再继续完善），之后尽量一个月内做完除饭田线以外的所有路线，饭田线争取一周内完工，同时还有做京急电铁的计划（猴年马月去了，先等东海地区做好）
