### ISSUE TITLE
Resources: New templates of Chuzhou Rail Transit

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#900]
**Justification:** 提供滁州轨道交通的RMG模板。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="chuzhourail" line="00config"><summary>New company: Chuzhou Rail Transit</summary><details type="name">{"en":"Chuzhou Rail Transit","zh-Hans":"滁州轨道交通","zh-Hant":"滁州軌道交通"}</details></details>

<details repo="rmg-templates" company="chuzhourail" line="czncx" major="false"><summary>chuzhourail/czncx</summary><details type="name">{"en":"Nanjing-Chuzhou Line","zh-Hans":"宁滁线","zh-Hant":"寧滁線","ko":"닝추선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1600,"indoor":2000},"svg_height":330,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["chuzhou","ningchu","#ff631b","#fff"],"line_name":["宁滁线","Nanjing-Chuzhou Line"],"current_stn_idx":"IRG7ho","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["IRG7ho"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"IRG7ho":{"name":["滁州高铁站","Chuzhou Railway Station"],"num":"01","services":["local"],"parents":["linestart"],"children":["CFn1jE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"railway"},"CFn1jE":{"name":["腰铺","YAOPU"],"num":"02","services":[],"parents":["IRG7ho"],"children":["gmRYy3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["9GLiw4"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"gmRYy3":{"name":["花博园","HUABOYUAN"],"num":"00","services":["local"],"parents":["CFn1jE"],"children":["pJTBqw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pJTBqw":{"name":["琅琊山","LANGYASHAN"],"num":"00","services":["local"],"parents":["gmRYy3"],"children":["zlv5_7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zlv5_7":{"name":["滁州政务中心","Chuzhou Government Affairs Center"],"num":"00","services":["local"],"parents":["pJTBqw"],"children":["rqdEL4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"rqdEL4":{"name":["担子","DANZI"],"num":"00","services":[],"parents":["zlv5_7"],"children":["88PdWi"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"88PdWi":{"name":["苏滁商务中心","SUCHU Business Center"],"num":"00","services":["local"],"parents":["rqdEL4"],"children":["W6OBJF"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"W6OBJF":{"name":["大王郢","DAWANGYING"],"num":"00","services":["local"],"parents":["88PdWi"],"children":["lX2iwN"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lX2iwN":{"name":["林楼","LINLOU"],"num":"00","services":["local"],"parents":["W6OBJF"],"children":["Bxpldy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Bxpldy":{"name":["水口","SHUIKOU"],"num":"00","services":[],"parents":["lX2iwN"],"children":["WhT-Oy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WhT-Oy":{"name":["十二里半","SHIERLIBAN"],"num":"00","services":["local"],"parents":["Bxpldy"],"children":["1LYxp0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1LYxp0":{"name":["相官","XIANGGUAN"],"num":"00","services":[],"parents":["WhT-Oy"],"children":["j-NFpS"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"j-NFpS":{"name":["汊河新城","CHAHEXINCHENG"],"num":"00","services":["local"],"parents":["1LYxp0"],"children":["9GLiw4"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"9GLiw4":{"name":["汊河","CHAHE"],"num":"00","services":["local"],"parents":["j-NFpS"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.13"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
