### ISSUE TITLE
Resources: New templates of Suzhou Rail Transit

### ISSUE THREAD

**Issue by stevetang8** [railmapgen/rmg-templates#902]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 苏州6号线开通在即，需要一张线路图
站点名来自百度百科

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="szmtr" line="sz6" major="false"><summary>szmtr/sz6</summary><details type="name">{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線","ko":"6호선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"1","theme":["suzhou","sz6","#41b6e6","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"jb7Rjn","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["qY2Ecv"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7lwHIx":{"name":["保丰","Baofeng"],"num":"01","services":["local"],"parents":["I6Kl0_"],"children":["QgdJ-P"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"QgdJ-P":{"name":["苏州新区火车站","Suzhou Xinqu Railway Station"],"num":"02","services":["local"],"parents":["7lwHIx"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["3号线","Line 3"]}]},{},{"lines":[{"theme":["suzhou","tram","#d8e4c0","#fff"],"name":["高新有轨电车2号线","SND Tram Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355,"facility":"hsr"},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["QgdJ-P"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"I6Kl0_":{"name":["富强","Fuqiang"],"num":"00","services":["local"],"parents":["YzlsT1"],"children":["7lwHIx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YzlsT1":{"name":["长青","Changqing"],"num":"00","services":["local"],"parents":["XCqQl3"],"children":["I6Kl0_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"XCqQl3":{"name":["白洋湾","Baiyangwan"],"num":"00","services":["local"],"parents":["RE36-U"],"children":["YzlsT1"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz8","#a09200","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"RE36-U":{"name":["金鸡墩","Jinjidun"],"num":"00","services":["local"],"parents":["4Y_PAQ"],"children":["XCqQl3"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4Y_PAQ":{"name":["虎丘","Huqiu"],"num":"00","services":["local"],"parents":["NIrveP"],"children":["RE36-U"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"NIrveP":{"name":["青山桥浜","Qingshanqiaobang"],"num":"00","services":["local"],"parents":["sDyF_q"],"children":["4Y_PAQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sDyF_q":{"name":["将星桥南","Jiangxingqiao South"],"num":"00","services":["local"],"parents":["YzbUPq"],"children":["NIrveP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"YzbUPq":{"name":["苏锦","Sujin"],"num":"00","services":["local"],"parents":["aPFhtU"],"children":["sDyF_q"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz4","#196EAE","#fff"],"name":["4号线","Line 4"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aPFhtU":{"name":["平河路","Pinghelu"],"num":"00","services":["local"],"parents":["zjjz0Z"],"children":["YzbUPq"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zjjz0Z":{"name":["梅巷","Meixiang"],"num":"00","services":["local"],"parents":["p4sV9l"],"children":["aPFhtU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"p4sV9l":{"name":["拙政园","Zhuozhengyuan"],"num":"00","services":["local"],"parents":["9Q9aOt"],"children":["zjjz0Z"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"9Q9aOt":{"name":["悬桥巷","Xuanqiaoxiang"],"num":"00","services":["local"],"parents":["p7hg0H"],"children":["p4sV9l"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"p7hg0H":{"name":["临顿路","Lindunlu"],"num":"00","services":["local"],"parents":["jb7Rjn"],"children":["9Q9aOt"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz1","#78BA25","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"jb7Rjn":{"name":["苏州大学","Soochow University"],"num":"00","services":["local"],"parents":["WMQxA7"],"children":["p7hg0H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WMQxA7":{"name":["徐家浜","Xujiabang"],"num":"00","services":["local"],"parents":["W6UVeC"],"children":["jb7Rjn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"W6UVeC":{"name":["惹云桥","Reyunqiao"],"num":"00","services":["local"],"parents":["OyUbpd"],"children":["WMQxA7"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"OyUbpd":{"name":["秋塘浜","Qiutangbang"],"num":"00","services":["local"],"parents":["5pyzLE"],"children":["W6UVeC"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"5pyzLE":{"name":["李公堤西","Ligongdi West"],"num":"00","services":["local"],"parents":["Wx1bmJ"],"children":["OyUbpd"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz3","#F88211","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Wx1bmJ":{"name":["琼姬墩","Qiongjidun"],"num":"00","services":["local"],"parents":["lJXu1d"],"children":["5pyzLE"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz8","#a09200","#fff"],"name":["8号线","Line 8"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lJXu1d":{"name":["南施公园南","Nanshigongyuan South"],"num":"00","services":["local"],"parents":["W3Hxjt"],"children":["Wx1bmJ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"W3Hxjt":{"name":["苏州奥体中心","Suzhou Olympic Sports Center"],"num":"00","services":["local"],"parents":["HuVo0H"],"children":["lJXu1d"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz5","#E63A9A","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"HuVo0H":{"name":["丰泰桥","Fengtaiqiao"],"num":"00","services":["local"],"parents":["ORiCF1"],"children":["W3Hxjt"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"ORiCF1":{"name":["涵青桥","Hanqingqiao"],"num":"00","services":["local"],"parents":["s1PqU0"],"children":["HuVo0H"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"s1PqU0":{"name":["金家堰","Jinjiayan"],"num":"00","services":["local"],"parents":["y590IQ"],"children":["ORiCF1"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"y590IQ":{"name":["北斜步","Beixiebu"],"num":"00","services":["local"],"parents":["7r2ups"],"children":["s1PqU0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"7r2ups":{"name":["南斜步","Nanxiebu"],"num":"00","services":["local"],"parents":["fCx9LQ"],"children":["y590IQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"fCx9LQ":{"name":["金尚路","Jinshanglu"],"num":"00","services":["local"],"parents":["MgUHpP"],"children":["7r2ups"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"MgUHpP":{"name":["桑田岛","Sangtiandao"],"num":"00","services":["local"],"parents":["qY2Ecv"],"children":["fCx9LQ"],"transfer":{"groups":[{"lines":[{"theme":["suzhou","sz2","#ED3240","#fff"],"name":["2号线","Line 2"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"qY2Ecv":{"name":["华云","Huayun"],"num":"00","services":["local"],"parents":["linestart"],"children":["MgUHpP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.13"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板包括但不限于以下问题：

- “望星桥”站中文站名错误，不为“苏州大学”站
- 建议您调整换乘线路的间距，并调整画面宽度

请您修改后重新提交，感谢您的贡献。

**（请您在收到本消息后一个月内及时回复，超过此期限的我们将拒绝汇入）**

_另外，由于该线路暂未开通，我们会待到线路开通后再进行汇入。_

**Comment by Windows-Taskmgr** [comment]
您好，由于您已超过一个月未回复，我们将会关闭此issue，感谢您的理解。
