### ISSUE TITLE
Resources: New templates of Transport for London

### ISSUE THREAD

**Issue by UnnamedKiana** [railmapgen/rmg-templates#911]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 自主制作，翻译来源自部分介绍视频及网络。
因缺少伦敦地铁条目，因此加以补充。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="tfl" line="00config"><summary>New company: Transport for London</summary><details type="name">{"en":"Transport for London","zh-Hans":"伦敦交通局","zh-Hant":"倫敦交通局"}</details></details>

<details repo="rmg-templates" company="tfl" line="victorialine" major="false"><summary>tfl/victorialine</summary><details type="name">{"en":"Victoria Line","zh-Hans":"维多利亚线","zh-Hant":"維多利亞線"}</details><details type="param">{"svgWidth":{"destination":2400,"runin":4000,"railmap":2400,"indoor":4000},"svg_height":300,"style":"mtr","y_pc":50,"padding":4,"branchSpacingPct":33,"direction":"l","platform_num":"3","theme":["london","victoria","#0098D8","#fff"],"line_name":["维多利亚线","Victoria Line"],"current_stn_idx":"sK99Nn","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["cKuhFZ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"cKuhFZ":{"name":["沃尔瑟姆斯托","Walthamstow Central"],"num":"01","services":["local"],"parents":["linestart"],"children":["sK99Nn"],"transfer":{"groups":[{"lines":[{"theme":["london","overground","#EF7B10","#fff"],"name":["伦敦地上铁","London Overground"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"sK99Nn":{"name":["黑马路","Blackhorse Road"],"num":"02","services":["local"],"parents":["cKuhFZ"],"children":["VCfRmx"],"transfer":{"groups":[{"lines":[{"theme":["london","overground","#EF7B10","#fff"],"name":["伦敦地上铁","London Overground"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["uJ9y4V"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"6FDx1-":{"name":["国王十字·圣潘克拉斯","King Cross St. Pancras"],"num":"00","services":["local"],"parents":["T6sVAp"],"children":["a9OI8e"],"transfer":{"groups":[{"lines":[{"theme":["london","circle","#FFD329","#fff"],"name":["环线","Circle Line"]},{"theme":["london","hsmithcity","#F4A9BE","#fff"],"name":["汉默史密斯与城市线","Hammersmith &amp; City Line"]},{"theme":["london","metropolitan","#9B0058","#fff"],"name":["大都会线","Metropolitan Line"]},{"theme":["london","northern","#000000","#fff"],"name":["北线","Northern Line"]},{"theme":["london","piccadily","#0019A8","#fff"],"name":["皮卡迪利线","Piccadilly Line"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":620},"T6sVAp":{"name":["海布里及伊斯灵顿","Highbury &amp; Islington"],"num":"00","services":["local"],"parents":["cPp1vC"],"children":["6FDx1-"],"transfer":{"groups":[{"lines":[{"theme":["london","overground","#EF7B10","#fff"],"name":["伦敦地上铁","London Overground"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"cPp1vC":{"name":["芬斯伯里公园","Finsbury Park"],"num":"00","services":["local"],"parents":["3p-Mwi"],"children":["T6sVAp"],"transfer":{"groups":[{"lines":[{"theme":["london","piccadily","#0019A8","#fff"],"name":["皮卡迪利线","Piccadilly Line"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"3p-Mwi":{"name":["七姐妹","Seven Sisters"],"num":"00","services":["local"],"parents":["VCfRmx"],"children":["cPp1vC"],"transfer":{"groups":[{"lines":[{"theme":["london","overground","#EF7B10","#fff"],"name":["伦敦地上铁","London Overground"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"VCfRmx":{"name":["托特纳姆黑尔","Tottenham Hale"],"num":"00","services":["local"],"parents":["sK99Nn"],"children":["3p-Mwi"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"uBo36H":{"name":["维多利亚","Victoria"],"num":"00","services":["local"],"parents":["74ctW5"],"children":["NxL4-j"],"transfer":{"groups":[{"lines":[{"theme":["london","circle","#FFD329","#fff"],"name":["环线","Circle Line"]},{"theme":["london","district","#007D32","#fff"],"name":["区域线","District Line"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"74ctW5":{"name":["格林公园","Green Park"],"num":"00","services":["local"],"parents":["XWc1Jh"],"children":["uBo36H"],"transfer":{"groups":[{"lines":[{"theme":["london","jubilee","#A1A5A7","#fff"],"name":["银禧线","Jubilee Line"]},{"theme":["london","piccadily","#0019A8","#fff"],"name":["皮卡迪利线","Piccadilly Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"XWc1Jh":{"name":["牛津圆环","Oxford Circus"],"num":"00","services":["local"],"parents":["U6RGmt"],"children":["74ctW5"],"transfer":{"groups":[{"lines":[{"theme":["london","central","#DC241F","#fff"],"name":["中央线","Central Line"]},{"theme":["london","bakerloo","#B26300","#fff"],"name":["贝克卢线","Bakerloo Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"U6RGmt":{"name":["沃伦街","Warren Street"],"num":"00","services":["local"],"parents":["a9OI8e"],"children":["XWc1Jh"],"transfer":{"groups":[{"lines":[{"theme":["london","northern","#000000","#fff"],"name":["北线","Northern Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"a9OI8e":{"name":["尤斯顿","Euston"],"num":"00","services":["local"],"parents":["6FDx1-"],"children":["U6RGmt"],"transfer":{"groups":[{"lines":[{"theme":["london","northern","#000000","#fff"],"name":["北线","Northern Line"]},{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]},{"theme":["london","overground","#EF7B10","#fff"],"name":["伦敦地上铁","London Overground"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"uJ9y4V":{"name":["布里克斯顿","Brixton"],"num":"00","services":["local"],"parents":["qkSRDB"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"qkSRDB":{"name":["斯托克韦尔","Stockwell"],"num":"00","services":["local"],"parents":["vayAwc"],"children":["uJ9y4V"],"transfer":{"groups":[{"lines":[{"theme":["london","northern","#000000","#fff"],"name":["北线","Northern Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"vayAwc":{"name":["沃克斯豪尔","Vauxhall"],"num":"00","services":["local"],"parents":["NxL4-j"],"children":["qkSRDB"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ffffff","#000"],"name":["国家铁路","National Rail"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355},"NxL4-j":{"name":["皮姆利科","Pimlico"],"num":"00","services":["local"],"parents":["uBo36H"],"children":["vayAwc"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":false,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":false},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.14.13"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題。請等待管理員加入到範本，感謝您的貢獻🙏

**Comment by Charlis-Wong** [comment]
@thekingofcity / @wongchito / @Windows-Taskmgr / @28yfang 請合拼此範本，謝謝🙏
