### ISSUE TITLE
Resources: New templates of Macao LRT

### ISSUE THREAD

**Issue by Hexiaozhi209723** [railmapgen/rmg-templates#913]
Hi RMG team! I would like to contribute the templates below.

**Justification:** 2023年8月11日，澳门轻轨氹仔线莲花口岸站更名为莲花站
2023年12月8日，澳门轻轨氹仔线妈阁站正式开通

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mlm" line="taipa" major="false"><summary>mlm/taipa</summary><details type="name">{"en":"Taipa Line","zh-Hans":"氹仔线","zh-Hant":"氹仔線","pt":"Linha Taipa"}</details><details type="param">{"style":"mtr","svg_height":300,"padding":7.05352436628492,"y_pc":40,"theme":["macau","taipa","#A4D65E","#fff"],"direction":"l","current_stn_idx":"hwTuQi","platform_num":"2","stn_list":{"linestart":{"parents":[],"children":["iwf6"],"name":["路綫右端","RIGHT END"],"num":"00","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["hwTuQi"],"children":[],"name":["路綫左端","LEFT END"],"num":"00","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["iwf6"],"children":["ujti"],"name":["機場","Aeroporto\\Airport"],"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["l1mz"],"parents":["linestart"],"name":["氹仔碼頭","Terminal Marítimo da Taipa\\Taipa Ferry Terminal"],"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"ujti":{"parents":["l1mz"],"children":["3ok9"],"name":["科大","UCTM\\MUST"],"num":"03","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"3ok9":{"parents":["ujti"],"children":["wgb3"],"name":["路氹東","Cotai Leste\\Cotai East"],"num":"04","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"wgb3":{"parents":["3ok9"],"children":["rul5"],"name":["東亞運","Jogos da Ásia Oriental\\East Asian Games"],"num":"05","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"rul5":{"parents":["wgb3"],"children":["s0vw"],"name":["蓮花","Lótus\\Lotus "],"num":"06","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"s0vw":{"parents":["rul5"],"children":["tu3q"],"name":["路氹西","Cotai Oeste\\Cotai West"],"num":"07","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"tu3q":{"parents":["s0vw"],"children":["tgzu"],"name":["排角","Pai Kok\\Pai Kok"],"num":"08","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"tgzu":{"parents":["tu3q"],"children":["kf85"],"name":["運動場","Estádio\\Stadium"],"num":"09","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"kf85":{"parents":["tgzu"],"children":["rygs"],"name":["馬會","Jockey Clube\\Jockey Club"],"num":"10","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"rygs":{"parents":["kf85"],"children":["hwTuQi"],"name":["海洋","Oceano\\Ocean"],"num":"11","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hwTuQi":{"name":["媽閣","Barra\\Barra"],"num":"12","services":["local"],"parents":["rygs"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"line_name":["氹仔綫","Linha Taipa"],"psd_num":"3","line_num":"TP","info_panel_type":"gz28","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1600,"runin":1100,"railmap":1000,"indoor":900},"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":30,"version":"5.14.13"}</details></details>

**Comment by 28yfang** [comment]
您好，您的模版没有问题。
以下为一个建议：根据[澳门轻轨官网](https://www.mlm.com.mo/sc/route.html)，线路图中的中文站名为简体字而非繁体字。您可以选择更改至简体，也可以不做修改直接汇入。请问您要做修改吗？

**Comment by wongchito** [comment]
@28yfang 請留意RMG範本以**車站月台路線圖**的資訊為參考標準，因此澳門輕軌的範本應使用繁體中文。

**Comment by 28yfang** [comment]
> @28yfang 請留意RMG範本以**車站月台路線圖**的資訊為參考標準，因此澳門輕軌的範本應使用繁體中文。

好的，那我merge了
