### ISSUE TITLE
Resources: New templates of Beijing Subway

### ISSUE THREAD

**Issue by LWY-K2** [railmapgen/rmg-templates#930]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Justification:** 修改昌平线南延段广州地铁版样式未开通的错误

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="bjsubway" line="cpl" major="false"><summary>bjsubway/cpl</summary><details type="name">{"en":"Changping Line","zh-Hans":"昌平线","zh-Hant":"昌平線"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1200,"railmap":1500,"indoor":2000},"svg_height":320,"style":"gzmtr","y_pc":51,"padding":6,"direction":"r","platform_num":"4","theme":["other","other","#de82b2","#fff"],"line_name":["昌平线","Changping Line"],"current_stn_idx":"D41K6Q","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["NrI7z9"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"NrI7z9":{"name":["昌平西山口","Changping Xishankou"],"num":"01","services":["local"],"parents":["linestart"],"children":["Uo1cC5"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":225},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["TqMYsK"],"children":[],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"Uo1cC5":{"name":["十三陵景区","Ming Tombs"],"num":"02","services":["local"],"parents":["NrI7z9"],"children":["fL5ELd"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"fL5ELd":{"name":["昌平","Changping"],"num":"03","services":["local"],"parents":["Uo1cC5"],"children":["IAVl4Y"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"IAVl4Y":{"name":["昌平东关","Changping Dongguan"],"num":"04","services":["local"],"parents":["fL5ELd"],"children":["K0pGta"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"K0pGta":{"name":["北邵洼","Beishaowa"],"num":"05","services":["local"],"parents":["IAVl4Y"],"children":["oOBH4w"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"oOBH4w":{"name":["南邵","Nanshao"],"num":"06","services":["local"],"parents":["K0pGta"],"children":["2Q9NFl"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"2Q9NFl":{"name":["沙河高教园","Shahe Univ. Park"],"num":"07","services":["local"],"parents":["oOBH4w"],"children":["_KMMdD"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"_KMMdD":{"name":["沙河","Shahe"],"num":"08","services":["local"],"parents":["2Q9NFl"],"children":["16eL_R"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"16eL_R":{"name":["巩华城","Gonghua Cheng"],"num":"09","services":["local"],"parents":["_KMMdD"],"children":["rm5957"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"rm5957":{"name":["朱辛庄","Zhuxinzhuang"],"num":"10","services":["local"],"parents":["16eL_R"],"children":["XvUcAp"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj8","#009b6b","#fff"],"name":["8号线","Line 8"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225},"XvUcAp":{"name":["生命科学园","Life Science Park"],"num":"11","services":["local"],"parents":["rm5957"],"children":["D41K6Q"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"D41K6Q":{"name":["西二旗","Xi'erqi"],"num":"12","services":["local"],"parents":["XvUcAp"],"children":["2ehewK"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj13","#f9e700","#000"],"name":["13号线","Line 13"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225},"2ehewK":{"name":["清河站","Qinghe Zhan\\(Qinghe Railway Station)"],"num":"13","services":["local"],"parents":["D41K6Q"],"children":["iPrnwL"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj13","#f9e700","#000"],"name":["13号线","Line 13"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225},"iPrnwL":{"name":["朱房北","Zhufangbei"],"secondaryName":["暂缓开通","Under Construction"],"num":"14","services":[],"parents":["2ehewK"],"children":["LZWT_i"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"LZWT_i":{"name":["清河小营桥","Qinghe Xiaoyingqiao"],"num":"15","services":["local"],"parents":["iPrnwL"],"children":["0w2L9O"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"0w2L9O":{"name":["学知园","Xuezhiyuan"],"num":"16","services":["local"],"parents":["LZWT_i"],"children":["vaZb2j"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"vaZb2j":{"name":["六道口","Liudaokou"],"num":"18","services":["local"],"parents":["0w2L9O"],"children":["vfZeeU"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj15","#5b2c68","#fff"],"name":["15号线","Line 15"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225},"vfZeeU":{"name":["学院桥","Xueyuanqiao"],"num":"19","services":["local"],"parents":["vaZb2j"],"children":["TqMYsK"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"TqMYsK":{"name":["西土城","Xitucheng"],"num":"20","services":["local"],"parents":["vfZeeU"],"children":["lineend"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225}},"namePosMTR":{"isStagger":true,"isFlip":false},"customiseMTRDest":{"isLegacy":false,"terminal":["西土城","Xitucheng"]},"line_num":" 27","psd_num":"12","info_panel_type":"gz5","direction_gz_x":23,"direction_gz_y":79.666667,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":47,"version":"5.14.13","notesGZMTR":[["朱房北站未开通。","ZhufangBei Station is under construction.",10,10,true]]}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，在您的备注里，朱房北站的英文名称应为“Zhufangbei”而不为“ZhufangBei”，请您修改后重新提交，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
请见 #932 。
