### ISSUE TITLE
Resources: New templates of Zhengzhou Metro

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#954]
**Justification:** 郑州地铁12号线已于12月20日开通运营，以此更新12号线模版。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="zzmetro" line="zz12" major="false"><summary>zzmetro/zz12</summary><details type="name">{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1800,"indoor":2000},"svg_height":330,"style":"shmetro","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"l","platform_num":"","theme":["zhengzhou","zz12","#225E9E","#fff"],"line_name":["12号线","Line 12"],"current_stn_idx":"CqodsS","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["8qmS4Y"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"dNFcGn":{"name":["龙子湖","LONGZIHU"],"num":"10","services":["local"],"parents":["Bs3Evd"],"children":["CqodsS"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz1","#D20200","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"CqodsS":{"name":["龙子湖东","LONGZIHU DONG"],"num":"11","services":["local"],"parents":["dNFcGn"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["CqodsS"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"Bs3Evd":{"name":["龙子湖西","LONGZIHU XI"],"num":"09","services":["local"],"parents":["JmmOVn"],"children":["dNFcGn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"JmmOVn":{"name":["高铁公园","GAOTIE GONGYUAN"],"num":"08","services":["local"],"parents":["MClgsg"],"children":["Bs3Evd"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"MClgsg":{"name":["东风东路","DONGFENGDONG LU"],"num":"07","services":["local"],"parents":["ZS79Tj"],"children":["JmmOVn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"ZS79Tj":{"name":["儿童医院","Children’s Hospital"],"num":"06","services":["local"],"parents":["bP-yqo"],"children":["MClgsg"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"bP-yqo":{"name":["黄河南路","HUANGHENANLU"],"num":"05","services":["local"],"parents":["EqIP9d"],"children":["ZS79Tj"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz1","#D20200","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"EqIP9d":{"name":["西周","XIZHOU"],"num":"04","services":["local"],"parents":["wdDEJX"],"children":["bP-yqo"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz3","#CB5100","#fff"],"name":["3号线","Line 3"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"wdDEJX":{"name":["经北五路","JINGBEIWU LU"],"num":"03","services":["local"],"parents":["dARzCK"],"children":["EqIP9d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"dARzCK":{"name":["福塔东","ZHONGYUAN Tower East"],"num":"00","services":["local"],"parents":["8qmS4Y"],"children":["wdDEJX"],"transfer":{"groups":[{"lines":[{"theme":["zhengzhou","zz5","#25AC74","#fff"],"name":["5号线","Line 5"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":210},"8qmS4Y":{"name":["梁湖","LIANGHU"],"num":"00","services":["local"],"parents":["linestart"],"children":["dARzCK"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"12","spanLineNum":true,"psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":80,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.15.3"}</details></details>

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的模版含有以下问题：
1. 福塔东站英文名应为FUTA DONG（如图）
2. 所有英文站名均为大写字母
![image](https://github.com/railmapgen/rmg-templates/assets/123239445/b2d99001-bd19-43d1-b10b-62bcab2f67ba)

请在修正后重新提交，并附上本议题编号（#954），感谢。
