### ISSUE TITLE
Resources: New templates of Chongqing Rail Transit Jiangtiao Line

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#967]
**Justification:** 重庆轨道交通18号线已于2023年12月28日开通，以在江跳线的跳磴站添加18号线换乘信息。

- Major update of Jiangtiao Line/江跳线/江跳線: 跳磴站添加18号线换乘信息。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="crt" line="cjt" major="true"><summary>crt/cjt(M)</summary><details type="name">{"en":"Jiangtiao Line","zh-Hans":"江跳线","zh-Hant":"江跳線","ko":"강점선"}</details><details type="param">{"svgWidth":{"destination":1200,"runin":1200,"railmap":1200,"indoor":1200},"svg_height":300,"style":"mtr","y_pc":50,"padding":10,"branchSpacingPct":33,"direction":"r","platform_num":"5","theme":["chongqing","jiangtiao","#0077c8","#fff"],"line_name":["江跳线","Jiangtiao Line"],"current_stn_idx":"bo50Tw","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["bo50Tw"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"bo50Tw":{"name":["圣泉寺","Shengquansi"],"num":"01","services":["local"],"parents":["linestart"],"children":["Z7grvz"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Z7grvz":{"name":["江津高铁","Jiangjin High-Speed Railway"],"num":"02","services":["local"],"parents":["bo50Tw"],"children":["X6jfMh"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["COMWvB"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"X6jfMh":{"name":["享堂","Xiangtang"],"num":"00","services":["local"],"parents":["Z7grvz"],"children":["S6HUIx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"S6HUIx":{"name":["双福","Shuangfu"],"num":"00","services":["local"],"parents":["X6jfMh"],"children":["zD7yIW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zD7yIW":{"name":["九龙园","Jiulongyuan"],"num":"00","services":["local"],"parents":["S6HUIx"],"children":["WzX7t_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WzX7t_":{"name":["石林寺","Shilinsi"],"num":"00","services":["local"],"parents":["zD7yIW"],"children":["COMWvB"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"COMWvB":{"name":["跳磴","Tiaodeng"],"num":"00","services":["local"],"parents":["WzX7t_"],"children":["lineend"],"transfer":{"groups":[{"lines":[{"theme":["chongqing","cq5","#00A3E0","#fff"],"name":["5号线","Line 5"]},{"theme":["chongqing","cq18","#2ad2c9","#fff"],"name":["18号线","Line 18"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"gz1","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.15.3"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題。但是18號線還在建設中，所以我們的管理員會保留至開通後上傳。感謝您的貢獻🙏

@wongchito / @Windows-Taskmgr / @thekingofcity 請加Hold標籤，謝謝🙏

**Comment by Windows-Taskmgr** [comment]
@Charlis-Wong 您好，18号线目前已开通，所以我们将合入此作品，感谢您的审核。
