### ISSUE TITLE
Resources: New templates of MTR

### ISSUE THREAD

**Issue by DanielWed14821** [railmapgen/rmg-templates#971]
**Justification:** 新增了港鐵未來計畫中的車站和線路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="mtr" line="東鐵綫(港鐵未來計畫)" major="false"><summary>mtr/東鐵綫(港鐵未來計畫)</summary><details type="name">{"en":"East Rail Line","zh-Hans":"东铁线(港铁未来计划)","zh-Hant":"東鐵綫(港鐵未來計畫)","ko":"둥팃선"}</details><details type="param">{"style":"mtr","svg_height":300,"padding":7,"y_pc":42.5019305019305,"theme":["hongkong","eal","#61B4E4","#fff"],"direction":"r","current_stn_idx":"q027","platform_num":"1","stn_list":{"linestart":{"parents":[],"children":["2It3ab"],"name":["路綫右端","RIGHT END"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"00","loop_pivot":false,"one_line":false,"int_padding":355},"lineend":{"parents":["fhq4","m2ot"],"children":[],"name":["路綫左端","LEFT END"],"branch":{"left":["through","fhq4"]},"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"num":"00","loop_pivot":false,"one_line":false,"int_padding":355},"l1mz":{"parents":["iwf6"],"children":["q027"],"name":["旺角東","Mong Kok East"],"num":"02","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"iwf6":{"children":["l1mz"],"parents":["JW3KcT"],"name":["紅磡","Hung Hom"],"num":"01","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","mol","#9A3820","#fff"],"name":["屯馬綫","Tuen Ma Line"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"q027":{"parents":["l1mz"],"children":["6r9r"],"name":["九龍塘","Kowloon Tong"],"num":"03","transfer":{"tick_direc":"r","paid_area":false,"groups":[{"lines":[{"theme":["hongkong","ktl","#00AF41","#fff"],"name":["觀塘綫","Kwun Tong Line"]},{"theme":["other","other","#000000","#fff"],"name":["中鐵線","Central Rail Line"]}]},{},{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"6r9r":{"parents":["q027"],"children":["u8xj"],"name":["大圍","Tai Wai"],"num":"04","transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","mol","#9A3820","#fff"],"name":["屯馬綫","Tuen Ma Line"]}]}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"u8xj":{"parents":["6r9r"],"children":["7gy7","hybz"],"branch":{"right":["through","hybz"]},"name":["沙田","Sha Tin"],"num":"05","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"7gy7":{"parents":["u8xj"],"children":["rr8a"],"name":["火炭","Fo Tan"],"num":"06","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"rr8a":{"parents":["7gy7","hybz"],"children":["fwhz"],"branch":{"left":["through","hybz"]},"name":["大學","University"],"num":"08","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"fwhz":{"parents":["rr8a"],"children":["WKh9Z0"],"name":["大埔墟","Tai Po Market"],"num":"09","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"7dwu":{"parents":["WKh9Z0"],"children":["jce3"],"name":["太和","Tai Wo"],"num":"10","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"jce3":{"parents":["7dwu"],"children":["l116"],"name":["粉嶺","Fanling"],"num":"11","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"l116":{"parents":["jce3"],"children":["TOpMhe","m2ot"],"branch":{"right":["through","TOpMhe"]},"name":["上水","Sheung Shui"],"num":"12","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"m2ot":{"parents":["l116"],"children":["lineend"],"name":["羅湖","Lo Wu"],"num":"13","transfer":{"tick_direc":"r","paid_area":false,"groups":[{},{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"fhq4":{"parents":["TOpMhe"],"children":["lineend"],"name":["落馬洲","Lok Ma Chau"],"num":"14","transfer":{"tick_direc":"r","paid_area":false,"groups":[{},{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"hybz":{"parents":["u8xj"],"children":["rr8a"],"name":["馬場","Racecourse"],"num":"07","transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"services":["local"],"loop_pivot":false,"one_line":false,"int_padding":355},"JW3KcT":{"name":["會展","Exibition Centre"],"num":"00","services":["local"],"parents":["2It3ab"],"children":["iwf6"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":false,"int_padding":355},"2It3ab":{"name":["金鐘","Admiralty"],"num":"00","services":["local"],"parents":["linestart"],"children":["JW3KcT"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["hongkong","twl","#E2231A","#fff"],"name":["荃灣綫","Tsuen Wan Line"]},{"theme":["hongkong","isl","#0071CE","#fff"],"name":["港島綫","Island Line"]},{"theme":["hongkong","sile","#B6BD00","#fff"],"name":["南港島綫","South Island Line"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":355},"TOpMhe":{"name":["古洞","Kwu Tung"],"num":"00","services":["local"],"parents":["l116"],"children":["fhq4"],"transfer":{"groups":[{"lines":[{"theme":["hongkong","nol","#a1208a","#fff"],"name":["北環線","Northern Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"WKh9Z0":{"name":["白石角","Pak Shek Kok"],"num":"00","services":["local"],"parents":["fwhz"],"children":["7dwu"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"line_name":["東鐵綫","East Rail Line"],"psd_num":"1","line_num":"ER","info_panel_type":"gz28","direction_gz_x":50,"direction_gz_y":70,"customiseMTRDest":{"isLegacy":false,"terminal":false},"svgWidth":{"destination":1500,"runin":1050,"railmap":1500,"indoor":1000},"namePosMTR":{"isStagger":true,"isFlip":false},"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":0,"bottom_factor":1},"branchSpacingPct":33,"version":"5.15.3"}</details></details>

**Comment by wongchito** [comment]
Hi @DanielWed14821 ,

由於古洞站尚未開工，因此我們暫不接納該範本。請於車站開通後再次提交，多謝！
