### ISSUE TITLE
Resources: New templates of Beijing Subway

### ISSUE THREAD

**Issue by chengxuyuan-duxirui** [railmapgen/rmg-templates#977]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

**Lines opening status:** OPENED

**Reference source:** 4. 互联网上的路线图

**Justification:** 1、更新17号线北端工程车站
2、更改部分英文翻译

- Major update of Line 17/17호선/17号线/17號線: 1、更新17号线北端工程车站
2、更改部分英文翻译

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="bjsubway" line="bj17" major="true"><summary>bjsubway/bj17(M)</summary><details type="name">{"en":"Line 17","zh-Hans":"17号线","zh-Hant":"17號線","ko":"17호선"}</details><details type="param">{"svgWidth":{"destination":1500,"runin":1200,"railmap":1800,"indoor":2600},"svg_height":320,"style":"shmetro","y_pc":40,"padding":8,"direction":"r","platform_num":"","theme":["beijing","bj17","#00A9A9","#fff"],"line_name":["17号线","Line 17"],"current_stn_idx":"1HXVYK","stn_list":{"linestart":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":[],"children":["xbk-zM"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"NrI7z9":{"name":["十里河","Shilihe"],"num":"15","services":["local"],"parents":["Uo1cC5"],"children":["bpJoiq"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]},{"theme":["beijing","bj14","#d5a7a1","#000"],"name":["14号线","Line 14"]}]}]},"loop_pivot":false,"one_line":false,"int_padding":100},"lineend":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":["zw_rFx"],"children":[],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"Uo1cC5":{"name":["周家庄","Zhoujiazhuang"],"num":"16","services":["local"],"parents":["fL5ELd"],"children":["NrI7z9"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"fL5ELd":{"name":["十八里店","Shibalidian"],"num":"17","services":["local"],"parents":["k2w-eF"],"children":["Uo1cC5"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"k2w-eF":{"name":["北神树","Beishenshu"],"num":"18","services":["local"],"parents":["WVLahn"],"children":["fL5ELd"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"WVLahn":{"name":["次渠北","Ciqubei"],"num":"19","services":["local"],"parents":["z5wjAP"],"children":["k2w-eF"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"z5wjAP":{"name":["次渠","Ciqu"],"num":"20","services":["local"],"parents":["xbk-zM"],"children":["WVLahn"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{"lines":[{"theme":["beijing","bj24yz","#e40077","#fff"],"name":["亦庄线","Yizhuang Line"]}]}]},"loop_pivot":false,"one_line":true,"int_padding":225},"xbk-zM":{"name":["嘉会湖","Jiahuihu"],"num":"21","services":["local"],"parents":["linestart"],"children":["z5wjAP"],"transfer":{"tick_direc":"r","paid_area":true,"groups":[{}]},"loop_pivot":false,"one_line":true,"int_padding":225},"bpJoiq":{"name":["潘家园西","Panjiayuan Xi"],"num":"00","services":[],"parents":["NrI7z9"],"children":["IxdtLe"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"GQTZ_o":{"name":["天通苑东","Tiantongyuandong"],"num":"00","services":["local"],"parents":["dtYmGL"],"children":["Y2kLuP"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"dtYmGL":{"name":["清河营","Qingheying"],"num":"00","services":["local"],"parents":["J2b5WU"],"children":["GQTZ_o"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"J2b5WU":{"name":["红军营","Hongjunying"],"num":"00","services":["local"],"parents":["rQAh78"],"children":["dtYmGL"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"rQAh78":{"name":["望京西","Wangjing Xi(W)"],"num":"00","services":[],"parents":["nQVvCO"],"children":["J2b5WU"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj13","#f9e700","#000"],"name":["13号线","Line 13"]},{"theme":["beijing","bj15","#5b2c68","#fff"],"name":["15号线","Line 15"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"nQVvCO":{"name":["太阳宫","Taiyanggong"],"num":"00","services":["local"],"parents":["L5XSBM"],"children":["rQAh78"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj10","#009bc0","#fff"],"name":["10号线","Line 10"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"L5XSBM":{"name":["西坝河","Xibahe"],"num":"00","services":["local"],"parents":["3qug0A"],"children":["nQVvCO"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"3qug0A":{"name":["左家庄","Zuojiazhuang"],"num":"00","services":["local"],"parents":["1HXVYK"],"children":["L5XSBM"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1HXVYK":{"name":["工人体育场","Gongren Tiyuchang\\(Workers' Stadium)"],"num":"00","services":["local"],"parents":["gJWD6J"],"children":["3qug0A"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"gJWD6J":{"name":["东大桥","Dongdaqiao"],"num":"00","services":[],"parents":["bqd0nC"],"children":["1HXVYK"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj6","#d29700","#fff"],"name":["6号线","Line 6"]},{"theme":["beijing","bj22","#f4c1ca","#000"],"name":["22号线","Line 22"]},{"theme":["beijing","bj28","#476205","#fff"],"name":["28号线","Line 28"]}]},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"bqd0nC":{"name":["永安里","Yong’an Li"],"num":"00","services":[],"parents":["IxdtLe"],"children":["gJWD6J"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj1","#c23a30","#fff"],"name":["1号线","Line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"IxdtLe":{"name":["广渠门外","Guangqumen Wai"],"num":"00","services":[],"parents":["bpJoiq"],"children":["bqd0nC"],"transfer":{"groups":[{"lines":[{"theme":["beijing","bj7","#f6c582","#000"],"name":["7号线","Line 7"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250},"zw_rFx":{"name":["未来科学城北","Weilaikexuechengbei\\(Future Science City North)"],"num":"00","services":["local"],"parents":["Y2kLuP"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Y2kLuP":{"name":["未来科学城","Weilaikexuecheng\\(Future Science City)"],"num":"00","services":["local"],"parents":["GQTZ_o"],"children":["zw_rFx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"17","psd_num":"20","info_panel_type":"sh2020","direction_gz_x":3.666667,"direction_gz_y":79.666667,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"branchSpacingPct":40,"version":"5.14.16.#608.0cc7553"}</details></details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
您好，3号线目前暂未开通，不过我们已经将您的作品的换乘3号线去除了，所以我们将汇入您的作品，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
还有，工人体育场的英文站名错误，不过正如前面所说，此错误已被我们修改。
