### ISSUE TITLE
Resources: New templates of Basic

### ISSUE THREAD

**Issue by guqihan** [railmapgen/rmg-templates#983]
Hi RMG team! I would like to contribute the templates below.

_Follow instruction in https://railmapgen.github.io/?app=rmg-templates-upload and paste the template(s) data below_

(REPLACE ME/替代我)
**Lines opening status:** OPENED

**Reference source:** 6. 其他（请于下方注明）

**Justification:** minecraft mtr

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="basic" line="default" major="false"><summary>basic/default</summary><details type="name">{"en":"Default","zh-Hans":"默认","zh-Hant":"預設","ko":"묵인"}</details><details type="param">{"svgWidth":{"destination":3000,"runin":3000,"railmap":3000,"indoor":3000},"svg_height":400,"style":"shmetro","y_pc":50,"padding":15,"branchSpacingPct":33,"direction":"r","platform_num":"","theme":["other","other","#00ff00","#fff"],"line_name":["1号线","Line 1"],"current_stn_idx":"8HhZ8s","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["ziIliy"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":300},"ziIliy":{"name":["未命名 ziIliy","Unnamed ziIliy"],"num":"01","services":["local"],"parents":["linestart"],"children":["8HhZ8s"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":300},"8HhZ8s":{"name":["深暗古城","Deep Derk"],"num":"02","services":["local","express","direct"],"parents":["ziIliy"],"children":["Su8hSU"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#ff0000","#fff"],"name":["2号线","Lien 2"]}]},{},{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":250,"facility":"railway"},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["wQfpKZ"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":300},"Su8hSU":{"name":["深暗古城西","Unnamed Su8hSU"],"num":"00","services":["local"],"parents":["8HhZ8s"],"children":["wQfpKZ"],"transfer":{"groups":[{"lines":[{"theme":["other","other","#00ff00","#fff"],"name":["1","branch line 1"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wQfpKZ":{"name":["未命名 wQfpKZ","Unnamed wQfpKZ"],"num":"00","services":["local"],"parents":["Su8hSU"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":false,"loop_info":{"bank":true,"left_and_right_factor":1,"bottom_factor":1},"version":"5.15.3"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，此議題和 #984 重複。

@thekingofcity / @wongchito / @Windows-Taskmgr 請關閉，謝謝
