### ISSUE TITLE
Resources: New templates of Kaohsiung Rapid Transit Coropration

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-templates#986]
**Lines opening status:** OPENED

**Reference source:** 4. 互联网上的路线图

**Justification:** 环状轻轨剩余段（爱河之心-凯旋公园）开通运营，以此更新环状轻轨的RMG模板。

- Major update of Circular LRT/环状轻轨/環狀輕軌/원형 경전철: 补充剩余段（爱河之心-凯旋公园）站点

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-templates" company="krtc" line="krtc-c" major="true"><summary>krtc/krtc-c(M)</summary><details type="name">{"en":"Circular LRT","zh-Hans":"环状轻轨","zh-Hant":"環狀輕軌","ko":"원형 경전철"}</details><details type="param">{"svgWidth":{"destination":1400,"runin":1400,"railmap":3200,"indoor":2800},"svg_height":600,"style":"shmetro","y_pc":50,"padding":7,"branchSpacingPct":0,"direction":"r","platform_num":"","theme":["kaohsiung","circular","#7cbd52","#fff"],"line_name":["環状輕軌","Circular LRT"],"current_stn_idx":"Kh_aiU","stn_list":{"linestart":{"name":["LEFT END","LEFT END"],"num":"00","services":["local"],"parents":[],"children":["KqtSP-"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Kh_aiU":{"name":["籬仔內","Lizihnei"],"num":"01","services":["local"],"parents":["YmPbi0"],"children":["vs2peo"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vs2peo":{"name":["凱旋瑞田","Kaisyuan Rueitian"],"num":"02","services":["local"],"parents":["Kh_aiU"],"children":["0ry_Rm"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"lineend":{"name":["RIGHT END","RIGHT END"],"num":"00","services":["local"],"parents":["pzbKtE"],"children":[],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"0ry_Rm":{"name":["前鎮之星","Cianjhen Star"],"num":"00","services":["local"],"parents":["vs2peo"],"children":["heEBdD"],"transfer":{"groups":[{},{},{"lines":[{"theme":["kaohsiung","red","#e20b65","#fff"],"name":["紅線","Red Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":true,"one_line":true,"int_padding":160},"YmPbi0":{"name":["輕軌機廠","LRT Depot"],"num":"00","services":["local"],"parents":["iXG0XD"],"children":["Kh_aiU"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"iXG0XD":{"name":["凱旋二聖","Kaisyuan Ersheng"],"num":"00","services":["local"],"parents":["zXgudq"],"children":["YmPbi0"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"heEBdD":{"name":["凱旋中華","Kaisyuan Jhonghua"],"num":"00","services":["local"],"parents":["0ry_Rm"],"children":["B1xRJk"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zXgudq":{"name":["凱旋武昌","Kaisyuan Wuchang"],"num":"00","services":["local"],"parents":["753Ri8"],"children":["iXG0XD"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"753Ri8":{"name":["五權國小","Wucyuan Elementary School"],"num":"00","services":["local"],"parents":["8ODG73"],"children":["zXgudq"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8ODG73":{"name":["衛生局","Department of Health"],"num":"00","services":["local"],"parents":["KqtSP-"],"children":["753Ri8"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"KqtSP-":{"name":["凱旋公園","Kaisyuan Park"],"num":"00","services":["local"],"parents":["linestart"],"children":["8ODG73"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"B1xRJk":{"name":["夢時代","Dream Mall"],"num":"00","services":["local"],"parents":["heEBdD"],"children":["Rx50HW"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Rx50HW":{"name":["經貿園區","Commerce and Trade Park"],"num":"00","services":["local"],"parents":["B1xRJk"],"children":["sxhtcf"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"sxhtcf":{"name":["軟體園區","Software Technology Park"],"num":"00","services":["local"],"parents":["Rx50HW"],"children":["wm_Ogj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wm_Ogj":{"name":["高雄展覽館","Kaohsiung Exhibition Center"],"num":"00","services":["local"],"parents":["sxhtcf"],"children":["kurWja"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"kurWja":{"name":["旅運中心","Cruise Terminal"],"num":"00","services":["local"],"parents":["wm_Ogj"],"children":["1m88ZA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"1m88ZA":{"name":["光榮碼頭","Glory Pier"],"num":"00","services":["local"],"parents":["kurWja"],"children":["vYu1Pj"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"vYu1Pj":{"name":["真愛碼頭","Love Pier"],"num":"00","services":["local"],"parents":["1m88ZA"],"children":["V4AXlg"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"V4AXlg":{"name":["駁二大義","Dayi Pier-2"],"num":"00","services":["local"],"parents":["vYu1Pj"],"children":["yqr3zd"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"yqr3zd":{"name":["駁二蓬萊","Penglai Pier-2"],"num":"00","services":["local"],"parents":["V4AXlg"],"children":["4D0D-S"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4D0D-S":{"name":["哈瑪星","Hamasen"],"num":"00","services":["local"],"parents":["yqr3zd"],"children":["X5V4KU"],"transfer":{"groups":[{},{},{"lines":[{"theme":["kaohsiung","orange","#faa73f","#fff"],"name":["橘線","Orange Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":160},"X5V4KU":{"name":["壽山公園","Shoushan Park"],"num":"00","services":["local"],"parents":["4D0D-S"],"children":["aN_b4R"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"aN_b4R":{"name":["文武聖殿","Wenwu Temple"],"num":"00","services":["local"],"parents":["X5V4KU"],"children":["9gRcrB"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"9gRcrB":{"name":["鼓山區公所","Gushan District Office"],"num":"00","services":["local"],"parents":["aN_b4R"],"children":["kDUBfA"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":true,"one_line":true,"int_padding":355},"kDUBfA":{"name":["鼓山","Gushan"],"num":"00","services":["local"],"parents":["9gRcrB"],"children":["uTW6dn"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"uTW6dn":{"name":["馬卡道","Makadao"],"num":"00","services":["local"],"parents":["kDUBfA"],"children":["EpnAtx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EpnAtx":{"name":["臺鐵美術館","TRA Museum of Fine Arts"],"num":"00","services":["local"],"parents":["uTW6dn"],"children":["dOdkna"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"dOdkna":{"name":["內惟藝術中心","Neiwei Arts Center"],"num":"00","services":["local"],"parents":["EpnAtx"],"children":["zzq2vx"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"zzq2vx":{"name":["美術館","Kaohsiung Museum of Fine Arts"],"num":"00","services":["local"],"parents":["dOdkna"],"children":["jWQweG"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"jWQweG":{"name":["聯合醫院","Kaohsiung Municipal United Hospital"],"num":"00","services":["local"],"parents":["zzq2vx"],"children":["wH8x0j"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"wH8x0j":{"name":["龍華國小","Longhua Elementary School"],"num":"00","services":["local"],"parents":["jWQweG"],"children":["BqwPJQ"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"BqwPJQ":{"name":["愛河之心","Heart of Love River"],"num":"00","services":["local"],"parents":["wH8x0j"],"children":["xSxxXO"],"transfer":{"groups":[{},{},{"lines":[{"theme":["kaohsiung","red","#e20b65","#fff"],"name":["紅線","Red Line"]}]}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":160},"xSxxXO":{"name":["新上國小","Sinshang Elementary School"],"num":"00","services":["local"],"parents":["BqwPJQ"],"children":["4Kxyy_"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"4Kxyy_":{"name":["灣仔內","Wanzihnei"],"num":"00","services":["local"],"parents":["xSxxXO"],"children":["8fdZwr"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"8fdZwr":{"name":["鼎山街","Dingshan Street"],"num":"00","services":["local"],"parents":["4Kxyy_"],"children":["Z9UB3x"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Z9UB3x":{"name":["高雄高工","Kaohsiung Industrial High School"],"num":"00","services":["local"],"parents":["8fdZwr"],"children":["Wd-m8b"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"Wd-m8b":{"name":["樹德家商","Shu-Te Home-Economics"],"num":"00","services":["local"],"parents":["Z9UB3x"],"children":["EvEs9d"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"EvEs9d":{"name":["科工館","Science and Technology Museum"],"num":"00","services":["local"],"parents":["Wd-m8b"],"children":["pzbKtE"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355},"pzbKtE":{"name":["聖功醫院","St. Joseph Hospital"],"num":"00","services":["local"],"parents":["EvEs9d"],"children":["lineend"],"transfer":{"groups":[{}],"tick_direc":"r","paid_area":true},"loop_pivot":false,"one_line":true,"int_padding":355}},"namePosMTR":{"isStagger":true,"isFlip":true},"customiseMTRDest":{"isLegacy":false,"terminal":false},"line_num":"1","spanLineNum":true,"psd_num":"1","info_panel_type":"sh2020","direction_gz_x":40,"direction_gz_y":70,"coline":{},"loop":true,"loop_info":{"bank":false,"left_and_right_factor":1,"bottom_factor":18},"version":"5.15.3"}</details></details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本有以下的問題：
- 科工館站沒有新增台灣鐵路的轉乘標示

請修改，謝謝🙏

@28yfang 請加Need Fixing，謝謝
